-- Dedicated Voter Pulse quiz question generated by Claude.
-- Safe to re-run.

alter table public.processed_votes
  add column if not exists onboarding_question text;

comment on column public.processed_votes.onboarding_question is
  'Complete standalone natural-English question (≤20 words) for the Voter Pulse onboarding quiz.';
