-- seed-tx-all-mapping-and-high-courts.sql
-- Paste into Supabase SQL Editor and Run.
-- 1) Upserts county_district_mapping for all 254 TX counties
--    (appellate from Gov't Code §22.201; judicial from Oct 2024 district-court list)
-- 2) Upserts Statewide + Appellate high-court officials
-- Does NOT wipe District / County-Magistrate rows you already have.

-- ===== A) County mapping =====
insert into public.county_district_mapping (
  state_code, county_name, appellate_district_numbers, judicial_district_numbers
)
values
  ('TX', 'Anderson', array[12]::integer[], array[3, 87, 349, 369]::integer[]),
  ('TX', 'Andrews', array[8]::integer[], array[109]::integer[]),
  ('TX', 'Angelina', array[12]::integer[], array[159, 217]::integer[]),
  ('TX', 'Aransas', array[13]::integer[], array[36, 156, 343]::integer[]),
  ('TX', 'Archer', array[2]::integer[], array[97]::integer[]),
  ('TX', 'Armstrong', array[7]::integer[], array[47]::integer[]),
  ('TX', 'Atascosa', array[4]::integer[], array[81, 218]::integer[]),
  ('TX', 'Austin', array[1, 14]::integer[], array[155]::integer[]),
  ('TX', 'Bailey', array[7]::integer[], array[287]::integer[]),
  ('TX', 'Bandera', array[4]::integer[], array[198]::integer[]),
  ('TX', 'Bastrop', array[3]::integer[], array[21, 335, 423, 465]::integer[]),
  ('TX', 'Baylor', array[11]::integer[], array[50]::integer[]),
  ('TX', 'Bee', array[13]::integer[], array[36, 156, 343]::integer[]),
  ('TX', 'Bell', array[3]::integer[], array[27, 146, 169, 264, 426, 478]::integer[]),
  ('TX', 'Bexar', array[4]::integer[], array[37, 45, 57, 73, 131, 144, 150, 166, 175, 186, 187, 224, 225, 226, 227, 285, 288, 289, 290, 379, 386, 399, 407, 408, 436, 437, 438]::integer[]),
  ('TX', 'Blanco', array[3]::integer[], array[33, 424]::integer[]),
  ('TX', 'Borden', array[11]::integer[], array[132]::integer[]),
  ('TX', 'Bosque', array[10]::integer[], array[220]::integer[]),
  ('TX', 'Bowie', array[6]::integer[], array[5, 102, 202]::integer[]),
  ('TX', 'Brazoria', array[1, 14]::integer[], array[149, 239, 300, 412, 461]::integer[]),
  ('TX', 'Brazos', array[10]::integer[], array[85, 272, 361, 472]::integer[]),
  ('TX', 'Brewster', array[8]::integer[], array[394]::integer[]),
  ('TX', 'Briscoe', array[7]::integer[], array[110]::integer[]),
  ('TX', 'Brooks', array[4]::integer[], array[79]::integer[]),
  ('TX', 'Brown', array[11]::integer[], array[35]::integer[]),
  ('TX', 'Burleson', array[10]::integer[], array[21, 335]::integer[]),
  ('TX', 'Burnet', array[3]::integer[], array[33, 424]::integer[]),
  ('TX', 'Caldwell', array[3]::integer[], array[22, 207, 421]::integer[]),
  ('TX', 'Calhoun', array[13]::integer[], array[24, 135, 267]::integer[]),
  ('TX', 'Callahan', array[11]::integer[], array[42]::integer[]),
  ('TX', 'Cameron', array[13]::integer[], array[103, 107, 138, 197, 357, 404, 444, 445, 484]::integer[]),
  ('TX', 'Camp', array[6]::integer[], array[76, 276]::integer[]),
  ('TX', 'Carson', array[7]::integer[], array[100]::integer[]),
  ('TX', 'Cass', array[6]::integer[], array[5]::integer[]),
  ('TX', 'Castro', array[7]::integer[], array[64, 242]::integer[]),
  ('TX', 'Chambers', array[1, 14]::integer[], array[253, 344]::integer[]),
  ('TX', 'Cherokee', array[12]::integer[], array[2, 369]::integer[]),
  ('TX', 'Childress', array[7]::integer[], array[100]::integer[]),
  ('TX', 'Clay', array[2]::integer[], array[97]::integer[]),
  ('TX', 'Cochran', array[7]::integer[], array[286]::integer[]),
  ('TX', 'Coke', array[3]::integer[], array[51]::integer[]),
  ('TX', 'Coleman', array[11]::integer[], array[42]::integer[]),
  ('TX', 'Collin', array[5]::integer[], array[199, 219, 296, 366, 380, 401, 416, 417, 429, 468, 469, 470, 471, 493, 494]::integer[]),
  ('TX', 'Collingsworth', array[7]::integer[], array[100]::integer[]),
  ('TX', 'Colorado', array[1, 14]::integer[], array[2, 25]::integer[]),
  ('TX', 'Comal', array[3]::integer[], array[22, 207, 274, 433, 466]::integer[]),
  ('TX', 'Comanche', array[11]::integer[], array[220]::integer[]),
  ('TX', 'Concho', array[3]::integer[], array[119]::integer[]),
  ('TX', 'Cooke', array[2]::integer[], array[235]::integer[]),
  ('TX', 'Coryell', array[10]::integer[], array[52, 440]::integer[]),
  ('TX', 'Cottle', array[7]::integer[], array[50]::integer[]),
  ('TX', 'Crane', array[8]::integer[], array[109]::integer[]),
  ('TX', 'Crockett', array[8]::integer[], array[112]::integer[]),
  ('TX', 'Crosby', array[7]::integer[], array[72]::integer[]),
  ('TX', 'Culberson', array[8]::integer[], array[205, 394]::integer[]),
  ('TX', 'Dallam', array[7]::integer[], array[69]::integer[]),
  ('TX', 'Dallas', array[5]::integer[], array[14, 44, 68, 95, 101, 116, 134, 160, 162, 191, 192, 193, 194, 195, 203, 204, 254, 255, 256, 265, 282, 283, 291, 292, 298, 301, 302, 303, 304, 305, 330, 363]::integer[]),
  ('TX', 'Dawson', array[11]::integer[], array[106]::integer[]),
  ('TX', 'Deaf Smith', array[7]::integer[], array[222]::integer[]),
  ('TX', 'Delta', array[6]::integer[], array[8, 62]::integer[]),
  ('TX', 'Denton', array[2]::integer[], array[16, 158, 211, 362, 367, 393, 431, 442, 462, 467, 481]::integer[]),
  ('TX', 'DeWitt', array[13]::integer[], array[24, 135, 267]::integer[]),
  ('TX', 'Dickens', array[7]::integer[], array[110]::integer[]),
  ('TX', 'Dimmit', array[4]::integer[], array[293, 365]::integer[]),
  ('TX', 'Donley', array[7]::integer[], array[100]::integer[]),
  ('TX', 'Duval', array[4]::integer[], array[229]::integer[]),
  ('TX', 'Eastland', array[11]::integer[], array[91]::integer[]),
  ('TX', 'Ector', array[11]::integer[], array[70, 161, 244, 358, 446]::integer[]),
  ('TX', 'Edwards', array[4]::integer[], array[452]::integer[]),
  ('TX', 'Ellis', array[10]::integer[], array[40, 378, 443]::integer[]),
  ('TX', 'El Paso', array[8]::integer[], array[34, 41, 65, 120, 168, 171, 205, 210, 243, 327, 346, 383, 384, 388, 409, 448]::integer[]),
  ('TX', 'Erath', array[11]::integer[], array[266]::integer[]),
  ('TX', 'Falls', array[10]::integer[], array[82]::integer[]),
  ('TX', 'Fannin', array[6]::integer[], array[336]::integer[]),
  ('TX', 'Fayette', array[3]::integer[], array[155]::integer[]),
  ('TX', 'Fisher', array[11]::integer[], array[32]::integer[]),
  ('TX', 'Floyd', array[7]::integer[], array[110]::integer[]),
  ('TX', 'Foard', array[7]::integer[], array[46]::integer[]),
  ('TX', 'Fort Bend', array[1, 14]::integer[], array[240, 268, 328, 387, 400, 434, 458, 505]::integer[]),
  ('TX', 'Franklin', array[6]::integer[], array[8, 62]::integer[]),
  ('TX', 'Freestone', array[10]::integer[], array[77, 87]::integer[]),
  ('TX', 'Frio', array[4]::integer[], array[81, 218]::integer[]),
  ('TX', 'Gaines', array[11]::integer[], array[106]::integer[]),
  ('TX', 'Galveston', array[1, 14]::integer[], array[10, 56, 122, 212, 306, 405]::integer[]),
  ('TX', 'Garza', array[7]::integer[], array[106]::integer[]),
  ('TX', 'Gillespie', array[4]::integer[], array[216]::integer[]),
  ('TX', 'Glasscock', array[11]::integer[], array[118]::integer[]),
  ('TX', 'Goliad', array[13]::integer[], array[24, 135, 267]::integer[]),
  ('TX', 'Gonzales', array[13]::integer[], array[2, 25]::integer[]),
  ('TX', 'Gray', array[7]::integer[], array[31, 223]::integer[]),
  ('TX', 'Grayson', array[5]::integer[], array[15, 59, 397]::integer[]),
  ('TX', 'Gregg', array[6, 12]::integer[], array[124, 188, 307]::integer[]),
  ('TX', 'Grimes', array[1, 14]::integer[], array[12, 506]::integer[]),
  ('TX', 'Guadalupe', array[4]::integer[], array[2, 25, 274, 456]::integer[]),
  ('TX', 'Hale', array[7]::integer[], array[64, 242]::integer[]),
  ('TX', 'Hall', array[7]::integer[], array[100]::integer[]),
  ('TX', 'Hamilton', array[10]::integer[], array[220]::integer[]),
  ('TX', 'Hansford', array[7]::integer[], array[84]::integer[]),
  ('TX', 'Hardeman', array[7]::integer[], array[46]::integer[]),
  ('TX', 'Hardin', array[9]::integer[], array[88, 356]::integer[]),
  ('TX', 'Harris', array[1, 14]::integer[], array[11, 55, 61, 80, 113, 125, 127, 129, 133, 151, 152, 157, 164, 165, 174, 176, 177, 178, 179, 180, 182, 183, 184, 185, 189, 190, 208, 209, 215, 228, 230, 232, 234, 245, 246, 247, 248, 257, 262, 263, 269, 270, 280, 281, 295, 308, 309, 310, 311, 312, 313, 314, 315, 333, 334, 337, 338, 339, 351, 482, 486, 487, 488, 495, 496, 497, 507]::integer[]),
  ('TX', 'Harrison', array[6]::integer[], array[71]::integer[]),
  ('TX', 'Hartley', array[7]::integer[], array[69]::integer[]),
  ('TX', 'Haskell', array[11]::integer[], array[39]::integer[]),
  ('TX', 'Hays', array[3]::integer[], array[22, 207, 274, 428, 453, 483]::integer[]),
  ('TX', 'Hemphill', array[7]::integer[], array[31]::integer[]),
  ('TX', 'Henderson', array[12]::integer[], array[3, 173, 392]::integer[]),
  ('TX', 'Hidalgo', array[13]::integer[], array[92, 93, 139, 206, 275, 332, 370, 389, 398, 430, 449, 464, 476]::integer[]),
  ('TX', 'Hill', array[10]::integer[], array[66]::integer[]),
  ('TX', 'Hockley', array[7]::integer[], array[286]::integer[]),
  ('TX', 'Hood', array[2]::integer[], array[355]::integer[]),
  ('TX', 'Hopkins', array[6]::integer[], array[8, 62]::integer[]),
  ('TX', 'Houston', array[12]::integer[], array[3, 349]::integer[]),
  ('TX', 'Howard', array[11]::integer[], array[118]::integer[]),
  ('TX', 'Hudspeth', array[8]::integer[], array[205, 394]::integer[]),
  ('TX', 'Hunt', array[5, 6]::integer[], array[196, 354]::integer[]),
  ('TX', 'Hutchinson', array[7]::integer[], array[84, 316]::integer[]),
  ('TX', 'Irion', array[3]::integer[], array[51]::integer[]),
  ('TX', 'Jack', array[2]::integer[], array[271]::integer[]),
  ('TX', 'Jackson', array[13]::integer[], array[24, 135, 267]::integer[]),
  ('TX', 'Jasper', array[9]::integer[], array[1]::integer[]),
  ('TX', 'Jeff Davis', array[8]::integer[], array[394]::integer[]),
  ('TX', 'Jefferson', array[9]::integer[], array[58, 60, 136, 172, 252, 279, 317]::integer[]),
  ('TX', 'Jim Hogg', array[4]::integer[], array[229]::integer[]),
  ('TX', 'Jim Wells', array[4]::integer[], array[79]::integer[]),
  ('TX', 'Johnson', array[10]::integer[], array[18, 249, 413]::integer[]),
  ('TX', 'Jones', array[11]::integer[], array[259]::integer[]),
  ('TX', 'Karnes', array[4]::integer[], array[81, 218]::integer[]),
  ('TX', 'Kaufman', array[5]::integer[], array[86, 422, 489]::integer[]),
  ('TX', 'Kendall', array[4]::integer[], array[451]::integer[]),
  ('TX', 'Kenedy', array[13]::integer[], array[105]::integer[]),
  ('TX', 'Kent', array[7]::integer[], array[39]::integer[]),
  ('TX', 'Kerr', array[4]::integer[], array[198, 216]::integer[]),
  ('TX', 'Kimble', array[4]::integer[], array[452]::integer[]),
  ('TX', 'King', array[7]::integer[], array[50]::integer[]),
  ('TX', 'Kinney', array[4]::integer[], array[63]::integer[]),
  ('TX', 'Kleberg', array[13]::integer[], array[105]::integer[]),
  ('TX', 'Knox', array[11]::integer[], array[50]::integer[]),
  ('TX', 'La Salle', array[4]::integer[], array[81, 218]::integer[]),
  ('TX', 'Lamar', array[6]::integer[], array[6, 62]::integer[]),
  ('TX', 'Lamb', array[7]::integer[], array[154]::integer[]),
  ('TX', 'Lampasas', array[3]::integer[], array[27]::integer[]),
  ('TX', 'Lavaca', array[13]::integer[], array[2, 25]::integer[]),
  ('TX', 'Lee', array[3]::integer[], array[21, 335]::integer[]),
  ('TX', 'Leon', array[10]::integer[], array[87, 278, 369]::integer[]),
  ('TX', 'Liberty', array[9]::integer[], array[75, 253]::integer[]),
  ('TX', 'Limestone', array[10]::integer[], array[77, 87]::integer[]),
  ('TX', 'Lipscomb', array[7]::integer[], array[31]::integer[]),
  ('TX', 'Live Oak', array[13]::integer[], array[36, 156, 343]::integer[]),
  ('TX', 'Llano', array[3]::integer[], array[33, 424]::integer[]),
  ('TX', 'Loving', array[8]::integer[], array[143]::integer[]),
  ('TX', 'Lubbock', array[7]::integer[], array[72, 99, 137, 140, 237, 364]::integer[]),
  ('TX', 'Lynn', array[7]::integer[], array[106]::integer[]),
  ('TX', 'Madison', array[10]::integer[], array[12, 278]::integer[]),
  ('TX', 'Marion', array[6]::integer[], array[115, 276]::integer[]),
  ('TX', 'Martin', array[11]::integer[], array[118]::integer[]),
  ('TX', 'Mason', array[4]::integer[], array[452]::integer[]),
  ('TX', 'Matagorda', array[13]::integer[], array[23, 130]::integer[]),
  ('TX', 'Maverick', array[4]::integer[], array[293, 365]::integer[]),
  ('TX', 'McCulloch', array[3]::integer[], array[452]::integer[]),
  ('TX', 'McLennan', array[10]::integer[], array[19, 54, 74, 170, 414, 474]::integer[]),
  ('TX', 'McMullen', array[4]::integer[], array[36, 156, 343]::integer[]),
  ('TX', 'Medina', array[4]::integer[], array[454]::integer[]),
  ('TX', 'Menard', array[4]::integer[], array[452]::integer[]),
  ('TX', 'Midland', array[11]::integer[], array[142, 238, 318, 385, 441]::integer[]),
  ('TX', 'Milam', array[3]::integer[], array[20]::integer[]),
  ('TX', 'Mills', array[3]::integer[], array[35]::integer[]),
  ('TX', 'Mitchell', array[11]::integer[], array[32]::integer[]),
  ('TX', 'Montague', array[2]::integer[], array[97]::integer[]),
  ('TX', 'Montgomery', array[9]::integer[], array[9, 221, 284, 359, 410, 418, 435, 457]::integer[]),
  ('TX', 'Moore', array[7]::integer[], array[69]::integer[]),
  ('TX', 'Morris', array[6]::integer[], array[76, 276]::integer[]),
  ('TX', 'Motley', array[7]::integer[], array[110]::integer[]),
  ('TX', 'Nacogdoches', array[12]::integer[], array[145, 420]::integer[]),
  ('TX', 'Navarro', array[10]::integer[], array[13]::integer[]),
  ('TX', 'Newton', array[9]::integer[], array[1]::integer[]),
  ('TX', 'Nolan', array[11]::integer[], array[32]::integer[]),
  ('TX', 'Nueces', array[13]::integer[], array[28, 94, 105, 117, 148, 214, 319, 347]::integer[]),
  ('TX', 'Ochiltree', array[7]::integer[], array[84]::integer[]),
  ('TX', 'Oldham', array[7]::integer[], array[222]::integer[]),
  ('TX', 'Orange', array[9]::integer[], array[128, 163, 260]::integer[]),
  ('TX', 'Palo Pinto', array[11]::integer[], array[29]::integer[]),
  ('TX', 'Panola', array[6]::integer[], array[123]::integer[]),
  ('TX', 'Parker', array[2]::integer[], array[43, 415]::integer[]),
  ('TX', 'Parmer', array[7]::integer[], array[287]::integer[]),
  ('TX', 'Pecos', array[8]::integer[], array[83, 112]::integer[]),
  ('TX', 'Polk', array[9]::integer[], array[258, 411]::integer[]),
  ('TX', 'Potter', array[7]::integer[], array[47, 108, 181, 251, 320]::integer[]),
  ('TX', 'Presidio', array[8]::integer[], array[394]::integer[]),
  ('TX', 'Rains', array[12]::integer[], array[8, 354]::integer[]),
  ('TX', 'Randall', array[7]::integer[], array[47, 181, 251]::integer[]),
  ('TX', 'Reagan', array[8]::integer[], array[112]::integer[]),
  ('TX', 'Real', array[4]::integer[], array[38]::integer[]),
  ('TX', 'Red River', array[6]::integer[], array[6, 102]::integer[]),
  ('TX', 'Reeves', array[8]::integer[], array[143]::integer[]),
  ('TX', 'Refugio', array[13]::integer[], array[24, 135, 267]::integer[]),
  ('TX', 'Roberts', array[7]::integer[], array[31]::integer[]),
  ('TX', 'Robertson', array[10]::integer[], array[82]::integer[]),
  ('TX', 'Rockwall', array[5]::integer[], array[382, 439]::integer[]),
  ('TX', 'Runnels', array[3]::integer[], array[119]::integer[]),
  ('TX', 'Rusk', array[6, 12]::integer[], array[4]::integer[]),
  ('TX', 'Sabine', array[12]::integer[], array[1, 273]::integer[]),
  ('TX', 'San Augustine', array[12]::integer[], array[1, 273]::integer[]),
  ('TX', 'San Jacinto', array[9]::integer[], array[258, 411]::integer[]),
  ('TX', 'San Patricio', array[13]::integer[], array[36, 156, 343]::integer[]),
  ('TX', 'San Saba', array[3]::integer[], array[33, 424]::integer[]),
  ('TX', 'Schleicher', array[3]::integer[], array[51]::integer[]),
  ('TX', 'Scurry', array[11]::integer[], array[132]::integer[]),
  ('TX', 'Shackelford', array[11]::integer[], array[259]::integer[]),
  ('TX', 'Shelby', array[12]::integer[], array[123, 273]::integer[]),
  ('TX', 'Sherman', array[7]::integer[], array[69]::integer[]),
  ('TX', 'Smith', array[12]::integer[], array[7, 114, 241, 321, 475]::integer[]),
  ('TX', 'Somervell', array[10]::integer[], array[18, 249]::integer[]),
  ('TX', 'Starr', array[4]::integer[], array[229, 381]::integer[]),
  ('TX', 'Stephens', array[11]::integer[], array[90]::integer[]),
  ('TX', 'Sterling', array[3]::integer[], array[51]::integer[]),
  ('TX', 'Stonewall', array[11]::integer[], array[39]::integer[]),
  ('TX', 'Sutton', array[4]::integer[], array[112]::integer[]),
  ('TX', 'Swisher', array[7]::integer[], array[64, 242]::integer[]),
  ('TX', 'Tarrant', array[2]::integer[], array[17, 48, 67, 96, 141, 153, 213, 231, 233, 236, 297, 322, 323, 324, 325, 342, 348, 352, 360, 371, 372, 396, 432, 485]::integer[]),
  ('TX', 'Taylor', array[11]::integer[], array[42, 104, 326, 350]::integer[]),
  ('TX', 'Terrell', array[8]::integer[], array[63, 83]::integer[]),
  ('TX', 'Terry', array[7]::integer[], array[121]::integer[]),
  ('TX', 'Throckmorton', array[11]::integer[], array[39]::integer[]),
  ('TX', 'Titus', array[6]::integer[], array[76, 276]::integer[]),
  ('TX', 'Tom Green', array[3]::integer[], array[51, 119, 340, 391]::integer[]),
  ('TX', 'Travis', array[3]::integer[], array[53, 98, 126, 147, 167, 200, 201, 250, 261, 299, 331, 345, 353, 390, 403, 419, 427, 450, 455, 459, 460]::integer[]),
  ('TX', 'Trinity', array[12]::integer[], array[258, 411]::integer[]),
  ('TX', 'Tyler', array[9]::integer[], array[1, 88]::integer[]),
  ('TX', 'Upshur', array[6, 12]::integer[], array[115]::integer[]),
  ('TX', 'Upton', array[8]::integer[], array[112]::integer[]),
  ('TX', 'Uvalde', array[4]::integer[], array[38]::integer[]),
  ('TX', 'Val Verde', array[4]::integer[], array[63, 83]::integer[]),
  ('TX', 'Van Zandt', array[12]::integer[], array[294]::integer[]),
  ('TX', 'Victoria', array[13]::integer[], array[24, 135, 267, 377]::integer[]),
  ('TX', 'Walker', array[10]::integer[], array[12, 278]::integer[]),
  ('TX', 'Waller', array[1, 14]::integer[], array[506]::integer[]),
  ('TX', 'Ward', array[8]::integer[], array[143]::integer[]),
  ('TX', 'Washington', array[1, 14]::integer[], array[21, 335]::integer[]),
  ('TX', 'Webb', array[4]::integer[], array[49, 111, 341, 406]::integer[]),
  ('TX', 'Wharton', array[13]::integer[], array[23, 329]::integer[]),
  ('TX', 'Wheeler', array[7]::integer[], array[31]::integer[]),
  ('TX', 'Wichita', array[2]::integer[], array[30, 78, 89]::integer[]),
  ('TX', 'Wilbarger', array[7]::integer[], array[46]::integer[]),
  ('TX', 'Willacy', array[13]::integer[], array[197]::integer[]),
  ('TX', 'Williamson', array[3]::integer[], array[26, 277, 368, 395, 425, 480]::integer[]),
  ('TX', 'Wilson', array[4]::integer[], array[81, 218]::integer[]),
  ('TX', 'Winkler', array[8]::integer[], array[109]::integer[]),
  ('TX', 'Wise', array[2]::integer[], array[271]::integer[]),
  ('TX', 'Wood', array[6, 12]::integer[], array[402]::integer[]),
  ('TX', 'Yoakum', array[7]::integer[], array[121]::integer[]),
  ('TX', 'Young', array[2]::integer[], array[90]::integer[]),
  ('TX', 'Zapata', array[4]::integer[], array[49]::integer[]),
  ('TX', 'Zavala', array[4]::integer[], array[2, 293, 365]::integer[])
on conflict (state_code, county_name) do update set
  appellate_district_numbers = excluded.appellate_district_numbers,
  judicial_district_numbers = excluded.judicial_district_numbers;

-- ===== B) Clear prior TX Statewide / Appellate seed rows we manage =====
delete from public.state_officials
where state_code = 'TX'
  and level in ('Statewide', 'Appellate');

-- ===== C) Insert Statewide + Appellate =====
insert into public.state_officials (
  full_name, title, level, state_code, district_number, county_name
)
values
  ('Jimmy Blacklock', 'Chief Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('James P. Sullivan', 'Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('Debra Lehrmann', 'Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('Jeffrey S. Boyd', 'Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('John Devine', 'Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('Jane Bland', 'Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('Rebeca Huddle', 'Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('Evan Young', 'Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('Brett Busby', 'Justice, Supreme Court of Texas', 'Statewide', 'TX', NULL, NULL),
  ('Sharon Keller', 'Presiding Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('Barbara Hervey', 'Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('Bert Richardson', 'Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('Kevin Yeary', 'Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('David Newell', 'Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('Mary Lou Keel', 'Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('Scott Walker', 'Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('Jesse McClure', 'Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('Gina Parker', 'Judge, Texas Court of Criminal Appeals', 'Statewide', 'TX', NULL, NULL),
  ('Greg Abbott', 'Governor of Texas', 'Statewide', 'TX', NULL, NULL),
  ('Terry Adams', 'Chief Justice, First Court of Appeals', 'Appellate', 'TX', 1, NULL),
  ('Bonnie Sudderth', 'Chief Justice, Second Court of Appeals', 'Appellate', 'TX', 2, NULL),
  ('Darlene Byrne', 'Chief Justice, Third Court of Appeals', 'Appellate', 'TX', 3, NULL),
  ('Rebeca Martinez', 'Chief Justice, Fourth Court of Appeals', 'Appellate', 'TX', 4, NULL),
  ('J.J. Koch', 'Chief Justice, Fifth Court of Appeals', 'Appellate', 'TX', 5, NULL),
  ('Scott Stevens', 'Chief Justice, Sixth Court of Appeals', 'Appellate', 'TX', 6, NULL),
  ('Brian Quinn', 'Chief Justice, Seventh Court of Appeals', 'Appellate', 'TX', 7, NULL),
  ('Maria Salas Mendoza', 'Chief Justice, Eighth Court of Appeals', 'Appellate', 'TX', 8, NULL),
  ('Scott Golemon', 'Chief Justice, Ninth Court of Appeals', 'Appellate', 'TX', 9, NULL),
  ('Tom Gray', 'Chief Justice, Tenth Court of Appeals', 'Appellate', 'TX', 10, NULL),
  ('John Bailey', 'Chief Justice, Eleventh Court of Appeals', 'Appellate', 'TX', 11, NULL),
  ('Jim Worthen', 'Chief Justice, Twelfth Court of Appeals', 'Appellate', 'TX', 12, NULL),
  ('Gina Benavides', 'Chief Justice, Thirteenth Court of Appeals', 'Appellate', 'TX', 13, NULL),
  ('Tracy Christopher', 'Chief Justice, Fourteenth Court of Appeals', 'Appellate', 'TX', 14, NULL),
  ('Kevin Jewell', 'Justice (Place 2), Fourteenth Court of Appeals', 'Appellate', 'TX', 14, NULL),
  ('Charles Spain', 'Justice (Place 4), Fourteenth Court of Appeals', 'Appellate', 'TX', 14, NULL),
  ('Frances Bourliot', 'Justice (Place 5), Fourteenth Court of Appeals', 'Appellate', 'TX', 14, NULL),
  ('Randy Wilson', 'Justice (Place 3), Fourteenth Court of Appeals', 'Appellate', 'TX', 14, NULL);

-- Confirm:
-- select count(*) from county_district_mapping where state_code='TX';
-- select level, count(*) from state_officials where state_code='TX' group by level order by 1;
