-- seed-state-executives.sql
-- Paste into Supabase SQL Editor and Run.
-- Seeds Governor, Lieutenant Governor, Attorney General, Secretary of State,
-- and Treasurer (or treasury equivalent) for all 50 states under
-- court_or_agency = 'Executive Branch'.
--
-- Includes title, name, party, photo_url.
-- Safe to re-run.

alter table public.state_officials
  add column if not exists party text;

alter table public.state_officials
  add column if not exists photo_url text;

delete from public.state_officials
where court_or_agency = 'Executive Branch'
   or (
     level = 'Statewide'
     and lower(coalesce(title, '')) in (
       'governor',
       'lieutenant governor',
       'attorney general',
       'secretary of state',
       'treasurer',
       'chief financial officer',
       'comptroller of public accounts',
       'comptroller'
     )
     and (
       court_or_agency is null
       or court_or_agency ilike 'Office of the %'
       or court_or_agency = 'Executive Branch'
     )
   );

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url
)
values
  ('Mike Dunleavy', 'Governor', 'Executive Branch', 'Statewide', 'AK', NULL, NULL, 'Republican', NULL),
  ('Nancy Dahlstrom', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'AK', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Nancy_Dahlstrom%2C_2024.jpg/330px-Nancy_Dahlstrom%2C_2024.jpg'),
  ('Treg Taylor', 'Attorney General', 'Executive Branch', 'Statewide', 'AK', NULL, NULL, 'Republican', NULL),
  ('Kay Ivey', 'Governor', 'Executive Branch', 'Statewide', 'AL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Governor_Kay_Ivey_2017_%28cropped%29.jpg/330px-Governor_Kay_Ivey_2017_%28cropped%29.jpg'),
  ('Will Ainsworth', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'AL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Alabama_Lieutenant_Governor_visits_Lyster_Army_Health_Clinic_%28cropped%29.jpg/330px-Alabama_Lieutenant_Governor_visits_Lyster_Army_Health_Clinic_%28cropped%29.jpg'),
  ('Steve Marshall', 'Attorney General', 'Executive Branch', 'Statewide', 'AL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Steve_Marshall_%2841773693585%29.jpg'),
  ('Wes Allen', 'Secretary of State', 'Executive Branch', 'Statewide', 'AL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Jerry_Carl_with_Wes_Allen_%28cropped%29.jpg/330px-Jerry_Carl_with_Wes_Allen_%28cropped%29.jpg'),
  ('Young Boozer', 'Treasurer', 'Executive Branch', 'Statewide', 'AL', NULL, NULL, 'Republican', NULL),
  ('Sarah Huckabee Sanders', 'Governor', 'Executive Branch', 'Statewide', 'AR', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Governor_Sarah_Huckabee_Sanders_2026.jpg/330px-Governor_Sarah_Huckabee_Sanders_2026.jpg'),
  ('Leslie Rutledge', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'AR', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Leslie_Rutledge_%2825475720912%29_%281%29.jpg/330px-Leslie_Rutledge_%2825475720912%29_%281%29.jpg'),
  ('Tim Griffin', 'Attorney General', 'Executive Branch', 'Statewide', 'AR', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Rep_Tim_Griffin_Official_Photo.jpg/330px-Rep_Tim_Griffin_Official_Photo.jpg'),
  ('Cole Jester', 'Secretary of State', 'Executive Branch', 'Statewide', 'AR', NULL, NULL, 'Republican', NULL),
  ('John Thurston', 'Treasurer', 'Executive Branch', 'Statewide', 'AR', NULL, NULL, 'Republican', NULL),
  ('Katie Hobbs', 'Governor', 'Executive Branch', 'Statewide', 'AZ', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Katie_Hobbs_2026.jpg/330px-Katie_Hobbs_2026.jpg'),
  ('Kris Mayes', 'Attorney General', 'Executive Branch', 'Statewide', 'AZ', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Kris_Mayes_%2852365525231%29_%28cropped%29.jpg/330px-Kris_Mayes_%2852365525231%29_%28cropped%29.jpg'),
  ('Adrian Fontes', 'Secretary of State', 'Executive Branch', 'Statewide', 'AZ', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Adrian_Fontes_2025.jpg/330px-Adrian_Fontes_2025.jpg'),
  ('Kimberly Yee', 'Treasurer', 'Executive Branch', 'Statewide', 'AZ', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Kimberly_Yee_by_Gage_Skidmore_3.jpg/330px-Kimberly_Yee_by_Gage_Skidmore_3.jpg'),
  ('Gavin Newsom', 'Governor', 'Executive Branch', 'Statewide', 'CA', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Governor_of_California_Gavin_Newsom_%28cropped_3x4%29.jpg/330px-Governor_of_California_Gavin_Newsom_%28cropped_3x4%29.jpg'),
  ('Eleni Kounalakis', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'CA', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/LG_Kounalakis_Signing_%28cropped%29.jpg/330px-LG_Kounalakis_Signing_%28cropped%29.jpg'),
  ('Rob Bonta', 'Attorney General', 'Executive Branch', 'Statewide', 'CA', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Rob_Bonta_official_portrait_%28cropped%29.jpg/330px-Rob_Bonta_official_portrait_%28cropped%29.jpg'),
  ('Shirley Weber', 'Secretary of State', 'Executive Branch', 'Statewide', 'CA', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Shirley_Weber.jpg/330px-Shirley_Weber.jpg'),
  ('Fiona Ma', 'Treasurer', 'Executive Branch', 'Statewide', 'CA', NULL, NULL, 'Democratic', NULL),
  ('Jared Polis', 'Governor', 'Executive Branch', 'Statewide', 'CO', NULL, NULL, 'Democratic', NULL),
  ('Dianne Primavera', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'CO', NULL, NULL, 'Democratic', NULL),
  ('Phil Weiser', 'Attorney General', 'Executive Branch', 'Statewide', 'CO', NULL, NULL, 'Democratic', NULL),
  ('Jena Griswold', 'Secretary of State', 'Executive Branch', 'Statewide', 'CO', NULL, NULL, 'Democratic', NULL),
  ('Dave Young', 'Treasurer', 'Executive Branch', 'Statewide', 'CO', NULL, NULL, 'Democratic', NULL),
  ('Ned Lamont', 'Governor', 'Executive Branch', 'Statewide', 'CT', NULL, NULL, 'Democratic', NULL),
  ('Susan Bysiewicz', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'CT', NULL, NULL, 'Democratic', NULL),
  ('William Tong', 'Attorney General', 'Executive Branch', 'Statewide', 'CT', NULL, NULL, 'Democratic', NULL),
  ('Stephanie Thomas', 'Secretary of State', 'Executive Branch', 'Statewide', 'CT', NULL, NULL, 'Democratic', NULL),
  ('Erick Russell', 'Treasurer', 'Executive Branch', 'Statewide', 'CT', NULL, NULL, 'Democratic', NULL),
  ('Matt Meyer', 'Governor', 'Executive Branch', 'Statewide', 'DE', NULL, NULL, 'Democratic', NULL),
  ('Kyle Evans Gay', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'DE', NULL, NULL, 'Democratic', NULL),
  ('Kathy Jennings', 'Attorney General', 'Executive Branch', 'Statewide', 'DE', NULL, NULL, 'Democratic', NULL),
  ('Jeffrey Bullock', 'Secretary of State', 'Executive Branch', 'Statewide', 'DE', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/4/43/Jeffery_Bullock_Speaking_2015_Cropped_v1.png'),
  ('Colleen Davis', 'Treasurer', 'Executive Branch', 'Statewide', 'DE', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Colleen_Davis_%2852834741300%29_%28cropped%29.jpg/330px-Colleen_Davis_%2852834741300%29_%28cropped%29.jpg'),
  ('Ron DeSantis', 'Governor', 'Executive Branch', 'Statewide', 'FL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Ron_DeSantis_official_photo.jpg/330px-Ron_DeSantis_official_photo.jpg'),
  ('Jay Collins', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'FL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Official_portrait_of_Lieutenant_Governor_of_Florida_Jay_Collins_%28cropped_5%29.jpg/330px-Official_portrait_of_Lieutenant_Governor_of_Florida_Jay_Collins_%28cropped_5%29.jpg'),
  ('James Uthmeier', 'Attorney General', 'Executive Branch', 'Statewide', 'FL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Official_portrait_of_Attorney_General_James_Uthmeier%2C_2025_%28cropped%29.jpg/330px-Official_portrait_of_Attorney_General_James_Uthmeier%2C_2025_%28cropped%29.jpg'),
  ('Cord Byrd', 'Secretary of State', 'Executive Branch', 'Statewide', 'FL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Rep_Cord_Byrd.jpg'),
  ('Blaise Ingoglia', 'Chief Financial Officer', 'Executive Branch', 'Statewide', 'FL', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Official_portrait_of_Chief_Financial_Officer_Blaise_Ingoglia_%28cropped%29.jpg/330px-Official_portrait_of_Chief_Financial_Officer_Blaise_Ingoglia_%28cropped%29.jpg'),
  ('Brian Kemp', 'Governor', 'Executive Branch', 'Statewide', 'GA', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Brian_Kemp_portrait%2C_2024_%28cropped%29.jpg/330px-Brian_Kemp_portrait%2C_2024_%28cropped%29.jpg'),
  ('Burt Jones', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'GA', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Burt-jones.jpg/330px-Burt-jones.jpg'),
  ('Chris Carr', 'Attorney General', 'Executive Branch', 'Statewide', 'GA', NULL, NULL, 'Republican', NULL),
  ('Brad Raffensperger', 'Secretary of State', 'Executive Branch', 'Statewide', 'GA', NULL, NULL, 'Republican', NULL),
  ('Steve McCoy', 'Treasurer', 'Executive Branch', 'Statewide', 'GA', NULL, NULL, 'Nonpartisan', NULL),
  ('Josh Green', 'Governor', 'Executive Branch', 'Statewide', 'HI', NULL, NULL, 'Democratic', NULL),
  ('Sylvia Luke', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'HI', NULL, NULL, 'Democratic', NULL),
  ('Anne Lopez', 'Attorney General', 'Executive Branch', 'Statewide', 'HI', NULL, NULL, 'Democratic', NULL),
  ('Kim Reynolds', 'Governor', 'Executive Branch', 'Statewide', 'IA', NULL, NULL, 'Republican', NULL),
  ('Chris Cournoyer', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'IA', NULL, NULL, 'Republican', NULL),
  ('Brenna Bird', 'Attorney General', 'Executive Branch', 'Statewide', 'IA', NULL, NULL, 'Republican', NULL),
  ('Paul Pate', 'Secretary of State', 'Executive Branch', 'Statewide', 'IA', NULL, NULL, 'Republican', NULL),
  ('Roby Smith', 'Treasurer', 'Executive Branch', 'Statewide', 'IA', NULL, NULL, 'Republican', NULL),
  ('Brad Little', 'Governor', 'Executive Branch', 'Statewide', 'ID', NULL, NULL, 'Republican', NULL),
  ('Scott Bedke', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'ID', NULL, NULL, 'Republican', NULL),
  ('Raúl Labrador', 'Attorney General', 'Executive Branch', 'Statewide', 'ID', NULL, NULL, 'Republican', NULL),
  ('Phil McGrane', 'Secretary of State', 'Executive Branch', 'Statewide', 'ID', NULL, NULL, 'Republican', NULL),
  ('Julie Ellsworth', 'Treasurer', 'Executive Branch', 'Statewide', 'ID', NULL, NULL, 'Republican', NULL),
  ('J. B. Pritzker', 'Governor', 'Executive Branch', 'Statewide', 'IL', NULL, NULL, 'Democratic', NULL),
  ('Juliana Stratton', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'IL', NULL, NULL, 'Democratic', NULL),
  ('Kwame Raoul', 'Attorney General', 'Executive Branch', 'Statewide', 'IL', NULL, NULL, 'Democratic', NULL),
  ('Alexi Giannoulias', 'Secretary of State', 'Executive Branch', 'Statewide', 'IL', NULL, NULL, 'Democratic', NULL),
  ('Susana Mendoza', 'Comptroller', 'Executive Branch', 'Statewide', 'IL', NULL, NULL, 'Democratic', NULL),
  ('Mike Braun', 'Governor', 'Executive Branch', 'Statewide', 'IN', NULL, NULL, 'Republican', NULL),
  ('Micah Beckwith', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'IN', NULL, NULL, 'Republican', NULL),
  ('Todd Rokita', 'Attorney General', 'Executive Branch', 'Statewide', 'IN', NULL, NULL, 'Republican', NULL),
  ('Diego Morales', 'Secretary of State', 'Executive Branch', 'Statewide', 'IN', NULL, NULL, 'Republican', NULL),
  ('Daniel Elliott', 'Treasurer', 'Executive Branch', 'Statewide', 'IN', NULL, NULL, 'Republican', NULL),
  ('Laura Kelly', 'Governor', 'Executive Branch', 'Statewide', 'KS', NULL, NULL, 'Democratic', NULL),
  ('David Toland', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'KS', NULL, NULL, 'Democratic', NULL),
  ('Kris Kobach', 'Attorney General', 'Executive Branch', 'Statewide', 'KS', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Kris_Kobach_official_portrait%2C_2024.jpg/330px-Kris_Kobach_official_portrait%2C_2024.jpg'),
  ('Scott Schwab', 'Secretary of State', 'Executive Branch', 'Statewide', 'KS', NULL, NULL, 'Republican', NULL),
  ('Steven Johnson', 'Treasurer', 'Executive Branch', 'Statewide', 'KS', NULL, NULL, 'Republican', NULL),
  ('Andy Beshear', 'Governor', 'Executive Branch', 'Statewide', 'KY', NULL, NULL, 'Democratic', NULL),
  ('Jacqueline Coleman', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'KY', NULL, NULL, 'Democratic', NULL),
  ('Russell Coleman', 'Attorney General', 'Executive Branch', 'Statewide', 'KY', NULL, NULL, 'Republican', NULL),
  ('Michael Adams', 'Secretary of State', 'Executive Branch', 'Statewide', 'KY', NULL, NULL, 'Republican', NULL),
  ('Mark Metcalf', 'Treasurer', 'Executive Branch', 'Statewide', 'KY', NULL, NULL, 'Republican', NULL),
  ('Jeff Landry', 'Governor', 'Executive Branch', 'Statewide', 'LA', NULL, NULL, 'Republican', NULL),
  ('Billy Nungesser', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'LA', NULL, NULL, 'Republican', NULL),
  ('Liz Murrill', 'Attorney General', 'Executive Branch', 'Statewide', 'LA', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Liz_Murrill_2024_%28cropped%29.jpg'),
  ('Nancy Landry', 'Secretary of State', 'Executive Branch', 'Statewide', 'LA', NULL, NULL, 'Republican', NULL),
  ('John Fleming', 'Treasurer', 'Executive Branch', 'Statewide', 'LA', NULL, NULL, 'Republican', NULL),
  ('Maura Healey', 'Governor', 'Executive Branch', 'Statewide', 'MA', NULL, NULL, 'Democratic', NULL),
  ('Kim Driscoll', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'MA', NULL, NULL, 'Democratic', NULL),
  ('Andrea Campbell', 'Attorney General', 'Executive Branch', 'Statewide', 'MA', NULL, NULL, 'Democratic', NULL),
  ('William F. Galvin', 'Secretary of State', 'Executive Branch', 'Statewide', 'MA', NULL, NULL, 'Democratic', NULL),
  ('Deb Goldberg', 'Treasurer', 'Executive Branch', 'Statewide', 'MA', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Deb_Goldberg.jpg/330px-Deb_Goldberg.jpg'),
  ('Wes Moore', 'Governor', 'Executive Branch', 'Statewide', 'MD', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Wes_Moore_Official_Governor_Portrait.jpg/330px-Wes_Moore_Official_Governor_Portrait.jpg'),
  ('Aruna Miller', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'MD', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Aruna_Miller_Official_Portrait.jpg/330px-Aruna_Miller_Official_Portrait.jpg'),
  ('Anthony Brown', 'Attorney General', 'Executive Branch', 'Statewide', 'MD', NULL, NULL, 'Democratic', NULL),
  ('Susan Lee', 'Secretary of State', 'Executive Branch', 'Statewide', 'MD', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Secretary_of_State_Susan_C._Lee_Headshot.jpg/330px-Secretary_of_State_Susan_C._Lee_Headshot.jpg'),
  ('Brooke Lierman', 'Comptroller', 'Executive Branch', 'Statewide', 'MD', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/BEL_Headshot_Casual.jpg/330px-BEL_Headshot_Casual.jpg'),
  ('Janet Mills', 'Governor', 'Executive Branch', 'Statewide', 'ME', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Maine_congressional_delegation_meets_with_Gov_Janet_Mills_%28cropped%29.jpg/330px-Maine_congressional_delegation_meets_with_Gov_Janet_Mills_%28cropped%29.jpg'),
  ('Aaron Frey', 'Attorney General', 'Executive Branch', 'Statewide', 'ME', NULL, NULL, 'Democratic', NULL),
  ('Shenna Bellows', 'Secretary of State', 'Executive Branch', 'Statewide', 'ME', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Shenna_Bellows.jpg/330px-Shenna_Bellows.jpg'),
  ('Henry Beck', 'Treasurer', 'Executive Branch', 'Statewide', 'ME', NULL, NULL, 'Democratic', NULL),
  ('Gretchen Whitmer', 'Governor', 'Executive Branch', 'Statewide', 'MI', NULL, NULL, 'Democratic', NULL),
  ('Garlin Gilchrist', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'MI', NULL, NULL, 'Democratic', NULL),
  ('Dana Nessel', 'Attorney General', 'Executive Branch', 'Statewide', 'MI', NULL, NULL, 'Democratic', NULL),
  ('Jocelyn Benson', 'Secretary of State', 'Executive Branch', 'Statewide', 'MI', NULL, NULL, 'Democratic', NULL),
  ('Rachael Eubanks', 'Treasurer', 'Executive Branch', 'Statewide', 'MI', NULL, NULL, 'Democratic', NULL),
  ('Tim Walz', 'Governor', 'Executive Branch', 'Statewide', 'MN', NULL, NULL, 'Democratic', NULL),
  ('Peggy Flanagan', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'MN', NULL, NULL, 'Democratic', NULL),
  ('Keith Ellison', 'Attorney General', 'Executive Branch', 'Statewide', 'MN', NULL, NULL, 'Democratic', NULL),
  ('Steve Simon', 'Secretary of State', 'Executive Branch', 'Statewide', 'MN', NULL, NULL, 'Democratic', NULL),
  ('Julie Blaha', 'State Auditor', 'Executive Branch', 'Statewide', 'MN', NULL, NULL, 'Democratic', NULL),
  ('Mike Kehoe', 'Governor', 'Executive Branch', 'Statewide', 'MO', NULL, NULL, 'Republican', NULL),
  ('David Wasinger', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'MO', NULL, NULL, 'Republican', NULL),
  ('Catherine Hanaway', 'Attorney General', 'Executive Branch', 'Statewide', 'MO', NULL, NULL, 'Republican', NULL),
  ('Denny Hoskins', 'Secretary of State', 'Executive Branch', 'Statewide', 'MO', NULL, NULL, 'Republican', NULL),
  ('Vivek Malek', 'Treasurer', 'Executive Branch', 'Statewide', 'MO', NULL, NULL, 'Republican', NULL),
  ('Tate Reeves', 'Governor', 'Executive Branch', 'Statewide', 'MS', NULL, NULL, 'Republican', NULL),
  ('Delbert Hosemann', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'MS', NULL, NULL, 'Republican', NULL),
  ('Lynn Fitch', 'Attorney General', 'Executive Branch', 'Statewide', 'MS', NULL, NULL, 'Republican', NULL),
  ('Michael Watson', 'Secretary of State', 'Executive Branch', 'Statewide', 'MS', NULL, NULL, 'Republican', NULL),
  ('David McRae', 'Treasurer', 'Executive Branch', 'Statewide', 'MS', NULL, NULL, 'Republican', NULL),
  ('Greg Gianforte', 'Governor', 'Executive Branch', 'Statewide', 'MT', NULL, NULL, 'Republican', NULL),
  ('Kristen Juras', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'MT', NULL, NULL, 'Republican', NULL),
  ('Austin Knudsen', 'Attorney General', 'Executive Branch', 'Statewide', 'MT', NULL, NULL, 'Republican', NULL),
  ('Christi Jacobsen', 'Secretary of State', 'Executive Branch', 'Statewide', 'MT', NULL, NULL, 'Republican', NULL),
  ('Brendan Beatty', 'Treasurer', 'Executive Branch', 'Statewide', 'MT', NULL, NULL, 'Republican', NULL),
  ('Josh Stein', 'Governor', 'Executive Branch', 'Statewide', 'NC', NULL, NULL, 'Democratic', NULL),
  ('Rachel Hunt', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'NC', NULL, NULL, 'Democratic', NULL),
  ('Jeff Jackson', 'Attorney General', 'Executive Branch', 'Statewide', 'NC', NULL, NULL, 'Democratic', NULL),
  ('Elaine Marshall', 'Secretary of State', 'Executive Branch', 'Statewide', 'NC', NULL, NULL, 'Democratic', NULL),
  ('Brad Briner', 'Treasurer', 'Executive Branch', 'Statewide', 'NC', NULL, NULL, 'Republican', NULL),
  ('Kelly Armstrong', 'Governor', 'Executive Branch', 'Statewide', 'ND', NULL, NULL, 'Republican', NULL),
  ('Michelle Strinden', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'ND', NULL, NULL, 'Republican', NULL),
  ('Drew Wrigley', 'Attorney General', 'Executive Branch', 'Statewide', 'ND', NULL, NULL, 'Republican', NULL),
  ('Michael Howe', 'Secretary of State', 'Executive Branch', 'Statewide', 'ND', NULL, NULL, 'Republican', NULL),
  ('Thomas Beadle', 'Treasurer', 'Executive Branch', 'Statewide', 'ND', NULL, NULL, 'Republican', NULL),
  ('Jim Pillen', 'Governor', 'Executive Branch', 'Statewide', 'NE', NULL, NULL, 'Republican', NULL),
  ('Joe Kelly', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'NE', NULL, NULL, 'Republican', NULL),
  ('Mike Hilgers', 'Attorney General', 'Executive Branch', 'Statewide', 'NE', NULL, NULL, 'Republican', NULL),
  ('Bob Evnen', 'Secretary of State', 'Executive Branch', 'Statewide', 'NE', NULL, NULL, 'Republican', NULL),
  ('Joey Spellerberg', 'Treasurer', 'Executive Branch', 'Statewide', 'NE', NULL, NULL, 'Republican', NULL),
  ('Kelly Ayotte', 'Governor', 'Executive Branch', 'Statewide', 'NH', NULL, NULL, 'Republican', NULL),
  ('John Formella', 'Attorney General', 'Executive Branch', 'Statewide', 'NH', NULL, NULL, 'Republican', NULL),
  ('David Scanlan', 'Secretary of State', 'Executive Branch', 'Statewide', 'NH', NULL, NULL, 'Republican', NULL),
  ('Monica Mezzapelle', 'Treasurer', 'Executive Branch', 'Statewide', 'NH', NULL, NULL, 'Democratic', NULL),
  ('Mikie Sherrill', 'Governor', 'Executive Branch', 'Statewide', 'NJ', NULL, NULL, 'Democratic', NULL),
  ('Dale Caldwell', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'NJ', NULL, NULL, 'Democratic', NULL),
  ('Matthew Platkin', 'Attorney General', 'Executive Branch', 'Statewide', 'NJ', NULL, NULL, 'Democratic', NULL),
  ('Tahesha Way', 'Secretary of State', 'Executive Branch', 'Statewide', 'NJ', NULL, NULL, 'Democratic', NULL),
  ('Elizabeth Maher Muoio', 'Treasurer', 'Executive Branch', 'Statewide', 'NJ', NULL, NULL, 'Democratic', NULL),
  ('Michelle Lujan Grisham', 'Governor', 'Executive Branch', 'Statewide', 'NM', NULL, NULL, 'Democratic', NULL),
  ('Howie Morales', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'NM', NULL, NULL, 'Democratic', NULL),
  ('Raúl Torrez', 'Attorney General', 'Executive Branch', 'Statewide', 'NM', NULL, NULL, 'Democratic', NULL),
  ('Maggie Toulouse Oliver', 'Secretary of State', 'Executive Branch', 'Statewide', 'NM', NULL, NULL, 'Democratic', NULL),
  ('Laura Montoya', 'Treasurer', 'Executive Branch', 'Statewide', 'NM', NULL, NULL, 'Democratic', NULL),
  ('Joe Lombardo', 'Governor', 'Executive Branch', 'Statewide', 'NV', NULL, NULL, 'Republican', NULL),
  ('Stavros Anthony', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'NV', NULL, NULL, 'Republican', NULL),
  ('Aaron Ford', 'Attorney General', 'Executive Branch', 'Statewide', 'NV', NULL, NULL, 'Democratic', NULL),
  ('Cisco Aguilar', 'Secretary of State', 'Executive Branch', 'Statewide', 'NV', NULL, NULL, 'Democratic', NULL),
  ('Zach Conine', 'Treasurer', 'Executive Branch', 'Statewide', 'NV', NULL, NULL, 'Democratic', NULL),
  ('Kathy Hochul', 'Governor', 'Executive Branch', 'Statewide', 'NY', NULL, NULL, 'Democratic', NULL),
  ('Antonio Delgado', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'NY', NULL, NULL, 'Democratic', NULL),
  ('Letitia James', 'Attorney General', 'Executive Branch', 'Statewide', 'NY', NULL, NULL, 'Democratic', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Letitia_James_Interview_Feb_2020.png/330px-Letitia_James_Interview_Feb_2020.png'),
  ('Walter Mosley', 'Secretary of State', 'Executive Branch', 'Statewide', 'NY', NULL, NULL, 'Democratic', NULL),
  ('Thomas DiNapoli', 'State Comptroller', 'Executive Branch', 'Statewide', 'NY', NULL, NULL, 'Democratic', NULL),
  ('Mike DeWine', 'Governor', 'Executive Branch', 'Statewide', 'OH', NULL, NULL, 'Republican', NULL),
  ('Jim Tressel', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'OH', NULL, NULL, 'Republican', NULL),
  ('Andy Wilson', 'Attorney General', 'Executive Branch', 'Statewide', 'OH', NULL, NULL, 'Republican', NULL),
  ('Frank LaRose', 'Secretary of State', 'Executive Branch', 'Statewide', 'OH', NULL, NULL, 'Republican', NULL),
  ('Robert Sprague', 'Treasurer', 'Executive Branch', 'Statewide', 'OH', NULL, NULL, 'Republican', NULL),
  ('Kevin Stitt', 'Governor', 'Executive Branch', 'Statewide', 'OK', NULL, NULL, 'Republican', NULL),
  ('Matt Pinnell', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'OK', NULL, NULL, 'Republican', NULL),
  ('Gentner Drummond', 'Attorney General', 'Executive Branch', 'Statewide', 'OK', NULL, NULL, 'Republican', NULL),
  ('Josh Cockroft', 'Secretary of State', 'Executive Branch', 'Statewide', 'OK', NULL, NULL, 'Republican', NULL),
  ('Todd Russ', 'Treasurer', 'Executive Branch', 'Statewide', 'OK', NULL, NULL, 'Republican', NULL),
  ('Tina Kotek', 'Governor', 'Executive Branch', 'Statewide', 'OR', NULL, NULL, 'Democratic', NULL),
  ('Dan Rayfield', 'Attorney General', 'Executive Branch', 'Statewide', 'OR', NULL, NULL, 'Democratic', NULL),
  ('Tobias Read', 'Secretary of State', 'Executive Branch', 'Statewide', 'OR', NULL, NULL, 'Democratic', NULL),
  ('Elizabeth Steiner', 'Treasurer', 'Executive Branch', 'Statewide', 'OR', NULL, NULL, 'Democratic', NULL),
  ('Josh Shapiro', 'Governor', 'Executive Branch', 'Statewide', 'PA', NULL, NULL, 'Democratic', NULL),
  ('Austin Davis', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'PA', NULL, NULL, 'Democratic', NULL),
  ('Dave Sunday', 'Attorney General', 'Executive Branch', 'Statewide', 'PA', NULL, NULL, 'Republican', NULL),
  ('Al Schmidt', 'Secretary of State', 'Executive Branch', 'Statewide', 'PA', NULL, NULL, 'Democratic', NULL),
  ('Stacy Garrity', 'Treasurer', 'Executive Branch', 'Statewide', 'PA', NULL, NULL, 'Republican', NULL),
  ('Dan McKee', 'Governor', 'Executive Branch', 'Statewide', 'RI', NULL, NULL, 'Democratic', NULL),
  ('Sabina Matos', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'RI', NULL, NULL, 'Democratic', NULL),
  ('Peter Neronha', 'Attorney General', 'Executive Branch', 'Statewide', 'RI', NULL, NULL, 'Democratic', NULL),
  ('Gregg Amore', 'Secretary of State', 'Executive Branch', 'Statewide', 'RI', NULL, NULL, 'Democratic', NULL),
  ('James Diossa', 'Treasurer', 'Executive Branch', 'Statewide', 'RI', NULL, NULL, 'Democratic', NULL),
  ('Henry McMaster', 'Governor', 'Executive Branch', 'Statewide', 'SC', NULL, NULL, 'Republican', NULL),
  ('Pamela Evette', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'SC', NULL, NULL, 'Republican', NULL),
  ('Alan Wilson', 'Attorney General', 'Executive Branch', 'Statewide', 'SC', NULL, NULL, 'Republican', NULL),
  ('Mark Hammond', 'Secretary of State', 'Executive Branch', 'Statewide', 'SC', NULL, NULL, 'Republican', NULL),
  ('Curtis Loftis', 'Treasurer', 'Executive Branch', 'Statewide', 'SC', NULL, NULL, 'Republican', NULL),
  ('Larry Rhoden', 'Governor', 'Executive Branch', 'Statewide', 'SD', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Larry_Rhoden_2025_%28cropped%29.jpg/330px-Larry_Rhoden_2025_%28cropped%29.jpg'),
  ('Tony Venhuizen', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'SD', NULL, NULL, 'Republican', NULL),
  ('Marty Jackley', 'Attorney General', 'Executive Branch', 'Statewide', 'SD', NULL, NULL, 'Republican', NULL),
  ('Monae Johnson', 'Secretary of State', 'Executive Branch', 'Statewide', 'SD', NULL, NULL, 'Republican', NULL),
  ('Josh Haeder', 'Treasurer', 'Executive Branch', 'Statewide', 'SD', NULL, NULL, 'Republican', NULL),
  ('Bill Lee', 'Governor', 'Executive Branch', 'Statewide', 'TN', NULL, NULL, 'Republican', NULL),
  ('Randy McNally', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'TN', NULL, NULL, 'Republican', NULL),
  ('Jonathan Skrmetti', 'Attorney General', 'Executive Branch', 'Statewide', 'TN', NULL, NULL, 'Republican', NULL),
  ('Tre Hargett', 'Secretary of State', 'Executive Branch', 'Statewide', 'TN', NULL, NULL, 'Republican', NULL),
  ('David Lillard', 'Treasurer', 'Executive Branch', 'Statewide', 'TN', NULL, NULL, 'Republican', NULL),
  ('Greg Abbott', 'Governor', 'Executive Branch', 'Statewide', 'TX', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Greg_Abbott_at_NASA_2024_%28cropped%29.jpg/330px-Greg_Abbott_at_NASA_2024_%28cropped%29.jpg'),
  ('Dan Patrick', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'TX', NULL, NULL, 'Republican', NULL),
  ('Ken Paxton', 'Attorney General', 'Executive Branch', 'Statewide', 'TX', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/K_Paxton.jpg/330px-K_Paxton.jpg'),
  ('Jane Nelson', 'Secretary of State', 'Executive Branch', 'Statewide', 'TX', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Sec-Jane-Nelson-TX.jpg/330px-Sec-Jane-Nelson-TX.jpg'),
  ('Kelly Hancock', 'Comptroller of Public Accounts', 'Executive Branch', 'Statewide', 'TX', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Kelly_Hancock.jpg/330px-Kelly_Hancock.jpg'),
  ('Spencer Cox', 'Governor', 'Executive Branch', 'Statewide', 'UT', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Spencer_Cox_-_54856206905_%28cropped%29.jpg/330px-Spencer_Cox_-_54856206905_%28cropped%29.jpg'),
  ('Deidre Henderson', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'UT', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Official_portrait_of_Utah_Lt._Gov._Deidre_Henderson.png/330px-Official_portrait_of_Utah_Lt._Gov._Deidre_Henderson.png'),
  ('Derek Brown', 'Attorney General', 'Executive Branch', 'Statewide', 'UT', NULL, NULL, 'Republican', NULL),
  ('Marlo Oaks', 'Treasurer', 'Executive Branch', 'Statewide', 'UT', NULL, NULL, 'Republican', NULL),
  ('Abigail Spanberger', 'Governor', 'Executive Branch', 'Statewide', 'VA', NULL, NULL, 'Democratic', NULL),
  ('Ghazala Hashmi', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'VA', NULL, NULL, 'Democratic', NULL),
  ('Jay Jones', 'Attorney General', 'Executive Branch', 'Statewide', 'VA', NULL, NULL, 'Democratic', NULL),
  ('Kelly Gee', 'Secretary of State', 'Executive Branch', 'Statewide', 'VA', NULL, NULL, 'Democratic', NULL),
  ('David Richardson', 'Treasurer', 'Executive Branch', 'Statewide', 'VA', NULL, NULL, 'Democratic', NULL),
  ('Phil Scott', 'Governor', 'Executive Branch', 'Statewide', 'VT', NULL, NULL, 'Republican', NULL),
  ('John S. Rodgers', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'VT', NULL, NULL, 'Republican', NULL),
  ('Charity Clark', 'Attorney General', 'Executive Branch', 'Statewide', 'VT', NULL, NULL, 'Democratic', NULL),
  ('Sarah Copeland Hanzas', 'Secretary of State', 'Executive Branch', 'Statewide', 'VT', NULL, NULL, 'Democratic', NULL),
  ('Mike Pieciak', 'Treasurer', 'Executive Branch', 'Statewide', 'VT', NULL, NULL, 'Democratic', NULL),
  ('Bob Ferguson', 'Governor', 'Executive Branch', 'Statewide', 'WA', NULL, NULL, 'Democratic', NULL),
  ('Denny Heck', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'WA', NULL, NULL, 'Democratic', NULL),
  ('Nick Brown', 'Attorney General', 'Executive Branch', 'Statewide', 'WA', NULL, NULL, 'Democratic', NULL),
  ('Steve Hobbs', 'Secretary of State', 'Executive Branch', 'Statewide', 'WA', NULL, NULL, 'Democratic', NULL),
  ('Mike Pellicciotti', 'Treasurer', 'Executive Branch', 'Statewide', 'WA', NULL, NULL, 'Democratic', NULL),
  ('Tony Evers', 'Governor', 'Executive Branch', 'Statewide', 'WI', NULL, NULL, 'Democratic', NULL),
  ('Sara Rodriguez', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'WI', NULL, NULL, 'Democratic', NULL),
  ('Josh Kaul', 'Attorney General', 'Executive Branch', 'Statewide', 'WI', NULL, NULL, 'Democratic', NULL),
  ('Sarah Godlewski', 'Secretary of State', 'Executive Branch', 'Statewide', 'WI', NULL, NULL, 'Democratic', NULL),
  ('John Leiber', 'Treasurer', 'Executive Branch', 'Statewide', 'WI', NULL, NULL, 'Republican', NULL),
  ('Patrick Morrisey', 'Governor', 'Executive Branch', 'Statewide', 'WV', NULL, NULL, 'Republican', NULL),
  ('Randy Smith', 'Lieutenant Governor', 'Executive Branch', 'Statewide', 'WV', NULL, NULL, 'Republican', NULL),
  ('JB McCuskey', 'Attorney General', 'Executive Branch', 'Statewide', 'WV', NULL, NULL, 'Republican', NULL),
  ('Kris Warner', 'Secretary of State', 'Executive Branch', 'Statewide', 'WV', NULL, NULL, 'Republican', NULL),
  ('Larry Pack', 'Treasurer', 'Executive Branch', 'Statewide', 'WV', NULL, NULL, 'Republican', NULL),
  ('Mark Gordon', 'Governor', 'Executive Branch', 'Statewide', 'WY', NULL, NULL, 'Republican', NULL),
  ('Bridget Hill', 'Attorney General', 'Executive Branch', 'Statewide', 'WY', NULL, NULL, 'Republican', NULL),
  ('Chuck Gray', 'Secretary of State', 'Executive Branch', 'Statewide', 'WY', NULL, NULL, 'Republican', NULL),
  ('Curt Meier', 'Treasurer', 'Executive Branch', 'Statewide', 'WY', NULL, NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Curt_Meier_at_Campbell_County_League_of_Women_Voters%27_General_Election_Candidates%27_Forum_in_Gillette%2C_Wyoming_%28cropped%29.jpg/330px-Curt_Meier_at_Campbell_County_League_of_Women_Voters%27_General_Election_Candidates%27_Forum_in_Gillette%2C_Wyoming_%28cropped%29.jpg');

-- Confirm:
-- select count(*) from state_officials where court_or_agency = 'Executive Branch';
-- select state_code, title, full_name, party, (photo_url is not null) as has_photo
-- from state_officials
-- where court_or_agency = 'Executive Branch'
-- order by state_code, title;
