-- seed-local-mayors-top100.sql
-- Run after supabase/migration-local-officials.sql
-- Safe to re-run for these cities.

delete from public.local_officials
where level = 'City'
  and title = 'Mayor'
  and (state_code, city_name) in (
    ('NY', 'New York'),
    ('CA', 'Los Angeles'),
    ('IL', 'Chicago'),
    ('TX', 'Houston'),
    ('AZ', 'Phoenix'),
    ('PA', 'Philadelphia'),
    ('TX', 'San Antonio'),
    ('CA', 'San Diego'),
    ('TX', 'Dallas'),
    ('TX', 'Fort Worth'),
    ('FL', 'Jacksonville'),
    ('TX', 'Austin'),
    ('CA', 'San Jose'),
    ('NC', 'Charlotte'),
    ('OH', 'Columbus'),
    ('IN', 'Indianapolis'),
    ('CA', 'San Francisco'),
    ('KY', 'Louisville'),
    ('WA', 'Seattle'),
    ('TN', 'Nashville'),
    ('CO', 'Denver'),
    ('OK', 'Oklahoma City'),
    ('DC', 'Washington, D.C.'),
    ('TX', 'El Paso'),
    ('NV', 'Las Vegas'),
    ('MA', 'Boston'),
    ('MI', 'Detroit'),
    ('OR', 'Portland'),
    ('TN', 'Memphis'),
    ('MD', 'Baltimore'),
    ('WI', 'Milwaukee'),
    ('NM', 'Albuquerque'),
    ('CA', 'Fresno'),
    ('AZ', 'Tucson'),
    ('CA', 'Sacramento'),
    ('GA', 'Atlanta'),
    ('MO', 'Kansas City'),
    ('AZ', 'Mesa'),
    ('NC', 'Raleigh'),
    ('CO', 'Colorado Springs'),
    ('FL', 'Miami'),
    ('NE', 'Omaha'),
    ('VA', 'Virginia Beach'),
    ('CA', 'Long Beach'),
    ('CA', 'Oakland'),
    ('MN', 'Minneapolis'),
    ('CA', 'Bakersfield'),
    ('OK', 'Tulsa'),
    ('FL', 'Tampa'),
    ('CO', 'Aurora'),
    ('TX', 'Arlington'),
    ('KS', 'Wichita'),
    ('OH', 'Cleveland'),
    ('LA', 'New Orleans'),
    ('NV', 'Henderson'),
    ('HI', 'Honolulu'),
    ('CA', 'Anaheim'),
    ('FL', 'Orlando'),
    ('KY', 'Lexington'),
    ('CA', 'Stockton'),
    ('NJ', 'Newark'),
    ('CA', 'Riverside'),
    ('CA', 'Irvine'),
    ('TX', 'Corpus Christi'),
    ('CA', 'Santa Ana'),
    ('OH', 'Cincinnati'),
    ('NC', 'Greensboro'),
    ('PA', 'Pittsburgh'),
    ('MN', 'St. Paul'),
    ('NC', 'Durham'),
    ('NJ', 'Jersey City'),
    ('NE', 'Lincoln'),
    ('NV', 'North Las Vegas'),
    ('TX', 'Plano'),
    ('AZ', 'Gilbert'),
    ('AK', 'Anchorage'),
    ('WI', 'Madison'),
    ('NV', 'Reno'),
    ('AZ', 'Chandler'),
    ('MO', 'St. Louis'),
    ('CA', 'Chula Vista'),
    ('IN', 'Fort Wayne'),
    ('NY', 'Buffalo'),
    ('TX', 'Lubbock'),
    ('TX', 'Laredo'),
    ('FL', 'Port St. Lucie'),
    ('FL', 'St. Petersburg'),
    ('OH', 'Toledo'),
    ('AZ', 'Glendale'),
    ('NC', 'Winston-Salem'),
    ('TX', 'Irving'),
    ('VA', 'Chesapeake'),
    ('TX', 'Garland'),
    ('AZ', 'Scottsdale'),
    ('ID', 'Boise'),
    ('VA', 'Richmond'),
    ('TX', 'Frisco'),
    ('FL', 'Cape Coral'),
    ('TX', 'McKinney'),
    ('AL', 'Huntsville')
  );

insert into public.local_officials (
  full_name,
  title,
  level,
  state_code,
  city_name,
  county_name,
  party,
  photo_url,
  website_url,
  selection_method,
  appointed_by,
  source_name,
  source_ref,
  government_type,
  took_office_year,
  term_ends_year,
  coverage_status
)
values
  ('Zohran Mamdani', 'Mayor', 'City', 'NY', 'New York', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2026, 2030, 'confirmed'),
  ('Karen Bass', 'Mayor', 'City', 'CA', 'Los Angeles', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2022, 2026, 'confirmed'),
  ('Brandon Johnson', 'Mayor', 'City', 'IL', 'Chicago', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2023, 2027, 'confirmed'),
  ('John Whitmire', 'Mayor', 'City', 'TX', 'Houston', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2024, 2028, 'confirmed'),
  ('Kate Gallego', 'Mayor', 'City', 'AZ', 'Phoenix', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2019, 2029, 'confirmed'),
  ('Cherelle Parker', 'Mayor', 'City', 'PA', 'Philadelphia', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2024, 2028, 'confirmed'),
  ('Gina Ortiz Jones', 'Mayor', 'City', 'TX', 'San Antonio', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2025, 2027, 'confirmed'),
  ('Todd Gloria', 'Mayor', 'City', 'CA', 'San Diego', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2020, 2028, 'confirmed'),
  ('Eric Johnson', 'Mayor', 'City', 'TX', 'Dallas', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2019, 2027, 'confirmed'),
  ('Mattie Parker', 'Mayor', 'City', 'TX', 'Fort Worth', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2021, 2027, 'confirmed'),
  ('Donna Deegan', 'Mayor', 'City', 'FL', 'Jacksonville', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2023, 2027, 'confirmed'),
  ('Kirk Watson', 'Mayor', 'City', 'TX', 'Austin', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2023, 2029, 'confirmed'),
  ('Matt Mahan', 'Mayor', 'City', 'CA', 'San Jose', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2023, 2029, 'confirmed'),
  ('Vi Lyles', 'Mayor', 'City', 'NC', 'Charlotte', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2017, 2027, 'confirmed'),
  ('Andrew J. Ginther', 'Mayor', 'City', 'OH', 'Columbus', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2015, 2027, 'confirmed'),
  ('Joseph Hogsett', 'Mayor', 'City', 'IN', 'Indianapolis', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2016, 2028, 'confirmed'),
  ('Daniel Lurie', 'Mayor', 'City', 'CA', 'San Francisco', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2025, 2029, 'confirmed'),
  ('Craig Greenberg', 'Mayor', 'City', 'KY', 'Louisville', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2023, 2027, 'confirmed'),
  ('Katie Wilson', 'Mayor', 'City', 'WA', 'Seattle', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2026, 2030, 'confirmed'),
  ('Freddie O''Connell', 'Mayor', 'City', 'TN', 'Nashville', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2023, 2027, 'confirmed'),
  ('Michael Johnston', 'Mayor', 'City', 'CO', 'Denver', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2023, 2027, 'confirmed'),
  ('David Holt', 'Mayor', 'City', 'OK', 'Oklahoma City', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2018, 2026, 'confirmed'),
  ('Muriel Bowser', 'Mayor', 'City', 'DC', 'Washington, D.C.', NULL, NULL, NULL, 'https://mayor.dc.gov/', 'elected', NULL, 'DC Mayor official site', 'https://mayor.dc.gov/biography/muriel-bowser', 'Strong mayor', 2015, 2027, 'confirmed'),
  ('Renard Johnson', 'Mayor', 'City', 'TX', 'El Paso', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2025, 2029, 'confirmed'),
  ('Shelley Berkley', 'Mayor', 'City', 'NV', 'Las Vegas', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2024, 2028, 'confirmed'),
  ('Michelle Wu', 'Mayor', 'City', 'MA', 'Boston', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2021, 2030, 'confirmed'),
  ('Mary Sheffield', 'Mayor', 'City', 'MI', 'Detroit', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2026, 2030, 'confirmed'),
  ('Keith Wilson', 'Mayor', 'City', 'OR', 'Portland', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Hybrid', 2025, 2029, 'confirmed'),
  ('Paul Young', 'Mayor', 'City', 'TN', 'Memphis', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2024, 2028, 'confirmed'),
  ('Brandon M. Scott', 'Mayor', 'City', 'MD', 'Baltimore', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2024, 2028, 'confirmed'),
  ('Cavalier Johnson', 'Mayor', 'City', 'WI', 'Milwaukee', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2021, 2028, 'confirmed'),
  ('Tim Keller', 'Mayor', 'City', 'NM', 'Albuquerque', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2017, 2029, 'confirmed'),
  ('Jerry Dyer', 'Mayor', 'City', 'CA', 'Fresno', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Hybrid', 2025, 2029, 'confirmed'),
  ('Regina Romero', 'Mayor', 'City', 'AZ', 'Tucson', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2019, 2027, 'confirmed'),
  ('Kevin McCarty', 'Mayor', 'City', 'CA', 'Sacramento', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2024, 2028, 'confirmed'),
  ('Andre Dickens', 'Mayor', 'City', 'GA', 'Atlanta', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2022, 2030, 'confirmed'),
  ('Quinton Lucas', 'Mayor', 'City', 'MO', 'Kansas City', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2019, 2027, 'confirmed'),
  ('Mark Freeman', 'Mayor', 'City', 'AZ', 'Mesa', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2025, 2029, 'confirmed'),
  ('Janet Cowell', 'Mayor', 'City', 'NC', 'Raleigh', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2024, 2026, 'confirmed'),
  ('Yemi Mobolade', 'Mayor', 'City', 'CO', 'Colorado Springs', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2023, 2027, 'confirmed'),
  ('Eileen Higgins', 'Mayor', 'City', 'FL', 'Miami', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Hybrid', 2025, 2029, 'confirmed'),
  ('John Ewing Jr.', 'Mayor', 'City', 'NE', 'Omaha', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2025, 2029, 'confirmed'),
  ('Bob Dyer', 'Mayor', 'City', 'VA', 'Virginia Beach', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2018, 2028, 'confirmed'),
  ('Rex Richardson', 'Mayor', 'City', 'CA', 'Long Beach', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2022, 2026, 'confirmed'),
  ('Barbara Lee', 'Mayor', 'City', 'CA', 'Oakland', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Hybrid', 2025, 2027, 'confirmed'),
  ('Jacob Frey', 'Mayor', 'City', 'MN', 'Minneapolis', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2022, 2030, 'confirmed'),
  ('Karen Goh', 'Mayor', 'City', 'CA', 'Bakersfield', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2017, 2029, 'confirmed'),
  ('Monroe Nichols', 'Mayor', 'City', 'OK', 'Tulsa', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2024, 2028, 'confirmed'),
  ('Jane Castor', 'Mayor', 'City', 'FL', 'Tampa', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2019, 2027, 'confirmed'),
  ('Mike Coffman', 'Mayor', 'City', 'CO', 'Aurora', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2019, 2027, 'confirmed'),
  ('Jim Ross', 'Mayor', 'City', 'TX', 'Arlington', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2021, 2026, 'confirmed'),
  ('Lily Wu', 'Mayor', 'City', 'KS', 'Wichita', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2024, 2028, 'confirmed'),
  ('Justin Bibb', 'Mayor', 'City', 'OH', 'Cleveland', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2022, 2030, 'confirmed'),
  ('Helena Moreno', 'Mayor', 'City', 'LA', 'New Orleans', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2026, 2030, 'confirmed'),
  ('Michelle Romero', 'Mayor', 'City', 'NV', 'Henderson', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2023, 2027, 'confirmed'),
  ('Rick Blangiardi', 'Mayor', 'City', 'HI', 'Honolulu', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2021, 2028, 'confirmed'),
  ('Ashleigh Aitken', 'Mayor', 'City', 'CA', 'Anaheim', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2022, 2026, 'confirmed'),
  ('Buddy Dyer', 'Mayor', 'City', 'FL', 'Orlando', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2003, 2028, 'confirmed'),
  ('Linda Gorton', 'Mayor', 'City', 'KY', 'Lexington', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2019, 2027, 'confirmed'),
  ('Christina Fugazi', 'Mayor', 'City', 'CA', 'Stockton', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2025, 2029, 'confirmed'),
  ('Ras J. Baraka', 'Mayor', 'City', 'NJ', 'Newark', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2014, 2026, 'confirmed'),
  ('Patricia Lock Dawson', 'Mayor', 'City', 'CA', 'Riverside', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2020, 2028, 'confirmed'),
  ('Larry Agran', 'Mayor', 'City', 'CA', 'Irvine', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2024, 2026, 'confirmed'),
  ('Paulette Guajardo', 'Mayor', 'City', 'TX', 'Corpus Christi', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2025, 2027, 'confirmed'),
  ('Valerie Amezcua', 'Mayor', 'City', 'CA', 'Santa Ana', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2022, 2026, 'confirmed'),
  ('Aftab Pureval', 'Mayor', 'City', 'OH', 'Cincinnati', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Hybrid', 2022, 2030, 'confirmed'),
  ('Marikay Abuzuaiter', 'Mayor', 'City', 'NC', 'Greensboro', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2025, 2029, 'confirmed'),
  ('Corey O''Connor', 'Mayor', 'City', 'PA', 'Pittsburgh', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2026, 2030, 'confirmed'),
  ('Kaohly Her', 'Mayor', 'City', 'MN', 'St. Paul', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2026, 2030, 'confirmed'),
  ('Leonardo Williams', 'Mayor', 'City', 'NC', 'Durham', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2023, 2027, 'confirmed'),
  ('James Solomon', 'Mayor', 'City', 'NJ', 'Jersey City', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2026, 2029, 'confirmed'),
  ('Leirion Gaylor Baird', 'Mayor', 'City', 'NE', 'Lincoln', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2019, 2027, 'confirmed'),
  ('Pamela Goynes-Brown', 'Mayor', 'City', 'NV', 'North Las Vegas', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2022, 2026, 'confirmed'),
  ('John Muns', 'Mayor', 'City', 'TX', 'Plano', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2021, 2029, 'confirmed'),
  ('Scott Anderson', 'Mayor', 'City', 'AZ', 'Gilbert', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Hybrid', 2025, 2029, 'confirmed'),
  ('Suzanne LaFrance', 'Mayor', 'City', 'AK', 'Anchorage', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Hybrid', 2024, 2027, 'confirmed'),
  ('Satya Rhodes-Conway', 'Mayor', 'City', 'WI', 'Madison', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2019, 2027, 'confirmed'),
  ('Hillary Schieve', 'Mayor', 'City', 'NV', 'Reno', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2014, 2026, 'confirmed'),
  ('Kevin Hartke', 'Mayor', 'City', 'AZ', 'Chandler', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2019, 2027, 'confirmed'),
  ('Cara Spencer', 'Mayor', 'City', 'MO', 'St. Louis', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2025, 2029, 'confirmed'),
  ('John McCann', 'Mayor', 'City', 'CA', 'Chula Vista', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2022, 2026, 'confirmed'),
  ('Sharon Tucker', 'Mayor', 'City', 'IN', 'Fort Wayne', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2024, 2027, 'confirmed'),
  ('Sean Ryan', 'Mayor', 'City', 'NY', 'Buffalo', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2026, 2030, 'confirmed'),
  ('Mark McBrayer', 'Mayor', 'City', 'TX', 'Lubbock', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2024, 2026, 'confirmed'),
  ('Victor Treviño', 'Mayor', 'City', 'TX', 'Laredo', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2022, 2026, 'confirmed'),
  ('Shannon Martin', 'Mayor', 'City', 'FL', 'Port St. Lucie', NULL, NULL, NULL, 'https://www.cityofpsl.com/Government/Your-City-Government/Mayor-City-Council/Mayor-Shannon-Martin', 'elected', NULL, 'City of Port St. Lucie', 'https://www.cityofpsl.com/Government/Your-City-Government/Mayor-City-Council/Mayor-Shannon-Martin', 'Council-manager', 2021, 2026, 'confirmed'),
  ('Kenneth Welch', 'Mayor', 'City', 'FL', 'St. Petersburg', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2022, 2027, 'confirmed'),
  ('Wade Kapszukiewicz', 'Mayor', 'City', 'OH', 'Toledo', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2022, 2026, 'confirmed'),
  ('Jerry Weiers', 'Mayor', 'City', 'AZ', 'Glendale', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2013, 2028, 'confirmed'),
  ('Allen Joines', 'Mayor', 'City', 'NC', 'Winston-Salem', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2001, 2028, 'confirmed'),
  ('Rick Stopfer', 'Mayor', 'City', 'TX', 'Irving', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2017, 2026, 'confirmed'),
  ('Richard West', 'Mayor', 'City', 'VA', 'Chesapeake', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2008, 2028, 'confirmed'),
  ('Dylan Hedrick', 'Mayor', 'City', 'TX', 'Garland', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2025, 2027, 'confirmed'),
  ('Lisa Borowsky', 'Mayor', 'City', 'AZ', 'Scottsdale', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Council-manager', 2025, 2029, 'confirmed'),
  ('Lauren McLean', 'Mayor', 'City', 'ID', 'Boise', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2020, 2028, 'confirmed'),
  ('Danny Avula', 'Mayor', 'City', 'VA', 'Richmond', NULL, NULL, NULL, NULL, 'elected', NULL, 'Ballotpedia', 'https://ballotpedia.org/United_States_mayoral_elections,_2028', 'Strong mayor', 2025, 2029, 'confirmed'),
  ('Mark Hill', 'Mayor', 'City', 'TX', 'Frisco', NULL, NULL, NULL, 'https://www.friscotexas.gov/2054/Mayor-Mark-Hill', 'elected', NULL, 'City of Frisco', 'https://www.friscotexas.gov/2054/Mayor-Mark-Hill', 'Council-manager', 2026, 2029, 'confirmed'),
  ('John Gunter', 'Mayor', 'City', 'FL', 'Cape Coral', NULL, NULL, NULL, 'https://www.capecoral.gov/government/city_council/mayor/index.php', 'elected', NULL, 'City of Cape Coral', 'https://www.capecoral.gov/government/city_council/mayor/index.php', 'Council-manager', 2022, 2026, 'confirmed'),
  ('Bill Cox', 'Mayor', 'City', 'TX', 'McKinney', NULL, NULL, NULL, 'https://www.mckinneytexas.org/1167/Council-Members', 'elected', NULL, 'City of McKinney', 'https://www.mckinneytexas.org/1167/Council-Members', 'Council-manager', 2025, 2029, 'confirmed'),
  ('Tommy Battle', 'Mayor', 'City', 'AL', 'Huntsville', NULL, NULL, NULL, 'https://www.huntsvilleal.gov/government/mayors-office/', 'elected', NULL, 'City of Huntsville', 'https://www.huntsvilleal.gov/government/voting-elections/elected-officials/', 'Strong mayor', 2008, 2028, 'confirmed');

-- Confirm:
-- select count(*) from public.local_officials where title = 'Mayor';
