-- HI state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'HI';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Adrian Tam', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '24', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Tam.jpg', 'elected', NULL),
('Amy Perruso', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '46', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Perruso.jpg', 'elected', NULL),
('Andrew Garrett', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '22', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Garrett.jpg', 'elected', NULL),
('Angus McKelvey', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '6', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/mckelvey.jpg', 'elected', NULL),
('Brandon Elefante', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '16', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/elefante.jpg', 'elected', NULL),
('Brenton Awa', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '23', NULL, 'Republican', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/awa.jpg', 'elected', NULL),
('Carol Fukunaga', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '11', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/fukunaga.jpg', 'elected', NULL),
('Chris Lee', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '25', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/clee.jpg', 'elected', NULL),
('Chris Muraoka', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '45', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/827989/827989.jpg', 'elected', NULL),
('Chris Todd', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '3', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Todd.jpg', 'elected', NULL),
('Cory Chun', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '35', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Chun.jpg', 'elected', NULL),
('Cov Ratcliffe', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '28', NULL, 'Democratic', 'https://wp.civilbeat.digitaldemocracy.org/wp-content/uploads/sites/3/2026/04/Screenshot-2026-04-15-at-2.52.51-PM.png?w=384&q=75', 'elected', NULL),
('Daisy Hartsfield', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '36', NULL, 'Democratic', NULL, 'elected', NULL),
('Darius Kila', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '44', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Kila.jpg', 'elected', NULL),
('David Tarnas', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '8', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Tarnas.jpg', 'elected', NULL),
('David Alcos', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '41', NULL, 'Republican', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Alcos.jpg', 'elected', NULL),
('Dee Morikawa', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '17', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Morikawa.jpg', 'elected', NULL),
('Della Belatti', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '26', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Belatti.jpg', 'elected', NULL),
('Diamond Garcia', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '42', NULL, 'Republican', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Garcia.jpg', 'elected', NULL),
('Donna Kim', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '14', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/kim.jpg', 'elected', NULL),
('Donovan Dela Cruz', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '17', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/delacruz.jpg', 'elected', NULL),
('Dru Kanuha', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '3', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/kanuha.jpg', 'elected', NULL),
('Elijah Pierick', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '39', NULL, 'Republican', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Pierick.jpg', 'elected', NULL),
('Elle Cochran', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '14', NULL, 'Republican', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Cochran.jpg', 'elected', NULL),
('Garner Shimizu', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '32', NULL, 'Republican', 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSUEhycIE3vAcgX_afwsIq8sAlJD9VW3SFAaNSI-Ey13ObCLFnj', 'elected', NULL),
('Glenn Wakai', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '15', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/wakai.jpg', 'elected', NULL),
('Gregg Takayama', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '34', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Takayama.jpg', 'elected', NULL),
('Greggor Ilagan', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '4', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Ilagan.jpg', 'elected', NULL),
('Tim Richards', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '4', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/richards.jpg', 'elected', NULL),
('Ikaika Hussey', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '29', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/IkaikaHussey2.jpeg', 'elected', NULL),
('Ikaika Olds', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '23', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Ikaika_Olds_20240812_095944.jpeg', 'elected', NULL),
('Jackson Sayama', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '21', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Sayama.jpg', 'elected', NULL),
('Jarrett Keohokalole', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '24', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/keohokalole.jpg', 'elected', NULL),
('Jeanné Kapela', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '5', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Kapela.jpg', 'elected', NULL),
('Jenna Takenouchi', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '27', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Takenouchi.jpg', 'elected', NULL),
('Joe Gedeon', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '18', NULL, 'Republican', NULL, 'elected', NULL),
('Joy San Buenaventura', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '2', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/sanbuenaventura.jpg', 'elected', NULL),
('Julie Reyes Oda', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '40', NULL, 'Republican', 'https://i0.wp.com/thefilipinochronicle.com/wp-content/uploads/2024/07/Julie-Reyes-Oda-scaled.jpg?resize=733%2C1024&ssl=1', 'elected', NULL),
('Justin Woodson', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '9', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Woodson.jpg', 'elected', NULL),
('Kanani Souza', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '43', NULL, 'Republican', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Souza.jpg', 'elected', NULL),
('Karl Rhoads', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '13', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/rhoads.jpg', 'elected', NULL),
('Kim Coco Iwamoto', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '25', NULL, 'Democratic', NULL, 'elected', NULL),
('Kirstin Kahaloa', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '6', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Kahaloa.jpg', 'elected', NULL),
('Kurt Fevella', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '20', NULL, 'Republican', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/fevella.jpg', 'elected', NULL),
('Kyle Yamashita', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '12', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Yamashita.jpg', 'elected', NULL),
('Lauren Matsumoto', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '38', NULL, 'Republican', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Matsumoto.jpg', 'elected', NULL),
('Les Ihara', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '10', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/ihara.jpg', 'elected', NULL),
('Linda Ichiyama', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '31', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Ichiyama.jpg', 'elected', NULL),
('Lisa Kitagawa', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '48', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Kitagawa.jpg', 'elected', NULL),
('Lisa Marten', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '51', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Marten.jpg', 'elected', NULL),
('Lorraine Inouye', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '1', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/inouye.jpg', 'elected', NULL),
('Luke Evslin', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '16', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Evslin.jpg', 'elected', NULL),
('Lynn DeCoite', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '7', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/decoite.jpg', 'elected', NULL),
('Mahina Poepoe', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '13', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Poepoe.jpg', 'elected', NULL),
('Mark Hashem', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '19', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Hashem.jpg', 'elected', NULL),
('Matthias Kusch', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '1', NULL, 'Democratic', 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/149765.jpg', 'elected', NULL),
('Michelle Kidani', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '18', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/kidani.jpg', 'elected', NULL),
('Mike Gabbard', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '21', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/gabbard.jpg', 'elected', NULL),
('Mike Lee', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '50', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/leemichael.jpg', 'elected', NULL),
('Nadine Nakamura', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '15', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Nakamura.jpg', 'elected', NULL),
('Nicole Lowen', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '7', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Lowen.jpg', 'elected', NULL),
('Rachele Lamosao', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '19', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Lamosao.jpg', 'elected', NULL),
('Ron Kouchi', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '8', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/kouchi.jpg', 'elected', NULL),
('Sam Kong', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '33', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Kong.jpg', 'elected', NULL),
('Samantha DeCorte', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '22', NULL, 'Republican', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/123803.jpg', 'elected', NULL),
('Scot Matayoshi', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '49', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Matayoshi.jpg', 'elected', NULL),
('Sean Quinlan', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '47', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Quinlan.jpg', 'elected', NULL),
('Sharon Moriwaki', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '12', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/moriwaki.jpg', 'elected', NULL),
('Shirley Templo', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '30', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Shirley_Ann_Templo.jpg', 'elected', NULL),
('Stanley Chang', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '9', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/schang.jpg', 'elected', NULL),
('Sue Lee Loy', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '2', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/SusanLeeLoy2024.png', 'elected', NULL),
('Terez Amato', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '11', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Amato.jpg', 'elected', NULL),
('Tina Grandinetti', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '20', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Anthony_Miranda_20240808_093602.jpg', 'elected', NULL),
('Trish La Chica', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '37', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/LaChica.jpg', 'elected', NULL),
('Troy Hashimoto', 'State Senator', 'Legislative Branch', 'Legislative', 'HI', '5', NULL, 'Democratic', 'http://www.capitol.hawaii.gov/MemberFiles/RepSenPhotos/Hashimoto.jpg', 'elected', NULL),
('Tyson Miyake', 'State Representative', 'Legislative Branch', 'Legislative', 'HI', '10', NULL, 'Democratic', NULL, 'elected', NULL);
