-- IA state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'IA';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Adam Zabner', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '90', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33993', 'elected', NULL),
('Adrian Dickey', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '44', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=31094', 'elected', NULL),
('Aime Wichtendahl', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '80', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37390', 'elected', NULL),
('Amy Nielsen', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '85', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18050', 'elected', NULL),
('Amy Sinclair', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '12', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10729', 'elected', NULL),
('Angel Ramirez', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '78', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=6145', 'elected', NULL),
('Ann Meyer', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '8', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27019', 'elected', NULL),
('Annette Sweeney', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '27', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=6585', 'elected', NULL),
('Art Staed', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '40', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10743', 'elected', NULL),
('Austin Baeth', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '36', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33976', 'elected', NULL),
('Austin Harris', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '26', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33971', 'elected', NULL),
('Barb Kniff McCulla', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '37', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33977', 'elected', NULL),
('Beth Wessel-Kroeschell', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '49', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=774&pType=3', 'elected', NULL),
('Bill Gustoff', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '40', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33978', 'elected', NULL),
('Blaine Watkins', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '100', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=28966', 'elected', NULL),
('Bob Kressig', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '75', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=781', 'elected', NULL),
('Bobby Kaufmann', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '82', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10756', 'elected', NULL),
('Brent Siegrist', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '19', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30646', 'elected', NULL),
('Brett Barker', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '51', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37386', 'elected', NULL),
('Brian Lohse', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '45', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27022', 'elected', NULL),
('Brian Meyer', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '29', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=6377', 'elected', NULL),
('Brooke Boden', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '21', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30648', 'elected', NULL),
('Carrie Koelker', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '33', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27001', 'elected', NULL),
('Carter Nordman', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '47', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30647', 'elected', NULL),
('Catelin Drey', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '1', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Catelin_Drey.png', 'elected', NULL),
('Chad Behn', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '48', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37384', 'elected', NULL),
('Chad Ingels', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '68', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30653', 'elected', NULL),
('Charley Thomson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '58', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33983', 'elected', NULL),
('Charlie McClintock', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '42', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30657', 'elected', NULL),
('Cherielynn Westrich', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '13', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30654', 'elected', NULL),
('Christian Hermanson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '59', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37387', 'elected', NULL),
('Cindy Golding', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '83', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33990', 'elected', NULL),
('Cindy Winckler', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '49', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=44', 'elected', NULL),
('Craig Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '67', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18075', 'elected', NULL),
('Craig Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '11', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30545', 'elected', NULL),
('Dan Dawson', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '10', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18072', 'elected', NULL),
('Dan Gehlbach', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '46', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33980', 'elected', NULL),
('Dan Gosa', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '81', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37391', 'elected', NULL),
('Dan Zumbach', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '34', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10733', 'elected', NULL),
('Dave Sires', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '38', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37464', 'elected', NULL),
('David Blom', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '52', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=25125', 'elected', NULL),
('Dave Rowley', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '5', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=32458', 'elected', NULL),
('David Young', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '28', NULL, 'Republican', NULL, 'elected', NULL),
('Dave Jacoby', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '86', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=320', 'elected', NULL),
('David Sieck', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '16', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=15920', 'elected', NULL),
('Dawn Driscoll', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '46', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30548', 'elected', NULL),
('Dean Fisher', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '53', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10755', 'elected', NULL),
('Dennis Guth', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '28', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10726', 'elected', NULL),
('Derek Wulf', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '76', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33986', 'elected', NULL),
('Devon Wood', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '17', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33968', 'elected', NULL),
('Doug Campbell', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '30', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37463', 'elected', NULL),
('Eddie Andrews', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '43', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30650', 'elected', NULL),
('Elinor Levin', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '89', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33992', 'elected', NULL),
('Elizabeth Wilson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '73', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33985', 'elected', NULL),
('Eric Gjerde', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '74', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30659', 'elected', NULL),
('Gary Mohr', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '93', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18038', 'elected', NULL),
('Hans Wilz', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '25', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33970', 'elected', NULL),
('Heather Hora', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '92', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33995', 'elected', NULL),
('Heather Matson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '42', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27023', 'elected', NULL),
('Helena Hayes', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '88', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33991', 'elected', NULL),
('Henry Stone', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '9', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30645', 'elected', NULL),
('Herman Quirmbach', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '25', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=161', 'elected', NULL),
('Izaah Knox', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '17', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=34010', 'elected', NULL),
('J.D. Scholten', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '1', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33963', 'elected', NULL),
('Jack Whitver', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '23', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=9768', 'elected', NULL),
('Jacob Bossman', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '14', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=25497', 'elected', NULL),
('Jane Bloomingdale', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '60', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18043', 'elected', NULL),
('Janet Petersen', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '18', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=72&pType=3', 'elected', NULL),
('Janice Weiner', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '45', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=34011', 'elected', NULL),
('Jason Gearhart', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '64', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37388', 'elected', NULL),
('Jason Schultz', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '6', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=6588', 'elected', NULL),
('Jeff Cooling', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '77', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33987', 'elected', NULL),
('Jeff Reichman', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '50', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30549', 'elected', NULL),
('Jeff Shipley', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '87', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27036', 'elected', NULL),
('Jeff Taylor', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '2', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30544', 'elected', NULL),
('Jennifer Konfrst', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '32', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27026', 'elected', NULL),
('Jennifer Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '72', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37389', 'elected', NULL),
('Jerome Amos', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '62', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=6174', 'elected', NULL),
('Jesse Green', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '24', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30546', 'elected', NULL),
('John Wills', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '10', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=13794', 'elected', NULL),
('Jon Dunwell', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '38', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=32165', 'elected', NULL),
('Josh Turek', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '20', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33969', 'elected', NULL),
('Josh Meggers', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '54', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33981', 'elected', NULL),
('Judd Lawler', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '91', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37392', 'elected', NULL),
('Julian Garrett', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '11', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=9404', 'elected', NULL),
('Kara Warme', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '26', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37462', 'elected', NULL),
('Ken Croken', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '97', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33997', 'elected', NULL),
('Ken Rozenboom', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '19', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10731', 'elected', NULL),
('Kenan Judge', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '27', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27027', 'elected', NULL),
('Kerry Gruenhagen', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '41', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=34009', 'elected', NULL),
('Kevin Alons', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '7', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33999', 'elected', NULL),
('Larry McBurney', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '44', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37383', 'elected', NULL),
('Lindsay James', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '71', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27039', 'elected', NULL),
('Liz Bennett', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '39', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=34000', 'elected', NULL),
('Lynn Evans', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '3', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=34008', 'elected', NULL),
('Mark Cisneros', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '96', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30656', 'elected', NULL),
('Mark Costello', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '8', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10749', 'elected', NULL),
('Mark Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '56', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33982', 'elected', NULL),
('Mark Lofgren', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '48', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=9406', 'elected', NULL),
('Mary Madison', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '31', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33974', 'elected', NULL),
('Matt Blake', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '22', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37460', 'elected', NULL),
('Matt Windschitl', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '15', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=6282', 'elected', NULL),
('Matt Rinker', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '99', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33998', 'elected', NULL),
('Megan Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '6', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10747', 'elected', NULL),
('Megan Srinivas', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '30', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33973', 'elected', NULL),
('Michael Bergan', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '63', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18044', 'elected', NULL),
('Mike Bousselot', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '21', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=32076&pType=3', 'elected', NULL),
('Mike Klimesh', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '32', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30547', 'elected', NULL),
('Mike Pike', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '20', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37458', 'elected', NULL),
('Mike Vondran', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '94', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33996', 'elected', NULL),
('Mike Zimmer', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '35', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37960', 'elected', NULL),
('Molly Donahue', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '37', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27031', 'elected', NULL),
('Monica Kurth', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '98', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18614', 'elected', NULL),
('Norlin Mommsen', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '70', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=14810', 'elected', NULL),
('Pat Grassley', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '57', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=6277', 'elected', NULL),
('Bubba Sorensen', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '23', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27020', 'elected', NULL),
('Renee Hardman', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '16', NULL, 'Democratic', 'https://media.tegna-media.com/assets/WOI/images/eb691334-5dc7-4bc6-9b19-2d2533483f86/eb691334-5dc7-4bc6-9b19-2d2533483f86_1920x1080.jpg', 'elected', NULL),
('Rick Olson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '39', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=776', 'elected', NULL),
('Rob Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '34', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37381', 'elected', NULL),
('Bob Henderson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '2', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33964', 'elected', NULL),
('Ross Wilburn', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '50', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=28701', 'elected', NULL),
('Ruth Ann Gaines', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '33', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=9413', 'elected', NULL),
('Ryan Weldon', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '41', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37382', 'elected', NULL),
('Sam Wengryn', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '24', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37380', 'elected', NULL),
('Samantha Fett', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '22', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37379', 'elected', NULL),
('Sandy Salmon', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '29', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=10754', 'elected', NULL),
('Sarah Garriott', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '14', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30551', 'elected', NULL),
('Scott Webster', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '47', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=13574', 'elected', NULL),
('Sean Bagniewski', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '35', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33975', 'elected', NULL),
('Shannon Latham', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '55', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30651', 'elected', NULL),
('Shannon Lundgren', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '65', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18046', 'elected', NULL),
('Skyler Wheeler', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '4', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=18040', 'elected', NULL),
('Steve Bradley', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '66', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=30652', 'elected', NULL),
('Steven Holt', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '12', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=14802', 'elected', NULL),
('Taylor Collins', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '95', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27618', 'elected', NULL),
('Tom Gerhold', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '84', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27033', 'elected', NULL),
('Tim Kraayenbrink', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '4', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=14812', 'elected', NULL),
('Timi Brown-Powers', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '61', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=14805', 'elected', NULL),
('Tom Determann', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '69', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33984', 'elected', NULL),
('Tom Jeneary', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '3', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27018', 'elected', NULL),
('Tom Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '18', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=17112', 'elected', NULL),
('Tom Shipley', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '9', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=14814', 'elected', NULL),
('Tom Townsend', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '36', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37465', 'elected', NULL),
('Tony Bisignano', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '15', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=906', 'elected', NULL),
('Tracy Ehlert', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '79', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27032', 'elected', NULL),
('Travis Sitzmann', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '13', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=37378', 'elected', NULL),
('Wendy Larson', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '7', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=39538', 'elected', NULL),
('Bill Dotzler', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '31', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=157', 'elected', NULL),
('Zach Dieken', 'State Representative', 'Legislative Branch', 'Legislative', 'IA', '5', NULL, 'Republican', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=33965', 'elected', NULL),
('Zach Wahls', 'State Senator', 'Legislative Branch', 'Legislative', 'IA', '43', NULL, 'Democratic', 'https://www.legis.iowa.gov/photo?action=getPhoto&ga=91&pid=27002', 'elected', NULL);
