-- ID state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'ID';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Ali Rabe', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '16', NULL, 'Democratic', 'https://cdn.theorg.com/61b74bbb-61b5-48d5-a84d-fb498da306b9_thumb.jpg', 'elected', NULL),
('Annie Henderson Haws', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '16B', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Haws10055.jpg', 'elected', NULL),
('Barbara Ehardt', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '33A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Ehardt4945.jpg', 'elected', NULL),
('Ben Adams', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '12', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Adams6685.jpg', 'elected', NULL),
('Ben Fuhriman', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '30B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Fuhriman9429.jpg', 'elected', NULL),
('Ben Toews', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '4', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Toews7795.jpg', 'elected', NULL),
('Brandon Mitchell', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '6B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Mitchell6704.jpg', 'elected', NULL),
('Brandon Shippy', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '9', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Shippy9215.jpg', 'elected', NULL),
('Brent Crane', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '13A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Crane21.jpg', 'elected', NULL),
('Brian Lenney', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '13', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Lenney7778.jpg', 'elected', NULL),
('Britt Raybould', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '34B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Raybould5381.jpg', 'elected', NULL),
('Brooke Green', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '18B', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Green5374.jpg', 'elected', NULL),
('Bruce Skaug', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '10B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Skaug6708.jpg', 'elected', NULL),
('Scott Grow', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '14', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Grow5126.jpg', 'elected', NULL),
('Camille Blaylock', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '11', NULL, 'Republican', 'https://idgop.org/wp-content/uploads/sites/4/2024/05/blaylock-1.jpg', 'elected', NULL),
('Carl Bjerke', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '5', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Bjerke7796.jpg', 'elected', NULL),
('Carrie Semmelroth', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '17', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2022/directory/Semmelroth7115.jpg', 'elected', NULL),
('Charlie Shepherd', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '7B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Shepherd6707.jpg', 'elected', NULL),
('Chris Bruce', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '23A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Bruce9423.jpg', 'elected', NULL),
('Chris Mathias', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '19B', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Mathias6703.jpg', 'elected', NULL),
('Christy Zito', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '8', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Zito4281.jpg', 'elected', NULL),
('Cindy Carlson', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '7', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Carlson7776.jpg', 'elected', NULL),
('Clay Handy', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '27B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Handy7811.jpg', 'elected', NULL),
('Clint Hostetler', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '24A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Hostetler9425.jpg', 'elected', NULL),
('Codi Galloway', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '15', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Galloway6702.jpg', 'elected', NULL),
('Cornel Rasor', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '1B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Rasor9315.jpg', 'elected', NULL),
('Dale Hawkins', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '2B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Hawkins7855.jpg', 'elected', NULL),
('Dan Garner', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '28B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Garner7813.jpg', 'elected', NULL),
('Dan Foreman', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '6', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Foreman4269.jpg', 'elected', NULL),
('Dave Lent', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '33', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Lent5345.jpg', 'elected', NULL),
('David Leavitt', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '25B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Leavitt9426.jpg', 'elected', NULL),
('David Cannon', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '30A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Cannon6699.jpg', 'elected', NULL),
('Don Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '25A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Hall10355.jpg', 'elected', NULL),
('Dori Healey', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '15B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Healey7861.jpg', 'elected', NULL),
('Doug Okuniewicz', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '3', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Okuniewicz6706.jpg', 'elected', NULL),
('Doug Ricks', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '34', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Ricks5383.jpg', 'elected', NULL),
('Doug Pickett', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '27A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Pickett7810.jpg', 'elected', NULL),
('Dustin Manwaring', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '29A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Manwaring4277.jpg', 'elected', NULL),
('Ted Hill', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '14A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Hill7859.jpg', 'elected', NULL),
('Elaine Price', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '4B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Price7856.jpg', 'elected', NULL),
('Erin Bingham', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '32B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Bingham10415.jpg', 'elected', NULL),
('Faye Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '8B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Thompson9420.jpg', 'elected', NULL),
('Glenneda Zuiderveld', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '24', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Zuiderveld7798.jpg', 'elected', NULL),
('Heather Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '2A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2019/directory/Scott3137.jpg', 'elected', NULL),
('Ilana Rubel', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '18A', NULL, 'Democratic', 'https://idahocapitalsun.com/wp-content/uploads/2021/04/IlanaRubel-scaled.jpg', 'elected', NULL),
('Jack Nelsen', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '26B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Nelsen7838.jpg', 'elected', NULL),
('James Ruchti', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '29', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Ruchti52.jpg', 'elected', NULL),
('James Holtzclaw', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '20B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2017/directory/Holtzclaw2086.jpg', 'elected', NULL),
('James Petzke', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '21A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Petzke7863.jpg', 'elected', NULL),
('Janie Ward-Engelking', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '18', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Ward-Engelking2091.jpg', 'elected', NULL),
('Jaron Crane', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '12B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Crane7803.jpg', 'elected', NULL),
('Jason Monks', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '22B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Monks2084.jpg', 'elected', NULL),
('Jeff Ehlers', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '21B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Ehlers7805.jpg', 'elected', NULL),
('Jeff Cornilles', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '12A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Cornilles7802.jpg', 'elected', NULL),
('Jerald Raymond', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '31A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Raymond5382.jpg', 'elected', NULL),
('Jim Guthrie', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '28', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2017/directory/Guthrie1179.jpg', 'elected', NULL),
('Jim Woodward', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '1', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Woodward5347.jpg', 'elected', NULL),
('Joe Alfieri', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '4A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Alfieri7857.jpg', 'elected', NULL),
('Joe Palmer', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '20A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Palmer749.jpg', 'elected', NULL),
('John Gannon', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '17A', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2017/directory/Gannon2144.jpg', 'elected', NULL),
('John Shirts', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '9A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Shirts9421.jpg', 'elected', NULL),
('John Vander Woude', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '22A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2017/directory/Vander%20Woude67.jpg', 'elected', NULL),
('Jon Weber', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '34A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Weber6709.jpg', 'elected', NULL),
('Jordan Redman', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '3B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Redman7800.jpg', 'elected', NULL),
('Josh Keyser', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '20', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Keyser9395.jpg', 'elected', NULL),
('Josh Kohl', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '25', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Kohl9401.jpg', 'elected', NULL),
('Josh Tanner', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '14B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Tanner7860.jpg', 'elected', NULL),
('Josh Wheeler', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '35B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Wheeler7839.jpg', 'elected', NULL),
('Judy Boyle', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '9B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Boyle745.jpg', 'elected', NULL),
('Julie VanOrden', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '30', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2017/directory/VanOrden2129.jpg', 'elected', NULL),
('Kelly Anthon', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '27', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzBUr0WfBwwJVjrJhYaJYV9f99Qba5dm5P6g&s', 'elected', NULL),
('Kent Marmon', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '11A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Marmon9417.jpg', 'elected', NULL),
('Kevin Cook', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '32', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/Cook6686.jpg', 'elected', NULL),
('Kyle Harris', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '7A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Harris9415.jpg', 'elected', NULL),
('Lori Den Hartog', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '22', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2017/directory/Den%20Hartog3124.jpg', 'elected', NULL),
('Lori McCann', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '6A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2021/directory/McCann6955.jpg', 'elected', NULL),
('Lucas Cayler', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '11B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Cayler9418.jpg', 'elected', NULL),
('Marco Erickson', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '33B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Erickson6700.jpg', 'elected', NULL),
('Mark Harris', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '35', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2017/directory/Harris3584.jpg', 'elected', NULL),
('Mark Sauter', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '1A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Sauter7799.jpg', 'elected', NULL),
('Megan Egbert', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '17B', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2024/directory/Egbert9195.jpg', 'elected', NULL),
('Melissa Wintrow', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '19', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Wintrow3139.jpg', 'elected', NULL),
('Mike Moyle', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '10A', NULL, 'Republican', 'https://www.idahoednews.org/wp-content/uploads/2018/12/Mike-Moyle-620x477.jpg', 'elected', NULL),
('Mike Pohanka', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '26A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Pohanka9427.jpg', 'elected', NULL),
('Mike Veile', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '35A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Veile10155.jpg', 'elected', NULL),
('Monica Church', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '19A', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Church9422.jpg', 'elected', NULL),
('Phil Hart', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '2', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Hart26.jpg', 'elected', NULL),
('Rick Cheatum', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '28A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2026/directory/Cheatum7812.jpg', 'elected', NULL),
('Rob Beiswenger', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '8A', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9psK7gbvCRFwbID4kl-z8CYjGocsNnfsafQ&s', 'elected', NULL),
('Rod Furniss', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '31B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2019/directory/Furniss5372.jpg', 'elected', NULL),
('Ron Taylor', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '26', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Taylor7836.jpg', 'elected', NULL),
('Ron Mendive', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '5A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2019/directory/Mendive2124.jpg', 'elected', NULL),
('Shawn Dygert', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '23B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Dygert9424.jpg', 'elected', NULL),
('Soñia Galaviz', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '16A', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Galaviz7862.jpg', 'elected', NULL),
('Stephanie Mickelsen', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '32A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Mickelsen7814.jpg', 'elected', NULL),
('Steve Berch', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '15A', NULL, 'Democratic', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2019/directory/Berch5368.jpg', 'elected', NULL),
('Steve Tanner', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '13B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2025/directory/Tanner9419.jpg', 'elected', NULL),
('Steve Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '24B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Miller2134.jpg', 'elected', NULL),
('Tammy Nichols', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '10', NULL, 'Republican', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Tammy_Nichols_Election_Photo.jpg/500px-Tammy_Nichols_Election_Photo.jpg', 'elected', NULL),
('Tanya Burgoyne', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '29B', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/812118/812118.jpg', 'elected', NULL),
('Todd Lakey', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '23', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Lakey2132.jpg', 'elected', NULL),
('Tony Wisniewski', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '5B', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2019/directory/Wisniewski5384.jpg', 'elected', NULL),
('Treg Bernt', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '21', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Bernt7797.jpg', 'elected', NULL),
('Van Burtenshaw', 'State Senator', 'Legislative Branch', 'Legislative', 'ID', '31', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2023/directory/Burtenshaw3140.jpg', 'elected', NULL),
('Vito Barbieri', 'State Representative', 'Legislative Branch', 'Legislative', 'ID', '3A', NULL, 'Republican', 'https://legislature.idaho.gov/wp-content/uploads/sessioninfo/2019/directory/Barbieri1171.jpg', 'elected', NULL);
