-- KS state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'KS';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Abi Boatman', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '86', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_boatman_abi_1.jpg', 'elected', NULL),
('Adam Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '120', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_smith_adam_1.jpg', 'elected', NULL),
('Adam Thomas', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '23', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_thomas_adam_1.jpg', 'elected', NULL),
('Adam Turk', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '117', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_turk_adam_1.jpg', 'elected', NULL),
('Alexis Simmons', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '58', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_simmons_alexis_1.jpg', 'elected', NULL),
('Allen Reavis', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '63', NULL, 'Republican', 'https://www.atchisoncountyks.org/ImageRepository/Document?documentID=2708', 'elected', NULL),
('Angel Roeser', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '67', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_roeser_angelina_1.jpg', 'elected', NULL),
('Angela Martinez', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '103', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_martinez_angela_1.jpg', 'elected', NULL),
('Angela Stiens', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '39', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_stiens_angela_1.jpg', 'elected', NULL),
('Avery Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '72', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_anderson_avery_1.jpg', 'elected', NULL),
('Barbara Ballard', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '44', NULL, 'Democratic', 'https://ogden_images.s3.amazonaws.com/www.ljworld.com/images/2016/07/20043350/candidate_Barbara_Ballard003-714x1024.jpg', 'elected', NULL),
('Barb Wasinger', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '111', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_wasinger_barbara_1.jpg', 'elected', NULL),
('Beverly Gossage', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '9', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_gossage_beverly_1.jpg', 'elected', NULL),
('Bill Clifford', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '39', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_clifford_william_1.jpg', 'elected', NULL),
('Bill Rhiley', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '80', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_rhiley_bill_1.jpg', 'elected', NULL),
('Bill Sutton', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '43', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_sutton_william_1.jpg', 'elected', NULL),
('Blake Carpenter', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '81', NULL, 'Republican', 'https://www.carpenterforkansas.com/wp-content/uploads/2022/07/Carpenter-Blues-Photo.png', 'elected', NULL),
('Bob Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '123', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_lewis_bob_1.jpg', 'elected', NULL),
('Brad Barrett', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '76', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_barrett_bradley_1.jpg', 'elected', NULL),
('Brad Starnes', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '22', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_starnes_brad_1.jpg', 'elected', NULL),
('Brandon Woodard', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '108', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_woodard_brandon_1.jpg', 'elected', NULL),
('Brenda Dietrich', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '20', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/rep_dietrich_brenda_1.jpg', 'elected', NULL),
('Brett Fairchild', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '113', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_fairchild_brett_1.jpg', 'elected', NULL),
('Brian Bergkamp', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '93', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Brian-Bergkamp.jpg', 'elected', NULL),
('Brooklynne Mosley', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '46', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_mosley_brooklynne_1.jpg', 'elected', NULL),
('Carl Turner', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '28', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_turner_carl_1.jpg', 'elected', NULL),
('Carolyn Caiharr', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '33', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_caiharr_carolyn_1.jpg', 'elected', NULL),
('Caryn Tyson', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '12', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_tyson_caryn_1.jpg', 'elected', NULL),
('Chuck Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '3', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_smith_charles_1.jpg', 'elected', NULL),
('Charlotte Esau', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '14', NULL, 'Republican', 'https://jcrpks.org/wp-content/uploads/2024/07/MbZyrxoRqtLO-EsauMediaHeadshot-3-668x900.jpg', 'elected', NULL),
('Chase Blasi', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '26', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_blasi_chase_1.jpg', 'elected', NULL),
('Chip VanHouden', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '26', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_vanhouden_charles_1.jpg', 'elected', NULL),
('Chris Croft', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '8', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_croft_chris_1.jpg', 'elected', NULL),
('Cindy Holscher', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '8', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Cindy-Holscher.jpg', 'elected', NULL),
('Cindy Neighbor', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '18', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_neighbor_cindy_1.jpg', 'elected', NULL),
('Clarke Sanders', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '69', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_sanders_clarke_1.jpg', 'elected', NULL),
('Courtney Sappington', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '5', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_sappington_courtney_1.jpg', 'elected', NULL),
('Craig Bowser', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '1', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Craig_Bowser.jpg', 'elected', NULL),
('Cyndi Howerton', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '98', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_howerton_cyndi_1.jpg', 'elected', NULL),
('Dale Helwig', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '1', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Dale_Helwig_20241007_022311.jpg', 'elected', NULL),
('Dan Goddard', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '7', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_goddard_dan_1.jpg', 'elected', NULL),
('Dan Osman', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '48', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_osman_dan_1.jpg', 'elected', NULL),
('Dan Hawkins', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '100', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_hawkins_daniel_1.jpg', 'elected', NULL),
('Dave Buehler', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '40', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_buehler_david_1.jpg', 'elected', NULL),
('David Haley', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '4', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/606b1f70a46bfa6ea792c03e/1618942086989-LIN2C4WCFMR47RKYDJ5V/Haley.jpg?format=1000w', 'elected', NULL),
('Dawn Wolf', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '107', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_wolf_dawn_1.jpg', 'elected', NULL),
('Dinah Sykes', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '21', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/sen_sykes_dinah_1.jpg', 'elected', NULL),
('Doug Blex', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '12', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_blex_doug_1.jpg', 'elected', NULL),
('Doug Shane', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '37', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_shane_doug_1.jpg', 'elected', NULL),
('Duane Droge', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '13', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_droge_duane_1.jpg', 'elected', NULL),
('Elaine Bowers', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '36', NULL, 'Republican', 'https://img1.wsimg.com/isteam/ip/80c40439-022d-4960-b9db-9edee1fb7239/116288352_1853414708116161_8330522447916288057.jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=h:500,cg:true', 'elected', NULL),
('Emil Bergquist', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '91', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_bergquist_emil_1.jpg', 'elected', NULL),
('Ethan Corson', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '7', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/sen_corson_ethan_1.jpg', 'elected', NULL),
('Ford Carr', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '84', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_carr_ford_1.jpg', 'elected', NULL),
('Francis Awerkamp', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '61', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_awerkamp_francis_1.jpg', 'elected', NULL),
('Fred Gardner', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '9', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_gardner_fred_1.jpg', 'elected', NULL),
('Gary White', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '115', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Gary_White.jpeg', 'elected', NULL),
('Greg Wilson', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '70', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/abilene-rc.com/content/tncms/assets/v3/editorial/9/19/919822b8-7b58-4d49-bf1d-499f9f717319/6882afbe93db1.image.jpg?resize=300%2C504', 'elected', NULL),
('Heather Meyer', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '29', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_meyer_heather_1.jpg', 'elected', NULL),
('Henry Helgerson', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '83', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/rep_helgerson_henry_1.jpg', 'elected', NULL),
('Jarrod Ousley', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '24', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_ousley_jarrod_1.jpg', 'elected', NULL),
('Jason Goetz', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '119', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_goetz_jason_1.jpg', 'elected', NULL),
('Jeff Klemp', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '5', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JeffKlemp2024.jpg', 'elected', NULL),
('Jerry Stogsdill', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '21', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_stogsdill_jerry_1.jpg', 'elected', NULL),
('Jesse Borjon', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '52', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_borjon_jesse_1.jpg', 'elected', NULL),
('Jill Ward', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '105', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JillWard24.jpeg', 'elected', NULL),
('Jim Minnix', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '118', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_minnix_jim_1.jpg', 'elected', NULL),
('Jo Ella Hoye', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '17', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jo-Ella-Hoye.PNG', 'elected', NULL),
('Joe Claeys', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '27', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_claeys_joseph_1.jpg', 'elected', NULL),
('Joe Seiwert', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '101', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_seiwert_joe_1.jpg', 'elected', NULL),
('John Alcala', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '57', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_alcala_john_1.jpg', 'elected', NULL),
('John Carmichael', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '92', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/John_Carmichael.jpg', 'elected', NULL),
('K.C. Ohaebosim', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '89', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_ohaebosim_kc_1.jpg', 'elected', NULL),
('Kellie Warren', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '11', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_warren_kellie_1.jpg', 'elected', NULL),
('Ken Corbet', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '54', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_corbet_ken_1.jpg', 'elected', NULL),
('Ken Rahjes', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '110', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_rahjes_ken_1.jpg', 'elected', NULL),
('Ken Collins', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '2', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_collins_kenneth_1.jpg', 'elected', NULL),
('Kenny Titus', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '18', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_titus_kenny_1.jpg', 'elected', NULL),
('Kevin Schwertfeger', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '114', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_schwertfeger_kevin_1.jpg', 'elected', NULL),
('Kirk Haskins', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '53', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_haskins_kirk_1.jpg', 'elected', NULL),
('Kristey Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '77', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_williams_kristey_1.jpg', 'elected', NULL),
('Kyle Hoffman', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '116', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_hoffman_kyle_1.jpg', 'elected', NULL),
('Kyle McNorton', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '50', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_mcnorton_kyle_1.jpg', 'elected', NULL),
('Kyler Sweely', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '102', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_sweely_kyler_1.jpg', 'elected', NULL),
('Lance Neelly', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '42', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_neelly_lance_1.jpg', 'elected', NULL),
('Larry Alley', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '32', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Larry_Alley.jpg', 'elected', NULL),
('Laura Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '30', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_williams_laura_1.jpg', 'elected', NULL),
('Lauren Bohi', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '15', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_bohi_lauren_1.jpg', 'elected', NULL),
('Leah Howell', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '82', NULL, 'Republican', 'https://img1.wsimg.com/isteam/ip/534758f8-3fcd-4777-8cd5-06b294ad98e6/Snapseed.JPG/:/cr=t:0%25,l:0%25,w:100%25,h:100%25', 'elected', NULL),
('Leo Delperdang', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '94', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/rep_delperdang_leo_1.jpg', 'elected', NULL),
('Bill Bloom', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '64', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_bloom_lewis_1.jpg', 'elected', NULL),
('Linda Featherston', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '16', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Linda-Featherston.jpg', 'elected', NULL),
('Lindsay Vaughn', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '22', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_vaughn_lindsay_1.jpg', 'elected', NULL),
('Lisa Moser', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '106', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_moser_lisa_1.jpg', 'elected', NULL),
('Lon Pishny', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '122', NULL, 'Republican', 'https://chambermaster.blob.core.windows.net/images/customers/1593/representatives/11391/400x400/Lon+Pishny_2640500.jpg', 'elected', NULL),
('Louis Ruiz', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '31', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_ruiz_louis_1.jpg', 'elected', NULL),
('Lynn Melton', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '36', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_melton_lynn_1.jpg', 'elected', NULL),
('Marci Francisco', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '2', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/sen_francisco_marci_1.jpg', 'elected', NULL),
('Mari-Lynn Poskin', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '20', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_poskin_mari_lynn_1.jpg', 'elected', NULL),
('Mark Schreiber', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '60', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_schreiber_mark_1.jpg', 'elected', NULL),
('Marty Long', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '124', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_long_martin_1.jpg', 'elected', NULL),
('Megan Steele', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '51', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_steele_megan_1.jpg', 'elected', NULL),
('Melissa Oropeza', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '37', NULL, 'Democratic', 'https://static.wixstatic.com/media/b85886_bf3234c73f3d4fc9860eabd10f95d123~mv2.jpg', 'elected', NULL),
('Mike Fagg', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '14', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_fagg_michael_1.jpg', 'elected', NULL),
('Mike Murphy', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '34', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvKwXLW2-GGx639WKAs10NgKJgmOprF8JoSnBrc3tSNe41yMEh6bGuVEiIvAulBU795Tk&usqp=CAU', 'elected', NULL),
('Mike Amyx', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '45', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_amyx_mike_1.jpg', 'elected', NULL),
('Mike Argabright', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '17', NULL, 'Republican', 'https://firststudentinc.com/wp-content/uploads/Michael-Argabright-KS-SOY-2023.png', 'elected', NULL),
('Mike King', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '74', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_king_mike_1.jpg', 'elected', NULL),
('Mike Petersen', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '28', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_petersen_mike_1.jpg', 'elected', NULL),
('Mike Storm', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '121', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_storm_mike_1.jpg', 'elected', NULL),
('Mike Thompson', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '10', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_thompson_mike_1.jpg', 'elected', NULL),
('Nate Butler', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '68', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_butler_nathan_1.jpg', 'elected', NULL),
('Nick Hoheisel', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '97', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_hoheisel_nick_1.jpg', 'elected', NULL),
('Nikki McDonald', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '49', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_mcdonald_nikki_1.jpg', 'elected', NULL),
('Oletha Faust-Goudeau', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '29', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Oletha_Faust-Goudeau.jpg', 'elected', NULL),
('Pam Curtis', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '32', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_curtis_pam_1.jpg', 'elected', NULL),
('Pat Pettey', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '6', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/sen_pettey_pat_1.jpg', 'elected', NULL),
('Pat Proctor', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '41', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_proctor_pat_1.jpg', 'elected', NULL),
('Patrick Schmidt', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '19', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/sen_schmidt_patrick_1.jpg', 'elected', NULL),
('Paul Waggoner', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '104', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_waggoner_paul_1.jpg', 'elected', NULL),
('Rebecca Schmoe', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '59', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_schmoe_rebecca_1.jpg', 'elected', NULL),
('Renee Erickson', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '30', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_erickson_renee_1.jpg', 'elected', NULL),
('Rick Billinger', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '40', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_billinger_rick_1.jpg', 'elected', NULL),
('Rick James', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '4', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_james_ricky_1.jpg', 'elected', NULL),
('Rick Kloos', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '3', NULL, 'Republican', 'https://www.ksn.com/wp-content/uploads/sites/13/2018/10/20180607_Rick20Kloos20-20Govenor20Candidate_3420-20Alexandra20Martinez_1539633409099.jpg_59052445_ver1.0.jpg?w=2560&h=1440&crop=1', 'elected', NULL),
('Rick Wilborn', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '73', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_wilborn_rick_1.jpg', 'elected', NULL),
('Robyn Essex', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '78', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_essex_robyn_1.jpg', 'elected', NULL),
('Ron Bryce', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '11', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_bryce_ron_1.jpg', 'elected', NULL),
('Ronald Ellis', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '47', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_ellis_ronald_1.jpg', 'elected', NULL),
('Ron Ryckman', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '38', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_ryckman_ronald_1.jpg', 'elected', NULL),
('Rui Xu', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '25', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/rui_xu.jpg', 'elected', NULL),
('Samantha Poetter Parshall', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '6', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_poetter_samantha_1.jpg', 'elected', NULL),
('Sandy Pickert', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '88', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_pickert_sandy_1.jpg', 'elected', NULL),
('Scott Hill', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '24', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_hill_scott_1.jpg', 'elected', NULL),
('Sean Tarwater', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '27', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_tarwater_sean_1.jpg', 'elected', NULL),
('Sean Willcott', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '62', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_willcott_sean_1.jpg', 'elected', NULL),
('Shannon Francis', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '125', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_francis_shannon_1.jpg', 'elected', NULL),
('Shawn Chauncey', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '65', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_chauncey_shawn_1.jpg', 'elected', NULL),
('Sherri Brantley', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '112', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_brantley_sherri_1.jpg', 'elected', NULL),
('Silas Miller', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '25', NULL, 'Democratic', 'https://media.sharethetrail.net/prod_d_1/images/silas-miller_5_sq.height-800.jpg', 'elected', NULL),
('Stephanie Sawyer-Clayton', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '19', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_clayton_stephanie_1.jpg', 'elected', NULL),
('Stephen Owens', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '31', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_owens_stephen_1.jpg', 'elected', NULL),
('Steve Brunk', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '85', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_brunk_steve_1.jpg', 'elected', NULL),
('Steve Huebert', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '90', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_huebert_steve_1.jpg', 'elected', NULL),
('Steve Howe', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '71', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_howe_steven_1.jpg', 'elected', NULL),
('Susan Estes', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '87', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_estes_susan_2.jpg', 'elected', NULL),
('Susan Humphries', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '99', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_humphries_susan_1.jpg', 'elected', NULL),
('Susan Ruiz', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '23', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_ruiz_susan_1.jpg', 'elected', NULL),
('Suzanne Wikle', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '10', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/SuzanneWikle2024.jpg', 'elected', NULL),
('Sydney Carlin', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '66', NULL, 'Democratic', 'https://assets.nationbuilder.com/carlinforkansas/pages/22/attachments/original/1473126263/IMG_0437.JPG?1473126263', 'elected', NULL),
('T.J. Rose', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '35', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/TJ_Rose_20240808_093657.jpeg', 'elected', NULL),
('Tim Shallenburger', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '13', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_shallenburger_tim_1.jpg', 'elected', NULL),
('Tim Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '38', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_johnson_timothy_1.jpg', 'elected', NULL),
('Tobias Schlingensiepen', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '55', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/62a93b88228a337fdf4f80e2/1655346125169-V2O5XAAA56EL7GFUJ9L6/Tobias+4KH+0422.jpg?format=500w', 'elected', NULL),
('Tom Kessler', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '96', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_kessler_tom_1.jpg', 'elected', NULL),
('Tom Sawyer', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '95', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_sawyer_tom_1.jpg', 'elected', NULL),
('Tory Marie Blew', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '33', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_blew_marie_1.jpg', 'elected', NULL),
('Troy Waymaster', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '109', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_waymaster_troy_1.jpg', 'elected', NULL),
('Ty Masterson', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '16', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_masterson_ty_1.jpg', 'elected', NULL),
('Val Winn', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '34', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_winn_valdenia_1.jpg', 'elected', NULL),
('Virgil Peck', 'State Senator', 'Legislative Branch', 'Legislative', 'KS', '15', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/sen_peck_virgil_1.jpg', 'elected', NULL),
('Virgil Weigel', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '56', NULL, 'Democratic', 'https://www.kslegislature.gov/static/li_pics/rep_weigel_virgil_1.jpg', 'elected', NULL),
('Wanda Paige', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '35', NULL, 'Democratic', 'https://resources.finalsite.net/images/f_auto,q_auto,t_image_size_1/v1706627854/kckpsorg/nslthss5ye6gddnitdew/W_Paige.png', 'elected', NULL),
('Web Roth', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '79', NULL, 'Republican', 'https://www.kslegislature.gov/static/li_pics/rep_roth_webster_1.jpg', 'elected', NULL),
('Will Carpenter', 'State Representative', 'Legislative Branch', 'Legislative', 'KS', '75', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Will_Carpenter.jpg', 'elected', NULL);
