-- KY state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'KY';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Aaron Reed', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '7', NULL, 'Republican', 'https://gunleash.com/wp-content/uploads/2023/11/Aaron_Reed.jpg', 'elected', NULL),
('Aaron Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '98', NULL, 'Republican', 'https://content.campaignpartner.net/images/126420/Headshot.jpg', 'elected', NULL),
('Adam Bowling', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '87', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house87.jpg', 'elected', NULL),
('Adam Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '45', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/AdamMoore2024.jpg', 'elected', NULL),
('Adrielle Camuel', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '93', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house93.jpg', 'elected', NULL),
('Al Gentry', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '46', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house46.jpg', 'elected', NULL),
('Amanda Bledsoe', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '12', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate112.jpg', 'elected', NULL),
('Amy Neighbors', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '21', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house21.jpg', 'elected', NULL),
('Anne Donworth', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '76', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/AnneDonworth.jpeg', 'elected', NULL),
('Ashley Laferty', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '95', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house95.jpg', 'elected', NULL),
('Beverly Chester-Burton', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '44', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house44.jpg', 'elected', NULL),
('Bill Wesley', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '91', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house91.jpg', 'elected', NULL),
('Bobby McCool', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '97', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house97.jpg', 'elected', NULL),
('Brandon Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '30', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate130.jpg', 'elected', NULL),
('Brandon Storm', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '21', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate121.jpg', 'elected', NULL),
('Candy Massaroni', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '50', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house50.jpg', 'elected', NULL),
('Cassie Armstrong', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '19', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate119.jpg', 'elected', NULL),
('Chad Aull', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '79', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house79.jpg', 'elected', NULL),
('Chris Freeland', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '6', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house6.jpg', 'elected', NULL),
('Chris Fugate', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '84', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house84.jpg', 'elected', NULL),
('Chris Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '29', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ChrisLewis2024.jpeg', 'elected', NULL),
('Chris McDaniel', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '23', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate123.jpg', 'elected', NULL),
('Craig Richardson', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '3', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate103.jpg', 'elected', NULL),
('D.J. Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '13', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house13.jpg', 'elected', NULL),
('Daniel Elliott', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '54', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house54.jpg', 'elected', NULL),
('Dan Fister', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '56', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house56.jpg', 'elected', NULL),
('Daniel Grossberg', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '30', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house30.jpg', 'elected', NULL),
('Danny Carroll', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '2', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate102.jpg', 'elected', NULL),
('David Hale', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '74', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house74.jpg', 'elected', NULL),
('David Meade', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '80', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house80.jpg', 'elected', NULL),
('David Osborne', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '59', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house59.jpg', 'elected', NULL),
('David Givens', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '9', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate109.jpg', 'elected', NULL),
('Deanna Gordon', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '81', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house81.jpg', 'elected', NULL),
('Derek Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '90', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house90.jpg', 'elected', NULL),
('Don Douglas', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '22', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate122.jpg', 'elected', NULL),
('Emily Callaway', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '37', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house37.jpg', 'elected', NULL),
('Erika Hancock', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '57', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house57.jpg', 'elected', NULL),
('Felicia Rabourn', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '47', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house47.jpg', 'elected', NULL),
('Gary Boswell', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '8', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate108.jpg', 'elected', NULL),
('Gary Clemons', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '37', NULL, 'Democratic', NULL, 'elected', NULL),
('George Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '77', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house77.jpg', 'elected', NULL),
('Gerald Neal', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '33', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate133.jpg', 'elected', NULL),
('Gex Williams', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '20', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate120.jpg', 'elected', NULL),
('Greg Elkins', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '28', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate128.jpg', 'elected', NULL),
('J.T. Payne', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '11', NULL, 'Republican', 'https://thenews.org/wp-content/uploads/2018/08/7BD9AD2B-7439-4C90-86BE-692CC9C4D09A-777x437.jpeg', 'elected', NULL),
('James Tipton', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '53', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house53.jpg', 'elected', NULL),
('Jared Bauman', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '28', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house28.jpg', 'elected', NULL),
('Jared Carpenter', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '34', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate134.jpg', 'elected', NULL),
('Jason Howell', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '1', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate101.jpg', 'elected', NULL),
('Jason Nemes', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '33', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house33.jpg', 'elected', NULL),
('Jason Petrie', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '16', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house16.jpg', 'elected', NULL),
('Jennifer Decker', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '58', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house58.jpg', 'elected', NULL),
('Jim Gooch', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '12', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house12.jpg', 'elected', NULL),
('Jimmy Higdon', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '14', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate114.jpg', 'elected', NULL),
('John Blanton', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '92', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house92.jpg', 'elected', NULL),
('John Hodgson', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '36', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house36.jpg', 'elected', NULL),
('Josh Branscum', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '83', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house83.jpg', 'elected', NULL),
('Josh Bray', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '71', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house71.jpg', 'elected', NULL),
('Josh Calloway', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '10', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house10.jpg', 'elected', NULL),
('Joshua Watkins', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '42', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JoshuaWatkins2024.jpg', 'elected', NULL),
('Julie Adams', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '36', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate136.jpg', 'elected', NULL),
('Karen Berg', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '26', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate126.jpg', 'elected', NULL),
('Ken Fleming', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '48', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house48.jpg', 'elected', NULL),
('Ken Upchurch', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '52', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house52.jpg', 'elected', NULL),
('Keturah Herron', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '35', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate135.jpg', 'elected', NULL),
('Kevin Jackson', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '20', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house20.jpg', 'elected', NULL),
('Kim Banta', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '63', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house63.jpg', 'elected', NULL),
('Kim Holloway', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '2', NULL, 'Republican', 'https://npr.brightspotcdn.com/01/2a/8d768d42405b8992ce1c5dcb8159/244626154-114463787658953-2523667072088681096-n.jpg', 'elected', NULL),
('Kim King', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '55', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house55.jpg', 'elected', NULL),
('Kim Moser', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '64', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house64.jpg', 'elected', NULL),
('Lindsey Burke', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '75', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house75.jpg', 'elected', NULL),
('Lindsey Tichenor', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '6', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate106.jpg', 'elected', NULL),
('Lisa Willner', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '35', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house35.jpg', 'elected', NULL),
('Marianne Proctor', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '60', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house60.jpg', 'elected', NULL),
('Mark Hart', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '78', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house78.jpg', 'elected', NULL),
('Mary Beth Imes', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '5', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house5.jpg', 'elected', NULL),
('Mary Lou Marzian', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '41', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house41.jpg', 'elected', NULL),
('Matt Lehman', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '67', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MatthewLehman2024.jpg', 'elected', NULL),
('Matt Lockett', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '39', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house39.jpg', 'elected', NULL),
('Matt Nunn', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '17', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkAwk-VsxWc9P7zUFu6kXXFswQiXfHR8HdEg&s', 'elected', NULL),
('Matt Deneen', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '10', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate110.jpg', 'elected', NULL),
('Matt Koch', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '72', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house72.jpg', 'elected', NULL),
('Max Wise', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '16', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate116.jpg', 'elected', NULL),
('Mike Nemes', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '38', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate138.jpg', 'elected', NULL),
('Michael Meredith', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '19', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house19.jpg', 'elected', NULL),
('Sarge Pollock', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '51', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house51.jpg', 'elected', NULL),
('Mike Clines', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '68', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house68.jpg', 'elected', NULL),
('Mike Wilson', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '32', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate132.jpg', 'elected', NULL),
('Mitch Whitaker', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '94', NULL, 'Republican', 'https://whitakerforky.com/wp-content/uploads/2023/10/174675061_4495865760430094_8296166563898892766_n-1024x1024.jpg', 'elected', NULL),
('Myron Dossett', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '9', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house9.jpg', 'elected', NULL),
('Nancy Tate', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '27', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house27.jpg', 'elected', NULL),
('Nick Wilson', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '82', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house82.jpg', 'elected', NULL),
('Nima Kulkarni', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '40', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house40.jpg', 'elected', NULL),
('Pamela Stevenson', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '43', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house43.jpg', 'elected', NULL),
('Patrick Flannery', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '96', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house96.jpg', 'elected', NULL),
('Peyton Griffee', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '26', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/PeytonGriffee2024.png', 'elected', NULL),
('Phillip Wheeler', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '31', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate131.jpg', 'elected', NULL),
('Rachel Roarx', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '38', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house38.jpg', 'elected', NULL),
('Randy Bridges', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '3', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house3.jpg', 'elected', NULL),
('Rebecca Raymer', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '15', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house15.jpg', 'elected', NULL),
('Reggie Thomas', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '13', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate113.jpg', 'elected', NULL),
('Richard White', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '99', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house99.jpg', 'elected', NULL),
('Rick Girdler', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '15', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate115.jpg', 'elected', NULL),
('Robby Mills', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '4', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate104.jpg', 'elected', NULL),
('Robert Duvall', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '17', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house17.jpg', 'elected', NULL),
('Robert Stivers', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '25', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate125.jpg', 'elected', NULL),
('Robin Webb', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '18', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate118.jpg', 'elected', NULL),
('Ryan Bivens', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '24', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house24.jpg', 'elected', NULL),
('Ryan Dotson', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '73', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house73.jpg', 'elected', NULL),
('Samara Heavrin', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '18', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house18.jpg', 'elected', NULL),
('Sarah Stalker', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '34', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house34.jpg', 'elected', NULL),
('Savannah Maddox', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '61', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house61.jpg', 'elected', NULL),
('Scott Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '14', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house14.jpg', 'elected', NULL),
('Scott Madon', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '29', NULL, 'Republican', 'https://thecityofpineville.com/wp-content/uploads/2018/08/mayor-scott-madon-228x300.jpg', 'elected', NULL),
('Scott Sharp', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '100', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house100.jpg', 'elected', NULL),
('Shane Baker', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '85', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house85.jpg', 'elected', NULL),
('Shawn McPherson', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '22', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house22.jpg', 'elected', NULL),
('Shelley Frommeyer', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '24', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate124.jpg', 'elected', NULL),
('Stephanie Dietz', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '65', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house65.jpg', 'elected', NULL),
('Steve Meredith', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '5', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate105.jpg', 'elected', NULL),
('Steve West', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '27', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate127.jpg', 'elected', NULL),
('Steve Bratcher', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '25', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house25.jpg', 'elected', NULL),
('Steve Rawlings', 'State Senator', 'Legislative Branch', 'Legislative', 'KY', '11', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/senate111.jpg', 'elected', NULL),
('Steve Riley', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '23', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house23.jpg', 'elected', NULL),
('Steven Doan', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '69', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house69.jpg', 'elected', NULL),
('Steven Rudy', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '1', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house1.jpg', 'elected', NULL),
('Susan Witten', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '31', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house31.jpg', 'elected', NULL),
('Suzanne Miles', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '7', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house7.jpg', 'elected', NULL),
('T.J. Roberts', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '66', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/T.J._Roberts.png', 'elected', NULL),
('Thomas Huff', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '49', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house49.jpg', 'elected', NULL),
('Timmy Truett', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '89', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house89.jpg', 'elected', NULL),
('Tina Bojanowski', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '32', NULL, 'Democratic', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house32.jpg', 'elected', NULL),
('Tom Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '86', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house86.jpg', 'elected', NULL),
('Tony Hampton', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '62', NULL, 'Republican', 'https://cdn.photos.sparkplatform.com/lex/20240524200530073416000000.jpg', 'elected', NULL),
('Vanessa Grossl', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '88', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/VanessaGrossl.jpeg', 'elected', NULL),
('Wade Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '4', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house4.jpg', 'elected', NULL),
('Walker Thomas', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '8', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house8.jpg', 'elected', NULL),
('William Lawrence', 'State Representative', 'Legislative Branch', 'Legislative', 'KY', '70', NULL, 'Republican', 'https://legislature.ky.gov/Legislators%20Thumbnail%20Images/house70.jpg', 'elected', NULL);
