-- LA state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'LA';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Adam Bass', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '36', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen36.jpg', 'elected', NULL),
('Adrian Fisher', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '16', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep16.jpg', 'elected', NULL),
('Aimee Freeman', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '98', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep98.jpg', 'elected', NULL),
('Alan Seabaugh', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '31', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen31.jpg', 'elected', NULL),
('Alonzo Knox', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '93', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep93.jpg', 'elected', NULL),
('Annie Spell', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '45', NULL, 'Republican', NULL, 'elected', NULL),
('Barbara Freiberg', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '70', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep70.jpg', 'elected', NULL),
('Barbara Carpenter', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '63', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep63.jpg', 'elected', NULL),
('Beryl Amedée', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '51', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep51.jpg', 'elected', NULL),
('Beth Billings', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '56', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep56.jpg', 'elected', NULL),
('Beth Mizell', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '12', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen12.jpg', 'elected', NULL),
('Bill Wheat', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '37', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen37.jpg', 'elected', NULL),
('Blake Miguez', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '22', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen22.jpg', 'elected', NULL),
('Bob Hensgens', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '26', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen26.jpg', 'elected', NULL),
('Bob Owen', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '1', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen1.jpg', 'elected', NULL),
('Brach Myers', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '23', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep45.jpg', 'elected', NULL),
('Brett Geymann', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '35', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep35.jpg', 'elected', NULL),
('Brian Glorioso', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '90', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep90.jpg', 'elected', NULL),
('Bryan Fontenot', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '55', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep55.jpg', 'elected', NULL),
('Denise Marcelle', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '61', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics/rep61.jpg', 'elected', NULL),
('Travis Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '21', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep21.jpg', 'elected', NULL),
('Caleb Kleinpeter', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '17', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen17.jpg', 'elected', NULL),
('Candace Newell', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '99', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep99.jpg', 'elected', NULL),
('Chad Boyer', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '46', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep46.jpg', 'elected', NULL),
('Chance Henry', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '42', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep42.jpg', 'elected', NULL),
('Chuck Owen', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '30', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep30.jpg', 'elected', NULL),
('Chasity Martinez', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '60', NULL, 'Democratic', 'https://ibervilleparish.com/wp-content/uploads/District-10-Chasity-Martinez.png', 'elected', NULL),
('Chris Turner', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '12', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep12.jpg', 'elected', NULL),
('Dana Henry', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '100', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Dana_Henry_20260113_023611.jpg', 'elected', NULL),
('Danny McCormick', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '1', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep1.jpg', 'elected', NULL),
('Daryl Deshotel', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '28', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep28.jpg', 'elected', NULL),
('Debbie Villio', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '79', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep79.jpg', 'elected', NULL),
('Delisha Boyd', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '102', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep102.jpg', 'elected', NULL),
('Dennis Bamburg', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '5', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep5.jpg', 'elected', NULL),
('Dixon McMakin', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '68', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep68.jpg', 'elected', NULL),
('Dodie Horton', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '9', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep9.jpg', 'elected', NULL),
('Doyle Boudreaux', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '39', NULL, 'Republican', 'https://static.wixstatic.com/media/66f8d9_8ae2cf856c374eee86e43d32c995830b~mv2.jpg/v1/fill/w_150,h_210,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/Doyle%20Boudreaux_JPG.jpg', 'elected', NULL),
('Dustin Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '40', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep40.jpg', 'elected', NULL),
('Ed Larvadain', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '26', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep26.jpg', 'elected', NULL),
('Ed Murray', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '97', NULL, 'Democratic', 'https://ed4nola.com/wp-content/uploads/2025/11/EdMurray_CampaignShoot_1-45-683x1024.jpg', 'elected', NULL),
('Eddie Lambert', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '18', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen18.jpg', 'elected', NULL),
('Edmond Jordan', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '29', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep29.jpg', 'elected', NULL),
('Ed Price', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '2', NULL, 'Democratic', 'https://senate.la.gov/SenatorPics/Sen2.jpg', 'elected', NULL),
('Emily Chenevert', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '66', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep66.jpg', 'elected', NULL),
('Foy Gadberry', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '15', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep15.jpg', 'elected', NULL),
('Francis Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '19', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep19.jpg', 'elected', NULL),
('Franklin Foil', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '16', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen16.jpg', 'elected', NULL),
('Gary Carter', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '7', NULL, 'Democratic', 'https://senate.la.gov/SenatorPics/Sen7.jpg', 'elected', NULL),
('Beau Beaullieu', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '48', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep48.jpg', 'elected', NULL),
('Gerald Boudreaux', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '24', NULL, 'Democratic', 'https://senate.la.gov/SenatorPics/Sen24.jpg', 'elected', NULL),
('Glen Womack', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '32', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen32.jpg', 'elected', NULL),
('Greg Miller', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '19', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen19.jpg', 'elected', NULL),
('Heather Cloud', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '28', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen28.jpg', 'elected', NULL),
('Cameron Henry', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '9', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen9.jpg', 'elected', NULL),
('Jack McFarland', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '13', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep13.jpg', 'elected', NULL),
('Jacob Braud', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '105', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep105.jpg', 'elected', NULL),
('Jacob Landry', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '49', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep49.jpg', 'elected', NULL),
('Jason DeWitt', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '25', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep25.jpg', 'elected', NULL),
('Jay Gallé', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '104', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep104.jpg', 'elected', NULL),
('Jay Morris', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '35', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen35.jpg', 'elected', NULL),
('Jeff Wiley', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '81', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep81.jpg', 'elected', NULL),
('Jeremy Stine', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '27', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen27.jpg', 'elected', NULL),
('Jeremy LaCombe', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '18', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep18.jpg', 'elected', NULL),
('Jerome Zeringue', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '52', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep52.jpg', 'elected', NULL),
('Jessica Domangue', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '53', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep53.jpg', 'elected', NULL),
('Jimmy Harris', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '4', NULL, 'Democratic', 'https://senate.la.gov/SenatorPics/Sen4.jpg', 'elected', NULL),
('John Illg', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '78', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep78.jpg', 'elected', NULL),
('John Wyble', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '75', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep75.jpg', 'elected', NULL),
('Joe Stagni', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '92', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep92.jpg', 'elected', NULL),
('Joe Orgeron', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '54', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep54.jpg', 'elected', NULL),
('Josh Carlson', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '43', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep43.jpg', 'elected', NULL),
('Joy Walters', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '4', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics/rep4.jpg', 'elected', NULL),
('Kathy Edmonston', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '88', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep88.jpg', 'elected', NULL),
('Katrina Jackson-Andrews', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '34', NULL, 'Democratic', 'https://senate.la.gov/SenatorPics/Sen34.jpg', 'elected', NULL),
('Kellee Hennessy', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '64', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep64.jpg', 'elected', NULL),
('Ken Brass', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '58', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep58.jpg', 'elected', NULL),
('Kim Carver', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '89', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep89.jpg', 'elected', NULL),
('Kim Coates', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '73', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep73.jpg', 'elected', NULL),
('Kirk Talbot', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '10', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen10.jpg', 'elected', NULL),
('Kyle Green', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '83', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep83.jpg', 'elected', NULL),
('Larry Selders', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '14', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep67.jpg', 'elected', NULL),
('Lauren Ventrella', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '65', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep65.jpg', 'elected', NULL),
('Laurie Schlegel', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '82', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep82.jpg', 'elected', NULL),
('Larry Bagley', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '7', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep7.jpg', 'elected', NULL),
('Les Farnum', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '33', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep33.jpg', 'elected', NULL),
('Mandie Landry', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '91', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep91.jpg', 'elected', NULL),
('Marcus Bryant', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '96', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep96.jpg', 'elected', NULL),
('Mark Abraham', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '25', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen25.jpg', 'elected', NULL),
('Mark Wright', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '77', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep77.jpg', 'elected', NULL),
('Mike Fési', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '20', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen20.jpg', 'elected', NULL),
('Michael Echols', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '14', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep14.jpg', 'elected', NULL),
('Gabe Firment', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '22', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep22.jpg', 'elected', NULL),
('Michael Melerine', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '6', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep6.jpg', 'elected', NULL),
('Mike Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '27', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep27.jpg', 'elected', NULL),
('Mike Bayham', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '103', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep103.jpg', 'elected', NULL),
('Mike Reese', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '30', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen30.jpg', 'elected', NULL),
('Neil Riser', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '20', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep20.jpg', 'elected', NULL),
('Nicky Muscarello', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '86', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep86.jpg', 'elected', NULL),
('Pat Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '17', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep17.jpg', 'elected', NULL),
('Patrick Connick', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '8', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen8.jpg', 'elected', NULL),
('Patrick McMath', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '11', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen11.jpg', 'elected', NULL),
('Paul Sawyer', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '69', NULL, 'Republican', 'https://static.wixstatic.com/media/9361fe_da91e496f1294126bbe3a43b182b5045~mv2.jpg/v1/fill/w_1159,h_772,fp_0.44_0.28,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/623291664_122110353027206892_603986649064719459_n.jpg', 'elected', NULL),
('Peter Egan', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '74', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep74.jpg', 'elected', NULL),
('Phil Tarver', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '36', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep36.jpg', 'elected', NULL),
('Phillip DeVillier', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '41', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep41.jpg', 'elected', NULL),
('Polly Thomas', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '80', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep80.jpg', 'elected', NULL),
('Dewith Carrier', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '32', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep32.jpg', 'elected', NULL),
('Robert Allain', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '21', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen21.jpg', 'elected', NULL),
('Rashid Young', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '11', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics/rep11.jpg', 'elected', NULL),
('Raymond Crews', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '8', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep8.jpg', 'elected', NULL),
('Regina Barrow', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '15', NULL, 'Democratic', 'https://senate.la.gov/SenatorPics/Sen15.jpg', 'elected', NULL),
('Rhonda Butler', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '38', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep38.jpg', 'elected', NULL),
('Rick Edmonds', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '6', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen6.jpg', 'elected', NULL),
('Robby Carter', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '72', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep72.jpg', 'elected', NULL),
('Rodney Lyons', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '87', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep87.jpg', 'elected', NULL),
('Rodney Schamerhorn', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '24', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep24.jpg', 'elected', NULL),
('Roger Wilder', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '71', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep71.jpg', 'elected', NULL),
('Roy Adams', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '62', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep62.jpg', 'elected', NULL),
('Royce Duplessis', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '5', NULL, 'Democratic', 'https://senate.la.gov/SenatorPics/Sen5.jpg', 'elected', NULL),
('Ryan Bourriaque', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '47', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep47.jpg', 'elected', NULL),
('Sam Jenkins', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '39', NULL, 'Democratic', 'https://senate.la.gov/SenPics/Sen39.jpg', 'elected', NULL),
('Shaun Mena', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '23', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics/rep23.jpg', 'elected', NULL),
('Shane Mack', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '95', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep95.jpg', 'elected', NULL),
('Sidney Barthelemy', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '3', NULL, 'Democratic', NULL, 'elected', NULL),
('Skip Broussard', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '37', NULL, 'Republican', 'https://americanpress.com/wp-content/uploads/sites/65/2026/02/IMG_7387.jpeg', 'elected', NULL),
('Stephanie Berault', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '76', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep76.jpg', 'elected', NULL),
('Stephanie Hilferty', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '94', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep94.jpg', 'elected', NULL),
('Steven Jackson', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '2', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics/rep2.jpg', 'elected', NULL),
('Stewart Cathey', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '33', NULL, 'Republican', 'https://senate.la.gov/SenatorPics/Sen33.jpg', 'elected', NULL),
('Sylvia Taylor', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '57', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics/rep57.jpg', 'elected', NULL),
('Tammy Phelps', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '3', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep3.jpg', 'elected', NULL),
('Tehmi Chassion', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '44', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics/rep44.jpg', 'elected', NULL),
('Terry Landry', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '67', NULL, 'Democratic', NULL, 'elected', NULL),
('Thomas Pressly', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '38', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen38.jpg', 'elected', NULL),
('Tim Kerner', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '84', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep84.jpg', 'elected', NULL),
('Tony Bacala', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '59', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep59.jpg', 'elected', NULL),
('Troy Hebert', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '31', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep31.jpg', 'elected', NULL),
('Valarie Hodges', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '13', NULL, 'Republican', 'https://senate.la.gov/SenPics/Sen13.jpg', 'elected', NULL),
('Vanessa LaFleur', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '101', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep101.jpg', 'elected', NULL),
('Vincent Cox', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '85', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics/rep85.jpg', 'elected', NULL),
('Vinney St. Blanc', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '50', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep50.jpg', 'elected', NULL),
('Jay Luneau', 'State Senator', 'Legislative Branch', 'Legislative', 'LA', '29', NULL, 'Democratic', 'https://senate.la.gov/SenatorPics/Sen29.jpg', 'elected', NULL),
('Wayne McMahen', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '10', NULL, 'Republican', 'https://house.louisiana.gov/H_Reps/RepPics20/rep10.jpg', 'elected', NULL),
('Wilford Carter', 'State Representative', 'Legislative Branch', 'Legislative', 'LA', '34', NULL, 'Democratic', 'https://house.louisiana.gov/H_Reps/RepPics20/rep34.jpg', 'elected', NULL);
