-- MA state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'MA';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Aaron Saunders', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '7th Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/ALS1.jpg', 'elected', NULL),
('Aaron Michlewitz', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/AMM1.jpg', 'elected', NULL),
('Adam Gómez', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/A_G0.jpg', 'elected', NULL),
('Adam Scanlon', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '14th Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/AJS1.jpg', 'elected', NULL),
('Adrian Madaro', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/ACM1.jpg', 'elected', NULL),
('Adrianne Ramos', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '14th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/APR1.jpg', 'elected', NULL),
('Alan Silvia', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '7th Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/A_S1.jpg', 'elected', NULL),
('Alice Peisch', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '14th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/AHP1.jpg', 'elected', NULL),
('Alyson Sullivan-Almeida', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '7th Plymouth', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/AMS2.jpg', 'elected', NULL),
('Amy Sangiolo', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '11th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/AMS3.jpg', 'elected', NULL),
('Andy Vargas', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/AXV1.jpg', 'elected', NULL),
('Angelo Puppolo', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '12th Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/AJP1.jpg', 'elected', NULL),
('Tony Cabral', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '13th Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/AFC1.jpg', 'elected', NULL),
('Barry Finegold', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Second Essex and Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/BRF0.jpg', 'elected', NULL),
('Brad Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '20th Middlesex', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/BHJ1.jpg', 'elected', NULL),
('Brandy Fluker-Reid', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '12th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/BFO1.jpg', 'elected', NULL),
('Brendan Crighton', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Third Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/BPC0.jpg', 'elected', NULL),
('Brian Ashe', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/BMA1.jpg', 'elected', NULL),
('Brian Murray', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '10th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/BWM1.jpg', 'elected', NULL),
('Bridget Plouffe', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '9th Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/BMP1.jpg', 'elected', NULL),
('Bruce Tarr', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'First Essex and Middlesex', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/BET0.jpg', 'elected', NULL),
('Bruce Ayers', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/BJA1.jpg', 'elected', NULL),
('Bud Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '11th Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/BLW1.jpg', 'elected', NULL),
('Carlos González', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '10th Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/C_G1.jpg', 'elected', NULL),
('Carmine Gentile', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '13th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CLG1.jpg', 'elected', NULL),
('Carole Fiola', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '6th Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CAF1.jpg', 'elected', NULL),
('Christine Barber', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '34th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CPB2.jpg', 'elected', NULL),
('Chris Hendricks', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '11th Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/C_H1.jpg', 'elected', NULL),
('Chris Worrell', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CJW1.jpg', 'elected', NULL),
('Christopher Markey', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '9th Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CMM1.jpg', 'elected', NULL),
('Chris Flanagan', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Barnstable', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CRF1.jpg', 'elected', NULL),
('Chynah Tyler', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '7th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/C_T1.jpg', 'elected', NULL),
('Cindy Friedman', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Fourth Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CFF0.jpg', 'elected', NULL),
('Colleen Garry', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '36th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CMG1.jpg', 'elected', NULL),
('Cynthia Creem', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Norfolk and Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/CSC0.jpg', 'elected', NULL),
('Dan Cahill', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '10th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/DFC1.jpg', 'elected', NULL),
('Dan Hunt', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '13th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/djh1.jpg', 'elected', NULL),
('Danny Ryan', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/djr1.jpg', 'elected', NULL),
('Dan Donahue', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '16th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/DMD1.jpg', 'elected', NULL),
('Danielle Gregoire', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/DWG1.jpg', 'elected', NULL),
('Dan Sena', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '37th Middlesex', NULL, 'Democratic', 'http://malegislature.gov/Legislators/Profile/170/DAS1.jpg', 'elected', NULL),
('Dave Robertson', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '19th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/D_R1.jpg', 'elected', NULL),
('David Biele', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/D_B1.jpg', 'elected', NULL),
('David DeCoste', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Plymouth', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/DFD1.jpg', 'elected', NULL),
('David LeBoeuf', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '17th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/DAL1.jpg', 'elected', NULL),
('Dave Muradian', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '9th Worcester', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/DKM1.jpg', 'elected', NULL),
('Dave Rogers', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '24th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/DMR1.jpg', 'elected', NULL),
('David Linsky', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/DPL1.jpg', 'elected', NULL),
('Dave Vieira', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Barnstable', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/DTV1.jpg', 'elected', NULL),
('Dawne Shand', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/D_S1.jpg', 'elected', NULL),
('Dennis Gallagher', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '8th Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/DCG2.jpg', 'elected', NULL),
('Donald Wong', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '9th Essex', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/DHW1.jpg', 'elected', NULL),
('Donnie Berthiaume', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Worcester', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/DRB1.jpg', 'elected', NULL),
('Dru Tarr', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/AFT1.jpg', 'elected', NULL),
('Dylan Fernandes', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Plymouth and Barnstable', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/DAF0.jpg', 'elected', NULL),
('Ted Philips', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '8th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/ERP1.jpg', 'elected', NULL),
('Erika Uyterhoeven', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '27th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/E_U1.jpg', 'elected', NULL),
('Estela Reyes', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/EAR1.jpg', 'elected', NULL),
('Francisco Paulino', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '16th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/FEP1.jpg', 'elected', NULL),
('Frank Moran', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '17th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/FAM1.jpg', 'elected', NULL),
('Greg Schwartz', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '12th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/G_S1.jpg', 'elected', NULL),
('Hadley Luddy', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Barnstable', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/H_L1.jpg', 'elected', NULL),
('Hannah Bowen', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '6th Essex', NULL, 'Democratic', 'https://www.resolutionnorthshore.org/images/staff/AG22-Hannah_Bowen-228832.jpg', 'elected', NULL),
('Hannah Kane', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '11th Worcester', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/HEK1.jpg', 'elected', NULL),
('Homar Gomez', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Hampshire', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/6616e5c7caac657d5a7f9682/0c122a29-b755-4647-a180-d5cbdb08bbcc/Screenshot+2024-04-10+at+4.35.35+PM.jpg', 'elected', NULL),
('Jack Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '7th Middlesex', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jack_Patrick_Lewis.jpg', 'elected', NULL),
('Jake Oliveira', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Hampden, Hampshire and Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JRO0.jpg', 'elected', NULL),
('Jim Arciero', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/J_A1.jpg', 'elected', NULL),
('Jamie Eldridge', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Middlesex and Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JBE0.jpg', 'elected', NULL),
('James Arena-DeRosa', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '8th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JCD1.jpg', 'elected', NULL),
('Jim O''Day', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '14th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JJO1.jpg', 'elected', NULL),
('Jim Hawkins', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JKH1.jpg', 'elected', NULL),
('Jamie Murphy', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JMM1.jpg', 'elected', NULL),
('Jason Lewis', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Fifth Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/jml0.jpg', 'elected', NULL),
('Jay Livingstone', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '8th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/J_L1.jpg', 'elected', NULL),
('Jeff Roy', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '10th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JNR1.jpg', 'elected', NULL),
('Jeff Turco', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '19th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JRT1.jpg', 'elected', NULL),
('Jenny Armini', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '8th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JBA1.jpg', 'elected', NULL),
('Jessica Giannino', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '16th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JAG1.jpg', 'elected', NULL),
('Joan Lovely', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Second Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JBL0.jpg', 'elected', NULL),
('Joan Meschino', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/J_M1.jpg', 'elected', NULL),
('Jo Comerford', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Hampshire, Franklin and Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JMC0.jpg', 'elected', NULL),
('John Barrett', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Berkshire', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/J_B1.jpg', 'elected', NULL),
('John Velis', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Hampden and Hampshire', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/jcv1.jpg', 'elected', NULL),
('John Cronin', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Worcester and Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JJC0.jpg', 'elected', NULL),
('John Keenan', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Norfolk and Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JFK0.jpg', 'elected', NULL),
('John Moran', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '9th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JFM1.jpg', 'elected', NULL),
('John Gaskey', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Plymouth', NULL, 'Republican', 'https://static.wixstatic.com/media/40d8f8_3ba01018eff64b309a92373daddd8344~mv2.jpg/v1/crop/x_140,y_436,w_734,h_891/fill/w_440,h_534,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/Untitled-6.jpg', 'elected', NULL),
('John Rogers', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '12th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JHR1.jpg', 'elected', NULL),
('John Lawn', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '10th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JJL2.jpg', 'elected', NULL),
('John Mahoney', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '13th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JJM2.jpg', 'elected', NULL),
('John Marsi', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '6th Worcester', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/JJM1.jpg', 'elected', NULL),
('Jon Zlotnik', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JDZ1.jpg', 'elected', NULL),
('Joe McKenna', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '18th Worcester', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/JDM1.jpg', 'elected', NULL),
('Joe McGonagle', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '28th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/jwm1.jpg', 'elected', NULL),
('Josh Tarsky', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '13th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/J_T1.jpg', 'elected', NULL),
('Judith García', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '11th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JAG2.jpg', 'elected', NULL),
('Julian Cyr', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Cape and Islands', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/JAC0.jpg', 'elected', NULL),
('Justin Thurber', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Bristol', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/J_T2.jpg', 'elected', NULL),
('Karen Spilka', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Middlesex and Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/KES0.jpg', 'elected', NULL),
('Kate Donaghue', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '19th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/K_D1.jpg', 'elected', NULL),
('Kate Hogan', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/K_H1.jpg', 'elected', NULL),
('Kate Lipper-Garabedian', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '32nd Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/KLG1.jpg', 'elected', NULL),
('Kathy LaNatra', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '12th Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/KPL1.jpg', 'elected', NULL),
('Kelly Dooner', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Third Bristol and Plymouth', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/KAD0.jpg', 'elected', NULL),
('Kelly Pease', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Hampden', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/KWP1.jpg', 'elected', NULL),
('Ken Sweezey', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '6th Plymouth', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/KPS1.jpg', 'elected', NULL),
('Ken Gordon', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '21st Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/KIG1.jpg', 'elected', NULL),
('Kevin Honan', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '17th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/KGH1.jpg', 'elected', NULL),
('Kim Ferguson', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Worcester', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Kimberly-Ferguson.jpg', 'elected', NULL),
('Kip Diggs', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Barnstable', NULL, 'Democratic', 'https://www.capecod.com/wp-content/uploads/NWS_Kip-Diggs_JS081720.jpg', 'elected', NULL),
('Kristin Kassner', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/K_K2.jpg', 'elected', NULL),
('Leigh Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Berkshire', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/LSD1.jpg', 'elected', NULL),
('Lindsay Sabadosa', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Hampshire', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/L_S1.jpg', 'elected', NULL),
('Lisa Field', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/LMF1.jpg', 'elected', NULL),
('Liz Miranda', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Second Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/L%20M0.jpg', 'elected', NULL),
('Lydia Edwards', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Third Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/LME0.jpg', 'elected', NULL),
('Manny Cruz', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '7th Essex', NULL, 'Democratic', 'https://www.wickedlocal.com/gcdn/authoring/2018/08/07/NWKL/ghows-WL-72d881e3-b92a-5ead-e053-0100007fbaea-a47ecf5e.jpeg?width=600&height=1068&fit=crop&format=pjpg&auto=webp', 'elected', NULL),
('Marc Lombardo', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '22nd Middlesex', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/MTL1.jpg', 'elected', NULL),
('Marcus Vaughn', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '9th Norfolk', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/MSV1.jpg', 'elected', NULL),
('Margaret Scarsdale', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MRS1.jpg', 'elected', NULL),
('Marjorie Decker', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '25th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MCD1.jpg', 'elected', NULL),
('Mark Montigny', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Second Bristol and Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MCM0.jpg', 'elected', NULL),
('Mark Cusack', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MJC1.jpg', 'elected', NULL),
('Mark Sylvia', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '10th Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MDS1.jpg', 'elected', NULL),
('Mary Keefe', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '15th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MSK1.jpg', 'elected', NULL),
('Meg Kilcoyne', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '12th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/M_K1.jpg', 'elected', NULL),
('Mike Brady', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Second Plymouth and Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MDB0.jpg', 'elected', NULL),
('Mike Rush', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Norfolk and Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MFR0.jpg', 'elected', NULL),
('Mike Barrett', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Third Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MJB0.jpg', 'elected', NULL),
('Mike Finn', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '6th Hampden', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Michael_Finn.jpg', 'elected', NULL),
('Mike Moran', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '18th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MJM1.jpg', 'elected', NULL),
('Michael Rodrigues', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'First Bristol and Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MJR0.jpg', 'elected', NULL),
('Mike Soter', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '8th Worcester', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/MJS3.jpg', 'elected', NULL),
('Mike Moore', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Second Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MOM0.jpg', 'elected', NULL),
('Mike Kushmerek', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MPK1.jpg', 'elected', NULL),
('Mike Day', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '31st Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MSD1.jpg', 'elected', NULL),
('Michelle Badger', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Plymouth', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MichelleBadger24.jpg', 'elected', NULL),
('Michelle Ciccolo', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '15th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/M_C2.jpg', 'elected', NULL),
('Michelle DuBois', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '10th Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/MMD1.jpg', 'elected', NULL),
('Mike Chaisson', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Bristol', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/MSC1.jpg', 'elected', NULL),
('Mike Connolly', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '26th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/M_C1.jpg', 'elected', NULL),
('Mindy Domb', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Hampshire', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/M_D2.jpg', 'elected', NULL),
('Natalie Higgins', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/N_H1.jpg', 'elected', NULL),
('Nick Boldyga', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Hampden', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/NAG1.jpg', 'elected', NULL),
('Nick Collins', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'First Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/N_C0.jpg', 'elected', NULL),
('Norm Orrall', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '12th Bristol', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/NJO1.jpg', 'elected', NULL),
('Orlando Ramos', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '9th Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/O_R1.jpg', 'elected', NULL),
('Pat Duffy', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/PAD1.jpg', 'elected', NULL),
('Pat Jehlen', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Second Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/PDJ0.jpg', 'elected', NULL),
('Patrick Kearney', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/PJK1.jpg', 'elected', NULL),
('Patrick O''Connor', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'First Plymouth and Norfolk', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/PMO.jpg', 'elected', NULL),
('Paul Donato', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '35th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/PJD1.jpg', 'elected', NULL),
('Paul Frost', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '7th Worcester', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Paul-Frost.jpg', 'elected', NULL),
('Paul McMurtry', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '11th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/P_M1.jpg', 'elected', NULL),
('Paul Feeney', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Bristol and Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/PRF0.jpg', 'elected', NULL),
('Paul Mark', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Berkshire, Hampden, Franklin and Hampshire', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/PWM0.jpg', 'elected', NULL),
('Pavel Payano', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'First Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/PMP0.jpg', 'elected', NULL),
('Peter Durant', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Worcester and Hampshire', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/PJD0.jpg', 'elected', NULL),
('Priscila Sousa', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '6th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/PSS1.jpg', 'elected', NULL),
('Becca Rausch', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Norfolk, Worcester and Middlesex', NULL, 'Democratic', 'https://www.brandeis.edu/now/2019/january/images/rausch620.jpg', 'elected', NULL),
('Rich Haggerty', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '30th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/RMH1.jpg', 'elected', NULL),
('Richard Wells', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '7th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/RGW1.jpg', 'elected', NULL),
('Rita Mendes', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '11th Plymouth', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/RAM1.jpg', 'elected', NULL),
('Rob Consalvo', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '14th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/R_C1.jpg', 'elected', NULL),
('Robyn Kennedy', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'First Worcester', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/RKK0.jpg', 'elected', NULL),
('Rodney Elliott', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '16th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/RME1.jpg', 'elected', NULL),
('Ron Mariano', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '3rd Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/R_M1.jpg', 'elected', NULL),
('Russell Holmes', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '6th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/REH1.jpg', 'elected', NULL),
('Ryan Fattman', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Worcester and Hampden', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/RCF0.jpg', 'elected', NULL),
('Ryan Hamilton', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '15th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/RMH2.jpg', 'elected', NULL),
('Sal DiDomenico', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Middlesex and Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/SND0.jpg', 'elected', NULL),
('Sally Kerans', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '13th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/SPK1.jpg', 'elected', NULL),
('Sam Montaño', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '15th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/S_M1.jpg', 'elected', NULL),
('Sean Garballey', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '23rd Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/S_G1.jpg', 'elected', NULL),
('Sean Reid', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '11th Essex', NULL, 'Democratic', 'https://static.wixstatic.com/media/afaf11_7be85579b8f44be19dc438362812307c~mv2.jpg/v1/crop/x_0,y_241,w_1500,h_1845/fill/w_560,h_689,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/SeanHeadshot.jpg', 'elected', NULL),
('Shirley Arriaga', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '8th Hampden', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/SBA1.jpg', 'elected', NULL),
('Simon Cataldo', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '14th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/S_C1.jpg', 'elected', NULL),
('Steve Owens', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '29th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/SCO1.jpg', 'elected', NULL),
('Steve Xiarhos', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '5th Barnstable', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/SGX1.jpg', 'elected', NULL),
('Steven Ouellette', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '8th Bristol', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Steven_Ouellette_20241027_114832.jpeg', 'elected', NULL),
('Steven Howitt', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '4th Bristol', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/SSH1.jpg', 'elected', NULL),
('Steve Ultrino', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '33rd Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/S_G2.jpg', 'elected', NULL),
('Susannah Whipps', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Franklin', NULL, 'Independent', 'https://malegislature.gov/Legislators/Profile/170/SLG1.jpg', 'elected', NULL),
('Tackey Chan', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/T_C1.jpg', 'elected', NULL),
('Tara Hong', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '18th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/TTH1.jpg', 'elected', NULL),
('Tom Stanley', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '9th Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/TMS1.jpg', 'elected', NULL),
('Thomas Moakley', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', 'Barnstable, Dukes and Nantucket', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/TWM1.jpg', 'elected', NULL),
('Tom Walsh', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '12th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/TJW1.jpg', 'elected', NULL),
('Todd Smola', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '1st Hampden', NULL, 'Republican', 'https://malegislature.gov/Legislators/Profile/170/TMS2.jpg', 'elected', NULL),
('Tommy Vitolo', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '15th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/T_V1.jpg', 'elected', NULL),
('Tram Nguyen', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '18th Essex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/TTN1.jpg', 'elected', NULL),
('Tricia Farley-Bouvier', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '2nd Berkshire', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/TFB1.jpg', 'elected', NULL),
('Vanna Howard', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'First Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/V_H1.jpg', 'elected', NULL),
('Bill Galvin', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '6th Norfolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/WCG1.jpg', 'elected', NULL),
('Bill Driscoll', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Norfolk, Plymouth and Bristol', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/WJD1.jpg', 'elected', NULL),
('Billy MacGregor', 'State Representative', 'Legislative Branch', 'Legislative', 'MA', '10th Suffolk', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/WFM1.jpg', 'elected', NULL),
('Will Brownsberger', 'State Senator', 'Legislative Branch', 'Legislative', 'MA', 'Suffolk and Middlesex', NULL, 'Democratic', 'https://malegislature.gov/Legislators/Profile/170/WNB0.jpg', 'elected', NULL);
