-- MD state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'MD';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Aaron Kaufman', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '18', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/kaufman01.jpg', 'elected', NULL),
('Adrian Boafo', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '23', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2026RS/images/boafo01.jpg', 'elected', NULL),
('Adrienne Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '10', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/jones.jpg', 'elected', NULL),
('Aletheia McCaskill', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '44B', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/mccaskill01.jpg', 'elected', NULL),
('Alonzo Washington', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '22', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/washington02.jpg', 'elected', NULL),
('Andre Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '34A', NULL, 'Democratic', 'https://msa.maryland.gov/msa/mdmanual/36loc/ha/leg/images/1198-1-09406b.jpg', 'elected', NULL),
('Andrea Harrison', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '24', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/harrison01.jpg', 'elected', NULL),
('Andrew Pruski', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '33A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/pruski01.jpg', 'elected', NULL),
('Anne Healey', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '22', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/healey.jpg', 'elected', NULL),
('Anne Kaiser', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '14', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/kaiser.jpg', 'elected', NULL),
('Antonio Hayes', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '40', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/hayes02.jpg', 'elected', NULL),
('April Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '4', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/April_Fleming_Miller.jpg', 'elected', NULL),
('April Rose', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '5', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/rose01.jpg', 'elected', NULL),
('Arthur Ellis', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '28', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/ellis01.jpg', 'elected', NULL),
('Ashanti Martínez', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '22', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/martinez01.jpg', 'elected', NULL),
('Barrie Ciliberti', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '4', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/ciliberti01.jpg', 'elected', NULL),
('Barry Beauchamp', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '38B', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/beauchamp01.jpg', 'elected', NULL),
('Ben Barnes', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '21', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/barnes.jpg', 'elected', NULL),
('Ben Brooks', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '10', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/brooks02.jpg', 'elected', NULL),
('Ben Kramer', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '19', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/kramer%20b.jpg', 'elected', NULL),
('Bernice Mireku-North', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '14', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/mireku01.jpg', 'elected', NULL),
('Bill Ferguson', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '46', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/ferguson.jpg', 'elected', NULL),
('Bonnie Cullison', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '19', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/cullison.jpg', 'elected', NULL),
('Brian Chisholm', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '31', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/chisholm01.jpg', 'elected', NULL),
('Brian Feldman', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '15', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/feldman.jpg', 'elected', NULL),
('Brian Crosby', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '29B', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/crosby01.jpg', 'elected', NULL),
('Bryan Simonaire', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '31', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/simonaire.jpg', 'elected', NULL),
('Anthony Muse', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '26', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/muse.jpg', 'elected', NULL),
('C.T. Wilson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '28', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2024RS/images/wilson.jpg', 'elected', NULL),
('Carl Jackson', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '8', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/jackson04.jpg', 'elected', NULL),
('Cathi Forbes', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '43B', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/forbes01.jpg', 'elected', NULL),
('Caylin Young', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '45', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/young05.jpg', 'elected', NULL),
('Chao Wu', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '9A', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ChaoWu.jpg', 'elected', NULL),
('Charlotte Crutchfield', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '19', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/crutchfield01.jpg', 'elected', NULL),
('Cheryl Kagan', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '17', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/kagan01.jpg', 'elected', NULL),
('Cheryl Pasteur', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '11A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/pasteur01.jpg', 'elected', NULL),
('Chris Tomlinson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '5', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/tomlinson01.jpg', 'elected', NULL),
('Chris West', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '42', NULL, 'Republican', 'http://mgaleg.maryland.gov/2019RS/images/west02.jpg', 'elected', NULL),
('Christopher Bouchat', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '5', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/bouchat01.jpg', 'elected', NULL),
('Chris Adams', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '37B', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/adams01.jpg', 'elected', NULL),
('Clarence Lam', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '12', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/lam01.jpg', 'elected', NULL),
('Cory McCray', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '45', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/mccray01.jpg', 'elected', NULL),
('Courtney Watson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '9B', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/watson02.jpg', 'elected', NULL),
('Craig Zucker', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '14', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/zucker01.jpg', 'elected', NULL),
('Dalya Attar', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '41', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/attar01.jpg', 'elected', NULL),
('Dana Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '30A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/jones01.jpg', 'elected', NULL),
('Dana Stein', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '11B', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/stein.jpg', 'elected', NULL),
('Darrell Odom', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '27A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2026RS/images/odom01.jpg', 'elected', NULL),
('David Fraser-Hidalgo', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '15', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/fraser01.jpg', 'elected', NULL),
('David Moon', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '20', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/moon01.jpg', 'elected', NULL),
('Dawn Gile', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '33', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/gile01.jpg', 'elected', NULL),
('Debra Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '28', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/davis02.jpg', 'elected', NULL),
('Deni Taveras', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '47B', NULL, 'Democratic', 'https://global-uploads.webflow.com/5e1b86c619c05c91b9967ad6/620e4aa91638bf13a472cf3e_DtOqMwcsRnKd3LnHjPV2jw_thumb_d6b.jpg', 'elected', NULL),
('Denise Roberts', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '25', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2024RS/images/roberts01.jpg', 'elected', NULL),
('Derrick Coley', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '24', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2026RS/images/coley01.jpg', 'elected', NULL),
('Diana Fennell', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '47A', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/fennell01.jpg', 'elected', NULL),
('Dylan Behler', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '30A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/behler01.jpg', 'elected', NULL),
('Edith Patterson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '28', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2018RS/images/patterson02.jpg', 'elected', NULL),
('Elizabeth Embry', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '43A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/embry01.jpg', 'elected', NULL),
('Emily Shetty', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '18', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2024RS/images/shetty01.jpg', 'elected', NULL),
('Eric Ebersole', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '44A', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/ebersole01.jpg', 'elected', NULL),
('Gabriel Acevero', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '39', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2026RS/images/acevero01.jpg', 'elected', NULL),
('Gabriel Moreno', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '13', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2026RS/images/moreno01.jpg', 'elected', NULL),
('Gary Simmons', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '12B', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/simmons01.jpg', 'elected', NULL),
('Greg Wims', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '39', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/wims01.jpg', 'elected', NULL),
('Guy Guzzone', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '13', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2020RS/images/guzzone.jpg', 'elected', NULL),
('Harry Bhandari', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '8', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/bhandari01.jpg', 'elected', NULL),
('Heather Bagnall Tudball', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '33C', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/bagnall01.jpg', 'elected', NULL),
('Charles Sydnor', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '44', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2021RS/images/sydnor02.jpg', 'elected', NULL),
('J.B. Jennings', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '7', NULL, 'Republican', 'http://mgaleg.maryland.gov/2020RS/images/jennings.jpg', 'elected', NULL),
('Sandy Bartlett', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '32', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/bartlett02.jpg', 'elected', NULL),
('Jack Bailey', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '29', NULL, 'Republican', 'http://mgaleg.maryland.gov/2019RS/images/bailey01.jpg', 'elected', NULL),
('Jackie Addison', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '45', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/addison01.jpg', 'elected', NULL),
('Jamila Woods', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '26', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jamila_01-2018.jpg', 'elected', NULL),
('Jared Solomon', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '18', NULL, 'Democratic', 'https://bosepublicaffairs.com/wp-content/uploads/2020/12/solomon-768x959.jpg', 'elected', NULL),
('Jason Buckel', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '1B', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/buckel01.jpg', 'elected', NULL),
('Jason Gallion', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '35', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/gallion01.jpg', 'elected', NULL),
('Jay Jacobs', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '36', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/jacobs%20j.jpg', 'elected', NULL),
('Jeff Waldstreicher', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '18', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/waldstreicher1.jpg', 'elected', NULL),
('Jeff Ghrist', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '36', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/ghrist01.jpg', 'elected', NULL),
('Jeff Long', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '27B', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/long02.jpg', 'elected', NULL),
('Jen Terrasa', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '13', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/terrasa01.jpg', 'elected', NULL),
('Jennifer White Holland', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '10', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2024RS/images/white01.jpg', 'elected', NULL),
('Jesse Pippy', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '4', NULL, 'Republican', 'http://mgaleg.maryland.gov/2019RS/images/pippy01.jpg', 'elected', NULL),
('Jessica Feldmark', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '12A', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/feldmark01.jpg', 'elected', NULL),
('Jheanelle Wilkins', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '20', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/wilkins01.jpg', 'elected', NULL),
('Jim Hinebaugh', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '1A', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/hinebaugh01.jpg', 'elected', NULL),
('Jim Rosapepe', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '21', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/rosapepe.jpg', 'elected', NULL),
('Joanne Benson', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '24', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/benson.jpg', 'elected', NULL),
('Joe Vogel', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '17', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/vogel01.jpg', 'elected', NULL),
('Johnny Mautz', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '37', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/mautz02.jpg', 'elected', NULL),
('Johnny Salling', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '6', NULL, 'Republican', 'http://mgaleg.maryland.gov/2020RS/images/salling01.jpg', 'elected', NULL),
('Jon Cardin', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '11B', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/cardin01.jpg', 'elected', NULL),
('Joseline Peña-Melnyk', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '21', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/pena.jpg', 'elected', NULL),
('Josh Stonko', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '42C', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/stonko01.jpg', 'elected', NULL),
('Frank Conaway', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '40', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/conaway.jpg', 'elected', NULL),
('Marvin Holmes', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '23', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/holmes.jpg', 'elected', NULL),
('Robin Grammer', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '6', NULL, 'Republican', 'http://mgaleg.maryland.gov/2020RS/images/grammer01.jpg', 'elected', NULL),
('Steve Hershey', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '36', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/hershey.jpg', 'elected', NULL),
('Will Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '20', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2017RS/images/smith02.jpg', 'elected', NULL),
('Julian Ivey', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '47A', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/ivey01.jpg', 'elected', NULL),
('Julie Palakovich Carr', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '17', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/palakovich01.jpg', 'elected', NULL),
('Justin Ready', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '5', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/ready01.jpg', 'elected', NULL),
('Karen Young', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '3', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/young04.jpg', 'elected', NULL),
('Karen Simpson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '3', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/simpson01.jpg', 'elected', NULL),
('Karen Toles', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '25', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/toles01.jpg', 'elected', NULL),
('Kathy Szeliga', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '7A', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/szeliga.jpg', 'elected', NULL),
('Katie Hester', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '9', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/hester01.jpg', 'elected', NULL),
('Ken Kerr', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '3', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/kerr01.jpg', 'elected', NULL),
('Kent Roberson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '25', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2024RS/images/roberson01.jpg', 'elected', NULL),
('Kevin Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '38A', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025S1/images/anderson01.jpg', 'elected', NULL),
('Kevin Hornberger', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '35B', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/hornberger01.jpg', 'elected', NULL),
('Kevin Harris', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '27', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2026RS/images/harris03.jpg', 'elected', NULL),
('Kim Ross', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '8', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/ross01.jpg', 'elected', NULL),
('Kris Fair', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '3', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/fair01.jpg', 'elected', NULL),
('Kris Valderrama', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '26', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/valderrama.jpg', 'elected', NULL),
('Kym Taylor', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '23', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Kym_Taylor.jpg', 'elected', NULL),
('LaToya Nkongolo', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '31', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/nkongolo01.jpg', 'elected', NULL),
('Lauren Arikan', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '7B', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/arikan01.jpg', 'elected', NULL),
('Lesley Lopez', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '39', NULL, 'Democratic', 'https://static.votesmart.org/static/canphoto/181654.jpg', 'elected', NULL),
('Lily Qi', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '15', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/qi01.jpg', 'elected', NULL),
('Linda Foley', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '15', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2022RS/images/foley01.jpg', 'elected', NULL),
('Lorig Charkoudian', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '20', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2026RS/images/charkoudian01.jpg', 'elected', NULL),
('Luke Clippinger', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '46', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2020RS/images/clippinger.jpg', 'elected', NULL),
('Malcolm Augustine', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '47', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/augustine01.jpg', 'elected', NULL),
('Malcolm Ruff', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '41', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/ruff01.jpg', 'elected', NULL),
('Marc Korman', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '16', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/korman01.jpg', 'elected', NULL),
('Mark Edelson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '46', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/edelson01.jpg', 'elected', NULL),
('Mark Fisher', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '27C', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/fisher.jpg', 'elected', NULL),
('Mark Chang', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '32', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/chang01.jpg', 'elected', NULL),
('Marlon Amprey', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '40', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2021RS/images/amprey01.jpg', 'elected', NULL),
('Mary Lehman', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '21', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/lehman01.jpg', 'elected', NULL),
('Mary Beth Carozza', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '38', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/carozza01.jpg', 'elected', NULL),
('Mary-Dulany James', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '34', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/james01.jpg', 'elected', NULL),
('Mary Washington', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '43', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/washington.jpg', 'elected', NULL),
('Matt Morgan', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '29A', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/morgan02.jpg', 'elected', NULL),
('Matthew Schindler', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '2B', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/schindler01.jpg', 'elected', NULL),
('Melissa Wells', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '40', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/wells02.jpg', 'elected', NULL),
('Michele Guyton', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '42B', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/guyton01.jpg', 'elected', NULL),
('Mike Griffith', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '35A', NULL, 'Republican', 'http://mgaleg.maryland.gov/2020RS/images/griffith02.jpg', 'elected', NULL),
('Mike McKay', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '1', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/mckay02.jpg', 'elected', NULL),
('Mike Rogers', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '32', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/rogers01.jpg', 'elected', NULL),
('Scott Phillips', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '10', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/phillips02.jpg', 'elected', NULL),
('Nancy King', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '39', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/king.jpg', 'elected', NULL),
('Natalie Ziegler', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '9A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/ziegler01.jpg', 'elected', NULL),
('Nic Kipke', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '31', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/kipke.jpg', 'elected', NULL),
('Nick Allen', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '8', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/allen01.jpg', 'elected', NULL),
('Nick Charles', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '25', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2024RS/images/charles02.jpg', 'elected', NULL),
('Nicole Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '22', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/williams01.jpg', 'elected', NULL),
('Nino Mangione', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '42A', NULL, 'Republican', 'http://mgaleg.maryland.gov/2019RS/images/mangione01.jpg', 'elected', NULL),
('Pam Guzzone', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '13', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/guzzone01.jpg', 'elected', NULL),
('Pam Queen', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '14', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/queen01.jpg', 'elected', NULL),
('Pam Beidle', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '32', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/beidle01.jpg', 'elected', NULL),
('Paul Corderman', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '2', NULL, 'Republican', 'http://mgaleg.maryland.gov/2018RS/images/corderman01.jpg', 'elected', NULL),
('Regina Boyce', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '43A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/boyce01.jpg', 'elected', NULL),
('Ric Metzgar', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '6', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/metzgar01.jpg', 'elected', NULL),
('Robbyn Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '46', NULL, 'Democratic', 'http://msa.maryland.gov/msa/mdmanual/06hse/images/1198-1-07944b.jpg', 'elected', NULL),
('Bob Long', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '6', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/long01.jpg', 'elected', NULL),
('Ron Watson', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '23', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/watson03.jpg', 'elected', NULL),
('Ryan Nawrocki', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '7A', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/nawrocki01.jpg', 'elected', NULL),
('Ryan Spiegel', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '17', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/spiegel01.jpg', 'elected', NULL),
('Sandy Rosenberg', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '41', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2022RS/images/rosenberg.jpg', 'elected', NULL),
('Sara Love', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '16', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2024RS/images/love02.jpg', 'elected', NULL),
('Sarah Wolek', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '16', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/wolek01.jpg', 'elected', NULL),
('Sean Stinnett', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '41', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/stinnett01.jpg', 'elected', NULL),
('Seth Howard', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '30B', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/howard01.jpg', 'elected', NULL),
('Shaneka Henson', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '30', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/henson02.jpg', 'elected', NULL),
('Sheila Ruth', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '44B', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2020RS/images/ruth01.jpg', 'elected', NULL),
('Shelly Hettleman', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '11', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/hettleman02.jpg', 'elected', NULL),
('Sheree Sample-Hughes', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '37A', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2016RS/images/sample01.jpg', 'elected', NULL),
('Stephanie Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '45', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/smith03.jpg', 'elected', NULL),
('Steve Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '34A', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/johnson01.jpg', 'elected', NULL),
('Steve Arentz', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '36', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/arentz01.jpg', 'elected', NULL),
('Stuart Schmidt', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '33B', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/schmidt01.jpg', 'elected', NULL),
('Susan McComas', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '34B', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/mccomas.jpg', 'elected', NULL),
('Teresa Reilly', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '35A', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/reilly01.jpg', 'elected', NULL),
('Teresa Woorman', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '16', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2024RS/images/woorman01.jpg', 'elected', NULL),
('Terri Hill', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '12A', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2025RS/images/hill02.jpg', 'elected', NULL),
('Terry Baker', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '1C', NULL, 'Republican', 'https://msa.maryland.gov/msa/mdmanual/36loc/wa/leg/images/1198-1-09528b.jpg', 'elected', NULL),
('Tiffany Alston', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '24', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2023RS/images/alston01.jpg', 'elected', NULL),
('Todd Morgan', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '29C', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/morgan03.jpg', 'elected', NULL),
('Tom Hutchinson', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '37B', NULL, 'Republican', 'https://mgaleg.maryland.gov/2023RS/images/hutchinson01.jpg', 'elected', NULL),
('Vaughn Stewart', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '19', NULL, 'Democratic', 'https://mgaleg.maryland.gov/2026RS/images/stewart01.jpg', 'elected', NULL),
('Veronica Turner', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '26', NULL, 'Democratic', 'http://mgaleg.maryland.gov/2019RS/images/turner01.jpg', 'elected', NULL),
('Wayne Hartman', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '38C', NULL, 'Republican', 'http://mgaleg.maryland.gov/2019RS/images/hartman01.jpg', 'elected', NULL),
('Bill Folden', 'State Senator', 'Legislative Branch', 'Legislative', 'MD', '4', NULL, 'Republican', 'http://mgaleg.maryland.gov/2016RS/images/folden01.jpg', 'elected', NULL),
('William Wivell', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '2A', NULL, 'Republican', 'https://mgaleg.maryland.gov/2025RS/images/wivell01.jpg', 'elected', NULL),
('William Valentine', 'State Representative', 'Legislative Branch', 'Legislative', 'MD', '2A', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/fredericknewspost.com/content/tncms/assets/v3/editorial/a/7a/a7adf4f6-64f2-5123-82bc-5d65e10bda6e/62b95a9a20374.image.jpg?crop=815%2C1208%2C356%2C15&resize=200%2C296&order=crop%2Cresize', 'elected', NULL);
