-- MI state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'MI';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Alabas Farhat', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '3', NULL, 'Democratic', NULL, 'elected', NULL),
('Alicia St. Germaine', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '62', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/St. Germaine-062.jpg', 'elected', NULL),
('Amos O''Neal', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '94', NULL, 'Democratic', NULL, 'elected', NULL),
('Angela Rigas', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '79', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Rigas-079.jpg', 'elected', NULL),
('Angela Witwer', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '76', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D071_Angela_Witwer/071_Witwer.jpg', 'elected', NULL),
('Ann Bollin', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '49', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2020/07/HS_AnnBollin_0119-scaled.jpg', 'elected', NULL),
('Aric Nesbitt', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '20', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2019/01/Nesbitt-580x770.jpg', 'elected', NULL),
('Betsy Coffia', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '103', NULL, 'Democratic', NULL, 'elected', NULL),
('Bill Schuette', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '95', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Schuette-095.jpg', 'elected', NULL),
('Brad Paquette', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '37', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2020/07/HS_PAQUETTE_0119.jpg', 'elected', NULL),
('Brad Slagh', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '85', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/02/HS_SLAGH_0221_NSC_1065-scaled.jpg', 'elected', NULL),
('Brenda Carter', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '53', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D029_Brenda_Carter/029_Carter.jpg', 'elected', NULL),
('Brian BeGole', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '71', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/BeGole-071.jpg', 'elected', NULL),
('Bryan Posthumus', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '90', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/01/Bryan-Posthumus_HS.jpg', 'elected', NULL),
('Cam Cavitt', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '106', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Cavitt-106.jpg', 'elected', NULL),
('Carol Glanville', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '84', NULL, 'Democratic', NULL, 'elected', NULL),
('Carrie Rheingans', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '47', NULL, 'Democratic', NULL, 'elected', NULL),
('Chedrick Greene', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '35', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Chedrick_Greene_20251023_010156.jpeg', 'elected', NULL),
('Curt VanderWall', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '102', NULL, 'Republican', 'https://senate.michigan.gov/_images/35th.jpg', 'elected', NULL),
('Cynthia Neeley', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '70', NULL, 'Democratic', NULL, 'elected', NULL),
('Dan Lauwers', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '25', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Lauwers-580x770.jpg', 'elected', NULL),
('Darrin Camilleri', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '4', NULL, 'Democratic', 'https://senatedems.com/camilleri/wp-content/uploads/sites/10/2022/12/Portrait_Camilleri_Web.jpg', 'elected', NULL),
('David Martin', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '68', NULL, 'Republican', NULL, 'elected', NULL),
('Dave Prestin', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '108', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Prestin-108.jpg', 'elected', NULL),
('Dayna Polehanki', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '5', NULL, 'Democratic', 'https://senatedems.com/polehanki/wp-content/uploads/sites/11/2022/12/Polehanki-Official-Portrait.jpeg', 'elected', NULL),
('Denise Mentzer', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '61', NULL, 'Democratic', NULL, 'elected', NULL),
('Donavan McKinney', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '11', NULL, 'Democratic', NULL, 'elected', NULL),
('Donni Steele', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '54', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Steele-054.jpg', 'elected', NULL),
('Doug Wozniak', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '59', NULL, 'Republican', 'https://senate.michigan.gov/_images/8th.jpg', 'elected', NULL),
('Dylan Wegela', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '26', NULL, 'Democratic', NULL, 'elected', NULL),
('Ed McBroom', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '38', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2019/01/McBroom-580x770.jpg', 'elected', NULL),
('Emily Dievendorf', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '77', NULL, 'Democratic', NULL, 'elected', NULL),
('Erika Geiss', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '1', NULL, 'Democratic', 'https://senatedems.com/geiss/wp-content/uploads/sites/7/2022/12/MDS_Geiss_DSC5413.jpg', 'elected', NULL),
('Erin Byrnes', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '15', NULL, 'Democratic', NULL, 'elected', NULL),
('Gina Johnsen', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '78', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Johnsen-078.jpg', 'elected', NULL),
('Greg VanWoerkom', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '88', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2020/07/HS_VAN-WOERKOM_0119.jpg', 'elected', NULL),
('Greg Alexander', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '98', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Alexander-098.jpg', 'elected', NULL),
('Greg Markkanen', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '110', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2020/07/HS_MARKKAMEN_0119.jpg', 'elected', NULL),
('Helena Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '8', NULL, 'Democratic', NULL, 'elected', NULL),
('Jaime Greene', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '65', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Greene-065.jpg', 'elected', NULL),
('Jim DeSana', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '29', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/DeSana-029.jpg', 'elected', NULL),
('Jamie Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '28', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Thompson-028.jpg', 'elected', NULL),
('Jason Hoskins', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '18', NULL, 'Democratic', NULL, 'elected', NULL),
('Jason Morgan', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '23', NULL, 'Democratic', NULL, 'elected', NULL),
('Jason Woolford', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '50', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/jwoolford.jpg', 'elected', NULL),
('Jaz Martus', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '69', NULL, 'Democratic', NULL, 'elected', NULL),
('Jay DeBoyer', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '63', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/DeBoyer-063.jpg', 'elected', NULL),
('Jeff Irwin', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '15', NULL, 'Democratic', 'https://senatedems.com/irwin/wp-content/uploads/sites/19/2022/12/MDS_Irwin_DSC5423.jpg', 'elected', NULL),
('Jennifer Conlin', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '48', NULL, 'Democratic', NULL, 'elected', NULL),
('Jennifer Wortz', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '35', NULL, 'Republican', 'https://media-cdn.socastsrm.com/wordpress/wp-content/blogs.dir/2484/files/2024/08/screenshot-2024-08-07-003528.png', 'elected', NULL),
('Jeremy Moss', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '7', NULL, 'Democratic', 'https://senatedems.com/moss/wp-content/uploads/sites/13/2023/01/MDS_Moss_W3A6000.jpg', 'elected', NULL),
('Jerry Neyer', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '92', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Neyer-092.jpg', 'elected', NULL),
('Jim Runestad', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '23', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2019/01/Runestad-580x770.jpg', 'elected', NULL),
('Jimmie Wilson', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '32', NULL, 'Democratic', NULL, 'elected', NULL),
('Joe Pavlov', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '64', NULL, 'Republican', 'https://i1.wp.com/www.joepavlov.com/wp-content/uploads/2024/08/JoePavolv-@-Wood-Door.jpg?resize=841%2C841&strip=info&ssl=1', 'elected', NULL),
('Joe Tate', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '9', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D002_Joe_Tate/002_Tate.jpg', 'elected', NULL),
('Joey Andrews', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '38', NULL, 'Democratic', NULL, 'elected', NULL),
('John Cherry', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '27', NULL, 'Democratic', 'https://senatedems.com/cherry/wp-content/uploads/sites/22/2022/12/Portrait_Cherry_Web.jpg', 'elected', NULL),
('John Damoose', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '37', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Damoose-580x770.jpg', 'elected', NULL),
('John Fitzgerald', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '83', NULL, 'Democratic', NULL, 'elected', NULL),
('J.R. Roth', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '104', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/01/HS_ROTH_1220_NSC_7566-scaled.jpg', 'elected', NULL),
('Jon Bumstead', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '32', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Bumstead-580x770.jpg', 'elected', NULL),
('Jonathan Lindsey', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '17', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Lindsey-580x770.jpg', 'elected', NULL),
('Joe Aragona', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '60', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Aragona-060.jpg', 'elected', NULL),
('Joe Bellino', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '16', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Bellino-580x770.jpg', 'elected', NULL),
('Joseph Fox', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '101', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Fox-101.jpg', 'elected', NULL),
('Josh Schriver', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '66', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Schriver-066.jpg', 'elected', NULL),
('Julie Brixie', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '73', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D069_Julie_Brixie/069_Brixie.jpg', 'elected', NULL),
('Julie Rogers', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '41', NULL, 'Democratic', NULL, 'elected', NULL),
('Kara Hope', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '74', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D067_Kara_Hope/067_Hope.jpg', 'elected', NULL),
('Karen Whitsett', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '4', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D009_Karen_Whitsett/009_Whitsett.jpg', 'elected', NULL),
('Karl Bohnak', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '109', NULL, 'Republican', 'https://votebohnak.com/wp-content/uploads/2024/03/k5-400x266.jpg', 'elected', NULL),
('Kathy Schmaltz', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '46', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Schmaltz-046.jpg', 'elected', NULL),
('Kelly Breen', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '21', NULL, 'Democratic', NULL, 'elected', NULL),
('Ken Borton', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '105', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/01/HS_BORTON_0121_NSC_7600-scaled.jpg', 'elected', NULL),
('Kevin Daley', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '26', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Daley-580x770.jpg', 'elected', NULL),
('Kevin Hertel', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '12', NULL, 'Democratic', 'https://senatedems.com/hertel/wp-content/uploads/sites/16/2022/12/Hertel_Portrait.jpg', 'elected', NULL),
('Kimberly Edwards', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '12', NULL, 'Democratic', NULL, 'elected', NULL),
('Kristian Grant', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '82', NULL, 'Democratic', NULL, 'elected', NULL),
('Lana Theis', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '22', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2019/01/Theis-580x770.jpg', 'elected', NULL),
('Laurie Pohutsky', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '17', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D019_Laurie_Pohutsky/019_Pohutsky.jpg', 'elected', NULL),
('Luke Meerman', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '89', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2020/07/HS_MEERMAN_0119.jpg', 'elected', NULL),
('Mai Xiong', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '13', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MaiXiong.jpeg', 'elected', NULL),
('Mallory McMorrow', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '8', NULL, 'Democratic', 'https://senatedems.com/mcmorrow/wp-content/uploads/sites/14/2023/02/MDS_McMorrow_DSC5342_dec20.jpg', 'elected', NULL),
('Mark Huizenga', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '30', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2021/11/Huizenga-580x770.jpg', 'elected', NULL),
('Mark Tisdel', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '55', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/01/HS_TISDEL_0121_NSC_7619-scaled.jpg', 'elected', NULL),
('Mary Cavanagh', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '6', NULL, 'Democratic', 'https://senatedems.com/cavanagh/wp-content/uploads/sites/12/2022/12/Cavanaugh_Web.jpg', 'elected', NULL),
('Matt Bierlein', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '97', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Bierlein-097.jpg', 'elected', NULL),
('Matt Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '42', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2023/01/Leader-Matt-Hall-headshot-scaled.jpg', 'elected', NULL),
('Matt Koleszar', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '22', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D020_Matt_Koleszar/020_Koleszar.jpg', 'elected', NULL),
('Matt Longjohn', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '40', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/mlongjohn.jpg', 'elected', NULL),
('Matt Maddock', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '51', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2023/01/Maddock-051.jpg', 'elected', NULL),
('Michael Webber', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '9', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Webber-580x770.jpg', 'elected', NULL),
('Michele Hoitenga', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '36', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Hoitenga-580x770.jpg', 'elected', NULL),
('Mike Harris', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '52', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2022/05/HS_HARRIS_0522_web-scaled.jpg', 'elected', NULL),
('Mike Hoadley', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '99', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Hoadley-099.jpg', 'elected', NULL),
('Mike McFall', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '14', NULL, 'Democratic', NULL, 'elected', NULL),
('Mike Mueller', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '72', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2020/07/HS_MULLER_1218_DSC_9358.jpg', 'elected', NULL),
('Morgan Foreman', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '33', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Nathan_Fallahi_20240808_091506.jpg', 'elected', NULL),
('Nancy DeBoer', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '86', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/De Boer-086.jpg', 'elected', NULL),
('Nancy Jenkins-Arno', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '34', NULL, 'Republican', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/21022.jpg', 'elected', NULL),
('Natalie Price', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '6', NULL, 'Democratic', NULL, 'elected', NULL),
('Noah Arbit', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '20', NULL, 'Democratic', NULL, 'elected', NULL),
('Parker Fairbairn', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '107', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ParkerFairbairn2024.JPG', 'elected', NULL),
('Pat Outman', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '91', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/01/HS_OUTMAN_0221_NSC_7638-scaled.jpg', 'elected', NULL),
('Paul Wojno', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '10', NULL, 'Democratic', 'https://senatedems.com/wojno/wp-content/uploads/sites/3/2023/01/MDS_Wojno_OfficialPortrait.jpg', 'elected', NULL),
('Pauline Wendzel', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '39', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2020/07/HS_WENDZEL_1218_DSC_9364.jpg', 'elected', NULL),
('Penelope Tsernoglou', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '75', NULL, 'Democratic', NULL, 'elected', NULL),
('Peter Herzberg', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '25', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/PeterHerzberg.jpg', 'elected', NULL),
('Phil Green', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '67', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2022/06/HS_GREEN_0522_NSC5945-scaled.jpg', 'elected', NULL),
('Phil Skaggs', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '80', NULL, 'Democratic', NULL, 'elected', NULL),
('Rachelle Smit', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '43', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Smit-043.jpg', 'elected', NULL),
('Ranjeev Puri', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '24', NULL, 'Democratic', NULL, 'elected', NULL),
('Reggie Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '31', NULL, 'Democratic', NULL, 'elected', NULL),
('Regina Weiss', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '5', NULL, 'Democratic', NULL, 'elected', NULL),
('Rick Outman', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '33', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2019/01/Outman-580x770.jpg', 'elected', NULL),
('Roger Hauck', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '34', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Hauck-580x770.jpg', 'elected', NULL),
('Roger Victory', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '31', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2019/01/Victory-580x770.jpg', 'elected', NULL),
('Ron Robinson', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '58', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Ron_Robinson_20240808_093235.jpg', 'elected', NULL),
('Rosemary Bayer', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '13', NULL, 'Democratic', 'https://senatedems.com/bayer/wp-content/uploads/sites/17/2022/12/Bayer-Official-Portrait.jpeg', 'elected', NULL),
('Ruth Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '24', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Johnson-580x770.jpg', 'elected', NULL),
('Rylee Linting', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '27', NULL, 'Republican', 'https://www.detroitnews.com/gcdn/authoring/authoring-images/2024/07/26/PDTN/74565149007-rylee-linting.jpg', 'elected', NULL),
('Sam Singh', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '28', NULL, 'Democratic', 'https://senatedems.com/singh/wp-content/uploads/sites/23/2023/01/Singh-portrait.jpg', 'elected', NULL),
('Samantha Steckloff', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '19', NULL, 'Democratic', NULL, 'elected', NULL),
('Sarah Anthony', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '21', NULL, 'Democratic', 'https://senatedems.com/anthony/wp-content/uploads/sites/21/2022/12/MDS_Anthony_DSC5449.jpg', 'elected', NULL),
('Sarah Lightner', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '45', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/04/HS_Lightner_0421_NSC_0141-scaled.jpg', 'elected', NULL),
('Sean McCann', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '19', NULL, 'Democratic', 'https://senatedems.com/mccann/wp-content/uploads/sites/20/2022/12/MDS_McCann_DSC5430.jpg', 'elected', NULL),
('Sharon MacDonell', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '56', NULL, 'Democratic', NULL, 'elected', NULL),
('Stephanie Chang', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '3', NULL, 'Democratic', 'https://senatedems.com/chang/wp-content/uploads/sites/9/2022/12/MDS_Chang_DSC5412.jpg', 'elected', NULL),
('Stephanie Young', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '16', NULL, 'Democratic', NULL, 'elected', NULL),
('Stephen Wooden', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '81', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/swooden.jpg', 'elected', NULL),
('Steve Carra', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '36', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/05/HS_CARRA_0221_NSC_2360-scaled.jpg', 'elected', NULL),
('Steve Frisbie', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '44', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkosbA1eo1rgLKVUU8dvxAKdj_-RAIjrqKtQ&s', 'elected', NULL),
('Sue Shink', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '14', NULL, 'Democratic', 'https://senatedems.com/shink/wp-content/uploads/sites/18/2022/12/Portrait_Shink_Web.jpg', 'elected', NULL),
('Sylvia Santana', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '2', NULL, 'Democratic', 'https://senatedems.com/santana/wp-content/uploads/sites/8/2022/12/Santana-Official-Portrait.jpeg', 'elected', NULL),
('Thomas Albert', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '18', NULL, 'Republican', 'https://www.misenategop.com/wp-content/uploads/2023/01/Albert-580x770.jpg', 'elected', NULL),
('Tom Kuhn', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '57', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Kuhn-057.jpg', 'elected', NULL),
('Tim Kelly', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '93', NULL, 'Republican', 'http://gophouse.org/wp-content/uploads/2015/01/HS_Kelly_0213_DSC6086_hr94-192x300.jpg', 'elected', NULL),
('Timmy Beson', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '96', NULL, 'Republican', 'https://dtj5wlj7ond0z.cloudfront.net/uploads/2021/01/HS_BESON_1220_NSC_6238-scaled.jpg', 'elected', NULL),
('Tom Kunse', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '100', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Kunse-100.jpg', 'elected', NULL),
('Tonya Phillips', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '7', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Tonya_Myers_Phillips_20241022_115414.png', 'elected', NULL),
('Tullio Liberati', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '2', NULL, 'Democratic', NULL, 'elected', NULL),
('Tyrone Carter', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '1', NULL, 'Democratic', 'https://housedems.com/sites/default/files/Images/Representative_Images/D006_Tyrone_Carter/006_Carter.jpg', 'elected', NULL),
('Veronica Klinefelt', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '11', NULL, 'Democratic', 'https://senatedems.com/klinefelt/wp-content/uploads/sites/15/2022/12/Portrait_Klinefelt_Web.jpg', 'elected', NULL),
('Veronica Paiz', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '10', NULL, 'Democratic', NULL, 'elected', NULL),
('Will Bruck', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '30', NULL, 'Republican', 'https://www.house.mi.gov/media/Representatives/Bruck-030.jpg', 'elected', NULL),
('Will Snyder', 'State Representative', 'Legislative Branch', 'Legislative', 'MI', '87', NULL, 'Democratic', NULL, 'elected', NULL),
('Winnie Brinks', 'State Senator', 'Legislative Branch', 'Legislative', 'MI', '29', NULL, 'Democratic', 'https://senatedems.com/brinks/wp-content/uploads/sites/6/2022/12/MDS_Brinks_DSC5456_536.jpg', 'elected', NULL);
