-- MN state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'MN';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Aisha Gomez', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '62A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/62A.gif?v=112221', 'elected', NULL),
('Alex Falconer', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '49A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/49A.gif?v=112221', 'elected', NULL),
('Alice Mann', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '50', NULL, 'Democratic', 'https://www.senate.mn/graphics/50Mann.jpg', 'elected', NULL),
('Liish Kozlowski', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '8B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/08B.gif?v=112221', 'elected', NULL),
('Amanda Hemmingsen-Jaeger', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '47', NULL, 'Democratic', 'https://www.senate.mn/graphics/47Hemmingsen-Jaeger.jpg', 'elected', NULL),
('Andrew Mathews', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '27', NULL, 'Republican', 'https://www.senate.mn/graphics/15Mathews.jpg', 'elected', NULL),
('Andrew Myers', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '45A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/45A.gif?v=112221', 'elected', NULL),
('Andrew Lang', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '16', NULL, 'Republican', 'https://www.senate.mn/graphics/16Lang.jpg', 'elected', NULL),
('Andy Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '25B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/25B.gif?v=112221', 'elected', NULL),
('Ann Rest', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '43', NULL, 'Democratic', 'https://www.senate.mn/graphics/43Rest.jpg', 'elected', NULL),
('Ann Johnson Stewart', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '45', NULL, 'Democratic', 'https://www.senate.mn/graphics/45Johnson_Stewart.jpg', 'elected', NULL),
('Anquam Mahamoud', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '62B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/62B.gif?v=112221', 'elected', NULL),
('Aric Putnam', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '14', NULL, 'Democratic', 'https://www.senate.mn/graphics/14PutnamAric.jpg', 'elected', NULL),
('Athena Hollins', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '66B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/66B.gif?v=112221', 'elected', NULL),
('Ben Bakeberg', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '54B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/54B.gif?v=112221', 'elected', NULL),
('Ben Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '6A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/06A.gif?v=112221', 'elected', NULL),
('Bernie Perryman', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '14A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/14A.gif?v=112221', 'elected', NULL),
('Bianca Virnig', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '52B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/52B.gif?v=112221', 'elected', NULL),
('Bidal Duran', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '2A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/02A.gif?v=112221', 'elected', NULL),
('Bill Lieske', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '58', NULL, 'Republican', 'https://www.senate.mn/graphics/58Lieske.jpg', 'elected', NULL),
('Bill Weber', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '21', NULL, 'Republican', 'https://www.senate.mn/graphics/22Weber.jpg', 'elected', NULL),
('Bjorn Olson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '22A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/22A.gif?v=112221', 'elected', NULL),
('Bobbie Harder', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '17B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/17B.gif?v=112221', 'elected', NULL),
('Bobby Joe Champion', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '59', NULL, 'Democratic', 'https://www.senate.mn/graphics/59Champion.jpg', 'elected', NULL),
('Bonnie Westlin', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '42', NULL, 'Democratic', 'https://www.senate.mn/graphics/42Westlin.jpg', 'elected', NULL),
('Brad Tabke', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '54A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/54A.gif?v=112221', 'elected', NULL),
('Brion Curran', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '36B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/36B.gif?v=112221', 'elected', NULL),
('Bryan Lawrence', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '27B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/27B.gif?v=112221', 'elected', NULL),
('Cal Bahr', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '31', NULL, 'Republican', 'https://www.senate.mn/graphics/31Bahr.jpg', 'elected', NULL),
('Cal Warwas', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '7B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/07B.gif?v=112221', 'elected', NULL),
('Carla Nelson', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '24', NULL, 'Republican', 'https://www.senate.mn/graphics/24Nelson.jpg', 'elected', NULL),
('Carlie Kotyza-Witthuhn', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '49B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/49B.gif?v=112221', 'elected', NULL),
('Cedrick Frazier', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '43A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/43A.gif?v=112221', 'elected', NULL),
('Cheryl Youakim', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '46B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/46B.gif?v=112221', 'elected', NULL),
('Chris Swedzinski', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '15A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/15A.gif?v=112221', 'elected', NULL),
('Clare Oumou Verbeten', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '66', NULL, 'Democratic', 'https://www.senate.mn/graphics/66OumouVerbeten.jpg', 'elected', NULL),
('Scott Dibble', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '61', NULL, 'Democratic', 'https://www.senate.mn/graphics/61Dibble.jpg', 'elected', NULL),
('Dan Wolgamott', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '14B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/14B.gif?v=112221', 'elected', NULL),
('Danny Nadeau', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '34A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/34A.gif?v=112221', 'elected', NULL),
('Dave Baker', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '16B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/16B.gif?v=112221', 'elected', NULL),
('Dave Pinto', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '64B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/64B.gif?v=112221', 'elected', NULL),
('David Gottfried', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '40B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/40B.gif?v=112221', 'elected', NULL),
('Dawn Gillman', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '17A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/17A.gif?v=112221', 'elected', NULL),
('Doron Clark', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '60', NULL, 'Democratic', 'https://www.senate.mn/graphics/60Clark.jpg', 'elected', NULL),
('Drew Roach', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '58B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/58B.gif?v=112221', 'elected', NULL),
('Duane Quam', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '24A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/24A.gif?v=112221', 'elected', NULL),
('Elliott Engen', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '36A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/36A.gif?v=112221', 'elected', NULL),
('Emma Greenman', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '63B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/63B.gif?v=112221', 'elected', NULL),
('Eric Lucero', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '30', NULL, 'Republican', 'https://www.senate.mn/graphics/30Lucero.jpg', 'elected', NULL),
('Eric Pratt', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '54', NULL, 'Republican', 'https://www.senate.mn/graphics/55Pratt.jpg', 'elected', NULL),
('Erica Schwartz', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '18A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/18A.gif?v=112221', 'elected', NULL),
('Erin Maye Quade', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '56', NULL, 'Democratic', 'https://www.senate.mn/graphics/56MayeQuade.jpg', 'elected', NULL),
('Erin Koegel', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '39A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/39A.gif?v=112221', 'elected', NULL),
('Erin Murphy', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '64', NULL, 'Democratic', 'https://www.senate.mn/graphics/64MurphyErin.jpg', 'elected', NULL),
('Esther Agbaje', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '59B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/59B.gif', 'elected', NULL),
('Ethan Cha', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '47B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/47B.gif?v=112221', 'elected', NULL),
('Foung Hawj', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '67', NULL, 'Democratic', 'https://www.senate.mn/graphics/67Hawj.jpg', 'elected', NULL),
('Fue Lee', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '59A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/59A.gif?v=112221', 'elected', NULL),
('Gary Dahms', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '15', NULL, 'Republican', 'https://www.senate.mn/graphics/16Dahms.jpg', 'elected', NULL),
('Gene Dornink', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '23', NULL, 'Republican', 'https://www.senate.mn/graphics/27DorninkGene.jpg', 'elected', NULL),
('Ginny Klevorn', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '42B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/42B.gif?v=112221', 'elected', NULL),
('Glenn Gruenhagen', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '17', NULL, 'Republican', 'https://www.senate.mn/graphics/17Gruenhagen.jpg', 'elected', NULL),
('Grant Hauschild', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '3', NULL, 'Democratic', 'https://www.senate.mn/graphics/03Hauschild.jpg', 'elected', NULL),
('Greg Davids', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '26B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/26B.gif?v=112221', 'elected', NULL),
('Harry Niska', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '31A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/31A.gif?v=112221', 'elected', NULL),
('Heather Gustafson', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '36', NULL, 'Democratic', 'https://www.senate.mn/graphics/36Gustafson.jpg', 'elected', NULL),
('Heather Keeler', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '4A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/04A.gif?v=112221', 'elected', NULL),
('Huldah Hiltsley', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '38A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/38A.gif?v=112221', 'elected', NULL),
('Isaac Schultz', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '10B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/10B.gif?v=112221', 'elected', NULL),
('Jamie Long', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '61B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/61B.gif?v=112221', 'elected', NULL),
('Jason Rarick', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '11', NULL, 'Republican', 'https://www.senate.mn/graphics/11Rarick.jpg', 'elected', NULL),
('Jay Xiong', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '67B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/67B.gif?v=112221', 'elected', NULL),
('Jeff Backer', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '9A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/09A.gif?v=112221', 'elected', NULL),
('Jeff Dotseth', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '11A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/11A.gif?v=112221', 'elected', NULL),
('Jeff Howe', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '13', NULL, 'Republican', 'https://www.senate.mn/graphics/13Howe.jpg', 'elected', NULL),
('Jeff Witte', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '57B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/57B.gif?v=112221', 'elected', NULL),
('Jen McEwen', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '8', NULL, 'Democratic', 'https://www.senate.mn/graphics/07McEwenJen.jpg', 'elected', NULL),
('Jeremy Miller', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '26', NULL, 'Republican', 'https://www.senate.mn/graphics/26Miller.jpg', 'elected', NULL),
('Jess Hanson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '55A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/55A.gif?v=112221', 'elected', NULL),
('Jim Abeler', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '35', NULL, 'Republican', 'https://www.senate.mn/graphics/35Abeler.jpg', 'elected', NULL),
('Jim Carlson', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '52', NULL, 'Democratic', 'https://www.senate.mn/graphics/51Carlson.jpg', 'elected', NULL),
('Jim Joy', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '4B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/04B.gif?v=112221', 'elected', NULL),
('Jim Nash', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '48A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/48A.gif?v=112221', 'elected', NULL),
('Jimmy Gordon', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '28A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/28A.gif?v=112221', 'elected', NULL),
('Joe McDonald', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '29A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/29A.gif?v=112221', 'elected', NULL),
('Joe Schomacker', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '29A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/21A.gif?v=112221', 'elected', NULL),
('John Hoffman', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '34', NULL, 'Democratic', 'https://www.senate.mn/graphics/36Hoffman.jpg', 'elected', NULL),
('John Burkel', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '1A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/01A.gif', 'elected', NULL),
('John Huot', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '56B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/56B.gif?v=112221', 'elected', NULL),
('John Marty', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '40', NULL, 'Democratic', 'https://www.senate.mn/graphics/40Marty.jpg', 'elected', NULL),
('John Jasinski', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '19', NULL, 'Republican', 'https://www.senate.mn/graphics/24Jasinski.jpg', 'elected', NULL),
('Jon Koznick', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '57A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/57A.gif?v=112221', 'elected', NULL),
('Jordan Rasmusson', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '9', NULL, 'Republican', 'https://www.senate.mn/graphics/09Rasmusson.jpg', 'elected', NULL),
('Josh Heintzeman', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '6B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/06B.gif?v=112221', 'elected', NULL),
('Josiah Hill', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '33B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/33B.gif?v=112221', 'elected', NULL),
('Judy Seeberger', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '41', NULL, 'Democratic', 'https://www.senate.mn/graphics/41Seeberger.jpg', 'elected', NULL),
('Julia Coleman', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '48', NULL, 'Republican', 'https://www.senate.mn/graphics/47ColemanJulia.jpg', 'elected', NULL),
('Julie Greene', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '50A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/50A.gif?v=112221', 'elected', NULL),
('Kaela Berg', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '55B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/55B.gif', 'elected', NULL),
('Kari Rehrauer', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '35B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/35B.gif?v=112221', 'elected', NULL),
('Karin Housley', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '33', NULL, 'Republican', 'https://www.senate.mn/graphics/39Housley.jpg', 'elected', NULL),
('Katie Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '61A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/61A.gif?v=112221', 'elected', NULL),
('Keith Allen', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '19A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/19A.gif', 'elected', NULL),
('Kelly Moller', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '40A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/40A.gif?v=112221', 'elected', NULL),
('Keri Heintzeman', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '6', NULL, 'Republican', 'https://www.senate.mn/graphics/06Heintzeman.jpg', 'elected', NULL),
('Kim Hicks', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '25A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/25A.gif?v=112221', 'elected', NULL),
('Krista Knudsen', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '5A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/05A.gif?v=112221', 'elected', NULL),
('Kristi Pursell', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '58A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/58A.gif?v=112221', 'elected', NULL),
('Kristin Bahner', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '37B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/37B.gif', 'elected', NULL),
('Kristin Robbins', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '37A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/37A.gif?v=112221', 'elected', NULL),
('Larry Kraft', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '46A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/46A.gif?v=112221', 'elected', NULL),
('Leigh Finke', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '66A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/66A.gif?v=112221', 'elected', NULL),
('Leon Lillie', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '44B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/44B.gif?v=112221', 'elected', NULL),
('Lindsey Port', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '55', NULL, 'Democratic', 'https://www.senate.mn/graphics/56PortLindsey.jpg', 'elected', NULL),
('Lisa Demuth', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '13A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls93/13A.gif?v=032323', 'elected', NULL),
('Liz Boldon', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '25', NULL, 'Democratic', 'https://www.senate.mn/graphics/25Boldon.jpg', 'elected', NULL),
('Liz Lee', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '67A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/67A.gif?v=112221', 'elected', NULL),
('Liz Reyer', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '52A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/52A.gif?v=112221', 'elected', NULL),
('Lucy Rehm', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '48B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/48B.gif?v=112221', 'elected', NULL),
('Luke Frederick', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '18B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/18B.gif?v=112221', 'elected', NULL),
('María Isa Pérez-Vega', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '65B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/65B.gif?v=112221', 'elected', NULL),
('Marion Rarick', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '29B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/29B.gif?v=112221', 'elected', NULL),
('Marj Fogelman', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '21B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/21B.gif?v=112221', 'elected', NULL),
('Mark Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '1', NULL, 'Republican', 'https://www.senate.mn/graphics/01Johnson.jpg', 'elected', NULL),
('Mark Koran', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '28', NULL, 'Republican', 'https://www.senate.mn/graphics/32Koran.jpg', 'elected', NULL),
('Mary Clardy', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '53A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/53A.gif?v=112221', 'elected', NULL),
('Mary Franson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '12B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/12B.gif?v=112221', 'elected', NULL),
('Mary Kunesh-Podein', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '39', NULL, 'Democratic', 'https://www.senate.mn/graphics/41KuneshPodeinMary.jpg', 'elected', NULL),
('Matt Bliss', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '2B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/02B.gif?v=112221', 'elected', NULL),
('Matt Klein', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '53', NULL, 'Democratic', 'https://www.senate.mn/graphics/52Klein.jpg', 'elected', NULL),
('Matt Norris', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '32B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/32B.gif?v=112221', 'elected', NULL),
('Max Rymer', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '28B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/28B.gif?v=112221', 'elected', NULL),
('Meg Luger-Nikolai', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '64A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/64A.gif?v=012126', 'elected', NULL),
('Melissa Wiklund', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '51', NULL, 'Democratic', 'https://www.senate.mn/graphics/50Wiklund.jpg', 'elected', NULL),
('Michael Kreun', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '32', NULL, 'Republican', 'https://www.senate.mn/graphics/32Kreun.jpg', 'elected', NULL),
('Mike Howard', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '51A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/51A.gif?v=112221', 'elected', NULL),
('Mike Freiberg', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '43B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/43B.gif?v=112221', 'elected', NULL),
('Mike Holmstrom', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '29', NULL, 'Republican', 'https://www.senate.mn/graphics/29Holmstrom.jpg', 'elected', NULL),
('Mike Wiener', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '5B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/05B.gif?v=112221', 'elected', NULL),
('Mohamud Noor', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '60B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/60B.gif?v=112221', 'elected', NULL),
('Natalie Zeleznikar', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '3B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/03B.gif?v=112221', 'elected', NULL),
('Nathan Coulter', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '51B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/51B.gif?v=112221', 'elected', NULL),
('Nathan Nelson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '11B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/11B.gif?v=112221', 'elected', NULL),
('Nathan Wesenberg', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '10', NULL, 'Republican', 'https://www.senate.mn/graphics/10Wesenberg.jpg', 'elected', NULL),
('Ned Carroll', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '42A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls93/42A.gif?v=112221', 'elected', NULL),
('Nick Frentz', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '18', NULL, 'Democratic', 'https://www.senate.mn/graphics/19Frentz.jpg', 'elected', NULL),
('Nolan West', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '32A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/32A.gif?v=112221', 'elected', NULL),
('Omar Fateh', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '62', NULL, 'Democratic', 'https://www.senate.mn/graphics/62FatehOmar.jpg', 'elected', NULL),
('Pam Altendorf', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '20A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/20A.gif', 'elected', NULL),
('Patty Mueller', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '23B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/23B.gif?v=112221', 'elected', NULL),
('Patti Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '33A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/33A.gif', 'elected', NULL),
('Patty Acomb', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '45B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/45B.gif', 'elected', NULL),
('Paul Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '12A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/12A.gif?v=112221', 'elected', NULL),
('Paul Utke', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '5', NULL, 'Republican', 'https://www.senate.mn/graphics/02Utke.jpg', 'elected', NULL),
('Paul Novotny', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '30B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/30B.gif?v=112221', 'elected', NULL),
('Paul Torkelson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '15B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/15B.gif?v=112221', 'elected', NULL),
('Peggy Bennett', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '23A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls93/23A.jpg', 'elected', NULL),
('Peggy Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '31B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/31B.gif?v=112221', 'elected', NULL),
('Pete Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '8A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/08A.gif?v=112221', 'elected', NULL),
('Peter Fischer', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '44A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/44A.gif?v=112221', 'elected', NULL),
('Rich Draheim', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '22', NULL, 'Republican', 'https://www.senate.mn/graphics/20Draheim.jpg', 'elected', NULL),
('Rick Hansen', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '53B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/53B.gif?v=112221', 'elected', NULL),
('Ripper Repinski', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '26A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/26A.gif?v=112221', 'elected', NULL),
('Robert Bierman', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '56A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/56A.gif', 'elected', NULL),
('Rob Farnsworth', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '7', NULL, 'Republican', 'https://www.senate.mn/graphics/07Farnsworth.jpg', 'elected', NULL),
('Rob Kupec', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '4', NULL, 'Democratic', 'https://www.senate.mn/graphics/04Kupec.jpg', 'elected', NULL),
('Roger Skraba', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '3A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/03A.gif?v=112221', 'elected', NULL),
('Ron Kresha', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '10A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/10A.gif?v=112221', 'elected', NULL),
('Ron Latz', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '46', NULL, 'Democratic', 'https://www.senate.mn/graphics/46Latz.jpg', 'elected', NULL),
('Samakab Hussein', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '65A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/65A.gif?v=112221', 'elected', NULL),
('Samantha Sencer-Mura', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '63A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/63A.gif?v=112221', 'elected', NULL),
('Samantha Vang', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '38B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/38B.gif?v=112221', 'elected', NULL),
('Sandra Feist', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '39B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/39B.gif?v=112221', 'elected', NULL),
('Sandy Pappas', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '65', NULL, 'Democratic', 'https://www.senate.mn/graphics/65Pappas.jpg', 'elected', NULL),
('Scott Van Binsbergen', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '16A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/16A.gif?v=112221', 'elected', NULL),
('Shane Mekeland', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '27A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/27A.gif?v=112221', 'elected', NULL),
('Shelley Buck', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '47A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/47A.gif?v=012126', 'elected', NULL),
('Spencer Igo', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '7A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/07A.gif?v=112221', 'elected', NULL),
('Steve Cwodzinski', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '49', NULL, 'Democratic', 'https://www.senate.mn/graphics/49Cwodzinski.jpg', 'elected', NULL),
('Steve Drazkowski', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '20', NULL, 'Republican', 'https://www.senate.mn/graphics/20Drazkowski.jpg', 'elected', NULL),
('Steve Elkins', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '50B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/50B.gif?v=112221', 'elected', NULL),
('Steve Gander', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '1B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/01B.gif?v=112221', 'elected', NULL),
('Steve Green', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '2', NULL, 'Republican', 'https://www.senate.mn/graphics/02Green.jpg', 'elected', NULL),
('Steve Jacob', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '20B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/20B.gif?v=112221', 'elected', NULL),
('Susan Pha', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '38', NULL, 'Democratic', 'https://www.senate.mn/graphics/38Pha.jpg', 'elected', NULL),
('Sydney Jordan', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '60A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/60A.gif?v=112221', 'elected', NULL),
('Terry Stier', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '22B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/22B.gif?v=112221', 'elected', NULL),
('Tim O''Driscoll', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '13B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/13B.gif?v=112221', 'elected', NULL),
('Tina Liebling', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '24B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/24B.gif?v=112221', 'elected', NULL),
('Tom Dippel', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '41B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/41B.gif?v=112221', 'elected', NULL),
('Tom Murphy', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '9B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/09B.gif?v=112221', 'elected', NULL),
('Tom Sexton', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '19B', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/19B.gif?v=112221', 'elected', NULL),
('Torrey Westrom', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '12', NULL, 'Republican', 'https://www.senate.mn/graphics/12Westrom.jpg', 'elected', NULL),
('Tou Xiong', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '44', NULL, 'Democratic', 'https://www.senate.mn/graphics/44Xiong.jpg', 'elected', NULL),
('Walter Hudson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '30A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/30A.gif?v=112221', 'elected', NULL),
('Warren Limmer', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '37', NULL, 'Republican', 'https://www.senate.mn/graphics/37Limmer.jpg', 'elected', NULL),
('Wayne Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '41A', NULL, 'Republican', 'https://www.house.mn.gov/hinfo/memberimgls94/41A.gif?v=112221', 'elected', NULL),
('Xp Lee', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '34B', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/34B.gif?v=112221', 'elected', NULL),
('Zach Duckworth', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '57', NULL, 'Republican', 'https://www.senate.mn/graphics/58DuckworthZach.jpg', 'elected', NULL),
('Zack Stephenson', 'State Representative', 'Legislative Branch', 'Legislative', 'MN', '35A', NULL, 'Democratic', 'https://www.house.mn.gov/hinfo/memberimgls94/35A.gif?v=112221', 'elected', NULL),
('Zaynab Mohamed', 'State Senator', 'Legislative Branch', 'Legislative', 'MN', '63', NULL, 'Democratic', 'https://www.senate.mn/graphics/63Mohamed.jpg', 'elected', NULL);
