-- MO state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'MO';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Aaron Crossley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '29', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2366', 'elected', NULL),
('Adam Schnelting', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '23', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2087', 'elected', NULL),
('Adrian Plank', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '47', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2395', 'elected', NULL),
('Alex Riley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '134', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2232', 'elected', NULL),
('Angela Mosley', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '13', NULL, 'Democratic', 'https://www.senate.mo.gov/21web/wp-content/uploads/2020/12/Mosley2021-200x300.jpg', 'elected', NULL),
('Ann Kelley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '127', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2051', 'elected', NULL),
('Anthony Ealy', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '36', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2384', 'elected', NULL),
('Ashley Aune', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '14', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2210', 'elected', NULL),
('Barbara Washington', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '9', NULL, 'Democratic', NULL, 'elected', NULL),
('Barry Hovis', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '146', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2129', 'elected', NULL),
('Becky Laubinger', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '117', NULL, 'Republican', NULL, 'elected', NULL),
('Ben Brown', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '26', NULL, 'Republican', 'https://www.senate.mo.gov/WebPhotos/SenatorPortraits/Brown26.jpg', 'elected', NULL),
('Ben Keathley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '101', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2389', 'elected', NULL),
('Bennie Cook', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '143', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2235', 'elected', NULL),
('Betsy Fogle', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '135', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2233', 'elected', NULL),
('Bill Allen', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '17', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2377', 'elected', NULL),
('Bill Falkner', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '10', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2062', 'elected', NULL),
('Bill Hardwick', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '121', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2253', 'elected', NULL),
('Bill Irwin', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '55', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/64e208458934da6e60e3a002/211532ff-154d-44d5-84d6-5cd347f4aaba/Irwin+4+Congress+office.jpg?format=2500w', 'elected', NULL),
('Bill Lucas', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '115', NULL, 'Republican', NULL, 'elected', NULL),
('Bill Owen', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '131', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2231', 'elected', NULL),
('Bishop Davidson', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '130', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2230', 'elected', NULL),
('Bob Bromley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '162', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2074', 'elected', NULL),
('Bob Titus', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '139', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2369', 'elected', NULL),
('Brad Banderman', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '119', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2379', 'elected', NULL),
('Brad Christ', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '96', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2374', 'elected', NULL),
('Brad Hudson', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '33', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2081', 'elected', NULL),
('Brad Pollitt', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '52', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2073', 'elected', NULL),
('Brandon Phelps', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '54', NULL, 'Republican', NULL, 'elected', NULL),
('Brenda Shields', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '11', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2093', 'elected', NULL),
('Brian Seitz', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '156', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2240', 'elected', NULL),
('Brian Williams', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '14', NULL, 'Democratic', 'https://www.senate.mo.gov/19web/wp-content/uploads/2019/05/Williams2019-200x300.jpg', 'elected', NULL),
('Bridget Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '93', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2248', 'elected', NULL),
('Bruce Sassmann', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '61', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2222', 'elected', NULL),
('Bryant Wolfin', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '145', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Bryant_Wolfin.jpg', 'elected', NULL),
('Burt Whaley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '138', NULL, 'Republican', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/164677.jpg', 'elected', NULL),
('Cameron Parker', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '150', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2393', 'elected', NULL),
('Carolyn Caton', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '33', NULL, 'Republican', NULL, 'elected', NULL),
('Cathy Loy', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '163', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/CathyLoy2024.jpg', 'elected', NULL),
('Cecelie Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '111', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/myleaderpaper.com/content/tncms/assets/v3/editorial/5/41/5413b724-454a-11ef-9a7c-074f5d50855a/669985197fe04.image.jpg?resize=500%2C500', 'elected', NULL),
('Chad Perkins', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '40', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2207', 'elected', NULL),
('Chanel Mosley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '75', NULL, 'Democratic', NULL, 'elected', NULL),
('Chris Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '16', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2212', 'elected', NULL),
('Chris Warwick', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '128', NULL, 'Republican', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/164674.jpg', 'elected', NULL),
('Cindy O''Laughlin', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '18', NULL, 'Republican', 'https://www.senate.mo.gov/19web/wp-content/uploads/2019/09/OLaughlin2019-200x300.jpg', 'elected', NULL),
('Colin Wellenkamp', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '105', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX0dvieAKQKNkpNLYf1CfTOGpW1d2Fr9PPxQ&s', 'elected', NULL),
('Connie Steinmetz', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '87', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Connie_Steinmetz.jpg', 'elected', NULL),
('Curtis Trent', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '20', NULL, 'Republican', NULL, 'elected', NULL),
('Dale Wright', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '116', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2095', 'elected', NULL),
('Dane Diehl', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '125', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2370', 'elected', NULL),
('Danny Busick', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '3', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2069', 'elected', NULL),
('Darin Chappell', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '137', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2362', 'elected', NULL),
('Dave Griffith', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '60', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2052', 'elected', NULL),
('Dave Hinman', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '103', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2357', 'elected', NULL),
('David Casteel', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '97', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2383', 'elected', NULL),
('David Dolan', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '148', NULL, 'Republican', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/167282.jpg', 'elected', NULL),
('David Gregory', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '15', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=1943', 'elected', NULL),
('David Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '46', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2290', 'elected', NULL),
('Dean VanSchoiack', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '9', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2243', 'elected', NULL),
('Deanna Self', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '64', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DeannaSelf.jpg', 'elected', NULL),
('Del Taylor', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '84', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2400', 'elected', NULL),
('Dirk Deaton', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '159', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2090', 'elected', NULL),
('Don Mayhew', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '124', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2082', 'elected', NULL),
('Donna Barnes', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '28', NULL, 'Democratic', NULL, 'elected', NULL),
('Doug Beck', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '1', NULL, 'Democratic', 'https://www.senate.mo.gov/21web/wp-content/uploads/2020/12/Beck2021-683x1024.jpg', 'elected', NULL),
('Doug Clemens', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '72', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2060', 'elected', NULL),
('Doyle Justus', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '41', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2364', 'elected', NULL),
('Ed Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '6', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2244', 'elected', NULL),
('Emily Weber', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '24', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2246', 'elected', NULL),
('Eric Woods', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '18', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2367', 'elected', NULL),
('George Hruza', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '89', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/GeorgeHruza2023.jpg', 'elected', NULL),
('Greg Sharpe', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '4', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2086', 'elected', NULL),
('Gregg Bush', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '50', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/GreggBush24.jpeg', 'elected', NULL),
('Hardy Billington', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '152', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2058', 'elected', NULL),
('Holly Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '88', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2388', 'elected', NULL),
('Ian Mackey', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '99', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2080', 'elected', NULL),
('Jaclyn Zimmermann', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '98', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JaclynZimmerman2024.JPG', 'elected', NULL),
('Jamie Burger', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '27', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2237', 'elected', NULL),
('Jamie Ray Gragg', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '140', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2386', 'elected', NULL),
('Jason Bean', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '25', NULL, 'Republican', 'https://www.senate.mo.gov/21web/wp-content/uploads/2020/12/Bean-200x300.jpg', 'elected', NULL),
('Jeff Coleman', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '32', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2071', 'elected', NULL),
('Jeff Farnan', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '1', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2354', 'elected', NULL),
('Jeff Hales', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '86', NULL, 'Democratic', NULL, 'elected', NULL),
('Jeff Knight', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '142', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2020', 'elected', NULL),
('Jeff Myers', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '42', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2392', 'elected', NULL),
('Jeff Vernetti', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '123', NULL, 'Republican', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/166122.jpg', 'elected', NULL),
('Jeremy Dean', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '132', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jeremy_Dean_20240911_121645.jpg', 'elected', NULL),
('Jill Carter', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '32', NULL, 'Republican', NULL, 'elected', NULL),
('Jim Kalberloh', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '126', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2229', 'elected', NULL),
('Jim Murphy', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '94', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2063', 'elected', NULL),
('Jim Schulte', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '49', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2397', 'elected', NULL),
('Jo Doll', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '91', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2224', 'elected', NULL),
('Joe Nicola', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '11', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JoeNicola2023.jpeg', 'elected', NULL),
('John Black', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '129', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2114', 'elected', NULL),
('John Hewkin', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '120', NULL, 'Republican', 'https://dailyjournalonline.com/wp-content/uploads/2023/09/Hewkin-1.jpeg', 'elected', NULL),
('John Martin', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '44', NULL, 'Republican', 'https://static.wixstatic.com/media/5e062e_e41671d0d6714f5cb9bbb25925e34d15~mv2.jpg/v1/crop/x_172,y_24,w_1449,h_1427/fill/w_397,h_391,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/DSC_6591%20copy%20(1)_edited.jpg', 'elected', NULL),
('John Simmons', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '109', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2097', 'elected', NULL),
('John Voss', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '147', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2355', 'elected', NULL),
('Jon Patterson', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '30', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2075', 'elected', NULL),
('Josh Hurlbert', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '8', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2242', 'elected', NULL),
('Justin Brown', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '16', NULL, 'Republican', 'https://www.senate.mo.gov/19web/wp-content/uploads/2019/09/Brown2019-200x300.jpg', 'elected', NULL),
('Karla May', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '4', NULL, 'Democratic', 'https://www.senate.mo.gov/19web/wp-content/uploads/2019/01/KarlaMay-200x300.jpg', 'elected', NULL),
('Kathy Steinhoff', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '45', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2361', 'elected', NULL),
('Keith Elliott', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '153', NULL, 'Republican', NULL, 'elected', NULL),
('Kem Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '68', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/KemSmith2024.jpg', 'elected', NULL),
('Kemp Strickler', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '34', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2358', 'elected', NULL),
('Ken Jamison', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '15', NULL, 'Democratic', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/167307.jpg', 'elected', NULL),
('Kent Haden', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '43', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2076', 'elected', NULL),
('Keri Ingle', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '35', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2134', 'elected', NULL),
('Kimberly-Ann Collins', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '77', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2277', 'elected', NULL),
('Kurtis Gregory', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '21', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2218', 'elected', NULL),
('LaDonna Appelbaum', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '71', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2057', 'elected', NULL),
('LaKeySha Bosley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '79', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2133', 'elected', NULL),
('Lane Roberts', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '161', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2092', 'elected', NULL),
('Lilly Fuchs', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '80', NULL, 'Democratic', 'https://victoryfund.org/wp-content/uploads/2024/08/Capital-Photos-Arm-on-hip-at-pillar-full-body-scaled-e1724799705880-500x500-250x250.jpg', 'elected', NULL),
('Lincoln Hough', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '30', NULL, 'Republican', 'https://www.senate.mo.gov/19web/wp-content/uploads/2019/10/Hough-200x300.jpg', 'elected', NULL),
('Lisa Durnell', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '154', NULL, 'Republican', NULL, 'elected', NULL),
('Louis Riggs', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '5', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2094', 'elected', NULL),
('Maggie Nurrenbern', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '17', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2211', 'elected', NULL),
('Mark Boyko', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '90', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Mark_Boyko.jpg', 'elected', NULL),
('Mark Matthiesen', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '107', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=1937', 'elected', NULL),
('Mark Meirath', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '39', NULL, 'Republican', NULL, 'elected', NULL),
('Mark Nolte', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '51', NULL, 'Republican', NULL, 'elected', NULL),
('Mark Sharp', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '37', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2169', 'elected', NULL),
('Marla Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '74', NULL, 'Democratic', NULL, 'elected', NULL),
('Marlene Terry', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '66', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2247', 'elected', NULL),
('Marlon Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '76', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2276', 'elected', NULL),
('Marty Jacobs', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '38', NULL, 'Democratic', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/167306.jpg', 'elected', NULL),
('Marty Murray', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '78', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MartyMurray2024.jpg', 'elected', NULL),
('Mary Elizabeth Coleman', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '22', NULL, 'Republican', NULL, 'elected', NULL),
('Matthew Overcast', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '155', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Matthew_Overcast23.jpeg', 'elected', NULL),
('Mazzie Christensen', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '2', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2381', 'elected', NULL),
('Melanie Stinnett', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '133', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2399', 'elected', NULL),
('Melissa Douglas', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '27', NULL, 'Democratic', NULL, 'elected', NULL),
('Melissa Schmidt', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '141', NULL, 'Republican', 'https://static.wixstatic.com/media/530e0b_df591691a465401684e3625621398fd5~mv2.jpg/v1/fill/w_952,h_721,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/530e0b_df591691a465401684e3625621398fd5~mv2.jpg', 'elected', NULL),
('Michael Burton', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '92', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2225', 'elected', NULL),
('Michael Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '56', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2220', 'elected', NULL),
('Michael Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '23', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2255', 'elected', NULL),
('Mike Bernskoetter', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '6', NULL, 'Republican', 'https://www.senate.mo.gov/19web/wp-content/uploads/2019/01/Bernskoetter-200x300.jpg', 'elected', NULL),
('Mike Cierpiot', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '8', NULL, 'Republican', 'https://www.senate.mo.gov/20web/wp-content/uploads/2020/01/Cierpiot2020-200x300.jpg', 'elected', NULL),
('Mike Costlow', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '108', NULL, 'Republican', 'https://costlowformissouri.com/wp-content/uploads/2024/05/Headshot-No-Background-2.png', 'elected', NULL),
('Mike Henderson', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '3', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=1944', 'elected', NULL),
('Mike Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '12', NULL, 'Republican', 'https://static.wixstatic.com/media/c0c31e_a5630222da5c43efb8e8c52283f027da~mv2.jpg/v1/fill/w_473,h_549,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/Michael-18%20(2)_edited.jpg', 'elected', NULL),
('Mike McGirl', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '118', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2065', 'elected', NULL),
('Mike Moon', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '29', NULL, 'Republican', NULL, 'elected', NULL),
('Mike Steinmeyer', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '20', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Mike_Steinmeyer_20241028_013139.jpeg', 'elected', NULL),
('Mitch Boggs', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '157', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2241', 'elected', NULL),
('Nick Kimble', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '82', NULL, 'Democratic', 'https://media.upballot.com/candidates/_250x250_crop_center-center_100_none/Nick-Kimble-Headshot.jpeg', 'elected', NULL),
('Nick Schroer', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '2', NULL, 'Republican', NULL, 'elected', NULL),
('Pattie Mansur', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '25', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/PattieMansur2024.jpg', 'elected', NULL),
('Patty Lewis', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '7', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2213', 'elected', NULL),
('Peggy McGaugh', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '7', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2019', 'elected', NULL),
('Phil Amato', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '113', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2378', 'elected', NULL),
('Philip Oehlerking', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '100', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2371', 'elected', NULL),
('Ray Reed', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '83', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/May162022836PM_104500298_ReedForMissouriHeadshot.jpeg', 'elected', NULL),
('Raychel Proudie', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '73', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2099', 'elected', NULL),
('Renee Reuter', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '112', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2396', 'elected', NULL),
('Richard West', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '102', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2245', 'elected', NULL),
('Rick Brattin', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '31', NULL, 'Republican', NULL, 'elected', NULL),
('Rodger Reedy', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '57', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2096', 'elected', NULL),
('Ron Fowler', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '31', NULL, 'Republican', NULL, 'elected', NULL),
('Rudy Veit', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '59', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2078', 'elected', NULL),
('Rusty Black', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '12', NULL, 'Republican', NULL, 'elected', NULL),
('Sandy Crawford', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '28', NULL, 'Republican', 'https://www.senate.mo.gov/19web/wp-content/uploads/2019/09/Crawford2019-200x300.jpg', 'elected', NULL),
('Scott Cupps', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '158', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2172', 'elected', NULL),
('Scott Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '69', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Scott_Miller_20240924_022629.png', 'elected', NULL),
('Sean Pouche', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '13', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2209', 'elected', NULL),
('Sherri Gallick', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '62', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2359', 'elected', NULL),
('Stephanie Boykin', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '70', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Stephanie__Boykin__20240808_091242.jpg', 'elected', NULL),
('Stephanie Hein', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '136', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2363', 'elected', NULL),
('Stephen Webber', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '19', NULL, 'Democratic', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/5569.jpg', 'elected', NULL),
('Steve Butz', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '81', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2061', 'elected', NULL),
('Steve Jordan', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '151', NULL, 'Republican', 'https://public-assets-prod.pubgen.ai/brand_a7b06a8b-02b9-4920-9426-9b9be1d4e410/asset_912fbf35-14cf-4899-857f-bfa1a8508a2d.jpg?w=1240', 'elected', NULL),
('Steve Roberts', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '5', NULL, 'Democratic', 'https://www.senate.mo.gov/21web/wp-content/uploads/2020/12/Roberts-2021-200x300.jpg', 'elected', NULL),
('Tara Peters', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '122', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2394', 'elected', NULL),
('Terri Violet', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '104', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Terri_Violet_20240810_031254.png', 'elected', NULL),
('Terry Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '53', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2219', 'elected', NULL),
('Tiffany Price', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '26', NULL, 'Democratic', NULL, 'elected', NULL),
('Tim Taylor', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '48', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2217', 'elected', NULL),
('Tony Harbison', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '144', NULL, 'Republican', NULL, 'elected', NULL),
('Tony Luetkemeyer', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '34', NULL, 'Republican', 'https://www.senate.mo.gov/20web/wp-content/uploads/2020/01/010720-002-200x300.jpg', 'elected', NULL),
('Tonya Rush', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '67', NULL, 'Democratic', 'https://assets.civicengine.com/uploads/candidate/headshot/824926/824926.jpg', 'elected', NULL),
('Tracy McCreery', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '24', NULL, 'Democratic', NULL, 'elected', NULL),
('Travis Fitzwater', 'State Senator', 'Legislative Branch', 'Legislative', 'MO', '10', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=1804', 'elected', NULL),
('Travis Wilson', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '106', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2373', 'elected', NULL),
('Tricia Byrnes', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '63', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2382', 'elected', NULL),
('Wendy Hausman', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '65', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2360', 'elected', NULL),
('Wick Thomas', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '19', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/wthomas2.jpg', 'elected', NULL),
('Will Jobe', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '21', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JoeStreno2024.jpg', 'elected', NULL),
('Willard Haley', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '58', NULL, 'Republican', 'https://house.mo.gov/MemberPhoto.aspx?id=2221', 'elected', NULL),
('Yolanda Young', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '22', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2168', 'elected', NULL),
('Yolonda Fountain-Henderson', 'State Representative', 'Legislative Branch', 'Legislative', 'MO', '85', NULL, 'Democratic', 'https://house.mo.gov/MemberPhoto.aspx?id=2385', 'elected', NULL);
