-- MS state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'MS';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Albert Butler', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '37', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/senate/butler.jpg', 'elected', NULL),
('Andy Berry', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '35', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/Berry.jpg', 'elected', NULL),
('Andy Boyd', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '37', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/boyd_(37).jpg', 'elected', NULL),
('Angela Hill', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '40', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/hill.jpg', 'elected', NULL),
('Angela Cockerham', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '96', NULL, 'Independent', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Angela_Cockerham.jpg', 'elected', NULL),
('Angela Turner-Ford', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '16', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/turner-ford.jpg', 'elected', NULL),
('Bradford Blackmon', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '21', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/senate/blackmon.jpg', 'elected', NULL),
('Bart Williams', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '15', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/williams.jpg', 'elected', NULL),
('Becky Currie', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '92', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/currie.jpg', 'elected', NULL),
('Ben Suber', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '8', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/suber.jpg', 'elected', NULL),
('Beth Waldo', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '15', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Beth_Luther_Waldo.jpeg', 'elected', NULL),
('Bill Kinkade', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '52', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/kinkade.jpg', 'elected', NULL),
('Bill Pigott', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '99', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/pigott.jpg', 'elected', NULL),
('Billy Adam Calvert', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '83', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/calvert.jpg', 'elected', NULL),
('Bo Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '70', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/brown_(70th).jpg', 'elected', NULL),
('Bob Evans', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '91', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/evans_(91st).jpg', 'elected', NULL),
('Brad Mattox', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '2', NULL, 'Republican', 'https://www.supertalk.fm/wp-content/uploads/2023/08/Brad-Mattox-960x540.png.webp', 'elected', NULL),
('Brent Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '122', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api/storage/uploads/thumbs/200/300/crop/best/80182230_img_6905.jpg', 'elected', NULL),
('Brent Powell', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '59', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/powell.jpg', 'elected', NULL),
('Brian Rhodes', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '36', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/rhodes.jpeg', 'elected', NULL),
('Brice Wiggins', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '52', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/wiggins.jpg', 'elected', NULL),
('Bryant Clark', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '47', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/clark.jpg', 'elected', NULL),
('Scott Bounds', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '44', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/bounds.jpg', 'elected', NULL),
('Carl Mickens', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '42', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/mickens.jpg', 'elected', NULL),
('Carolyn Crawford', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '121', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/crawford.jpg', 'elected', NULL),
('Casey Eure', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '116', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/eure.jpg', 'elected', NULL),
('Cedric Burnett', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '9', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/burnett.jpg', 'elected', NULL),
('Celeste Hurst', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '75', NULL, 'Republican', 'https://static.wixstatic.com/media/4b62c6_190e934501654befbc52179bbb3d45b0~mv2.jpeg/v1/fill/w_605,h_713,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/4b62c6_190e934501654befbc52179bbb3d45b0~mv2.jpeg', 'elected', NULL),
('Chad McMahan', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '6', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/mcmahan.jpg', 'elected', NULL),
('Cheikh Taylor', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '38', NULL, 'Democratic', 'http://www.starkvilledailynews.com/sites/default/files/styles/galleria_zoom/public/field/image/TAYLOR%20MUG_0.png?itok=jRnUfeN0', 'elected', NULL),
('Chris Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '44', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/johnson.jpg', 'elected', NULL),
('Chris Bell', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '65', NULL, 'Democratic', 'https://static.votesmart.org/static/canphoto/40229.jpg', 'elected', NULL),
('Chuck Blackwell', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '88', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/house/blackwell.jpg', 'elected', NULL),
('Chuck Younger', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '17', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/younger.jpg', 'elected', NULL),
('Clay Deweese', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '12', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/deweese.jpg', 'elected', NULL),
('Clay Mansell', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '56', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Clay_Mansell.jpg', 'elected', NULL),
('Dan Eubanks', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '25', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/eubanks.jpg', 'elected', NULL),
('Dana McLean', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '39', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/mclean.jpg', 'elected', NULL),
('Daniel Sparks', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '5', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/sparks.jpg', 'elected', NULL),
('Daryl Porter', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '98', NULL, 'Democratic', 'https://www.pepperodom.com/wp-content/uploads/2019/05/daryl-porter-683x1024.jpg', 'elected', NULL),
('David Blount', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '29', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/blount.jpg', 'elected', NULL),
('Dean Kirby', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '30', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/kirby.jpg', 'elected', NULL),
('Dennis DeBar', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '43', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/debar.jpg', 'elected', NULL),
('Derrick Simmons', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '12', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/simmons_(12th).jpg', 'elected', NULL),
('Doc Harris', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '28', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/harrisdoc.jpg', 'elected', NULL),
('Don Hartness', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '42', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/Hartness.jpg', 'elected', NULL),
('Donnie Bell', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '21', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/house/bell_(21st).jpg', 'elected', NULL),
('Donnie Scoggin', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '89', NULL, 'Republican', 'http://files.ctctcdn.com/ee25b30f001/08bd0580-a7b2-481a-a9d2-198a61aec56d.jpg', 'elected', NULL),
('Earle Banks', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '67', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/banks.jpg', 'elected', NULL),
('Lawrence Blackmon', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '57', NULL, 'Democratic', 'https://i0.wp.com/www.theindustrycosign.com/wp-content/uploads/2021/11/Lawrence-Blackmon-the-industry-cosign-big-ced.jpg?w=1170&ssl=1', 'elected', NULL),
('Elliot Burch', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '105', NULL, 'Republican', 'https://static.wixstatic.com/media/220c5e_621b140aa59647afa9d2a4370f2a9253~mv2_d_5184_3456_s_4_2.jpg', 'elected', NULL),
('Fabian Nelson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '66', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/fnelson.JPG', 'elected', NULL),
('Fred Shanks', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '60', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/shanks.jpg', 'elected', NULL),
('Gary Brumfield', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '38', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/senate/brumfield.png', 'elected', NULL),
('Gene Newman', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '61', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/newman.jpg', 'elected', NULL),
('Greg Haney', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '118', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/haney.jpg', 'elected', NULL),
('Gregory Elliott', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '82', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/house/elliott.jpg', 'elected', NULL),
('Greg Holloway', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '76', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/holloway.jpg', 'elected', NULL),
('Hank Zuber', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '113', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/zuber.jpg', 'elected', NULL),
('Hester Jackson-McCray', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '40', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/mccray.jpg', 'elected', NULL),
('Hillman Frazier', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '27', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/frazier.jpg', 'elected', NULL),
('Hob Bryan', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '7', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/bryan.jpg', 'elected', NULL),
('Walter Michel', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '25', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/michel.jpg', 'elected', NULL),
('Jansen Owen', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '106', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/owen.jpg', 'elected', NULL),
('Jason Barrett', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '39', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/barrett.jpg', 'elected', NULL),
('Jason White', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '48', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/white.jpg', 'elected', NULL),
('Jay McKnight', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '95', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/mcknight.jpg', 'elected', NULL),
('Jeff Hale', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '24', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/hale.jpg', 'elected', NULL),
('Jeff Tate', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '33', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/tate.jpg', 'elected', NULL),
('Jeffery Harness', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '85', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/harness.jpg', 'elected', NULL),
('Jeffrey Hulum', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '119', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/hulum.jpg', 'elected', NULL),
('Jeff Guice', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '114', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/guice.jpg', 'elected', NULL),
('Jeramey Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '110', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/anderson_(110th).jpg', 'elected', NULL),
('Jeremy England', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '51', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/england.jpg', 'elected', NULL),
('Jerry Turner', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '18', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/turner.jpg', 'elected', NULL),
('Jill Ford', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '73', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/ford_(73rd).jpg', 'elected', NULL),
('Jim Estrada', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '33', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JimEstrada2023.jpeg', 'elected', NULL),
('Jimmy Fondren', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '111', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jimmy_Fondren.jpg', 'elected', NULL),
('Jody Steverson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '4', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/steverson.jpg?rand=41826', 'elected', NULL),
('Joel Carter', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '49', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/carter.jpg', 'elected', NULL),
('Joey Fillingane', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '41', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/fillingane.jpg', 'elected', NULL),
('Joey Hood', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '35', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/hood.jpg', 'elected', NULL),
('John Faulkner', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '5', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/faulkner.jpg', 'elected', NULL),
('John Read', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '112', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/read.jpg', 'elected', NULL),
('Trey Lamar', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '8', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/5660bc77e4b02bc8dd3c055f/1463509030796-7AM0VGR04ZZUTAOF9TQW/image-asset.jpeg?format=500w', 'elected', NULL),
('John Hines', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '50', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/hines.jpg', 'elected', NULL),
('Johnny DuPree', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '45', NULL, 'Democratic', 'https://www.nationalcivicleague.org/wp-content/uploads/2021/11/DuPree.jpg', 'elected', NULL),
('Jonathan McMillan', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '58', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/house/mcmillan.jpg', 'elected', NULL),
('Mike Seymour', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '47', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/seymour.jpg', 'elected', NULL),
('Joseph Thomas', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '22', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/thomas.jpg', 'elected', NULL),
('Bubba Tubb', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '87', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/tubb.jpg', 'elected', NULL),
('Josh Harkins', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '20', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/harkins.jpg', 'elected', NULL),
('Josh Hawkins', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '10', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/80182230_83452a1c-4a99-4e85-9c86-d12418dab31b.jpeg', 'elected', NULL),
('Juan Barnett', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '34', NULL, 'Democratic', 'https://static.votesmart.org/static/canphoto/156222.jpg', 'elected', NULL),
('Justin Crosby', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '22', NULL, 'Democratic', 'https://cdn.mississippitoday.org/wp-content/uploads/2025/07/16124016/IMG_20250627_163819-200x200.jpg', 'elected', NULL),
('Justin Keen', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '6', NULL, 'Republican', 'https://desotocountynews.com/wp-content/uploads/2023/01/Justin-Keen-800x445.jpg', 'elected', NULL),
('Justin Pope', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '24', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/Senate/Pope.jpg', 'elected', NULL),
('Justis Gibbs', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '72', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/house/gibbs_(72nd).jpg', 'elected', NULL),
('Kabir Karriem', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '41', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/karriem.jpg', 'elected', NULL),
('Kamesha Mumford', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '26', NULL, 'Democratic', 'https://i0.wp.com/www.mississippifreepress.org/wp-content/uploads/2025/11/Kamesha-Mumford_courtesy.jpg?w=1200&quality=89&ssl=1', 'elected', NULL),
('Karl Gibbs', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '36', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/house/gibbs_(36th).jpg', 'elected', NULL),
('Karl Oliver', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '46', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/oliver.jpg', 'elected', NULL),
('Kathy Chism', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '3', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/chism.jpg', 'elected', NULL),
('Keith Jackson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '45', NULL, 'Democratic', 'https://www.theclintoncourier.net/wp-content/uploads/2024/03/Statement-by-Attorney-Christopher-A.-Collins-on-Behalf-of-Keith-Jackson.png', 'elected', NULL),
('Ken Morgan', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '100', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/morgan.jpg', 'elected', NULL),
('Kenji Holloway', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '27', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/KenjiHolloway.jpeg', 'elected', NULL),
('Kent McCarty', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '101', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/mccarty.jpg', 'elected', NULL),
('Kevin Blackwell', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '19', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/blackwell.jpg', 'elected', NULL),
('Kevin Felsher', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '117', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/felsher.jpg', 'elected', NULL),
('Kevin Ford', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '54', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/ford.jpg', 'elected', NULL),
('Kevin Horan', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '34', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/horan.jpg', 'elected', NULL),
('Kimberly Remak', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '7', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/KimberlyRemak.jpg', 'elected', NULL),
('Lance Varner', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '62', NULL, 'Republican', 'https://mcgeerealtyservices.com/wp-content/uploads/2020/09/Lances-Headshot-300x400.gif', 'elected', NULL),
('Lane Taylor', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '18', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/taylor.jpg', 'elected', NULL),
('Larry Byrd', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '104', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/byrd.jpg', 'elected', NULL),
('Lataisha Jackson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '11', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/jackson.jpg', 'elected', NULL),
('Lee Yancey', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '74', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/yancey.jpg', 'elected', NULL),
('Bubba Carpenter', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '1', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/carpenter.jpg', 'elected', NULL),
('Lydia Chassaniol', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '14', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/chassaniol.jpg', 'elected', NULL),
('Manly Barton', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '109', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/barton.jpg', 'elected', NULL),
('Mark Tullos', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '79', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/tullos.jpg', 'elected', NULL),
('Michael McLendon', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '1', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/mclendon.jpg', 'elected', NULL),
('Mike Thompson', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '48', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/thompson.jpg', 'elected', NULL),
('Missy McGee', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '102', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/mcgee.jpg', 'elected', NULL),
('Neil Whaley', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '10', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/whaley.jpg', 'elected', NULL),
('Nicole Boyd', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '9', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/boyd.jpg', 'elected', NULL),
('Noah Sanford', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '90', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/sanford.jpg', 'elected', NULL),
('Omeria Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '80', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/scott.jpg', 'elected', NULL),
('Oscar Denton', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '55', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/denton.jpg', 'elected', NULL),
('Otha Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '26', NULL, 'Democratic', 'https://magnoliatribune.com/wp-content/uploads/2025/11/Otha-Williams-1024x1024.jpg', 'elected', NULL),
('Otis Anthony', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '31', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/anthony.jpg', 'elected', NULL),
('Percy Watson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '103', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/watson.jpg', 'elected', NULL),
('Perry Bailey', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '23', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/bailey_(23rd).jpg', 'elected', NULL),
('Philman Ladner', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '46', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/Ladner.jpg', 'elected', NULL),
('Price Wallace', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '77', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/wallace.jpg', 'elected', NULL),
('Randy Boyd', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '19', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/boyd_(19th).jpg', 'elected', NULL),
('Randy Rushing', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '78', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/rushing.jpg', 'elected', NULL),
('Richard Bennett', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '120', NULL, 'Republican', 'https://static.votesmart.org/static/canphoto/69948.jpg', 'elected', NULL),
('Rickey Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '16', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/thompson.jpg', 'elected', NULL),
('Rita Parks', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '4', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/parks.jpg', 'elected', NULL),
('Rob Roberson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '43', NULL, 'Republican', 'https://robrobersonattorney.com/wp-content/uploads/2019/07/Rob-Roberson.jpg', 'elected', NULL),
('Reginald Jackson', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '11', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/senate/jackson.jpg', 'elected', NULL),
('Robert Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '94', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/johnson.jpg', 'elected', NULL),
('Robert Sanders', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '29', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/sanders.jpg', 'elected', NULL),
('Rod Hickman', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '32', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/hickman.jpg', 'elected', NULL),
('Rodney Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '20', NULL, 'Republican', NULL, 'elected', NULL),
('Ronnie Crudup', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '71', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/crudup.jpg', 'elected', NULL),
('Sam Mims', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '97', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/mims.jpg', 'elected', NULL),
('Sam Creekmore', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '14', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/creekmore_iv.jpg', 'elected', NULL),
('Sarita Simmons', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '13', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/simmons_(13th).jpg', 'elected', NULL),
('Scott DeLano', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '50', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/delano.jpg', 'elected', NULL),
('Shanda Yates', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '64', NULL, 'Independent', 'http://billstatus.ls.state.ms.us/members/house/yates.jpg', 'elected', NULL),
('Shane Aguirre', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '17', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/house/aguirre.jpg', 'elected', NULL),
('Shane Barnett', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '86', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/5472abbae4b0859145039552/1519227639852-W83BICPBB7LGL856WGBQ/Shane.jpg?format=500w', 'elected', NULL),
('Sollie Norwood', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '28', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/senate/norwood.jpg', 'elected', NULL),
('Solomon Osborne', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '32', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/osborne.jpg', 'elected', NULL),
('Stacey Hobgood-Wilkes', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '108', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/hobgood-wilkes.jpg', 'elected', NULL),
('Stephanie Foster', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '63', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/foster.jpg', 'elected', NULL),
('Steve Horne', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '81', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/horne.jpg', 'elected', NULL),
('Steve Lott', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '107', NULL, 'Republican', 'https://bloximages.chicago2.vip.townnews.com/stonecountyenterprise.com/content/tncms/assets/v3/editorial/2/fa/2faf492e-910b-11ed-8a24-b33c741f2b91/63bd9eedb8c9d.image.jpg', 'elected', NULL),
('Steve Massengill', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '13', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/massengill.jpg', 'elected', NULL),
('Grace Butler-Washington', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '69', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/TamarraGraceButlerWashington.png', 'elected', NULL),
('Theresa Gillespie Isom', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '2', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/Senate/Gillespie_Isom.jpg', 'elected', NULL),
('Timaka James-Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '51', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/TimakaJames-Jones2023.jpg', 'elected', NULL),
('Timmy Ladner', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '93', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/ladner.jpg', 'elected', NULL),
('Tracey Rosebud', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '30', NULL, 'Democratic', 'http://billstatus.ls.state.ms.us/members/house/rosebud.jpg', 'elected', NULL),
('Troy Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '84', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/smith.jpg', 'elected', NULL),
('Tyler McCaughn', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '31', NULL, 'Republican', 'https://billstatus.ls.state.ms.us/members/senate/mccaughn.jpg', 'elected', NULL),
('Vince Mangold', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '53', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/house/mangold.jpg', 'elected', NULL),
('Briggs Hopson', 'State Senator', 'Legislative Branch', 'Legislative', 'MS', '23', NULL, 'Republican', 'http://billstatus.ls.state.ms.us/members/senate/hopson.jpg', 'elected', NULL),
('Tracy Arnold', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '3', NULL, 'Republican', 'http://da.mdah.ms.gov/series-files/legislature/composites/2016/500/house-of-representatives/2016_2020HousePhotos/Tracy.Arnold.jpg', 'elected', NULL),
('Willie Bailey', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '49', NULL, 'Democratic', 'https://billstatus.ls.state.ms.us/members/house/bailey_(49th).jpg', 'elected', NULL),
('Zack Grady', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '115', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ZacharyGrady.jpg', 'elected', NULL),
('Zakiya Summers', 'State Representative', 'Legislative Branch', 'Legislative', 'MS', '68', NULL, 'Democratic', 'https://stateinnovation.org/wp-content/uploads/2021/04/Zakiya-Summers.png', 'elected', NULL);
