-- MT state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'MT';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Alanah Griffith', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '60', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/AlanahGriffith2024.jpg', 'elected', NULL),
('Amy Regier', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '6', NULL, 'Republican', NULL, 'elected', NULL),
('Andrea Olsen', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '48', NULL, 'Democratic', NULL, 'elected', NULL),
('Anthony Nicastro', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '50', NULL, 'Republican', NULL, 'elected', NULL),
('Barry Usher', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '19', NULL, 'Republican', NULL, 'elected', NULL),
('Becky Beard', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '38', NULL, 'Republican', NULL, 'elected', NULL),
('Becky Edwards', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '61', NULL, 'Democratic', NULL, 'elected', NULL),
('Bob Carter', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '96', NULL, 'Democratic', NULL, 'elected', NULL),
('Bob Phalen', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '17', NULL, 'Republican', NULL, 'elected', NULL),
('Brad Barker', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '55', NULL, 'Republican', NULL, 'elected', NULL),
('Brandon Ler', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '33', NULL, 'Republican', NULL, 'elected', NULL),
('Braxton Mitchell', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '5', NULL, 'Republican', NULL, 'elected', NULL),
('Brian Close', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '65', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Brian_Close_20240808_100432.jpg', 'elected', NULL),
('Butch Gillespie', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '9', NULL, 'Republican', NULL, 'elected', NULL),
('Caleb Hinkle', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '68', NULL, 'Republican', NULL, 'elected', NULL),
('Carl Glimm', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '3', NULL, 'Republican', NULL, 'elected', NULL),
('Chip Fitzpatrick', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '42', NULL, 'Democratic', NULL, 'elected', NULL),
('Chris Pope', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '33', NULL, 'Democratic', NULL, 'elected', NULL),
('Connie Keogh', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '92', NULL, 'Democratic', NULL, 'elected', NULL),
('Cora Neumann', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '30', NULL, 'Democratic', NULL, 'elected', NULL),
('Courtenay Sprunger', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '7', NULL, 'Republican', NULL, 'elected', NULL),
('Curt Cochran', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '90', NULL, 'Republican', NULL, 'elected', NULL),
('Curtis Schomer', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '48', NULL, 'Republican', NULL, 'elected', NULL),
('Daniel Emrich', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '11', NULL, 'Republican', NULL, 'elected', NULL),
('Daniel Zolnikov', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '22', NULL, 'Republican', NULL, 'elected', NULL),
('Dave Fern', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '2', NULL, 'Democratic', NULL, 'elected', NULL),
('Dave Bedey', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '86', NULL, 'Republican', NULL, 'elected', NULL),
('Debo Powers', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '3', NULL, 'Democratic', NULL, 'elected', NULL),
('Denise Baum', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '45', NULL, 'Democratic', NULL, 'elected', NULL),
('Denise Hayman', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '32', NULL, 'Democratic', NULL, 'elected', NULL),
('Denise Joy', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '46', NULL, 'Democratic', 'https://www.billingsmt.gov/ImageRepository/Document?documentId=49492', 'elected', NULL),
('Denley Loge', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '45', NULL, 'Republican', NULL, 'elected', NULL),
('Dennis Lenz', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '25', NULL, 'Republican', NULL, 'elected', NULL),
('Derek Harvey', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '37', NULL, 'Democratic', NULL, 'elected', NULL),
('Donavon Hawk', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '72', NULL, 'Democratic', NULL, 'elected', NULL),
('Ed Byrne', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '11', NULL, 'Republican', NULL, 'elected', NULL),
('Ed Buttrey', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '21', NULL, 'Republican', NULL, 'elected', NULL),
('Ellie Boldman', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '47', NULL, 'Democratic', NULL, 'elected', NULL),
('Emma Kerr-Carpenter', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '23', NULL, 'Democratic', NULL, 'elected', NULL),
('Eric Albus', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '28', NULL, 'Republican', NULL, 'elected', NULL),
('Eric Matthews', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '66', NULL, 'Democratic', NULL, 'elected', NULL),
('Eric Tilleman', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '23', NULL, 'Republican', NULL, 'elected', NULL),
('Fiona Nave', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '56', NULL, 'Republican', NULL, 'elected', NULL),
('Forrest Mandeville', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '28', NULL, 'Republican', NULL, 'elected', NULL),
('Frank Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '31', NULL, 'Democratic', NULL, 'elected', NULL),
('Gary Parry', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '35', NULL, 'Republican', NULL, 'elected', NULL),
('Gayle Lammers', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '21', NULL, 'Republican', 'https://static.wixstatic.com/media/bf4594_51bb3c90d2b140bc9f3286324b5fb6f6~mv2.jpg/v1/crop/x_0,y_0,w_420,h_496,q_80,enc_auto/bf4594_51bb3c90d2b140bc9f3286324b5fb6f6~mv2.jpg', 'elected', NULL),
('George Nikolakakos', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '22', NULL, 'Republican', NULL, 'elected', NULL),
('Greg Hertz', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '7', NULL, 'Republican', NULL, 'elected', NULL),
('Greg Kmetz', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '36', NULL, 'Republican', NULL, 'elected', NULL),
('Greg Oblander', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '38', NULL, 'Republican', NULL, 'elected', NULL),
('Greg Overstreet', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '88', NULL, 'Republican', NULL, 'elected', NULL),
('Gregg Hunter', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '15', NULL, 'Republican', NULL, 'elected', NULL),
('Jacinda Morigeau', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '46', NULL, 'Democratic', 'https://cdn.runforsomething.net/candidates/2024/05/campaign/190178bc3c51a6be225f4f2a711a5814.jpg', 'elected', NULL),
('Jade Sooktis', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '41', NULL, 'Democratic', NULL, 'elected', NULL),
('James Reavis', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '47', NULL, 'Democratic', NULL, 'elected', NULL),
('Jamie Isaly', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '58', NULL, 'Democratic', NULL, 'elected', NULL),
('Jane Gillette', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '77', NULL, 'Republican', NULL, 'elected', NULL),
('Jane Weber', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '19', NULL, 'Democratic', NULL, 'elected', NULL),
('Janet Ellis', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '41', NULL, 'Democratic', NULL, 'elected', NULL),
('Jason Ellsworth', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '43', NULL, 'Republican', NULL, 'elected', NULL),
('Jedediah Hinkle', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '67', NULL, 'Republican', NULL, 'elected', NULL),
('Jennifer Lynch', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '73', NULL, 'Democratic', NULL, 'elected', NULL),
('Jeremy Trebas', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '10', NULL, 'Republican', NULL, 'elected', NULL),
('Jerry Schillinger', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '34', NULL, 'Republican', NULL, 'elected', NULL),
('Jill Cohenour', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '83', NULL, 'Democratic', NULL, 'elected', NULL),
('Jodee Etchart', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '51', NULL, 'Republican', NULL, 'elected', NULL),
('John Esp', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '29', NULL, 'Republican', NULL, 'elected', NULL),
('John Fitzpatrick', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '76', NULL, 'Republican', NULL, 'elected', NULL),
('John Fuller', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '4', NULL, 'Republican', NULL, 'elected', NULL),
('Jonathan Karlen', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '98', NULL, 'Democratic', NULL, 'elected', NULL),
('Jonathan Windy Boy', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '16', NULL, 'Democratic', NULL, 'elected', NULL),
('Josh Seckinger', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '62', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/May262020913AM_80182230_B56A0395.jpg', 'elected', NULL),
('Josh Kassmier', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '13', NULL, 'Republican', NULL, 'elected', NULL),
('Julie Darling', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '84', NULL, 'Republican', NULL, 'elected', NULL),
('Kathy Love', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '85', NULL, 'Republican', NULL, 'elected', NULL),
('Katie Fire Thunder', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '59', NULL, 'Democratic', 'https://bloximages.chicago2.vip.townnews.com/bozemandailychronicle.com/content/tncms/assets/v3/editorial/8/92/892e4c6d-1520-4244-b414-6a86e405c9bc/696545afef0c7.image.jpg?resize=333%2C500', 'elected', NULL),
('Katie Sullivan', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '93', NULL, 'Democratic', NULL, 'elected', NULL),
('Katie Zolnikov', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '44', NULL, 'Republican', NULL, 'elected', NULL),
('Kelly Kortum', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '64', NULL, 'Democratic', NULL, 'elected', NULL),
('Ken Bogner', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '18', NULL, 'Republican', NULL, 'elected', NULL),
('Ken Walsh', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '69', NULL, 'Republican', NULL, 'elected', NULL),
('Kerri Seekins-Crowe', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '39', NULL, 'Republican', NULL, 'elected', NULL),
('Larry Brewster', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '43', NULL, 'Republican', NULL, 'elected', NULL),
('Laura Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '40', NULL, 'Democratic', NULL, 'elected', NULL),
('Lee Deming', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '54', NULL, 'Republican', NULL, 'elected', NULL),
('Linda Reksten', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '13', NULL, 'Republican', NULL, 'elected', NULL),
('Llew Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '18', NULL, 'Republican', NULL, 'elected', NULL),
('Lukas Schubert', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '8', NULL, 'Republican', NULL, 'elected', NULL),
('Luke Muszkiewicz', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '79', NULL, 'Democratic', NULL, 'elected', NULL),
('Lyn Bennett', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '4', NULL, 'Republican', NULL, 'elected', NULL),
('Marc Lee', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '74', NULL, 'Democratic', NULL, 'elected', NULL),
('Marilyn Marler', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '94', NULL, 'Democratic', NULL, 'elected', NULL),
('Mark Noland', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '6', NULL, 'Republican', NULL, 'elected', NULL),
('Mark Reinschmidt', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '75', NULL, 'Republican', 'https://www.whitehallledger.com/IMG/GgZmsn7rWaScoesaeXeK1AhXw0Fk0/XPATH/home/cms_data/dfault/photos/stories/id/8/2/9982/s_bottomXEXT1570x35634is.jpg', 'elected', NULL),
('Mark Thane', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '89', NULL, 'Democratic', NULL, 'elected', NULL),
('Mary Ann Dunwell', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '42', NULL, 'Democratic', NULL, 'elected', NULL),
('Mary Caferro', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '81', NULL, 'Democratic', NULL, 'elected', NULL),
('Matt Regier', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '5', NULL, 'Republican', NULL, 'elected', NULL),
('Melissa Nikolakakos', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '20', NULL, 'Republican', NULL, 'elected', NULL),
('Melissa Romano', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '80', NULL, 'Democratic', NULL, 'elected', NULL),
('Melody Cunningham', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '97', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/mcunningham.JPG', 'elected', NULL),
('Mike Cuffe', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '1', NULL, 'Republican', NULL, 'elected', NULL),
('Mike Fox', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '32', NULL, 'Democratic', NULL, 'elected', NULL),
('Mike Vinton', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '40', NULL, 'Republican', NULL, 'elected', NULL),
('Mike Yakawich', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '24', NULL, 'Republican', NULL, 'elected', NULL),
('Morgan Thiel', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '30', NULL, 'Republican', 'https://www.roundupweb.com/IMG/CW6HaGsPAQMKLKOUSxVmirLDbYqbX/XPATH/home/cms_data/dfault/photos/stories/id/0/1/20401/s_topXEXT1385x31824is.jpg', 'elected', NULL),
('Neil Duram', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '1', NULL, 'Republican', NULL, 'elected', NULL),
('Nelly Nicol', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '53', NULL, 'Republican', NULL, 'elected', NULL),
('Pat Flowers', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '31', NULL, 'Democratic', NULL, 'elected', NULL),
('Paul Fielder', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '14', NULL, 'Republican', NULL, 'elected', NULL),
('Paul Tuss', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '27', NULL, 'Democratic', NULL, 'elected', NULL),
('Pete Elverum', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '82', NULL, 'Democratic', NULL, 'elected', NULL),
('Peter Strand', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '63', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/pstrand.jpg', 'elected', NULL),
('Randyn Gregg', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '78', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/rgregg.jpeg', 'elected', NULL),
('Russ Miner', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '26', NULL, 'Republican', NULL, 'elected', NULL),
('Russel Tempel', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '14', NULL, 'Republican', NULL, 'elected', NULL),
('Sara Novak', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '36', NULL, 'Democratic', NULL, 'elected', NULL),
('Scott DeMarois', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '71', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ScottDemarois2024.jpg', 'elected', NULL),
('Scott Rosenzweig', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '57', NULL, 'Democratic', NULL, 'elected', NULL),
('Shane Klakken', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '37', NULL, 'Republican', NULL, 'elected', NULL),
('Shane Morigeau', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '50', NULL, 'Democratic', NULL, 'elected', NULL),
('Shannon Maness', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '70', NULL, 'Republican', NULL, 'elected', NULL),
('Shelley Vance', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '34', NULL, 'Republican', NULL, 'elected', NULL),
('Shelly Fyant', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '91', NULL, 'Democratic', 'https://shellyformontana.com/wp-content/uploads/sites/17/2024/03/headshot-1-scaled-e1709849197916.jpg', 'elected', NULL),
('Sherry Essmann', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '49', NULL, 'Republican', NULL, 'elected', NULL),
('S.J. Howell', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '100', NULL, 'Democratic', NULL, 'elected', NULL),
('Stacy Zinn', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '52', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/_MG_3733.jpg', 'elected', NULL),
('Steve Fitzpatrick', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '24', NULL, 'Republican', NULL, 'elected', NULL),
('Steve Gist', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '25', NULL, 'Republican', NULL, 'elected', NULL),
('Steve Kelly', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '9', NULL, 'Republican', NULL, 'elected', NULL),
('Sue Vinton', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '20', NULL, 'Republican', NULL, 'elected', NULL),
('Susan Webber', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '8', NULL, 'Democratic', NULL, 'elected', NULL),
('Terry Falk', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '10', NULL, 'Republican', NULL, 'elected', NULL),
('Terry Nelson', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '87', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Terry_Nelson.jpg', 'elected', NULL),
('Thedis Crowe', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '15', NULL, 'Democratic', 'https://www.legmt.gov/wp-content/legislator-photos/lowres/1323.jpg', 'elected', NULL),
('Theresa Manzella', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '44', NULL, 'Republican', NULL, 'elected', NULL),
('Tom France', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '99', NULL, 'Democratic', NULL, 'elected', NULL),
('Tom McGillvray', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '26', NULL, 'Republican', NULL, 'elected', NULL),
('Tom Millett', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '2', NULL, 'Republican', 'https://www.legmt.gov/wp-content/legislator-photos/lowres/1403.jpg', 'elected', NULL),
('Tony Tezak', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '35', NULL, 'Republican', NULL, 'elected', NULL),
('Tracy Sharp', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '12', NULL, 'Republican', NULL, 'elected', NULL),
('Tyson Running Wolf', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '16', NULL, 'Democratic', NULL, 'elected', NULL),
('Valerie Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '29', NULL, 'Republican', NULL, 'elected', NULL),
('Vince Ricci', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '27', NULL, 'Republican', NULL, 'elected', NULL),
('Wendy McKamey', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '12', NULL, 'Republican', NULL, 'elected', NULL),
('Willis Curdy', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '49', NULL, 'Democratic', NULL, 'elected', NULL),
('Wylie Galt', 'State Senator', 'Legislative Branch', 'Legislative', 'MT', '39', NULL, 'Republican', NULL, 'elected', NULL),
('Zack Wirth', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '17', NULL, 'Republican', NULL, 'elected', NULL),
('Zooey Zephyr', 'State Representative', 'Legislative Branch', 'Legislative', 'MT', '95', NULL, 'Democratic', NULL, 'elected', NULL);
