-- NC state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'NC';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Reece Pyrtle', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '65', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/787/Low', 'elected', NULL),
('Abe Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '38', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/780/Low', 'elected', NULL),
('Aisha Dew', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '107', NULL, 'Democratic', 'https://static.wixstatic.com/media/382708_03a01c002bae45c2a4dd4b665892e242~mv2.png/v1/fill/w_369,h_369,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/aisha%20dew%20updated%20headshot.png', 'elected', NULL),
('Alan Branson', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '59', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/alan_branson.jpg', 'elected', NULL),
('Allen Buansi', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '56', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/790/Low', 'elected', NULL),
('Allen Chesser', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '25', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/799/Low', 'elected', NULL),
('Allison Dahle', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '11', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/740/Low', 'elected', NULL),
('Amanda Cook', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '60', NULL, 'Democratic', NULL, 'elected', NULL),
('Amber Baker', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '72', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/782/Low', 'elected', NULL),
('Amos Quick', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '58', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/725/Low', 'elected', NULL),
('Amy Galey', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '25', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/429/Low', 'elected', NULL),
('Anna Ferguson', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '119', NULL, 'Republican', NULL, 'elected', NULL),
('Ray Jeffers', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '2', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/805/Low', 'elected', NULL),
('Becky Carney', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '102', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/322/Low', 'elected', NULL),
('Ben Moss', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '52', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/784/Low', 'elected', NULL),
('Benton Sawrey', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '10', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/445/Low', 'elected', NULL),
('Beth Gardner Helfrich', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '98', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Beth_Gardner_Helfrich.jpeg', 'elected', NULL),
('Bill Rabon', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '8', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/303/Low', 'elected', NULL),
('Bill Ward', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '5', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/816/Low', 'elected', NULL),
('Blair Eddins', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '94', NULL, 'Republican', 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/151642.jpg', 'elected', NULL),
('Bob Brinson', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '3', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Bob_Brinson.jpg', 'elected', NULL),
('Bobby Hanig', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '1', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/435/Low', 'elected', NULL),
('Brad Overcash', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '43', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/444/Low', 'elected', NULL),
('Brandon Lofton', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '104', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/751/Low', 'elected', NULL),
('Brenden Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '46', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/723/Low', 'elected', NULL),
('Brent Jackson', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '9', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/281/Low', 'elected', NULL),
('Brian Biggs', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '70', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/793/Low', 'elected', NULL),
('Brian Echevarria', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '82', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Brian_Echiveria_.jpg', 'elected', NULL),
('Brian Turner', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '116', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/696/Low', 'elected', NULL),
('Bryan Cohn', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '32', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Bryan__Cohn__20240808_093541.jpg', 'elected', NULL),
('Caleb Theodros', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '41', NULL, 'Democratic', 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcST0VSf38rEGBD-siclt6NuNe1QJ5F0bSq2yeTZaPl6B5jN6UixO_XTlOxWxObcJM0wmNgic4MjyZBFddFBYaj7sg', 'elected', NULL),
('Carl Ford', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '33', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/410/Low', 'elected', NULL),
('Carla Cunningham', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '106', NULL, 'Independent', 'https://www.ncleg.gov/Members/MemberImage/H/642/Low', 'elected', NULL),
('Carolyn Logan', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '101', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/750/Low', 'elected', NULL),
('Carson Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '16', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/755/Low', 'elected', NULL),
('Celeste Cairns', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '13', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/797/Low', 'elected', NULL),
('Charles Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '44', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/813/Low', 'elected', NULL),
('Charlie Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '19', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/778/Low', 'elected', NULL),
('Chris Humphrey', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '12', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/747/Low', 'elected', NULL),
('Chris Measmer', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '34', NULL, 'Republican', NULL, 'elected', NULL),
('Cody Huneycutt', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '67', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/797923/797923.jpg', 'elected', NULL),
('Cynthia Ball', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '49', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/711/Low', 'elected', NULL),
('Dan Blue', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '14', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/268/Low', 'elected', NULL),
('Dan Kiger', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '90', NULL, 'Republican', NULL, 'elected', NULL),
('Dana Jones', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '31', NULL, 'Republican', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/162671.jpg', 'elected', NULL),
('Danny Britt', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '24', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/399/Low', 'elected', NULL),
('Dante Pittman', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '24', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DantePittman2024.JPG', 'elected', NULL),
('Dave Craven', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '29', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/423/Low', 'elected', NULL),
('David Willis', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '68', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/779/Low', 'elected', NULL),
('DeAndrea Salvador', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '39', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/431/Low', 'elected', NULL),
('Dean Arp', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '69', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/640/Low', 'elected', NULL),
('Deb Butler', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '18', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/730/Low', 'elected', NULL),
('Dennis Riddell', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '64', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/665/Low', 'elected', NULL),
('Destin Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '87', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/719/Low', 'elected', NULL),
('Diane Wheatley', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '43', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/785/Low', 'elected', NULL),
('Donna White', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '26', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/728/Low', 'elected', NULL),
('Donnie Loftis', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '109', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/788/Low', 'elected', NULL),
('Donny Lambeth', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '75', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/646/Low', 'elected', NULL),
('Dudley Greene', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '85', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/777/Low', 'elected', NULL),
('Buck Newton', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '4', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/443/Low', 'elected', NULL),
('Eddie Settle', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '36', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/446/Low', 'elected', NULL),
('Ed Goodwin', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '1', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/744/Low', 'elected', NULL),
('Eric Ager', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '114', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/819/Low', 'elected', NULL),
('Erin Paré', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '37', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/770/Low', 'elected', NULL),
('Frances Jackson', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '45', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/803/Low', 'elected', NULL),
('Frank Iler', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '17', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/598/Low', 'elected', NULL),
('Gale Adcock', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '16', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/436/Low', 'elected', NULL),
('Garland Pierce', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '48', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/497/Low', 'elected', NULL),
('Gladys Robinson', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '28', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/364/Low', 'elected', NULL),
('Gloristine Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '8', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/794/Low', 'elected', NULL),
('Grant Campbell', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '83', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/campbellgrant.jpg', 'elected', NULL),
('Harry Warren', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '76', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/630/Low', 'elected', NULL),
('Haseeb Fatmi', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '18', NULL, 'Democratic', 'https://ogletree.com/app/uploads/people/haseeb-s-fatmi.jpg', 'elected', NULL),
('Heather Rhyne', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '97', NULL, 'Republican', 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/148921.jpg', 'elected', NULL),
('Howard Penny', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '53', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/768/Low', 'elected', NULL),
('Hugh Blackwell', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '86', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/580/Low', 'elected', NULL),
('Jake Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '113', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/762/Low', 'elected', NULL),
('James Roberson', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '39', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/786/Low', 'elected', NULL),
('Jay Adams', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '96', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/697/Low', 'elected', NULL),
('Jay Chaudhuri', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '15', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/395/Low', 'elected', NULL),
('Jeff Zenger', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '74', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/775/Low', 'elected', NULL),
('Jeff McNeely', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '84', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/761/Low', 'elected', NULL),
('Jennifer Balkcom', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '117', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/820/Low', 'elected', NULL),
('Jim Burgin', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '12', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/412/Low', 'elected', NULL),
('Jimmy Dixon', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '4', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/613/Low', 'elected', NULL),
('John Torbett', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '108', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/606/Low', 'elected', NULL),
('John Blust', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '62', NULL, 'Republican', 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/21657.jpg', 'elected', NULL),
('John Lowery', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '47', NULL, 'Republican', NULL, 'elected', NULL),
('John Bell', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '10', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/661/Low', 'elected', NULL),
('John Sauls', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '51', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/393/Low', 'elected', NULL),
('Jonah Garson', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '23', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/5ce70c57184229000120643d/1635110523522-15B7H44X3PRPJSL2DYJH/ParryLaw_PLLC_20211020_1501-2.jpg', 'elected', NULL),
('Jonathan Almond', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '73', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jonathan_Almond_20241029_031016.png', 'elected', NULL),
('Jordan Lopez', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '112', NULL, 'Democratic', 'https://lopez4nc.com/wp-content/uploads/2023/12/FAV1127_LOPEZ_-121.webp', 'elected', NULL),
('Joe Pike', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '6', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/808/Low', 'elected', NULL),
('Joyce Waddell', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '40', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/393/Low', 'elected', NULL),
('Julia Howard', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '77', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/53/Low', 'elected', NULL),
('Julia Greenfield', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '100', NULL, 'Democratic', 'https://greenvoterguidenc.org/wp-content/uploads/Julia-Greenfield-square-400x400.png', 'elected', NULL),
('Julie Mayfield', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '49', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/432/Low', 'elected', NULL),
('Julie von Haefen', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '36', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/758/Low', 'elected', NULL),
('Kandie Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '5', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/447/Low', 'elected', NULL),
('Kanika Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '71', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/795/Low', 'elected', NULL),
('Karl Gillespie', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '120', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/771/Low', 'elected', NULL),
('Keith Kidwell', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '79', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/749/Low', 'elected', NULL),
('Kelly Hastings', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '110', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/618/Low', 'elected', NULL),
('Kevin Corbin', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '50', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/433/Low', 'elected', NULL),
('Kyle Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '91', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/704/Low', 'elected', NULL),
('Larry Strickland', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '28', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/727/Low', 'elected', NULL),
('Larry Potts', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '81', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/724/Low', 'elected', NULL),
('Laura Budd', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '103', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/796/Low', 'elected', NULL),
('Lindsey Prather', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '115', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/809/Low', 'elected', NULL),
('Lisa Grafstein', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '13', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/439/Low', 'elected', NULL),
('Lisa Barnes', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '11', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/427/Low', 'elected', NULL),
('Marcia Morey', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '30', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/732/Low', 'elected', NULL),
('Maria Cervania', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '41', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/798/Low', 'elected', NULL),
('Mark Brody', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '55', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/663/Low', 'elected', NULL),
('Mark Pless', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '118', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/773/Low', 'elected', NULL),
('Mark Hollo', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '45', NULL, 'Republican', 'http://www.ncga.state.nc.us/House/pictures/hiRes/619.jpg', 'elected', NULL),
('Mary Belk', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '88', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/713/Low', 'elected', NULL),
('Matthew Winslow', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '7', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/776/Low', 'elected', NULL),
('Michael Lazzara', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '6', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/426/Low', 'elected', NULL),
('Michael Garrett', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '27', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/414/Low', 'elected', NULL),
('Michael Lee', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '7', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/387/Low', 'elected', NULL),
('Mike Colvin', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '42', NULL, 'Democratic', 'https://votemikecolvin.com/wp-content/uploads/2024/01/untitled-1024x1024.jpg', 'elected', NULL),
('Mike Schietzelt', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '35', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MikeSchietzelt2024.jpg', 'elected', NULL),
('Mitchell Setzer', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '89', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/149/Low', 'elected', NULL),
('Monika Johnson-Hostler', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '33', NULL, 'Democratic', 'https://www.uncfsu.edu/assets/Images/Student_Stories/Monika-Hostler.jpg', 'elected', NULL),
('Mujtaba Mohammed', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '38', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/417/Low', 'elected', NULL),
('Nasif Majeed', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '99', NULL, 'Independent', 'https://www.ncleg.gov/Members/MemberImage/H/752/Low', 'elected', NULL),
('Natalie Murdock', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '20', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/422/Low', 'elected', NULL),
('Neal Jackson', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '78', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/804/Low', 'elected', NULL),
('Norman Sanderson', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '2', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/375/Low', 'elected', NULL),
('Paul Lowe', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '32', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/394/Low', 'elected', NULL),
('Paul Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '111', NULL, 'Republican', 'https://static.wixstatic.com/media/a254ce_1422fda1afc540a697d4c59e20275ee8~mv2.png/v1/fill/w_626,h_1003,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/a254ce_1422fda1afc540a697d4c59e20275ee8~mv2.png', 'elected', NULL),
('Phil Berger', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '26', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/64/Low', 'elected', NULL),
('Phil Rubin', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '40', NULL, 'Democratic', NULL, 'elected', NULL),
('Phil Shepard', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '15', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/628/Low', 'elected', NULL),
('Pricey Harrison', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '61', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/504/Low', 'elected', NULL),
('Ralph Hise', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '47', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/298/Low', 'elected', NULL),
('Ray Pickett', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '93', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/772/Low', 'elected', NULL),
('Renée Price', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '50', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/810/Low', 'elected', NULL),
('Robert Reives', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '54', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/684/Low', 'elected', NULL),
('Rodney Pierce', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '27', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/RodneyPierce2024.jpeg', 'elected', NULL),
('Sam Watford', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '80', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/687/Low', 'elected', NULL),
('Sarah Crawford', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '66', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/800/Low', 'elected', NULL),
('Shelly Willingham', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '23', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/700/Low', 'elected', NULL),
('Sophia Chitlik', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '22', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/SophiaChitlik2024.jpg', 'elected', NULL),
('Stephen Ross', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '63', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/812/Low', 'elected', NULL),
('Steve Jarvis', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '30', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/430/Low', 'elected', NULL),
('Steve Tyson', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '3', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/774/Low', 'elected', NULL),
('Sydney Batch', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '17', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/434/Low', 'elected', NULL),
('Ted Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '20', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/637/Low', 'elected', NULL),
('Terry Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '92', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/783/Low', 'elected', NULL),
('Tim Moffitt', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '48', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/438/Low', 'elected', NULL),
('Tim Longest', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '34', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/818/Low', 'elected', NULL),
('Tim Reeder', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '9', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/811/Low', 'elected', NULL),
('Todd Carver', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '95', NULL, 'Republican', 'https://www.iredellfreenews.com/wp-content/uploads/2023/12/Todd-Carver.jpg.webp', 'elected', NULL),
('Todd Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '35', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/406/Low', 'elected', NULL),
('Tom McInnis', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '21', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/389/Low', 'elected', NULL),
('Tracy Clark', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '57', NULL, 'Democratic', 'https://storage.googleapis.com/enview-public-general/legislative-people-photos/148017.jpg', 'elected', NULL),
('Tricia Cotham', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '105', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/817/Low', 'elected', NULL),
('Val Applewhite', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '19', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/S/440/Low', 'elected', NULL),
('Vernetta Alston', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '29', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/765/Low', 'elected', NULL),
('Vickie Sawyer', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '37', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/405/Low', 'elected', NULL),
('Ted Alexander', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '44', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/416/Low', 'elected', NULL),
('Warren Daniel', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '46', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/S/295/Low', 'elected', NULL),
('William Brisson', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '22', NULL, 'Republican', 'https://www.ncleg.gov/Members/MemberImage/H/558/Low', 'elected', NULL),
('Woodson Bradley', 'State Senator', 'Legislative Branch', 'Legislative', 'NC', '42', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Woodson_Bradley_20240820_013503.jpg', 'elected', NULL),
('Wyatt Gable', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '14', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/6555362b58434b0824932281/15739355-3436-4410-b02c-ed4d63322f69/untitled-7317.jpg', 'elected', NULL),
('Ya Liu', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '21', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/806/Low', 'elected', NULL),
('Zack Hawkins', 'State Representative', 'Legislative Branch', 'Legislative', 'NC', '31', NULL, 'Democratic', 'https://www.ncleg.gov/Members/MemberImage/H/742/Low', 'elected', NULL);
