-- NE state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'NE';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Ashlei Spivey', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '13', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('Barry DeKay', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '40', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist40/highres/dist40.jpg', 'elected', NULL),
('Beau Ballard', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '21', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist21/highres/dist21.jpg', 'elected', NULL),
('Ben Hansen', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '16', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist16/highres/dist16.jpg', 'elected', NULL),
('Bob Andersen', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '49', NULL, 'Nonpartisan', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/167021.jpg', 'elected', NULL),
('Bob Hallstrom', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '1', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('Brian Hardin', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '48', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist48/highres/dist48.jpg', 'elected', NULL),
('Carolyn Bosn', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '25', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist25/highres/dist25.jpg', 'elected', NULL),
('Christy Armendariz', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '18', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist18/highres/dist18.jpg', 'elected', NULL),
('Dan Lonowski', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '33', NULL, 'Nonpartisan', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/167026.jpg', 'elected', NULL),
('Dan Quick', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '35', NULL, 'Nonpartisan', 'http://www.nebraskalegislature.gov/media/images/blogs/dist35.jpg', 'elected', NULL),
('Danielle Conrad', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '46', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist46/highres/dist46.jpg', 'elected', NULL),
('Dave Murman', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '38', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist38/highres/dist38.jpg', 'elected', NULL),
('Dunixi Guereca', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '7', NULL, 'Nonpartisan', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/161473.jpg', 'elected', NULL),
('Eliot Bostar', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '29', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist29/highres/dist29.jpg', 'elected', NULL),
('Fred Meyer', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '41', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist41/highres/dist41.jpg', 'elected', NULL),
('George Dungan', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '26', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist26/highres/dist26.jpg', 'elected', NULL),
('Glen Meyer', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '17', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('Jana Hughes', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '24', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist24/highres/dist24.jpg', 'elected', NULL),
('Jane Raybould', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '28', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist28/highres/dist28.jpg', 'elected', NULL),
('Jared Storm', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '23', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('Jason Prokop', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '27', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('John Arch', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '14', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist14/highres/dist14.jpg', 'elected', NULL),
('John Cavanaugh', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '9', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist09/highres/dist09.jpg', 'elected', NULL),
('John Fredrickson', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '20', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist20/highres/dist20.jpg', 'elected', NULL),
('Kathleen Kauth', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '31', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist31/highres/dist31.jpg', 'elected', NULL),
('Loren Lippincott', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '34', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist34/highres/dist34.jpg', 'elected', NULL),
('Machaela Cavanaugh', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '6', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist06/highres/dist06.jpg', 'elected', NULL),
('Margo Juarez', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '5', NULL, 'Nonpartisan', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/167027.jpg', 'elected', NULL),
('Megan Hunt', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '8', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist08/highres/dist08.jpg', 'elected', NULL),
('Merv Riepe', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '12', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist12/highres/dist12.jpg', 'elected', NULL),
('Mike Jacobson', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '42', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist42/highres/dist42.jpg', 'elected', NULL),
('Mike Moser', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '22', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist22/highres/dist22.jpg', 'elected', NULL),
('Myron Dorn', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '30', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist30/highres/dist30.jpg', 'elected', NULL),
('Paul Strommen', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '47', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('Brad von Gillern', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '4', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist04/highres/dist04.jpg', 'elected', NULL),
('Rick Holdcroft', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '36', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist36/highres/dist36.jpg', 'elected', NULL),
('Rita Sanders', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '45', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist45/highres/dist45.jpg', 'elected', NULL),
('Rob Clements', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '2', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist02/highres/dist02.jpg', 'elected', NULL),
('Robert Dover', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '19', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist19/highres/dist19.jpg', 'elected', NULL),
('Stan Clouse', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '37', NULL, 'Nonpartisan', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/167022.jpg', 'elected', NULL),
('Tanya Storer', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '43', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('Teresa Ibach', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '44', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist44/highres/dist44.jpg', 'elected', NULL),
('Terrell McKinney', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '11', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist11/highres/dist11.jpg', 'elected', NULL),
('Tom Brandt', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '32', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist32/highres/dist32.jpg', 'elected', NULL),
('Tony Sorrentino', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '39', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('Victor Rountree', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '3', NULL, 'Nonpartisan', NULL, 'elected', NULL),
('Wendy DeBoer', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '10', NULL, 'Nonpartisan', 'https://www.nebraskalegislature.gov/media/images/senators/dist10/highres/dist10.jpg', 'elected', NULL),
('Woody Wordekemper', 'State Senator', 'Legislative Branch', 'Legislative', 'NE', '15', NULL, 'Nonpartisan', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/164427.jpg', 'elected', NULL);
