-- NJ state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'NJ';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Al Abdelaziz', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '35', NULL, 'Democratic', NULL, 'elected', NULL),
('Al Barlas', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '40', NULL, 'Republican', NULL, 'elected', NULL),
('Alex Sauickie', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '12', NULL, 'Republican', NULL, 'elected', NULL),
('Alixon Collazos-Gill', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '27', NULL, 'Democratic', NULL, 'elected', NULL),
('Andrea Katz', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '8', NULL, 'Democratic', NULL, 'elected', NULL),
('Andrew Macurdy', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '21', NULL, 'Democratic', NULL, 'elected', NULL),
('Andrew Zwicker', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '16', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/zwicker_andrew_2019.jpg', 'elected', NULL),
('Angela McKnight', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '31', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/mcknight_color.jpg', 'elected', NULL),
('Annette Quijano', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '20', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/quijano_annette_2020.jpg', 'elected', NULL),
('Anthony Angelozzi', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '8', NULL, 'Democratic', NULL, 'elected', NULL),
('Tony Bucco', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '25', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/bucco_a_m_color.jpg', 'elected', NULL),
('Anthony Verrelli', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '15', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/verrelli_anthony_2020.jpg', 'elected', NULL),
('Antwan McClellan', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '1', NULL, 'Republican', 'http://www.njleg.state.nj.us/members/memberphotos/mcclellan_antwan_2020.jpg', 'elected', NULL),
('Aura Dunn', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '25', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/dunn_aura_2020.jpg', 'elected', NULL),
('Avi Schnall', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '30', NULL, 'Democratic', NULL, 'elected', NULL),
('Balvir Singh', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '7', NULL, 'Democratic', NULL, 'elected', NULL),
('Benjie Wimberly', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '35', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/wimberly_color.jpg', 'elected', NULL),
('Bob Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '17', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/smith_bob_2021.jpg', 'elected', NULL),
('Brian Bergen', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '26', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/bergen_brian_2020.jpg', 'elected', NULL),
('Brian Rumpf', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '9', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/rumpf_brian_2020.jpg', 'elected', NULL),
('Brian Stack', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '33', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/stack_color.jpg', 'elected', NULL),
('Britnee Timberlake', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '34', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/timberlake_britnee_2018.jpg', 'elected', NULL),
('Carmen Amato', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '9', NULL, 'Republican', NULL, 'elected', NULL),
('Carmen Morales', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '34', NULL, 'Democratic', NULL, 'elected', NULL),
('Carol Murphy', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '7', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/murphy_carol_2021.jpg', 'elected', NULL),
('Chigozie Onyema', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '28', NULL, 'Democratic', NULL, 'elected', NULL),
('Chris DePhillips', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '40', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/dephillips_christopher_2020.jpg', 'elected', NULL),
('Cleopatra Tucker', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '28', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/tucker_cleopatra_2017.jpg', 'elected', NULL),
('Clinton Calabrese', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '36', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/calabrese_clinton_2018.jpg', 'elected', NULL),
('Cody Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '4', NULL, 'Democratic', NULL, 'elected', NULL),
('Craig Coughlin', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '19', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/coughlin_craig_2017.jpg', 'elected', NULL),
('Dan Hutchison', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '4', NULL, 'Democratic', NULL, 'elected', NULL),
('Dave Bailey', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '3', NULL, 'Democratic', NULL, 'elected', NULL),
('Dawn Fantasia', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '24', NULL, 'Republican', NULL, 'elected', NULL),
('Declan O''Scanlon', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '13', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/oscanlon_color.jpg', 'elected', NULL),
('Don Guardian', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '2', NULL, 'Republican', NULL, 'elected', NULL),
('Doug Steinhardt', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '23', NULL, 'Republican', NULL, 'elected', NULL),
('Ed Rodriguez', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '20', NULL, 'Democratic', NULL, 'elected', NULL),
('Eliana Pintor Marin', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '29', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/pintormarin_eliana_2017.jpg', 'elected', NULL),
('Ellen Park', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '37', NULL, 'Democratic', NULL, 'elected', NULL),
('Erik Peterson', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '23', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/peterson_erik_2020.jpg', 'elected', NULL),
('Erik Simonsen', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '1', NULL, 'Republican', 'http://www.njleg.state.nj.us/members/memberphotos/simonsen_erik_2020.jpg', 'elected', NULL),
('Gabe Rodriguez', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '33', NULL, 'Democratic', NULL, 'elected', NULL),
('Gary Schaer', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '36', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/schaer_color.jpg', 'elected', NULL),
('Gerry Scharfenberger', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '13', NULL, 'Republican', 'http://www.njleg.state.nj.us/members/memberphotos/scharfenberger_gerard_2020a.jpg', 'elected', NULL),
('Gordon Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '37', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/johnson_color.jpg', 'elected', NULL),
('Greg Myhre', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '9', NULL, 'Republican', NULL, 'elected', NULL),
('Greg McGuckin', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '10', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/mcguckin_gregory_2020.jpg', 'elected', NULL),
('Heather Simmons', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '3', NULL, 'Democratic', NULL, 'elected', NULL),
('Holly Schepisi', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '39', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/schepisi_holly_2021.jpg', 'elected', NULL),
('Jim Beach', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '6', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/beach_color.jpg', 'elected', NULL),
('Jim Kennedy', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '22', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/kennedy_color.jpg', 'elected', NULL),
('Jim Holzapfel', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '10', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/holzapfel_james_2020.jpg', 'elected', NULL),
('Jay Webber', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '26', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/webber_jay_2019.jpg', 'elected', NULL),
('Jerry Walker', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '31', NULL, 'Democratic', NULL, 'elected', NULL),
('Joe Danielsen', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '17', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/danielsen_joe_2021.jpg', 'elected', NULL),
('John Azzariti', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '39', NULL, 'Republican', NULL, 'elected', NULL),
('John DiMaio', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '23', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/dimaio_john_2020.jpg', 'elected', NULL),
('John McKeon', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '27', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/mckeon_color.jpg', 'elected', NULL),
('John Burzichelli', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '3', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/burzichelli_color.jpg', 'elected', NULL),
('Jon Bramnick', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '21', NULL, 'Republican', NULL, 'elected', NULL),
('Joe Lagana', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '38', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/lagana_joseph_2020.jpg', 'elected', NULL),
('Joe Vitale', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '19', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/vitale_color.jpg', 'elected', NULL),
('Joe Cryan', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '20', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/cryan_joseph_2017.jpg', 'elected', NULL),
('Joe Pennacchio', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '26', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/pennacchio_color.jpg', 'elected', NULL),
('Katie Brennan', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '32', NULL, 'Democratic', NULL, 'elected', NULL),
('Kenyatta Stewart', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '35', NULL, 'Democratic', NULL, 'elected', NULL),
('Kevin Egan', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '17', NULL, 'Democratic', NULL, 'elected', NULL),
('Kristin Corrado', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '40', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/corrado_kristin_2017.jpg', 'elected', NULL),
('Larry Wainstein', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '33', NULL, 'Democratic', NULL, 'elected', NULL),
('Latham Tiver', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '8', NULL, 'Republican', NULL, 'elected', NULL),
('Linda Greenstein', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '14', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/greenstein_color.jpg', 'elected', NULL),
('Linda Carter', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '22', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/carter_linda_2018a.jpg', 'elected', NULL),
('Lisa Swain', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '38', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/swain_lisa_2018a.jpg', 'elected', NULL),
('Lou Greenwald', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '6', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/greenwald_color.jpg', 'elected', NULL),
('Luanne Peterpaul', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '11', NULL, 'Democratic', NULL, 'elected', NULL),
('Teresa Ruiz', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '29', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/ruiz_teresa_2021.jpg', 'elected', NULL),
('Margie Donlon', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '11', NULL, 'Democratic', NULL, 'elected', NULL),
('Marisa Sweeney', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '25', NULL, 'Democratic', NULL, 'elected', NULL),
('Maureen Rowan', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '2', NULL, 'Democratic', NULL, 'elected', NULL),
('Melinda Kane', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '6', NULL, 'Democratic', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/168239.jpg', 'elected', NULL),
('Mike Testa', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '1', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/testa_michael_2019.jpg', 'elected', NULL),
('Mike Inganamort', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '24', NULL, 'Republican', NULL, 'elected', NULL),
('Mike Venezia', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '34', NULL, 'Democratic', NULL, 'elected', NULL),
('Mitchelle Drulis', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '16', NULL, 'Democratic', NULL, 'elected', NULL),
('Nick Scutari', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '22', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/scutari_nicholas_2020.jpg', 'elected', NULL),
('Nilsa Cruz-Perez', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '5', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/cruzperez_color.jpg', 'elected', NULL),
('Owen Henry', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '12', NULL, 'Republican', NULL, 'elected', NULL),
('Chris Tully', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '38', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/tully_christopher_2018b.jpg', 'elected', NULL),
('Parker Space', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '24', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/space_parker_2020.jpg', 'elected', NULL),
('Patrick Diegnan', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '18', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/diegnan_2017.jpg', 'elected', NULL),
('Paul Sarlo', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '36', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/sarlo_color.jpg', 'elected', NULL),
('Paul Moriarty', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '4', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/moriarty_color.jpg', 'elected', NULL),
('Paul Kanitra', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '10', NULL, 'Republican', NULL, 'elected', NULL),
('Raj Mukherji', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '32', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/mukherji_color.jpg', 'elected', NULL),
('Ravi Bhalla', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '32', NULL, 'Democratic', NULL, 'elected', NULL),
('Renee Burgess', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '28', NULL, 'Democratic', NULL, 'elected', NULL),
('Bob Auth', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '39', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/auth_robert_2017.jpg', 'elected', NULL),
('Rob Clifton', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '12', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/clifton_robert_2020.jpg', 'elected', NULL),
('Robert Karabinchak', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '18', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/karabinchak_color.jpg', 'elected', NULL),
('Bob Singer', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '30', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/singer_color.jpg', 'elected', NULL),
('Rosy Bagolie', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '27', NULL, 'Democratic', NULL, 'elected', NULL),
('Roy Freiman', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '16', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/freiman_roy_2020.jpg', 'elected', NULL),
('Sean Kean', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '30', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/kean_sean_2020.jpg', 'elected', NULL),
('Shama Haider', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '37', NULL, 'Democratic', NULL, 'elected', NULL),
('Shanique Speight', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '29', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/speight_shanique_2017.jpg', 'elected', NULL),
('Shirley Turner', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '15', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/turner_color.jpg', 'elected', NULL),
('Sterley Stanley', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '18', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/stanley_sterley_2021.jpg', 'elected', NULL),
('Tennille McCoy', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '14', NULL, 'Democratic', NULL, 'elected', NULL),
('Troy Singleton', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '7', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/singleton_troy_2019.jpg', 'elected', NULL),
('Verlina Reynolds-Jackson', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '15', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/reynolds-jackson_verlina_2018.jpg', 'elected', NULL),
('Vicky Flynn', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '13', NULL, 'Republican', NULL, 'elected', NULL),
('Vin Gopal', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '11', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/gopal_vin_2021.jpg', 'elected', NULL),
('Vince Polistina', 'State Senator', 'Legislative Branch', 'Legislative', 'NJ', '2', NULL, 'Republican', 'https://www.njleg.state.nj.us/members/memberphotos/polistina_vincent_2021.jpg', 'elected', NULL),
('Vinnie Kearney', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '21', NULL, 'Democratic', NULL, 'elected', NULL),
('Wayne DeAngelo', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '14', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/deangelo_color.jpg', 'elected', NULL),
('Will Sampson', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '31', NULL, 'Democratic', NULL, 'elected', NULL),
('Bill Moen', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '5', NULL, 'Democratic', NULL, 'elected', NULL),
('Bill Spearman', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '5', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/spearman_william_2018a.jpg', 'elected', NULL),
('Yvonne Lopez', 'State Representative', 'Legislative Branch', 'Legislative', 'NJ', '19', NULL, 'Democratic', 'https://www.njleg.state.nj.us/members/memberphotos/lopez_yvonne_2017.jpg', 'elected', NULL);
