-- NM state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'NM';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Alan Martinez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '23', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HMAAL.jpg', 'elected', NULL),
('Andi Reeb', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '64', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HREEB.jpg', 'elected', NULL),
('Andrea Romero', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '46', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HROAN.jpg', 'elected', NULL),
('Angel Charley', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '30', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/65a92fa05202ee2b13428333/630e642f-dfc6-48c0-930b-c25b16d80e76/Headshot.jpg', 'elected', NULL),
('Angelica Rubio', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '35', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HRUBI.jpg', 'elected', NULL),
('Angelita Mejia', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '58', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/rdrnews.com/content/tncms/assets/v3/editorial/5/0f/50f20b06-de3c-11ee-8fb3-1b97c5eaf40c/65ec9fd35dc59.image.jpg?resize=457%2C500', 'elected', NULL),
('Anita Gonzales', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '70', NULL, 'Democratic', 'https://anita4newmexico.com/wp-content/uploads/2024/02/Anita-ABOUT.jpg', 'elected', NULL),
('Ant Thornton', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '19', NULL, 'Republican', 'https://antthorntonfornm.com/wp-content/uploads/2024/02/Ant-Thornton-768x768.jpg', 'elected', NULL),
('Antoinette Sedillo Lopez', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '16', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SSEDI.jpg', 'elected', NULL),
('Moe Maestas', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '26', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SMAEM.jpg', 'elected', NULL),
('Art De La Cruz', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '12', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HDELA.jpg', 'elected', NULL),
('Benny Shendo', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '22', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SSHEN.jpg', 'elected', NULL),
('Bill Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '3', NULL, 'Republican', NULL, 'elected', NULL),
('Brian Baca', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '8', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HBACB.jpg', 'elected', NULL),
('Candy Ezzell', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '32', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HEZZE.jpg', 'elected', NULL),
('Carrie Hamblen', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '38', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SHAMB.jpg', 'elected', NULL),
('Catherine Cullen', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '57', NULL, 'Republican', 'https://cullen4nm.com/wp-content/plugins/phastpress/phast.php/c2VydmljZT1pbWFnZXMmc3JjPWh0dHBzJTNBJTJGJTJGY3VsbGVuNG5tLmNvbSUyRndwLWNvbnRlbnQlMkZ1cGxvYWRzJTJGMjAyNCUyRjA3JTJGSU1HXzMyMjguanBnJmNhY2hlTWFya2VyPTE3MzAxNTM0NzYtMTUyNzQyJnRva2VuPTU0MDM0MzcxMmJiYWYyZmY.q.jpg', 'elected', NULL),
('Cathrynn Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '55', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HBROW.jpg', 'elected', NULL),
('Charlotte Little', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '68', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HLITC.jpg', 'elected', NULL),
('Chris Chandler', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '43', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HCHAN.jpg', 'elected', NULL),
('Cindy Nava', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '9', NULL, 'Democratic', 'https://s3.amazonaws.com/cms.ipressroom.com/175/files/20187/5b883c6f2cfac267c6377417_Cindy+Nava+1/Cindy+Nava+1_mid.jpg', 'elected', NULL),
('Craig Brandt', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '40', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/Senate/SBRAN.jpg', 'elected', NULL),
('Cristina Parajón', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '25', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HPARA.jpg', 'elected', NULL),
('Crystal Brantley', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '35', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/Senate/SDIAM.jpg', 'elected', NULL),
('Cynthia Borrego', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '17', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HBORR.jpg', 'elected', NULL),
('Wonda Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '5', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HJOHD.jpg', 'elected', NULL),
('David Gallegos', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '41', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/Senate/SGADM.jpg', 'elected', NULL),
('Day Hochman-Vigil', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '15', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HHOCH.jpg', 'elected', NULL),
('Debbie O''Malley', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '13', NULL, 'Democratic', 'https://www.naco.org/sites/default/files/styles/349x333/public/PIC_OMalley%2C%20Debbie.webp', 'elected', NULL),
('Debbie Sariñana', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '21', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HSARI.jpg', 'elected', NULL),
('Derrick Lente', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '65', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HLENT.jpg', 'elected', NULL),
('Diane Torres-Velásquez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '30', NULL, 'Democratic', 'https://static.wixstatic.com/media/4db618_2eb9e70e0469459fa20a1b6a172d7f67~mv2.jpg/v1/fill/w_200,h_200,fp_0.47_0.36,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/image000000.jpg', 'elected', NULL),
('Doreen Gallegos', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '52', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HGADO.jpg', 'elected', NULL),
('Elaine Sena Cortez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '62', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/6101dbe38853cb26aaf1d169/482eeab7-b7c0-4dfc-bc83-1b4ecc0e66b4/945A8275-Edit.jpg', 'elected', NULL),
('Eleanor Chávez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '26', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HCHAL.jpg', 'elected', NULL),
('Liz Stefanics', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '39', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SSTEF.jpg', 'elected', NULL),
('Liz Thomson', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '24', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HTHOE.jpg', 'elected', NULL),
('Andrés Romero', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '10', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HROMA.jpg', 'elected', NULL),
('Gabriel Ramos', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '28', NULL, 'Republican', 'http://www.nmlegis.gov/Images/Legislators/Senate/SRAMO.jpg', 'elected', NULL),
('Gail Armstrong', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '49', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HARMG.jpg', 'elected', NULL),
('George Muñoz', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '4', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SMUNO.jpg', 'elected', NULL),
('Harlan Vincent', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '56', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HVINC.jpg', 'elected', NULL),
('Harold Pope', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '23', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SPOPE.jpg', 'elected', NULL),
('Heather Berghmans', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '15', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/HeatherBerghmans24.jpg', 'elected', NULL),
('Jack Chatfield', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '67', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HCHAT.jpg', 'elected', NULL),
('Jim Townsend', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '34', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HTOWJ.jpg', 'elected', NULL),
('Janelle Anyanonu', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '19', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HANYA.jpg', 'elected', NULL),
('Javier Martínez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '11', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HMARJ.jpg', 'elected', NULL),
('Jay Block', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '12', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jay_Block.jpg', 'elected', NULL),
('Jeff Steinborn', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '36', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SSTEI.jpg', 'elected', NULL),
('Jenifer Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '32', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HJONJ.jpg', 'elected', NULL),
('Jimmy Mason', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '66', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HMASO.jpg', 'elected', NULL),
('Joanne Ferrary', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '37', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HFERJ.jpg', 'elected', NULL),
('John Block', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '51', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HBLOC.jpg', 'elected', NULL),
('Jon Henry', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '54', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/810348/810348.jpg', 'elected', NULL),
('Joe Cervantes', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '31', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SCERV.jpg', 'elected', NULL),
('Joseph Hernandez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '4', NULL, 'Democratic', 'https://progressivevotersguide.com/sites/default/files/styles/candidate/public/new%20mexico/2024/general/Joseph%20H.jpg?itok=DRcr52HE', 'elected', NULL),
('Joseph Sanchez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '40', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HSAJO.jpg', 'elected', NULL),
('Joshua Sanchez', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '29', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/Senate/SSANJ.jpg', 'elected', NULL),
('Josh Hernandez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '60', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HHERN.jpg', 'elected', NULL),
('Joy Garratt', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '29', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HGARR.jpg', 'elected', NULL),
('Kathleen Cates', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '44', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HCATE.jpg', 'elected', NULL),
('Katy Duhigg', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '10', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SDUHI.jpg', 'elected', NULL),
('Kristina Ortez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '42', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HORTE.jpg', 'elected', NULL),
('Larry Scott', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '42', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HSCOT.jpg', 'elected', NULL),
('Leo Jaramillo', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '5', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SJARA.jpg', 'elected', NULL),
('Linda López', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '11', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SLOPE.jpg', 'elected', NULL),
('Linda Trujillo', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '24', NULL, 'Democratic', 'http://www.nmlegis.gov/Images/Legislators/House/HTRUL.jpg', 'elected', NULL),
('Linda Serrato', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '45', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HSERR.jpg', 'elected', NULL),
('Luis Terrazas', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '39', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HTERR.jpg', 'elected', NULL),
('Marian Matthews', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '27', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HMATT.jpg', 'elected', NULL),
('Marianna Anaya', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '18', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MariannaAnaya.jpg', 'elected', NULL),
('Mark Duncan', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '2', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HDUNC.jpg', 'elected', NULL),
('Mark Murphy', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '59', NULL, 'Republican', NULL, 'elected', NULL),
('Martha Garcia', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '6', NULL, 'Democratic', NULL, 'elected', NULL),
('Martin Hickey', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '20', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SHICK.jpg', 'elected', NULL),
('Martin Zamora', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '63', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HZAMO.jpg', 'elected', NULL),
('Matthew McQueen', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '50', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HMCQU.jpg', 'elected', NULL),
('Meredith Dixon', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '20', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HDIXO.jpg', 'elected', NULL),
('Micaela Cadena', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '33', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HCADA.jpg', 'elected', NULL),
('Michael Padilla', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '14', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SPADI.jpg', 'elected', NULL),
('Miguel García', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '14', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HGAMP.jpg', 'elected', NULL),
('Mimi Stewart', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '17', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SSTEW.jpg', 'elected', NULL),
('Natalie Figueroa', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '18', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HFIGU.jpg', 'elected', NULL),
('Nathan Small', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '36', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HSMAL.jpg', 'elected', NULL),
('Nicole Chavez', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '31', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/NicoleChavez.jpeg', 'elected', NULL),
('Nicole Tobiassen', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '21', NULL, 'Republican', 'https://nicolefornm.com/wp-content/uploads/2023/06/Nicole-Tobiassen-Headshot-3-768x512.jpg', 'elected', NULL),
('Pamelya Herndon', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '28', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HHEPA.jpg', 'elected', NULL),
('Pat Boone', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '27', NULL, 'Republican', 'https://senatorpatboone.com/wp-content/uploads/2024/03/Pat-Boone-Photo-1.jpg', 'elected', NULL),
('Pat Woods', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '7', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/Senate/SWOOD.jpg', 'elected', NULL),
('Patty Lundstrom', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '9', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HLUND.jpg', 'elected', NULL),
('Pat Roybal Caballero', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '13', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HROYB.jpg', 'elected', NULL),
('Paulene Abeyta', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '69', NULL, 'Democratic', 'https://womencount.org/wp-content/uploads/2024/03/Michelle-Paulene-Abeyta-300x300.jpeg', 'elected', NULL),
('Pete Campos', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '8', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SCAMP.jpg', 'elected', NULL),
('Peter Wirth', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '25', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SWIRT.jpg', 'elected', NULL),
('Randy Pettigrew', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '61', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HPETT.jpg', 'elected', NULL),
('Ray Lara', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '34', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HLARA.jpg', 'elected', NULL),
('Rebecca Dow', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '38', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HDOWR.jpg', 'elected', NULL),
('Reena Szczepanski', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '47', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HSZCZ.jpg', 'elected', NULL),
('Rex Wilson', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '33', NULL, 'Republican', NULL, 'elected', NULL),
('Bobby Gonzales', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '6', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SGONZ.jpg', 'elected', NULL),
('Rod Montoya', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '1', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HMONR.jpg', 'elected', NULL),
('Sarah Silva', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '53', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/66d0e643284c6d63d067a073/8916e12c-d13c-49fb-810a-2c7ffb58d300/SilvaSarah.JPG', 'elected', NULL),
('Shannon Pinto', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '3', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SPINS.jpg', 'elected', NULL),
('Stefani Lord', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '22', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HLORD.jpg', 'elected', NULL),
('Steve Lanier', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '2', NULL, 'Republican', 'https://www.naco.org/sites/default/files/styles/349x333/public/Steve%20Lanier.webp', 'elected', NULL),
('Susan Herrera', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '41', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HHERS.jpg', 'elected', NULL),
('Tanya Moya', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '7', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/House/HMIRA.jpg', 'elected', NULL),
('Tara Luján', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '48', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HLUTA.jpg', 'elected', NULL),
('Bill Sharer', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '1', NULL, 'Republican', 'https://www.nmlegis.gov/Images/Legislators/Senate/SSHAR.jpg', 'elected', NULL),
('Bill Soules', 'State Senator', 'Legislative Branch', 'Legislative', 'NM', '37', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/Senate/SSOUL.jpg', 'elected', NULL),
('Yanira Gurrola', 'State Representative', 'Legislative Branch', 'Legislative', 'NM', '16', NULL, 'Democratic', 'https://www.nmlegis.gov/Images/Legislators/House/HGURR.jpg', 'elected', NULL);
