-- NV state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'NV';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Alexis Hansen', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '32', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Hansen.Alexis.366.jpg', 'elected', NULL),
('Angie Taylor', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '15', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Taylor.Angela.424.jpg', 'elected', NULL),
('Bert Gurr', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '33', NULL, 'Republican', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/Gurr.Bert.402.jpg', 'elected', NULL),
('Blayne Osborn', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '39', NULL, 'Republican', 'http://www.leg.state.nv.us/Session/36th2025Special/legislators/Assembly/Images/Osborn.Blayne.427.jpg', 'elected', NULL),
('Brian Hibbetts', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '13', NULL, 'Republican', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/Hibbetts.Brian.394.jpg', 'elected', NULL),
('Brittney Miller', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '5', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Miller.Brittney.304.jpg', 'elected', NULL),
('Carrie Buck', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '5', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Buck.Carrie.387.jpg', 'elected', NULL),
('Cecelia González', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '16', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Gonzlez.Cecelia.378.jpg', 'elected', NULL),
('Cinthia Moore', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '11', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Moore.Cinthia.412.jpg', 'elected', NULL),
('Daniele Monroe-Moreno', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '1', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/MonroeMoreno.Daniele.307.jpg', 'elected', NULL),
('Danielle Gallant', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '23', NULL, 'Republican', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/Gallant.Danielle.397.jpg', 'elected', NULL),
('David Orentlicher', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '20', NULL, 'Democratic', 'http://www.leg.state.nv.us/Session/36th2025Special/legislators/Assembly/Images/Orentlicher.David.377.jpg', 'elected', NULL),
('Dina Neal', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '4', NULL, 'Democratic', 'http://leg.state.nv.us/Session/81st2021/legislators/Senators/Images/Neal.Dina.129.jpg', 'elected', NULL),
('Duy Nguyen', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '8', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/Nguyen.Duy.392.jpg', 'elected', NULL),
('Edgar Flores', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '2', NULL, 'Democratic', 'http://leg.state.nv.us/Session/81st2021/legislators/Assembly/Images/Flores.Edgar.273.jpg', 'elected', NULL),
('Elaine Marzola', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '21', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Marzola.Elaine.376.jpg', 'elected', NULL),
('Erica Mosca', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '14', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/Mosca.Erica.395.jpg', 'elected', NULL),
('Erica Roth', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '24', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Roth.Erica.413.jpg', 'elected', NULL),
('Fabian Doñate', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '10', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Senators/Images/Doate.Fabian.350.jpg', 'elected', NULL),
('Gregory Koenig', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '38', NULL, 'Republican', 'http://www.leg.state.nv.us/Session/36th2025Special/legislators/Assembly/Images/Koenig.Gregory.403.jpg', 'elected', NULL),
('Greg Hafen', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '36', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Hafen.Gregory.371.jpg', 'elected', NULL),
('Hanadi Nadeem', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '34', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Hanadi_Nadeem1.jpeg', 'elected', NULL),
('Heather Goulding', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '27', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Goulding.Heather.416.jpg', 'elected', NULL),
('Heidi Kasama', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '2', NULL, 'Republican', 'http://www.leg.state.nv.us/Session/36th2025Special/legislators/Assembly/Images/Kasama.Heidi.379.jpg', 'elected', NULL),
('Howard Watts', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '15', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Watts.Howard.363.jpg', 'elected', NULL),
('Ira Hansen', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '14', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Hansen.Ira.157.jpg', 'elected', NULL),
('James Ohrenschall', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '21', NULL, 'Democratic', 'http://leg.state.nv.us/Session/80th2019/legislators/Senators/Images/Ohrenschall.James.67.jpg', 'elected', NULL),
('Jason Patchett', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '19', NULL, 'Republican', 'https://media.lasvegassun.com/media/img/photos/2016/06/08/Patchett_Jason_t650.jpg?5711a3b57decb389a12ba40e20471e031ff69545', 'elected', NULL),
('Jeff Stone', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '20', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Stone.Jeff.390.jpg', 'elected', NULL),
('Jill Dickman', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '31', NULL, 'Republican', 'http://www.leg.state.nv.us/Session/36th2025Special/legislators/Assembly/Images/Dickman.Jill.277.jpg', 'elected', NULL),
('Joe Dalia', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '29', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Dalia.Joe.414.jpg', 'elected', NULL),
('John Ellison', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '19', NULL, 'Republican', 'http://leg.state.nv.us/Session/81st2021/legislators/Assembly/Images/Ellison.John.159.jpg', 'elected', NULL),
('John Steinbeck', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '18', NULL, 'Republican', 'http://www.leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Steinbeck.John.418.jpg', 'elected', NULL),
('Jovan Jackson', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '6', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Jackson.Jovan.422.jpg', 'elected', NULL),
('Julie Pazina', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '12', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Senators/Images/Pazina.Julie.391.jpg', 'elected', NULL),
('Linda Hunt', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '17', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Hunt.Linda.420.jpg', 'elected', NULL),
('Lisa Cole', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '4', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Cole.Lisa.410.jpg', 'elected', NULL),
('Lisa Krasner', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '16', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Krasner.Lisa.327.jpg', 'elected', NULL),
('Lori Rogich', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '11', NULL, 'Republican', 'http://www.leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Rogich.Lori.425.jpg', 'elected', NULL),
('Marilyn Dondero Loop', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '8', NULL, 'Democratic', 'http://leg.state.nv.us/Session/80th2019/legislators/Senators/Images/DonderoLoop.Marilyn.92.jpg', 'elected', NULL),
('Max Carter', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '12', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/Carter.Max.393.jpg', 'elected', NULL),
('Melanie Scheible', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '9', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Scheible.Melanie.358.jpg', 'elected', NULL),
('Melissa Hardy', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '22', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Hardy.Melissa.364.jpg', 'elected', NULL),
('Natha Anderson', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '30', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Anderson.Natha.375.jpg', 'elected', NULL),
('Nicole Cannizzaro', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '6', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Cannizzaro.Nicole.347.jpg', 'elected', NULL),
('P.K. O''Neill', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '40', NULL, 'Republican', 'http://leg.state.nv.us/Session/81st2021/legislators/Assembly/Images/ONeill.PhilipPK.285.jpg', 'elected', NULL),
('Rebecca Edgeworth', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '35', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Edgeworth.Rebecca.411.jpg', 'elected', NULL),
('Reuben D''Silva', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '28', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/DSilva.Reuben.401.jpg', 'elected', NULL),
('Rich DeLong', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '26', NULL, 'Republican', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/DeLong.Rich.399.jpg', 'elected', NULL),
('Roberta Lange', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '7', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Lange.Roberta.383.jpg', 'elected', NULL),
('Robin Titus', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '17', NULL, 'Republican', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/Titus.Robin.281.jpg', 'elected', NULL),
('Rochelle Nguyen', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '3', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Senators/Images/Nguyen.Rochelle.372.jpg', 'elected', NULL),
('Sandra Jauregui', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '41', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Jauregui.Sandra.344.jpg', 'elected', NULL),
('Selena La Rue Hatch', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '25', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Assembly/Images/LaRueHatch.Selena.398.jpg', 'elected', NULL),
('Selena Torres-Fossett', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '3', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Torres.Selena.359.jpg', 'elected', NULL),
('Shea Backus', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '37', NULL, 'Democratic', 'http://www.leg.state.nv.us/Session/36th2025Special/legislators/Assembly/Images/Backus.Shea.368.jpg', 'elected', NULL),
('Shelly Crawford', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '1', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Senators/Images/CruzCrawford.MicheleeShelly.419.jpg', 'elected', NULL),
('Skip Daly', 'State Senator', 'Legislative Branch', 'Legislative', 'NV', '13', NULL, 'Democratic', 'http://leg.state.nv.us/Session/82nd2023/legislators/Senators/Images/Daly.Skip.155.jpg', 'elected', NULL),
('Steve Yeager', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '9', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Yeager.Steve.310.jpg', 'elected', NULL),
('Tanya Flanagan', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '7', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/Flanagan.Tanya.423.jpg', 'elected', NULL),
('Tracy Brown-May', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '42', NULL, 'Democratic', 'http://leg.state.nv.us/Session/83rd2025/legislators/Assembly/Images/BrownMay.Tracy.353.jpg', 'elected', NULL),
('Venicia Considine', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '18', NULL, 'Democratic', 'http://leg.state.nv.us/Session/81st2021/legislators/Assembly/Images/Considine.Venicia.380.jpg', 'elected', NULL),
('Venise Karris', 'Assembly Member', 'Legislative Branch', 'Legislative', 'NV', '10', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/VeniseKarris2024.jpg', 'elected', NULL);
