-- OK state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'OK';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Aaron Reinhardt', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '37', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Aaron_Reinhardt_20241023_121244.jpeg', 'elected', NULL),
('Adam Pugh', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '41', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/pugh.jpg', 'elected', NULL),
('Aletia Timmons', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '97', NULL, 'Democratic', NULL, 'elected', NULL),
('Ally Seifried', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '2', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Seifried%2C%20Ally%20Flags%202022.jpg', 'elected', NULL),
('Amanda Clinton', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '71', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Amanda_Clinton_20250516_045055.png', 'elected', NULL),
('Andy Fugate', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '94', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Fugate,%20Andy.jpg', 'elected', NULL),
('Annie Menz', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '45', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Menz,%20Annie.jpg', 'elected', NULL),
('Anthony Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '57', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Moore,%20Anthony.jpg', 'elected', NULL),
('Arturo Alonso', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '89', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Alonso,%20Arturo.jpg', 'elected', NULL),
('Avery Frix', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '9', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Frix,%20Avery.jpg', 'elected', NULL),
('Bill Coleman', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '10', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Coleman%2C%20Bill%20Flags%202022.jpg', 'elected', NULL),
('Bob Culver', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '4', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Culver,%20BobEd.jpg', 'elected', NULL),
('Brad Boles', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '51', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Boles,%20Brad.jpg', 'elected', NULL),
('Brenda Stanley', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '42', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Brenda-Stanley_1.jpg', 'elected', NULL),
('Brent Howard', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '38', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Howard%2C%20Brent_flags.jpg', 'elected', NULL),
('Brian Guthrie', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '25', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/citynewsokc.com/content/tncms/assets/v3/editorial/5/d2/5d26a700-4e64-11ee-be35-db82e824c57c/64fb4b329045b.image.jpg?resize=500%2C500', 'elected', NULL),
('Brian Hill', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '47', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Hill,%20Brian.jpg', 'elected', NULL),
('Bryan Logan', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '8', NULL, 'Republican', 'https://nondoc.com/wp-content/uploads/2025/05/Bryan-Logan-mug-cropped-640x373.jpg', 'elected', NULL),
('Carl Newton', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '58', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Newton,%20Carl.jpg', 'elected', NULL),
('Carri Hicks', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '40', NULL, 'Democratic', 'https://oksenate.gov/sites/default/files/Hicks%2C%20Carri%20Flags%202022.jpg', 'elected', NULL),
('Casey Murdock', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '27', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/murdock.jpg', 'elected', NULL),
('Chad Caldwell', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '40', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Caldwell,%20Chad.jpg', 'elected', NULL),
('Chris Banning', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '24', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Banning,%20Chris.jpg', 'elected', NULL),
('Chris Kannady', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '91', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Kannady,%20Chris.jpg', 'elected', NULL),
('Chris Sneed', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '14', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Sneed,%20Chris.jpg', 'elected', NULL),
('Christi Gillespie', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '33', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgg9y84-E8FaeDWzhd1s97N3Ko90lCow4sAQ&s', 'elected', NULL),
('Chuck Hall', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '20', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/hall.jpg', 'elected', NULL),
('Clay Staires', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '66', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Staires,%20Clay.jpg', 'elected', NULL),
('Cody Maynard', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '21', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Maynard,%20Cody.jpg', 'elected', NULL),
('Collin Duel', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '31', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Duel,%20Collin.jpg', 'elected', NULL),
('Cyndi Munson', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '85', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Munson,%20Cyndie.jpg', 'elected', NULL),
('Cindy Roe', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '42', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Cindy-Roe.jpg', 'elected', NULL),
('Dana Prieto', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '34', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Prieto%2C%20Dana%20Flags%202022.jpg', 'elected', NULL),
('Daniel Pae', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '62', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Pae,%20Daniel.jpg', 'elected', NULL),
('Danny Sterling', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '27', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Danny-Sterling.jpg', 'elected', NULL),
('Danny Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '28', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Williams,%20Danny.jpg', 'elected', NULL),
('Darcy Jech', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '26', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/1200px-DarcyJech_0.jpg', 'elected', NULL),
('Darrell Weaver', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '24', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Weaver%2C%20Darrell_flags.jpg', 'elected', NULL),
('Dave Rader', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '39', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Rader%2C%20Dave%20Flags%202022.jpg', 'elected', NULL),
('David Bullard', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '6', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Bullard_David.jpg', 'elected', NULL),
('David Hardin', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '86', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Hardin,%20David.jpg', 'elected', NULL),
('David Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '18', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Smith,%20David.jpg', 'elected', NULL),
('Dell Kerbs', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '26', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Kerbs,%20Dell.jpg', 'elected', NULL),
('Denise Crosswhite Hader', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '41', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Crosswhite%20Hader,%20Denise.jpg', 'elected', NULL),
('Derrick Hildebrant', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '23', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DerrickHildebrant2024.jpg', 'elected', NULL),
('Dick Lowe', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '56', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Lowe,%20Dick.jpg', 'elected', NULL),
('Dillon Travis', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '35', NULL, 'Republican', NULL, 'elected', NULL),
('Dusty Deevers', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '32', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Deevers%2C%20Dusty%202023%20Flags%20S_0.jpg', 'elected', NULL),
('Eddy Dempsey', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '1', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Dempsey,%20Eddy.jpg', 'elected', NULL),
('Ellen Pogemiller', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '88', NULL, 'Democratic', 'https://static.wixstatic.com/media/d59798_0699f998a916470598404706be4aca74~mv2.jpg/v1/fill/w_1349,h_1019,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/d59798_0699f998a916470598404706be4aca74~mv2.jpg', 'elected', NULL),
('Ellyn Hefner', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '87', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Hefner,%20Ellyn.jpg', 'elected', NULL),
('Emily Gise', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '90', NULL, 'Republican', 'https://www.cairoklahoma.com/wp-content/uploads/2024/09/emily-200x200.jpeg', 'elected', NULL),
('Eric Roberts', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '83', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Roberts,%20Eric.jpg', 'elected', NULL),
('Erick Harris', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '39', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ErickHarris.jpg', 'elected', NULL),
('Gabe Woolley', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '98', NULL, 'Republican', 'https://www.cairoklahoma.com/wp-content/uploads/2024/06/gabe-960x958.jpg', 'elected', NULL),
('George Burns', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '5', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Burns%2C%20George_flags_1.jpg', 'elected', NULL),
('Gerrid Kendrix', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '52', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Kendrix,%20Gerrid.jpg', 'elected', NULL),
('Grant Green', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '28', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Green%2C%20Grant%20Flags%202022.jpg', 'elected', NULL),
('Jack Stewart', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '18', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Stewart%2C%20Jack%20Flags%202022.jpg', 'elected', NULL),
('Jacob Rosecrants', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '46', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Rosecrants,%20Jacob.jpg', 'elected', NULL),
('Jared Deck', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '44', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Deck,%20Jared.jpg', 'elected', NULL),
('Jason Blair', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '53', NULL, 'Republican', 'https://www.oklahoman.com/gcdn/authoring/authoring-images/2024/06/10/NOKL/74049882007-jason-blair.jpg?width=300&height=366&fit=crop&format=pjpg&auto=webp', 'elected', NULL),
('Jay Steagall', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '43', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Steagall,%20Jay.jpg', 'elected', NULL),
('Jerry Alvord', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '14', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Alvord%2C%20Jerry%20Flags%202022.jpg', 'elected', NULL),
('Jim Grego', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '17', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Grego,%20Jim.jpg', 'elected', NULL),
('Jim Olsen', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '2', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Olsen,%20Jim.jpg', 'elected', NULL),
('Jim Shaw', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '32', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JimShaw2.jpg', 'elected', NULL),
('Jo Anna Dossett', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '35', NULL, 'Democratic', 'https://oksenate.gov/sites/default/files/Dossett%2C%20Jo%20Anna_flags.jpg', 'elected', NULL),
('John George', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '36', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/George,%20John.jpg', 'elected', NULL),
('John Haste', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '36', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Haste%2C%20John%202022%20Flags.jpg', 'elected', NULL),
('John Kane', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '11', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Kane,%20John.jpg', 'elected', NULL),
('John Pfeiffer', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '38', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Pfeiffer,%20John.JPG', 'elected', NULL),
('John Waldron', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '77', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Waldron,%20John.jpg', 'elected', NULL),
('Jonathan Wilk', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '20', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQcSK-0G7vutoYpyD-I4rn3EZVvTgV8ij17A&s', 'elected', NULL),
('Jonathan Wingard', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '13', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JonathanWingard2024.png', 'elected', NULL),
('Josh Cantrell', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '49', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Cantrell,%20Josh.jpg', 'elected', NULL),
('Josh West', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '5', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/West,%20Josh.jpg', 'elected', NULL),
('Judd Strom', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '10', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Strom,%20Judd.jpg', 'elected', NULL),
('Julia Kirt', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '30', NULL, 'Democratic', 'https://oksenate.gov/sites/default/files/Kirt%2C%20Julia%202023%20Flags%20S.jpg', 'elected', NULL),
('Julie Daniels', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '29', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Daniels%2C%20Julie%202022.jpg', 'elected', NULL),
('Julie McIntosh', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '3', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JulieMcIntosh2024.jpeg', 'elected', NULL),
('Justin Humphrey', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '19', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Humphrey,%20Justin.jpg', 'elected', NULL),
('Kelly Hines', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '47', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/642c607b85563b44f0aa5800/5c9a6226-10da-4b2b-848d-746244b9e4ad/headshot+%28002%29.jpg', 'elected', NULL),
('Ken Luttrell', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '37', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Luttrell,%20Ken.jpg', 'elected', NULL),
('Kendal Sacchieri', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '43', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/KendalSacchieri2024.jpg', 'elected', NULL),
('Kenton Patzkowsky', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '61', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Kenton-Patzkowsky,.jpg', 'elected', NULL),
('Kevin Norwood', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '74', NULL, 'Republican', NULL, 'elected', NULL),
('Kevin West', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '54', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Kevin-West.jpg', 'elected', NULL),
('Kristen Thompson', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '22', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Thompson%2C%20Kristen%20Flags%202022.jpg', 'elected', NULL),
('Kyle Hilbert', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '29', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Hilbert,%20Kyle.jpg', 'elected', NULL),
('Lisa Standridge', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '15', NULL, 'Republican', 'https://www.cairoklahoma.com/wp-content/uploads/2024/08/lisa-474x474.jpeg', 'elected', NULL),
('Lonnie Paxton', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '23', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/paxton.jpg', 'elected', NULL),
('Marilyn Stark', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '100', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Stark,%20Marilyn.jpg', 'elected', NULL),
('Mark Chapman', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '12', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MarkChapman2024.JPG', 'elected', NULL),
('Mark Lawson', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '30', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Lawson,%20Mark.jpg', 'elected', NULL),
('Mark Lepak', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '9', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Lepak,%20Mark.jpg', 'elected', NULL),
('Mark Mann', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '46', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Mark_Mann.png', 'elected', NULL),
('Mark Tedford', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '69', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Tedford,%20Mark.jpg', 'elected', NULL),
('Mary Boren', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '16', NULL, 'Democratic', 'https://oksenate.gov/sites/default/files/Boren%2C%20Mary%20Flags%202022.jpg', 'elected', NULL),
('Max Wolfley', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '95', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Wolfley,%20Max.jpg', 'elected', NULL),
('Melissa Provenzano', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '79', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Melissa-Provenzano.jpg', 'elected', NULL),
('Meloyde Blancett', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '78', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Blancett,%20Meloyde.jpg', 'elected', NULL),
('Michael Brooks', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '44', NULL, 'Democratic', 'https://oksenate.gov/sites/default/files/Brooks%2C%20Michael%20Flags%202022.jpg', 'elected', NULL),
('Micheal Bergstrom', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '1', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Bergstrom%2C%20Micheal%202022%20flags.jpg', 'elected', NULL),
('Michelle McCane', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '72', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MichelleMcCane2024.jpg', 'elected', NULL),
('Mickey Dollens', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '93', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Mickey-Dollens.jpg', 'elected', NULL),
('Mike Dobrinski', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '59', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Dobrinski,%20Mike.jpg', 'elected', NULL),
('Mike Kelley', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '60', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MikeKelley2024.jpg', 'elected', NULL),
('Mike Lay', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '68', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6rbtW0elpYl-o3FI3jbR9-PkUylFA7p5-Ig&s', 'elected', NULL),
('Mike Osburn', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '81', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Osburn,%20Mike.jpg', 'elected', NULL),
('Molly Jenkins', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '33', NULL, 'Republican', 'https://www.cushingcitizen.com/sites/cushingcitizen.com/files/styles/article_420/public/3d8c9a84be_Ar00503010.jpg?itok=QUjuCFyZ', 'elected', NULL),
('Neil Hays', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '13', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Hays,%20Neil.jpg', 'elected', NULL),
('Nick Archer', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '55', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Archer,%20Nick.jpg', 'elected', NULL),
('Nicole Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '82', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Nicole-Miller.jpg', 'elected', NULL),
('Nikki Nice', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '48', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/008O6811.jpg', 'elected', NULL),
('Paul Rosino', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '45', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Rosino%2C%20Paul%20Flags%202022.jpg', 'elected', NULL),
('Preston Stinson', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '96', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Stinson,%20Preston.jpg', 'elected', NULL),
('Rande Worthen', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '64', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Rande-Worthen.jpg', 'elected', NULL),
('Randy Grellner', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '21', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/RandyGrellner2024.jpg', 'elected', NULL),
('Regina Goodwin', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '11', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Goodwin,%20Regina.jpg', 'elected', NULL),
('Rick West', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '3', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/West,%20Rick.jpg', 'elected', NULL),
('Rob Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '67', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/rhall.jpg', 'elected', NULL),
('Robert Manger', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '101', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Manger,%20Robert.jpg', 'elected', NULL),
('Roland Pederson', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '19', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Pederson%2C%20Roland%202022%20flags.jpg', 'elected', NULL),
('Ron Stewart', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '73', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/RonStewart2024.jpg', 'elected', NULL),
('Ronny Johns', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '25', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Johns,%20Ronny.jpg', 'elected', NULL),
('Ross Ford', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '76', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Ford,%20Ross.jpg', 'elected', NULL),
('Rusty Cornwell', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '6', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Cornwell,%20Rusty.jpg', 'elected', NULL),
('Ryan Eaves', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '22', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/RyanEaves2024.jpg', 'elected', NULL),
('Scott Fetgatter', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '16', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Fetgatter,%20Scott.jpg', 'elected', NULL),
('Shane Jett', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '17', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Jett%2C%20Shane_flags.jpg', 'elected', NULL),
('Spencer Kern', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '31', NULL, 'Republican', 'https://static.votesmart.org/static/canphoto/216441.jpg', 'elected', NULL),
('Stacy Adams', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '50', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/StacyAdams2024.png', 'elected', NULL),
('Stan May', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '80', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/May,%20Stan.jpg', 'elected', NULL),
('Steve Bashore', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '7', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Bashore,%20Steve.jpg', 'elected', NULL),
('Suzanne Schreiber', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '70', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Schreiber,%20Suzanne.jpg', 'elected', NULL),
('T.J. Marti', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '75', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Marti,%20TJ.jpg', 'elected', NULL),
('Tammy Townley', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '48', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Townley,%20Tammy.jpg', 'elected', NULL),
('Tammy West', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '84', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Tammy-West.jpg', 'elected', NULL),
('Tim Turner', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '15', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdKW8Yps28Qqd_HZ-KGr8HDljGbqjeswJrSA&s', 'elected', NULL),
('Todd Gollihare', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '12', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Gollihare%2C%20Todd%20Flags%202022.jpg', 'elected', NULL),
('Tom Gann', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '8', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Gann,%20Tom.jpg', 'elected', NULL),
('Tom Woods', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '4', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Woods%2C%20Tom%20Flags%202022.jpg', 'elected', NULL),
('Toni Hasenbeck', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '65', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Hasenbeck,%20Toni.jpg', 'elected', NULL),
('Trey Caldwell', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '63', NULL, 'Republican', 'https://www.okhouse.gov/Members/Pictures/HiRes/Caldwell,%20Trey.jpg', 'elected', NULL),
('Trish Ranson', 'State Representative', 'Legislative Branch', 'Legislative', 'OK', '34', NULL, 'Democratic', 'https://www.okhouse.gov/Members/Pictures/HiRes/Ranson,%20Trish.jpg', 'elected', NULL),
('Warren Hamilton', 'State Senator', 'Legislative Branch', 'Legislative', 'OK', '7', NULL, 'Republican', 'https://oksenate.gov/sites/default/files/Hamilton%2C%20Warren%202022%20flags.jpg', 'elected', NULL);
