-- OR state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'OR';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Alek Skarlatos', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '4', NULL, 'Republican', 'https://storage.googleapis.com/enview-dev-public-general/legislative-people-photos/121328.jpg', 'elected', NULL),
('Andrea Valderrama', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '47', NULL, 'Democratic', 'https://www.oregonlegislature.gov/valderrama/PublishingImages/member_photo.jpg', 'elected', NULL),
('Anna Scharf', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '23', NULL, 'Republican', 'https://www.oregonlegislature.gov/scharf/PublishingImages/member_photo.jpg', 'elected', NULL),
('Annessa Hartman', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '40', NULL, 'Democratic', 'https://www.clackamas.us/sites/default/files/2021-12/annessa_hartman.jpg', 'elected', NULL),
('Anthony Broadman', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '27', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Anthony_Broadman.jpg', 'elected', NULL),
('April Dobson', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '39', NULL, 'Democratic', 'https://resources.finalsite.net/images/f_auto,q_auto,t_image_size_2/v1753906547/nclackk12orus/tvxc3ditrbsdipxxntfk/CopyofAprilDobsonPhoto2.jpg', 'elected', NULL),
('Ben Bowman', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '25', NULL, 'Democratic', 'https://www.oregonlegislature.gov/bowman/PublishingImages/member_photo.jpg', 'elected', NULL),
('Bobby Levy', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '58', NULL, 'Republican', 'https://www.oregonlegislature.gov/levy/PublishingImages/member_photo.jpg', 'elected', NULL),
('Boomer Wright', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '9', NULL, 'Republican', 'https://www.oregonlegislature.gov/wright/PublishingImages/member_photo.jpg', 'elected', NULL),
('Bruce Starr', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '12', NULL, 'Republican', 'https://www.oregonlegislature.gov/starr/PublishingImages/member_photo.jpg', 'elected', NULL),
('Cedric Hayden', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '6', NULL, 'Republican', 'https://www.oregonlegislature.gov/hayden/PublishingImages/Pages/default/Sen%20Hayden%202023%20closer.jpg', 'elected', NULL),
('Chris Gorsek', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '25', NULL, 'Democratic', 'http://www.oregonlegislature.gov/house/MemberPhotos/gorsek.jpg', 'elected', NULL),
('Christine Drazan', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '26', NULL, 'Republican', 'https://www.oregonlegislature.gov/drazan/PublishingImages/member_photo.jpg', 'elected', NULL),
('Court Boice', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '1', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Court_Boice.png', 'elected', NULL),
('Courtney Neron Misslin', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '13', NULL, 'Democratic', 'https://www.oregonlegislature.gov/neron/PublishingImages/member_photo.jpg', 'elected', NULL),
('Cyrus Javadi', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '32', NULL, 'Democratic', 'https://www.oregonlegislature.gov/javadi/PublishingImages/member_photo.jpg', 'elected', NULL),
('Dacia Grayber', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '28', NULL, 'Democratic', 'https://www.oregonlegislature.gov/grayber/PublishingImages/member_photo.jpg', 'elected', NULL),
('Daniel Nguyen', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '38', NULL, 'Democratic', 'https://www.oregonlegislature.gov/nguyend/PublishingImages/member_photo.jpg', 'elected', NULL),
('Darcey Edwards', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '31', NULL, 'Republican', 'https://www.oregonlegislature.gov/edwards/PublishingImages/member_photo.jpg', 'elected', NULL),
('Darin Harbick', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '12', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DarinHarbick.png', 'elected', NULL),
('David Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '1', NULL, 'Republican', 'https://www.oregonlegislature.gov/smithd/PublishingImages/member_photo.jpg', 'elected', NULL),
('David Gomberg', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '10', NULL, 'Democratic', 'https://www.oregonlegislature.gov/gomberg/PublishingImages/member_photo.jpg', 'elected', NULL),
('Deb Patterson', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '10', NULL, 'Democratic', 'https://www.oregonlegislature.gov/patterson/PublishingImages/member_photo.jpg', 'elected', NULL),
('Diane Linthicum', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '28', NULL, 'Republican', 'https://ormoneywatch.com/wp-content/uploads/2023/11/Diane-Linthicum-Senate-1.jpeg', 'elected', NULL),
('Dick Anderson', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '5', NULL, 'Republican', 'https://www.oregonlegislature.gov/anderson/PublishingImages/member_photo.jpg', 'elected', NULL),
('Dwayne Yunker', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '3', NULL, 'Republican', 'https://www.oregonlegislature.gov/yunker/PublishingImages/member_photo.jpg', 'elected', NULL),
('Werner Reschke', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '55', NULL, 'Republican', 'https://www.oregonlegislature.gov/reschke/PublishingImages/member_photo.jpg', 'elected', NULL),
('Ed Diehl', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '17', NULL, 'Republican', 'https://www.oregonlegislature.gov/diehl/PublishingImages/member_photo.jpg', 'elected', NULL),
('Em Levy', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '53', NULL, 'Democratic', 'https://www.oregonlegislature.gov/levye/PublishingImages/member_photo.jpg', 'elected', NULL),
('Emily McIntire', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '56', NULL, 'Republican', 'https://www.oregonlegislature.gov/mcintire/PublishingImages/member_photo.jpg', 'elected', NULL),
('Farrah Chaichi', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '35', NULL, 'Democratic', 'https://www.oregonlegislature.gov/chaichi/PublishingImages/member_photo.jpg', 'elected', NULL),
('Floyd Prozanski', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '4', NULL, 'Democratic', 'http://www.oregonlegislature.gov/senate/MemberPhotos/prozanski.jpg', 'elected', NULL),
('Fred Girod', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '9', NULL, 'Republican', 'http://www.oregonlegislature.gov/senate/MemberPhotos/girod.jpg', 'elected', NULL),
('Greg Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '57', NULL, 'Republican', 'http://www.oregonlegislature.gov/house/MemberPhotos/smithg.jpg', 'elected', NULL),
('Hai Pham', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '36', NULL, 'Democratic', 'https://www.oregonlegislature.gov/phamh/PublishingImages/member_photo.jpg', 'elected', NULL),
('James Manning', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '7', NULL, 'Democratic', 'https://www.oregonlegislature.gov/manning/PublishingImages/member_photo.jpg', 'elected', NULL),
('Jami Cate', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '11', NULL, 'Republican', 'https://www.oregonlegislature.gov/cate/PublishingImages/member_photo.jpg', 'elected', NULL),
('Janeen Sollman', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '15', NULL, 'Democratic', 'https://www.oregonlegislature.gov/sollman/PublishingImages/Pages/staff/alteza_films-66_43format.jpg', 'elected', NULL),
('Jason Kropf', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '54', NULL, 'Democratic', 'https://www.oregonlegislature.gov/kropf/PublishingImages/member_photo.jpg', 'elected', NULL),
('Jeff Golden', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '3', NULL, 'Democratic', 'https://www.oregonlegislature.gov/golden/PublishingImages/member_photo.jpg', 'elected', NULL),
('Jeff Helfrich', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '52', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api/storage/uploads/thumbs/200/300/crop/best/Jeffrey_Helfrich.jpg', 'elected', NULL),
('John Lively', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '7', NULL, 'Democratic', 'https://www.oregonlegislature.gov/lively/PublishingImages/member_photo.jpg', 'elected', NULL),
('Jules Walters', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '37', NULL, 'Democratic', 'https://www.oregonlegislature.gov/house/MemberPhotos/walters.jpg', 'elected', NULL),
('Julie Fahey', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '14', NULL, 'Democratic', 'https://www.oregonlegislature.gov/fahey/PublishingImages/member_photo.jpg', 'elected', NULL),
('Kate Lieber', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '14', NULL, 'Democratic', 'https://www.oregonlegislature.gov/lieber/PublishingImages/member_photo.jpg', 'elected', NULL),
('Kathleen Taylor', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '21', NULL, 'Democratic', 'https://www.oregonlegislature.gov/taylor/PublishingImages/member_photo.jpg', 'elected', NULL),
('Kayse Jama', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '24', NULL, 'Democratic', 'https://www.oregonlegislature.gov/Jama/PublishingImages/member_photo.jpg', 'elected', NULL),
('Ken Helm', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '27', NULL, 'Democratic', 'https://www.oregonlegislature.gov/helm/PublishingImages/HD18-784-Edit.jpg', 'elected', NULL),
('Kevin Mannix', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '21', NULL, 'Republican', 'https://www.oregonlegislature.gov/mannix/PublishingImages/member_photo.jpg', 'elected', NULL),
('Khanh Pham', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '23', NULL, 'Democratic', 'https://www.oregonlegislature.gov/pham/PublishingImages/member_photo.jpg', 'elected', NULL),
('Kim Thatcher', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '11', NULL, 'Republican', 'https://www.oregonlegislature.gov/thatcher/PublishingImages/thatcher2023.jpg', 'elected', NULL),
('Kim Wallan', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '6', NULL, 'Republican', 'https://www.oregonlegislature.gov/wallan/PublishingImages/member_photo.jpg', 'elected', NULL),
('Lamar Wise', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '48', NULL, 'Democratic', 'https://www.oregonlegislature.gov/wise/PublishingImages/member_photo.jpg', 'elected', NULL),
('Lesly Muñoz', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '22', NULL, 'Democratic', 'https://www.oregonlegislature.gov/munoz/PublishingImages/member_photo.jpg', 'elected', NULL),
('Lew Frederick', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '22', NULL, 'Democratic', 'https://www.oregonlegislature.gov/frederick/PublishingImages/member_photo.jpg', 'elected', NULL),
('Lisa Fragala', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '8', NULL, 'Democratic', 'https://www.oregonlegislature.gov/fragala/PublishingImages/member_photo.jpg', 'elected', NULL),
('Lisa Reynolds', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '17', NULL, 'Democratic', 'https://www.oregonlegislature.gov/reynolds/PublishingImages/member_photo.jpg', 'elected', NULL),
('Lucetta Elmer', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '24', NULL, 'Republican', 'https://www.oregonlegislature.gov/elmer/PublishingImages/member_photo.jpg', 'elected', NULL),
('Mari Watanabe', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '34', NULL, 'Democratic', 'https://www.oregonlive.com/resizer/v2/NV2ILLLSBNAY7DMKF7SP6EY5UU.jpeg?auth=2bd1feb1c12fa2e0f581e2670cead324d4c2e630233f41037e778e6ade02f6cf&width=1280&quality=90', 'elected', NULL),
('Mark Gamba', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '41', NULL, 'Democratic', 'https://www.oregonlegislature.gov/gamba/PublishingImages/member_photo.jpg', 'elected', NULL),
('Mark Meek', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '20', NULL, 'Democratic', 'https://www.oregonlegislature.gov/meek/PublishingImages/member_photo.jpg', 'elected', NULL),
('Mark Owens', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '60', NULL, 'Republican', 'https://www.oregonlegislature.gov/owens/PublishingImages/member_photo.jpg', 'elected', NULL),
('Matt Bunch', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '51', NULL, 'Republican', 'https://www.oregonlegislature.gov/bunch/PublishingImages/member_photo.jpg', 'elected', NULL),
('Mike McLane', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '30', NULL, 'Republican', 'http://www.oregonlegislature.gov/house/MemberPhotos/mclane.jpg', 'elected', NULL),
('Nancy Nathanson', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '13', NULL, 'Democratic', 'https://www.oregonlegislature.gov/nathanson/PublishingImages/member_photo.jpg', 'elected', NULL),
('Nathan Sosa', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '30', NULL, 'Democratic', 'https://www.oregonlegislature.gov/sosa/PublishingImages/member_photo.jpg', 'elected', NULL),
('Noah Robinson', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '2', NULL, 'Republican', 'https://ormoneywatch.b-cdn.net/wp-content/uploads/2023/11/Noah-Robinson.jpg', 'elected', NULL),
('Pam Marsh', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '5', NULL, 'Democratic', 'https://www.oregonlegislature.gov/marsh/PublishingImages/member_photo.jpg', 'elected', NULL),
('Paul Evans', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '20', NULL, 'Democratic', 'https://www.oregonlegislature.gov/evans/PublishingImages/member_photo.jpg', 'elected', NULL),
('Rick Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '18', NULL, 'Republican', 'https://www.oregonlegislature.gov/lewis/PublishingImages/member_photo.jpg', 'elected', NULL),
('Ricki Ruiz', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '50', NULL, 'Democratic', 'https://www.oregonlegislature.gov/ruiz/PublishingImages/member_photo.jpg', 'elected', NULL),
('Rob Nosse', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '42', NULL, 'Democratic', 'http://www.oregonlegislature.gov/house/MemberPhotos/nosse.jpg', 'elected', NULL),
('Rob Wagner', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '19', NULL, 'Democratic', 'https://www.oregonlegislature.gov/wagner/PublishingImages/Headshot%20in%20the%20shrub.jpg', 'elected', NULL),
('Sara Gelser Blouin', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '8', NULL, 'Democratic', 'http://www.oregonlegislature.gov/senate/MemberPhotos/gelser.jpg', 'elected', NULL),
('Sarah McDonald', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '16', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Sarah_McDonald.jpg', 'elected', NULL),
('Shannon Isadore', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '33', NULL, 'Democratic', 'https://www.oregonlegislature.gov/isadore/PublishingImages/member_photo.jpg', 'elected', NULL),
('Shelly Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '15', NULL, 'Republican', 'https://www.oregonlegislature.gov/boshartdavis/PublishingImages/member_photo.jpg', 'elected', NULL),
('Sue Rieke Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '26', NULL, 'Democratic', 'https://www.oregonlegislature.gov/riekesmith/PublishingImages/member_photo.jpg', 'elected', NULL),
('Susan McLain', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '29', NULL, 'Democratic', 'https://www.oregonlegislature.gov/mclain/PublishingImages/member_photo.jpg', 'elected', NULL),
('Suzanne Weber', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '16', NULL, 'Republican', 'https://www.oregonlegislature.gov/weber/PublishingImages/member_photo.jpg', 'elected', NULL),
('Tawna Sanchez', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '43', NULL, 'Democratic', 'https://www.oregonlegislature.gov/sanchez/PublishingImages/member_photo.jpg', 'elected', NULL),
('Thuy Tran', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '45', NULL, 'Democratic', 'https://www.oregonlegislature.gov/tran/PublishingImages/member_photo.jpg', 'elected', NULL),
('Todd Nash', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '29', NULL, 'Republican', 'https://www.oregonlegislature.gov/nash/PublishingImages/member_photo.jpg', 'elected', NULL),
('Tom Andersen', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '19', NULL, 'Democratic', 'https://www.oregonlegislature.gov/andersen/PublishingImages/member_photo.jpg', 'elected', NULL),
('Travis Nelson', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '44', NULL, 'Democratic', 'https://www.oregonlegislature.gov/nelson/PublishingImages/member_photo.jpg', 'elected', NULL),
('Vikki Breese Iverson', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '59', NULL, 'Republican', 'https://www.oregonlegislature.gov/breese-iverson/PublishingImages/member_photo.jpg', 'elected', NULL),
('Virgle Osborne', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '2', NULL, 'Republican', 'https://www.oregonlegislature.gov/osborne/PublishingImages/member_photo.jpg', 'elected', NULL),
('Willy Chotzen', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '46', NULL, 'Democratic', 'https://www.oregonlegislature.gov/chotzen/PublishingImages/member_photo.jpg', 'elected', NULL),
('Wlnsvey Campos', 'State Senator', 'Legislative Branch', 'Legislative', 'OR', '18', NULL, 'Democratic', 'https://www.oregonlegislature.gov/campos/PublishingImages/member_photo.jpg', 'elected', NULL),
('Zach Hudson', 'State Representative', 'Legislative Branch', 'Legislative', 'OR', '49', NULL, 'Democratic', 'https://www.oregonlegislature.gov/hudson/PublishingImages/member_photo.jpg', 'elected', NULL);
