-- RI state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'RI';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Alana DiMario', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '36', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/pictures/dimario.jpg', 'elected', NULL),
('Alex Marszalkowski', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '52', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/marszalkowski.jpg', 'elected', NULL),
('Alex Finkelman', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '74', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/Pictures/Alex%20Finkelman.jpg', 'elected', NULL),
('Ana Quezada', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '2', NULL, 'Democratic', 'http://www.rilegislature.gov/senators/pictures/quezada.jpg', 'elected', NULL),
('Andrew Dimitri', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '25', NULL, 'Democratic', 'https://assets.civicengine.com/uploads/candidate/headshot/830447/830447.jpg', 'elected', NULL),
('Anthony DeSimone', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '5', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/Pictures/DeSimone.jpg', 'elected', NULL),
('Arthur Handy', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '18', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/handy.jpg', 'elected', NULL),
('Doc Corvese', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '55', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/corvese.jpg', 'elected', NULL),
('Brandon Potter', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '16', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/potter.jpg', 'elected', NULL),
('Brandon Voas', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '57', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/Pictures/Brandon%20Voas.jpg', 'elected', NULL),
('Brian Newberry', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '48', NULL, 'Republican', 'http://www.rilegislature.gov/representatives/pictures/newberry.jpg', 'elected', NULL),
('Brian Kennedy', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '38', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/kennedy.jpg', 'elected', NULL),
('Brian Thompson', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '20', NULL, 'Democratic', 'https://assets.civicengine.com/uploads/candidate/headshot/830443/830443.jpg', 'elected', NULL),
('Bridget Valverde', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '35', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/valverde.jpg', 'elected', NULL),
('Carol McEntee', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '33', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/McEntee.jpg', 'elected', NULL),
('Charlene Lima', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '14', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/lima.jpg', 'elected', NULL),
('Cherie Cruz', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '58', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/Pictures/Cruz%20preferred%20pic.jpg', 'elected', NULL),
('Chris Paplauskas', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '15', NULL, 'Republican', 'https://www.cranstonri.gov/_resources/common/userfiles/image/IMG-0103.JPG', 'elected', NULL),
('Chris Blazejewski', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '2', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/blazejewski.jpg', 'elected', NULL),
('David Bennett', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '20', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/bennett.jpg', 'elected', NULL),
('David Place', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '47', NULL, 'Republican', 'http://www.rilegislature.gov/representatives/pictures/place.jpg', 'elected', NULL),
('David Morales', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '7', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/Morales.JPG', 'elected', NULL),
('David Tikoian', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '22', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/Tikoian%202023.jpg', 'elected', NULL),
('Dawn Euer', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '13', NULL, 'Democratic', 'http://www.rilegislature.gov/senators/pictures/euer.jpg', 'elected', NULL),
('Deb Fellela', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '43', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/fellela.jpg', 'elected', NULL),
('Dick Fascia', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '42', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Richard_Fascia_20240808_092707.png', 'elected', NULL),
('Earl Read', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '26', NULL, 'Democratic', 'https://bloximages.newyork1.vip.townnews.com/ricentral.com/content/tncms/assets/v3/editorial/4/30/4303801c-a298-11ef-872c-ffd5089fe627/67360f284e7b9.image.jpg?resize=415%2C500', 'elected', NULL),
('Edith Ajello', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '1', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/ajello.jpg', 'elected', NULL),
('Elaine Morgan', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '34', NULL, 'Republican', 'http://www.rilegislature.gov/Senators/Pictures/morgan.jpg', 'elected', NULL),
('Enrique Sanchez', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '9', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/Pictures/Sanchez.jpg', 'elected', NULL),
('Evan Shanley', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '24', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/shanley.jpg', 'elected', NULL),
('Frank Ciccone', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '7', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/ciccone.jpg', 'elected', NULL),
('George Nardone', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '28', NULL, 'Republican', 'http://www.rilegislature.gov/representatives/pictures/nardone.jpg', 'elected', NULL),
('Gordon Rogers', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '21', NULL, 'Republican', 'https://www.rilegislature.gov/LegislationPictures/gordon_rogers.jpg', 'elected', NULL),
('Grace Diaz', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '11', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/diaz.jpg', 'elected', NULL),
('Greg Costantino', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '44', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/costantino.jpg', 'elected', NULL),
('Hanna Gallo', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '27', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/gallo.jpg', 'elected', NULL),
('Jake Bissaillon', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '1', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/62d5679913ecdf027fe552fe/d50030ca-d566-4d1d-a60a-8f2ddb95b187/Jake+Bissaillon+Cropped+background.jpg', 'elected', NULL),
('Jackie Baginski', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '17', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/Baginski.jpg', 'elected', NULL),
('Jason Knight', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '67', NULL, 'Democratic', 'https://www.jasonknightlaw.com/wp-content/uploads/2025/01/about-img.webp', 'elected', NULL),
('Jenni Furtado', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '64', NULL, 'Democratic', 'https://rhodeislandcurrent.com/wp-content/uploads/2024/09/272274786_329286515874430_6351954859366181023_n-1-1024x1024.jpg', 'elected', NULL),
('Jennifer Stewart', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '59', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/Pictures/Stewart.jpg', 'elected', NULL),
('Jennifer Boylan', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '66', NULL, 'Democratic', 'https://www.rilegislature.gov/LegislationPictures/jennifer_boylan.jpg', 'elected', NULL),
('Jessica de la Cruz', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '23', NULL, 'Republican', 'http://www.rilegislature.gov/Senators/Pictures/de%20la%20cruz%20NEW%202022.jpg', 'elected', NULL),
('Jay Edwards', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '70', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/edwards.jpg', 'elected', NULL),
('John Lombardi', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '8', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/lombardi.jpg', 'elected', NULL),
('John Burke', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '9', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/pictures/burke.jpg', 'elected', NULL),
('Jon Brien', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '49', NULL, 'Independent', 'https://www.rilegislature.gov/representatives/Pictures/Brien.jpg', 'elected', NULL),
('Jonathon Acosta', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '16', NULL, 'Democratic', 'https://d2gjqh9j26unp0.cloudfront.net/profilepic/35446a34e894fdf32e04c9a2069c7915', 'elected', NULL),
('Jose Batista', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '12', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/batista.jpg', 'elected', NULL),
('Joseph Solomon', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '22', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/solomon.jpg', 'elected', NULL),
('Joseph McNamara', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '19', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/mcnamara.jpg', 'elected', NULL),
('Joshua Giraldo', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '56', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/Giraldo.jpg', 'elected', NULL),
('Julie Casimiro', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '31', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/casimiro.jpg', 'elected', NULL),
('June Speakman', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '68', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/speakman.jpg', 'elected', NULL),
('Justine Caldwell', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '30', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/caldwell.jpg', 'elected', NULL),
('Joe Shekarchi', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '23', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/shekarchi.jpg', 'elected', NULL),
('Karen Alzate', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '60', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/alzate.jpg', 'elected', NULL),
('Katie Kazarian', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '63', NULL, 'Democratic', 'https://www.rilegislature.gov/LegislationPictures/katherine_kazarian.jpg', 'elected', NULL),
('Kathleen Fogarty', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '35', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/fogarty.jpg', 'elected', NULL),
('Lammis Vargas', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '28', NULL, 'Democratic', 'https://lammisvargas.com/wp-content/uploads/2024/07/Lammis-Headshot-1536x1536.jpg', 'elected', NULL),
('Lauren Carson', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '75', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/carson.jpg', 'elected', NULL),
('Leo Felix', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '61', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/Felix.jpg', 'elected', NULL),
('Lou Raptakis', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '33', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/raptakis.jpg', 'elected', NULL),
('Linda Ujifusa', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '11', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/Ujifusa%20FINAL.jpg', 'elected', NULL),
('Lori Urso', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '8', NULL, 'Democratic', 'https://rhodeislandcurrent.com/wp-content/uploads/2024/09/1-Lori-Urso-09.24-1024x776.jpg', 'elected', NULL),
('Lou DiPalma', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '12', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/dipalma.jpg', 'elected', NULL),
('Marie Hopkins', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '21', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MarieHopkins.jpg', 'elected', NULL),
('Mark McKenney', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '30', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/McKenney%202023.jpg', 'elected', NULL),
('Marvin Abney', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '73', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/abney.jpg', 'elected', NULL),
('Mary Ann Shallcross-Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '46', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/shallcross%20smith.jpg', 'elected', NULL),
('Mary Messier', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '62', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/messier.jpg', 'elected', NULL),
('Matt LaMountain', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '31', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/LaMountain%202023.jpg', 'elected', NULL),
('Matthew Dawson', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '65', NULL, 'Democratic', 'https://www.lynchpine.com/wp-content/uploads/sites/1101520/2020/04/dawson_matthew_s.jpg', 'elected', NULL),
('Megan Cotter', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '39', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/Pictures/Cotter.jpg', 'elected', NULL),
('Meghan Kallman', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '15', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/pictures/kallman.jpg', 'elected', NULL),
('Melissa Murray', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '24', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/murray.jpg', 'elected', NULL),
('Mia Ackerman', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '45', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/ackerman.jpg', 'elected', NULL),
('Mike Chippendale', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '40', NULL, 'Republican', 'http://www.rilegislature.gov/representatives/pictures/chippendale.jpg', 'elected', NULL),
('Michelle McGaw', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '71', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/mcgaw.jpg', 'elected', NULL),
('Nathan Biah', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '3', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/biah.jpg', 'elected', NULL),
('Pam Lauria', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '32', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/Lauria%202023.jpg', 'elected', NULL),
('Pat Serpa', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '27', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/serpa.jpg', 'elected', NULL),
('Paul Santucci', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '53', NULL, 'Republican', 'https://static.votesmart.org/static/canphoto/195096.jpg', 'elected', NULL),
('Pete Appollonio', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '29', NULL, 'Democratic', 'https://www.rilegislature.gov/LegislationPictures/peter_appollonio.jpg', 'elected', NULL),
('Ramon Perez', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '13', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/perez.jpg', 'elected', NULL),
('Raymond Hull', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '6', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/hull.jpg', 'elected', NULL),
('Rebecca Kislak', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '4', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/kislak.jpg', 'elected', NULL),
('Bob Phillips', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '51', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/pictures/phillips.jpg', 'elected', NULL),
('Robert Craven', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '32', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/craven.jpg', 'elected', NULL),
('Bob Quattrocchi', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '41', NULL, 'Republican', 'https://www.rilegislature.gov/LegislationPictures/robert_quattrocchi.jpg', 'elected', NULL),
('Bob Britto', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '18', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/Britto%202023.jpg', 'elected', NULL),
('Ryan Pearson', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '19', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/pearson.jpg', 'elected', NULL),
('Sam Azzinaro', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '37', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/azzinaro.jpg', 'elected', NULL),
('Sam Zurier', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '3', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/Zurier-2022.jpg?csf=1&e=5y4LAP', 'elected', NULL),
('Sam Bell', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '5', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/bell.jpg', 'elected', NULL),
('Scott Slater', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '10', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/slater.jpg', 'elected', NULL),
('Sherry Roberts', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '29', NULL, 'Republican', 'http://www.rilegislature.gov/representatives/pictures/roberts.jpg', 'elected', NULL),
('Stefano Famiglietti', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '4', NULL, 'Democratic', 'https://www.rilegislature.gov/LegislationPictures/stefano_famiglietti.jpg', 'elected', NULL),
('Stephen Casey', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '50', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/casey.jpg', 'elected', NULL),
('Susan Donovan', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '69', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/Pictures/donovan.jpg', 'elected', NULL),
('Teresa Tanzi', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '34', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/tanzi.jpg', 'elected', NULL),
('Terri Cortvriend', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '72', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/cortvriend.jpg', 'elected', NULL),
('Tom Noret', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '25', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/noret.jpg', 'elected', NULL),
('Thomas Paolino', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '17', NULL, 'Republican', 'https://www.rilegislature.gov/senators/Pictures/Paolino%202022.jpg', 'elected', NULL),
('Tiara Mack', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '6', NULL, 'Democratic', 'https://media3.s-nbcnews.com/j/newscms/2020_47/3429284/201118-MAIN-tiara-mack-benjamin-branchaud-ew-1140a_41fc9dcc361b3077b5b335fab1dc4a55.fit-760w.jpg', 'elected', NULL),
('Tina Spears', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '36', NULL, 'Democratic', 'https://www.rilegislature.gov/representatives/Pictures/Tina%20Spears.jpg', 'elected', NULL),
('Todd Patalano', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '26', NULL, 'Democratic', 'https://rilegislature.gov/LegislationPictures/todd_patalano.jpg', 'elected', NULL),
('Sue Sosnowski', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '37', NULL, 'Democratic', 'http://www.rilegislature.gov/Senators/Pictures/sosnowski.jpg', 'elected', NULL),
('Val Lawson', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '14', NULL, 'Democratic', 'https://www.rilegislature.gov/LegislationPictures/valarie_lawson.jpg', 'elected', NULL),
('Victoria Gu', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '38', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/Gu%202023.jpg', 'elected', NULL),
('Walter Felag', 'State Senator', 'Legislative Branch', 'Legislative', 'RI', '10', NULL, 'Democratic', 'https://www.rilegislature.gov/senators/Pictures/Felag%202023.jpg', 'elected', NULL),
('Bill O''Brien', 'State Representative', 'Legislative Branch', 'Legislative', 'RI', '54', NULL, 'Democratic', 'http://www.rilegislature.gov/representatives/pictures/o''brien.jpg', 'elected', NULL);
