-- SC state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'SC';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Shane Massey', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '25', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1185227131.jpg', 'elected', NULL),
('Adam Duncan', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '2', NULL, 'Republican', 'https://bloximages.chicago2.vip.townnews.com/upstatetoday.com/content/tncms/assets/v3/editorial/2/db/2dbe7f98-2879-11ef-8c0d-7356b5095dbe/66692c7a1bcf4.image.jpg?crop=1045%2C588%2C12%2C42&resize=1045%2C588&order=crop%2Cresize', 'elected', NULL),
('Allen Blackmon', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '27', NULL, 'Republican', 'https://scdailygazette.com/wp-content/uploads/2024/06/image000001-682x1024.jpg', 'elected', NULL),
('Annie McDaniel', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '41', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1221590763.jpg', 'elected', NULL),
('April Cromer', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '6', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0434090857.jpg', 'elected', NULL),
('Beth Bernstein', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '78', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0141477256.jpg', 'elected', NULL),
('Bill Taylor', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '86', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1811363419.jpg', 'elected', NULL),
('Billy Garrett', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '10', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0638636287.jpg', 'elected', NULL),
('Blake Sanders', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '9', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/BlakeSanders24.jpg', 'elected', NULL),
('Brad Hutto', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '40', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0912499891.jpg', 'elected', NULL),
('Brandon Guffey', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '48', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0730681731.jpg', 'elected', NULL),
('Brandon Cox', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '92', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0428124949.jpg', 'elected', NULL),
('Brandon Newton', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '45', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1418607785.jpg', 'elected', NULL),
('Brian Adams', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '44', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0002272727.jpg', 'elected', NULL),
('Bruce Bannister', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '24', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0103409079.jpg', 'elected', NULL),
('Cal Forrest', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '39', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0608238564.jpg', 'elected', NULL),
('Carl Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '103', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0021590907.jpg', 'elected', NULL),
('Carla Schuessler', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '61', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1635227077.jpg', 'elected', NULL),
('Carlisle Kennedy', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '23', NULL, 'Republican', 'https://votecarlislekennedy.com/wp-content/uploads/2024/04/MG_3387-scaled.jpg', 'elected', NULL),
('Chandra Dillard', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '23', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0479545397.jpg', 'elected', NULL),
('Charlie Hartz', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '81', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/postandcourier.com/content/tncms/assets/v3/editorial/6/dd/6ddc9b30-8988-11ef-9d6e-abf6ce2aa967/62e03fbeba019.image.jpg?crop=724%2C987%2C710%2C3&resize=367%2C500&order=crop%2Cresize', 'elected', NULL),
('Chris Huff', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '28', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/817554/817554.jpg', 'elected', NULL),
('Chris Wooten', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '69', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1978408854.jpg', 'elected', NULL),
('Chris Hart', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '73', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0770454453.jpg', 'elected', NULL),
('Cody Mitchell', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '65', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1344033930.jpg', 'elected', NULL),
('Courtney Waters', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '113', NULL, 'Democratic', 'https://courtneywaters.com/wp-content/uploads/2024/11/courtney-waters.jpg', 'elected', NULL),
('Craig Gagnon', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '11', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0632954470.jpg', 'elected', NULL),
('Danny Verdin', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '9', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1874999775.jpg', 'elected', NULL),
('Daniel Gibson', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '12', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0667045375.jpg', 'elected', NULL),
('Darrell Jackson', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '21', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0920454435.jpg', 'elected', NULL),
('David Martin', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '26', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/David_Martin_20240907_125219.jpeg', 'elected', NULL),
('Davey Hiott', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '4', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0848863535.jpg', 'elected', NULL),
('David Vaughan', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '27', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1865908867.jpg', 'elected', NULL),
('Dennis Moss', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '29', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1379545289.jpg', 'elected', NULL),
('Deon Tedder', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '42', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1811931601.jpg', 'elected', NULL),
('Dianne Mitchell', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '21', NULL, 'Republican', NULL, 'elected', NULL),
('Don Chapman', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '8', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0347727231.jpg', 'elected', NULL),
('Ryan McCabe', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '96', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1206818037.jpg', 'elected', NULL),
('Ed Sutton', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '20', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Ed_Sutton2024.jpg', 'elected', NULL),
('Spencer Wetmore', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '115', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1905681590.jpg', 'elected', NULL),
('Everett Stubbs', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '17', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/817690/817690.jpg', 'elected', NULL),
('Fawn Pedalino', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '64', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1453408917.jpg', 'elected', NULL),
('Murrell Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '67', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1703408887.jpg', 'elected', NULL),
('Gary Brewer', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '114', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0192045432.jpg', 'elected', NULL),
('Chip Campsen', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '43', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0302272691.jpg', 'elected', NULL),
('Gil Gatch', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '94', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0658522648.jpg', 'elected', NULL),
('Gilda Cobb-Hunter', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '95', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0372727228.jpg', 'elected', NULL),
('Greg Ford', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '98', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0605681746.jpg', 'elected', NULL),
('Greg Hembree', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '28', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0819318084.jpg', 'elected', NULL),
('Hamilton Grant', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '79', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/HamiltonGrant2024.jpeg', 'elected', NULL),
('Harriet Holman', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '102', NULL, 'Republican', 'https://static.wixstatic.com/media/8accea_e11fd53b395c467b9a13c9643ee9b49f~mv2.jpg', 'elected', NULL),
('Harvey Peeler', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '14', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1454545280.jpg', 'elected', NULL),
('Heath Sessions', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '46', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1649715712.jpg', 'elected', NULL),
('Heather Crawford', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '68', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0428977222.jpg', 'elected', NULL),
('Heather Bauer', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '75', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0125568167.jpg', 'elected', NULL),
('David Weeks', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '51', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1898863409.jpg', 'elected', NULL),
('Todd Rutherford', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '74', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1614772534.jpg', 'elected', NULL),
('J.A. Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '15', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1356818019.jpg', 'elected', NULL),
('J.D. Chaplin', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '29', NULL, 'Republican', 'https://npr.brightspotcdn.com/dims4/default/533a1d5/2147483647/strip/true/crop/1761x1084+0+0/resize/1760x1084!/format/webp/quality/90/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fde%2F35%2F0ec3711f4b1ab8064a0a54363740%2Fchaplin.JPG', 'elected', NULL),
('Jackie Hayes', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '55', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0802272631.jpg', 'elected', NULL),
('Jackie Terribile', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '66', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jackie_Terribile.jpeg', 'elected', NULL),
('Mike Neese', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '44', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1403977105.jpg', 'elected', NULL),
('Mike Burns', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '17', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0257954515.jpg', 'elected', NULL),
('James Teeple', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '116', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/James_Teeple_20240908_101043.jpg', 'elected', NULL),
('Jason Elliott', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '6', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0529545391.jpg', 'elected', NULL),
('Jason Luck', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '54', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jason_Luck1.png', 'elected', NULL),
('Jeff Zell', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '36', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jeffrey_Zell.jpg', 'elected', NULL),
('Jeff Bradley', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '123', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0171590889.jpg', 'elected', NULL),
('Jeff Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '58', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0938636251.jpg', 'elected', NULL),
('Jeffrey Graham', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '35', NULL, 'Democratic', 'https://www.grahamrealtyinc.com/files/images/agents/g/4d80bc35-8f04-43ab-84f1-1858ae7a8b42/1.jpg', 'elected', NULL),
('Jermaine Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '52', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0943181705.jpg', 'elected', NULL),
('Jerry Govan', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '93', NULL, 'Democratic', 'https://www.scstatehouse.gov/images/members/0702272643.jpg', 'elected', NULL),
('Jay Kilmartin', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '85', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0993323745.jpg', 'elected', NULL),
('John Lastinger', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '88', NULL, 'Republican', NULL, 'elected', NULL),
('John McCravy', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '13', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1217045309.jpg', 'elected', NULL),
('John King', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '49', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1002272607.jpg', 'elected', NULL),
('Jordan Pace', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '117', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1433984204.jpg', 'elected', NULL),
('Joe Bustos', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '112', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0278409057.jpg', 'elected', NULL),
('Joe White', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '40', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1912499771.jpg', 'elected', NULL),
('Josh Kimbrell', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '11', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0993465790.jpg', 'elected', NULL),
('Josiah Magnuson', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '38', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1130965774.jpg', 'elected', NULL),
('Justin Bamberg', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '90', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0102840897.jpg', 'elected', NULL),
('Kambrell Garvin', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '77', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0657954467.jpg', 'elected', NULL),
('Karl Allen', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '7', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0015340908.jpg', 'elected', NULL),
('Kathy Landing', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '80', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1066477145.jpg', 'elected', NULL),
('Keishan Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '50', NULL, 'Democratic', NULL, 'elected', NULL),
('Kent Williams', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '30', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1938636131.jpg', 'elected', NULL),
('Kevin Hardee', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '105', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0743749911.jpg', 'elected', NULL),
('Larry Grooms', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '37', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0729545367.jpg', 'elected', NULL),
('Lee Bright', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '12', NULL, 'Republican', 'http://www.scstatehouse.gov/images/members/0193181795.jpg', 'elected', NULL),
('Lee Gilreath', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '7', NULL, 'Republican', 'https://lirp.cdn-website.com/4c846247/dms3rep/multi/opt/_DSC0892-a9d9c1ff-1920w.jpg', 'elected', NULL),
('Lee Hewitt', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '108', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0834658991.jpg', 'elected', NULL),
('Doug Gilliam', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '42', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0675426055.jpg', 'elected', NULL),
('Leon Howard', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '76', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0879545349.jpg', 'elected', NULL),
('Leon Stavrinakis', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '119', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1747727063.jpg', 'elected', NULL),
('Lonnie Hosey', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '91', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0874999895.jpg', 'elected', NULL),
('Lucas Atkinson', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '57', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0066477265.jpg', 'elected', NULL),
('Luke Rankin', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '33', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1511363455.jpg', 'elected', NULL),
('Luke Rankin', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '14', NULL, 'Republican', 'https://lirp.cdn-website.com/44a83ceb/dms3rep/multi/opt/P1011798-1920w.jpg', 'elected', NULL),
('Brian Lawson', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '30', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1067613508.jpg', 'elected', NULL),
('Margie Bright Matthews', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '45', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0194318159.jpg', 'elected', NULL),
('Mark Willis', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '16', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1942613404.jpg', 'elected', NULL),
('Mark Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '99', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1724999793.jpg', 'elected', NULL),
('Matt Leber', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '41', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1074431690.jpg', 'elected', NULL),
('Melissa Oremus', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '84', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1432386192.jpg', 'elected', NULL),
('Micah Caskey', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '89', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0329545415.jpg', 'elected', NULL),
('Michael Rivers', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '121', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1564346404.jpg', 'elected', NULL),
('Michael Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '16', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0949431704.jpg', 'elected', NULL),
('Mike Gambrell', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '4', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0635227197.jpg', 'elected', NULL),
('Mike Reichenbach', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '31', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1528408908.jpg', 'elected', NULL),
('Nathan Ballentine', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '71', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0102272715.jpg', 'elected', NULL),
('Neal Collins', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '5', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0388636317.jpg', 'elected', NULL),
('Overture Walker', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '22', NULL, 'Democratic', 'https://overture4scsenate.com/wp-content/uploads/2024/05/Screenshot-2024-05-09-at-12.12.03%E2%80%AFPM-813x1024.png', 'elected', NULL),
('Patrick Haddon', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '19', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0733806731.jpg', 'elected', NULL),
('Paul Wickensimer', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '22', NULL, 'Republican', 'https://static.wixstatic.com/media/669915_0fcf6e9fdd9e484b959c5ec5b9c80ce2~mv2.jpg/v1/fill/w_489,h_982,al_l,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/669915_0fcf6e9fdd9e484b959c5ec5b9c80ce2~mv2.jpg', 'elected', NULL),
('Paula Calhoon', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '87', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0293181783.jpg', 'elected', NULL),
('Phillip Bowers', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '3', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Phillip_Bowers.PNG', 'elected', NULL),
('Phillip Lowe', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '60', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1125568047.jpg', 'elected', NULL),
('Rex Rice', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '2', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1547727087.jpg', 'elected', NULL),
('Richard Cash', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '3', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0328409052.jpg', 'elected', NULL),
('Richie Yow', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '53', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1998863577.jpg', 'elected', NULL),
('Robby Robbins', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '97', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1565340722.jpg', 'elected', NULL),
('Rob Harris', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '36', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0764772636.jpg', 'elected', NULL),
('Robert Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '62', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1942045222.jpg', 'elected', NULL),
('Robert Reese', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '70', NULL, 'Democratic', 'https://i0.wp.com/robertreeseforsc70.com/wp-content/uploads/2024/05/Rob_Marketing_-08-removebg-preview.png?w=408&ssl=1', 'elected', NULL),
('Roger Kirby', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '101', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1006818061.jpg', 'elected', NULL),
('Ronnie Sabb', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '32', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1617045261.jpg', 'elected', NULL),
('Ronnie Cromer', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '18', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0438636311.jpg', 'elected', NULL),
('Rosalyn Henderson-Myers', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '31', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0824999901.jpg', 'elected', NULL),
('Ross Turner', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '8', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1847727051.jpg', 'elected', NULL),
('Russell Ott', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '26', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1433096420.jpg', 'elected', NULL),
('Sarita Edgerton', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '34', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/SaritaEdgerton2024.jpeg', 'elected', NULL),
('Scott Montgomery', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '32', NULL, 'Republican', 'https://static.wixstatic.com/media/78a712_6c314e5806da4a328efc91387de831c7~mv2.jpg/v1/fill/w_321,h_446,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/DSC_6157-Edit.jpg', 'elected', NULL),
('Sean Bennett', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '38', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0141193165.jpg', 'elected', NULL),
('Seth Rose', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '72', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/1584090719.jpg', 'elected', NULL),
('Shane Martin', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '13', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1179545313.jpg', 'elected', NULL),
('Shannon Erickson', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '124', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0539772663.jpg', 'elected', NULL),
('Stephen Frank', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '20', NULL, 'Republican', 'https://votestephenfrank.com/wp-content/uploads/2024/05/430804199_10168719229715314_3862493250670651338_n.jpg', 'elected', NULL),
('Stephen Goldfinch', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '34', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0682386282.jpg', 'elected', NULL),
('Steven Long', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '37', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1120454411.jpg', 'elected', NULL),
('Sylleste Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '100', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0456249946.jpg', 'elected', NULL),
('Alan Morgan', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '18', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1374999835.jpg', 'elected', NULL),
('Tameika Isaac Devine', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '19', NULL, 'Democratic', NULL, 'elected', NULL),
('Terry Alexander', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '59', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0011363635.jpg', 'elected', NULL),
('Thomas Beach', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '10', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0129545439.jpg', 'elected', NULL),
('Tom Alexander', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '1', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0013636362.jpg', 'elected', NULL),
('Case Brittain', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '107', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0202272703.jpg', 'elected', NULL),
('Tom Corbin', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '5', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0402272679.jpg', 'elected', NULL),
('Val Guest', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '106', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0730113549.jpg', 'elected', NULL),
('Tommy Pope', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '47', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1484090731.jpg', 'elected', NULL),
('Tom Hartnett', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '110', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0774999907.jpg', 'elected', NULL),
('Randy Ligon', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '43', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1087499870.jpg', 'elected', NULL),
('Tiffany Spann-Wilder', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '109', NULL, 'Democratic', NULL, 'elected', NULL),
('Tim McGinnis', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '56', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1256818031.jpg', 'elected', NULL),
('Tom Davis', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '46', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0456818127.jpg', 'elected', NULL),
('Tom Fernandez', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '39', NULL, 'Republican', 'https://tomfernandezforsenate.com/wp-content/uploads/2023/03/tom-fernandez-headshot-2-957x1024.png', 'elected', NULL),
('Tom Young', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '24', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1996590730.jpg', 'elected', NULL),
('Travis Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '33', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1365908927.jpg', 'elected', NULL),
('Jay Jordan', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '63', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0957954431.jpg', 'elected', NULL),
('Wendell Gilliard', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '111', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0675568101.jpg', 'elected', NULL),
('Wendell Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '25', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0953408977.jpg', 'elected', NULL),
('Wes Climer', 'State Senator', 'Legislative Branch', 'Legislative', 'SC', '15', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0356818139.jpg', 'elected', NULL),
('Bill Clyburn', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '82', NULL, 'Democratic', 'https://scstatehouse.gov/images/members/0363636320.jpg', 'elected', NULL),
('Bill Herbkersman', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '118', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0832954446.jpg', 'elected', NULL),
('William Bailey', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '104', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0088636353.jpg', 'elected', NULL),
('Bill Chumley', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '35', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0351704504.jpg', 'elected', NULL),
('Bill Hixon', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '83', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0849715808.jpg', 'elected', NULL),
('Bill Whitmire', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '1', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1914204316.jpg', 'elected', NULL),
('Bill Hager', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '122', NULL, 'Republican', 'https://scstatehouse.gov/images/members/0733948776.jpg', 'elected', NULL),
('Weston Newton', 'State Representative', 'Legislative Branch', 'Legislative', 'SC', '120', NULL, 'Republican', 'https://scstatehouse.gov/images/members/1418749830.jpg', 'elected', NULL);
