-- SD state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'SD';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Aaron Aylward', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '6', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Aaron-Aylward.PNG', 'elected', NULL),
('Al Novstrup', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '3', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/NOVSTRUP_2017.jpg', 'elected', NULL),
('Amber Arlint', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '12', NULL, 'Republican', 'https://siouxfallschamber.com/wp-content/uploads/sites/3/2022/11/District-12-Amber-Arlint.webp', 'elected', NULL),
('Amber Hulse', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '30', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ahulse.jpg', 'elected', NULL),
('Arch Beal', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '12', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/BEAL_2017.jpg', 'elected', NULL),
('Bethany Soye', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '9', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/_Bethany-Soye_.PNG', 'elected', NULL),
('Bobbi Andera', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '10', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Bobbi_Andera_20250303_091250.jpg', 'elected', NULL),
('Brandei Schaefbauer', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '3', NULL, 'Republican', 'https://gray-ksfy-prod.cdn.arcpublishing.com/resizer/3wAp2PAmslSttABhdOPnmasLDYI=/980x0/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/Y4ZM7RT3TRB2ZBPHKDXEI5HL6E.jpg', 'elected', NULL),
('Brandon Wipf', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '22', NULL, 'Republican', 'https://governor.sd.gov/doc/IMG_4416-scaled.jpg', 'elected', NULL),
('Brian Mulder', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '11', NULL, 'Republican', 'https://img1.wsimg.com/isteam/ip/27b7dcd4-adbb-4603-9579-073f083153b8/Brian_BriCowanPhotography-11.jpg/:/cr=t:0%25,l:0%25,w:100%25,h:100%25/rs=w:400,cg:true', 'elected', NULL),
('Carl Perry', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '3', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Carl_Perry_20230524_083211.jpeg', 'elected', NULL),
('Casey Crabtree', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '8', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/crabtree_2020.jpg', 'elected', NULL),
('Chris Karr', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '11', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Karr_2017.jpg', 'elected', NULL),
('Chris Kassin', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '17', NULL, 'Republican', 'https://lawmakerdocuments.blob.core.usgovcloudapi.net/photos/kassin,%20chris%20rep-0599%20rt.webp', 'elected', NULL),
('Curt Massie', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '33', NULL, 'Republican', 'https://cloudfront-us-east-1.images.arcpublishing.com/gray/JN4WUIDOKVFC5NL33TGXE5YFOM.JPG', 'elected', NULL),
('Curt Voight', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '33', NULL, 'Republican', 'https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1b0cc545-be4d-4e1d-a25e-504b7057b344.heic', 'elected', NULL),
('David Kull', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '2', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DavidKull.png', 'elected', NULL),
('Drew Peterson', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '19', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DrewPeterson.png', 'elected', NULL),
('Dylan Jordan', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '4', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/815272/815272.jpg', 'elected', NULL),
('Eric Emery', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '26A', NULL, 'Democratic', 'https://www.sfsimplified.com/content/images/2022/09/Eric-Emery.jpg', 'elected', NULL),
('Erik Muckey', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '15', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ErikMuckey.png', 'elected', NULL),
('Erin Healy', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '10', NULL, 'Democratic', 'https://sdlegislature.gov/inc/img/Legislators/Healy_2019.jpg', 'elected', NULL),
('Ernie Otten', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '6', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/OTTEN_2017.jpg', 'elected', NULL),
('Glen Vilhauer', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '5', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Glen_Vilhauer.jpg', 'elected', NULL),
('Greg Blanc', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '35', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/gblanc2.png', 'elected', NULL),
('Greg Jamison', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '12', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Jamison_2017.jpg', 'elected', NULL),
('Heather Baxter', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '34', NULL, 'Republican', 'https://substackcdn.com/image/fetch/w_1200,h_600,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F110b1f43-2918-4e73-928e-0b9834191446_750x517.webp', 'elected', NULL),
('Les Heinemann', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '25', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Leslie_Heinemann.jpg', 'elected', NULL),
('Helene Duhamel', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '32', NULL, 'Republican', 'http://sdlegislature.gov/inc/img/Legislators/Duhamel_2020.jpg', 'elected', NULL),
('Jack Kolbeck', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '13', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Kolbeck_2017.jpg', 'elected', NULL),
('Jamie Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '15', NULL, 'Democratic', 'https://sdlegislature.gov/inc/img/Legislators/Smith_jamie_2019.jpg', 'elected', NULL),
('Jana Hunt', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '28A', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jana_Hunt_2025.jpg', 'elected', NULL),
('Jeff Bathke', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '20', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jeff_Bathke_20240808_100312fgd.jpg', 'elected', NULL),
('Jessica Bahmuller', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '19', NULL, 'Republican', 'https://gray-ksfy-prod.cdn.arcpublishing.com/resizer/uVfdl5DqYxBK5BAgVB1sNda9-dw=/980x0/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/XEYMZWQPXBGYFJAKREMXYXNXCI.png', 'elected', NULL),
('Jim Halverson', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '21', NULL, 'Republican', 'https://halversonforhouse.com/wp-content/uploads/2024/04/Jim-Halverson-for-House.jpg', 'elected', NULL),
('Jim Mehlhaff', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '24', NULL, 'Republican', 'https://jimmehlhaff.com/wp-content/uploads/2022/03/Jim-High-Res-819x1024.jpeg', 'elected', NULL),
('John Carley', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '29', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JohnCarley3.png', 'elected', NULL),
('John Hughes', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '13', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/John_Hughes_2025.jpg', 'elected', NULL),
('John Shubeck', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '16', NULL, 'Republican', 'https://southdakotasearchlight.com/wp-content/uploads/2025/09/Shubeck-197x300.jpg', 'elected', NULL),
('John Sjaarda', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '2', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JohnSjaarda.png', 'elected', NULL),
('Jon Hansen', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '25', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jon_Hansen.jpg', 'elected', NULL),
('Josephine Garcia', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '5', NULL, 'Republican', 'https://static.wixstatic.com/media/3f6c9b_7103450fc62d4fb8acfceb568e4a1545~mv2.jpg/v1/fill/w_705,h_802,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/3f6c9b_7103450fc62d4fb8acfceb568e4a1545~mv2.jpg', 'elected', NULL),
('Joy Hohn', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '9', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/jhohn.jpg', 'elected', NULL),
('Julie Auch', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '18', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JulieAuch.png', 'elected', NULL),
('Kadyn Wittman', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '15', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/KadynWittman.png', 'elected', NULL),
('Kaley Nolz', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '20', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Kaley_Nolz_2025.jpg', 'elected', NULL),
('Karla Lems', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '16', NULL, 'Republican', 'https://gray-ksfy-prod.cdn.arcpublishing.com/resizer/fX4I5GWdwjL88Z9n8a1Dah-NctM=/980x0/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/72HOS665ZZDWHPEMYA6BWMS6BA.jpg', 'elected', NULL),
('Kathy Rice', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '29', NULL, 'Republican', 'https://gray-kota-prod.gtv-cdn.com/resizer/v2/J7PTGE337BGX3PYCKMQSGVCMWI.jpg?auth=219de6028a2c39d4fe6c781ce1d7fbf5c6d380c1863d80fe91b11b9e80c54ea1&width=980&height=1030&smart=true', 'elected', NULL),
('Kent Roe', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '4', NULL, 'Republican', 'https://static.votesmart.org/static/canphoto/216142.jpg', 'elected', NULL),
('Keri Weems', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '11', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/6633129388483f6e2a0ea63e/4fa432f3-e858-4d44-a401-ddc328a1f893/29d976e1-b6bb-4539-807c-c4e93f10ee4f+%281%29.jpg?format=2500w', 'elected', NULL),
('Kevin Jensen', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '16', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Jensen_2017.jpg', 'elected', NULL),
('Kevin Van Diepen', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '22', NULL, 'Republican', 'https://www.plainsman.com/uploads/original/20240109-142336-0a240151fba44bcc2fecc73323c1cfdd.jpg', 'elected', NULL),
('Kyle Schoenfish', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '19', NULL, 'Republican', 'http://sdlegislature.gov/inc/img/Legislators/Schoenfish_2019.jpg', 'elected', NULL),
('Lana Greenfield', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '22', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/GreenfieldLana_2017.jpg', 'elected', NULL),
('Larry Zikmund', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '14', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/ZIKMUND_2017.jpg', 'elected', NULL),
('Lauren Nelson', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '18', NULL, 'Republican', 'https://cdn.socast.io/6942/sites/13/2024/06/04233345/Lauren-Nelson.jpg', 'elected', NULL),
('Liz Larson', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '10', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Liz_Larson__.jpg', 'elected', NULL),
('Liz May', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '27', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/MAY_2017.jpg', 'elected', NULL),
('Logan Manhart', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '1', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Logan_Manhart.jpeg', 'elected', NULL),
('Mark Lapka', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '23', NULL, 'Republican', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZm0bH8MRxxVDUSQkCXbPkK3Lm-BaDg8Cog&s', 'elected', NULL),
('Marty Overweg', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '21', NULL, 'Republican', 'http://sdlegislature.gov/inc/img/Legislators/overweg_2020.jpg', 'elected', NULL),
('Mary Fitzgerald', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '31', NULL, 'Republican', 'https://bloximages.chicago2.vip.townnews.com/capjournal.com/content/tncms/assets/v3/editorial/6/bb/6bb95f06-3413-11eb-b8a6-77bddc8623d9/5fc6d265841ef.image.png?resize=630%2C630', 'elected', NULL),
('Matt Roby', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '5', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/mykxlg.com/content/tncms/assets/v3/editorial/8/8b/88bea3ac-5e1f-11ee-ba1f-dfd780c64f5d/6515af82998be.image.jpg?resize=333%2C500', 'elected', NULL),
('Mellissa Heermann', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '7', NULL, 'Republican', 'https://img1.wsimg.com/isteam/ip/805d1e30-7bc9-464e-a3b8-c366e5bfe518/IMG_1300%20(1).JPG', 'elected', NULL),
('Michael Rohl', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '1', NULL, 'Republican', 'https://lawmakerdocuments.blob.core.usgovcloudapi.net/photos/rohl,%20michael%20sen-2772%20full%20rt.webp', 'elected', NULL),
('Mike Stevens', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '18', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/STEVENS_2017.jpg', 'elected', NULL),
('Mike Derby', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '34', NULL, 'Republican', 'https://lloydcompanies.com/wp/wp-content/uploads/2020/07/Mike-Derby-816x1024.jpg', 'elected', NULL),
('Mike Weisgram', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '24', NULL, 'Republican', 'https://bloximages.chicago2.vip.townnews.com/capjournal.com/content/tncms/assets/v3/editorial/5/dd/5dd71c64-93d9-11ea-a386-83ab371b2512/5eb9d679c54ee.image.jpg', 'elected', NULL),
('MyKala Voita', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '21', NULL, 'Republican', 'https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7b0400d1-d3d8-4073-95b9-39e28c8c6203.heic', 'elected', NULL),
('Nick Fosness', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '1', NULL, 'Republican', 'https://sdaho.org/wp-content/uploads/2018/03/nick-fosness-big-696x967.jpg', 'elected', NULL),
('Nicole Uhre-Balk', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '32', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/nubalk.jpg', 'elected', NULL),
('Paul Miskimins', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '20', NULL, 'Republican', 'https://lawmakerdocuments.blob.core.usgovcloudapi.net/photos/miskimins_2019.jpg', 'elected', NULL),
('Peri Pourier', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '27', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Pourier_2019.jpg', 'elected', NULL),
('Phil Jensen', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '33', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Phil-Jensen.jpg', 'elected', NULL),
('Randy Deibert', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '31', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/RandyDeibert.png', 'elected', NULL),
('Rebecca Reimer', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '26B', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Reimer_2017.jpg', 'elected', NULL),
('Red Dawn Foster', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '27', NULL, 'Democratic', 'https://listen.sdpb.org/sites/sdpb/files/201905/lege_red_dawn_foster_2019.jpg', 'elected', NULL),
('Roger DeGroot', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '7', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/RogerDeGroot.png', 'elected', NULL),
('Sam Marty', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '28', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/MARTY.jpg', 'elected', NULL),
('Scott Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '23', NULL, 'Republican', 'https://gray-ksfy-prod.cdn.arcpublishing.com/resizer/PaauCW6h0UcuEU2uhSkymFUQnhU=/980x0/smart/filters:quality(85)/cloudfront-us-east-1.images.arcpublishing.com/gray/WIET46SP6JBKTLV2GTADMR27PY.jpg', 'elected', NULL),
('Scott Odenbach', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '31', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Scott-Odenbach.PNG', 'elected', NULL),
('Spencer Gosch', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '23', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Gosch_2017.jpg', 'elected', NULL),
('Stephanie Sauder', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '4', NULL, 'Republican', 'https://lawmakerdocuments.blob.core.usgovcloudapi.net/photos/sm_sauder,%20stephanie%20rep-0648%20rt.webp', 'elected', NULL),
('Steve Duffy', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '32', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/SteveDuffy.png', 'elected', NULL),
('Steve Kolbeck', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '2', NULL, 'Republican', 'https://kolbeckforsouthdakota.com/wp-content/uploads/2022/02/Kolbeck-Headshot1.png-684x1024.jpg', 'elected', NULL),
('Sue Peterson', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '13', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/PetersonSue_2017.jpg', 'elected', NULL),
('Sydney Davis', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '17', NULL, 'Republican', 'https://bloximages.chicago2.vip.townnews.com/plaintalk.net/content/tncms/assets/v3/editorial/e/f2/ef29df3c-0515-11eb-b916-33278c4cf760/5f77d0e624605.image.jpg?resize=500%2C750', 'elected', NULL),
('Taffy Howard', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '34', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Howard_2017.jpg', 'elected', NULL),
('Tamara Grove', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '26', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/TamaraGrove2024.jpeg', 'elected', NULL),
('Taylor Rehfeldt', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '14', NULL, 'Republican', 'https://www.gannett-cdn.com/presto/2020/05/22/PSIF/4cc05ff5-5458-4aa1-a67d-b9f2ac8e2cd2-Taylor_Rae_Rehfeldt.jpg', 'elected', NULL),
('Terri Jorgenson', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '29', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Terri-Jorgenson.jpg', 'elected', NULL),
('Tesa Schwans', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '9', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/TesaSchwans2024.jpeg', 'elected', NULL),
('Tim Czmowski', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '6', NULL, 'Republican', 'https://npr.brightspotcdn.com/89/8f/6dd0f43d4ee39f123a628f41ba91/tim-czmowski.jpg', 'elected', NULL),
('Tim Goodwin', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '30', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Goodwin_2017.jpg', 'elected', NULL),
('Tim Reed', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '7', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Reed_2017.jpg', 'elected', NULL),
('Tim Reisch', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '8', NULL, 'Republican', 'https://lawmakerdocuments.blob.core.usgovcloudapi.net/photos/https://lawmakerdocuments.blob.core.usgovcloudapi.net/photos/reisch, tim rep-1757 rt.jpg', 'elected', NULL),
('Tim Walburg', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '8', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/208150/208150.jpg', 'elected', NULL),
('Tina Mulally', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '35', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Mulally_2019.jpg', 'elected', NULL),
('Tom Pischke', 'State Senator', 'Legislative Branch', 'Legislative', 'SD', '25', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Pischke_2017.jpg', 'elected', NULL),
('Tony Kayser', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '14', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/815298/815298.jpg', 'elected', NULL),
('Tony Randolph', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '35', NULL, 'Republican', 'https://sdlegislature.gov/inc/img/Legislators/Randolph_2019.jpg', 'elected', NULL),
('Travis Ismay', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '28B', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Travis_Ismay_2025.jpg', 'elected', NULL),
('Trish Ladner', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '30', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Trish_Ladner.png', 'elected', NULL),
('Will Mortenson', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '24', NULL, 'Republican', 'https://www.gannett-cdn.com/-mm-/7d2e32043f35f170234758f26dd14f0d4c05b2fa/c=0-17-3772-2148/local/-/media/2016/12/28/SiouxFalls/SiouxFalls/636185485920955826-Will-Mortenson.jpg?width=3200&height=1808&fit=crop&format=pjpg&auto=webp', 'elected', NULL),
('William Shorma', 'State Representative', 'Legislative Branch', 'Legislative', 'SD', '17', NULL, 'Republican', 'https://lawmakerdocuments.blob.core.usgovcloudapi.net/photos/shorma,%20william%20rep-1194%20rt.webp', 'elected', NULL);
