-- TN state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'TN';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Adam Lowe', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '1', NULL, 'Republican', 'https://static.wixstatic.com/media/599b12_afa74a3390064dd386df25e882ac9659~mv2.jpeg/v1/fill/w_675,h_716,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/599b12_afa74a3390064dd386df25e882ac9659~mv2.jpeg', 'elected', NULL),
('Aftyn Behn', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '51', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Aftyn_Behn.png', 'elected', NULL),
('Andrew Farmer', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '17', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h17.jpg', 'elected', NULL),
('Aron Maberry', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '68', NULL, 'Republican', 'https://www.cmcss.net/wp-content/uploads/elementor/thumbs/L10A9877-2-scaled-qx0h1ahjmd2n4yug9v0d3onejmbo99kwtpl6ybvbxo.jpg', 'elected', NULL),
('Becky Massey', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '6', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s6.jpg', 'elected', NULL),
('Bill Powers', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '22', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s22.jpg', 'elected', NULL),
('Bo Mitchell', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '50', NULL, 'Democratic', 'http://www.capitol.tn.gov/house/members/images/h50.jpg', 'elected', NULL),
('Bo Watson', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '11', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s11.jpg', 'elected', NULL),
('Bob Freeman', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '56', NULL, 'Democratic', 'https://www.capitol.tn.gov/house/members/images/H56.jpg', 'elected', NULL),
('Bobby Harshbarger', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '4', NULL, 'Republican', 'https://tennesseelookout.com/wp-content/uploads/2024/09/Bobby-Harshbarger-975x1024.jpeg', 'elected', NULL),
('Brent Taylor', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '31', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/BrentTaylor_TN.jpeg', 'elected', NULL),
('Brock Martin', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '79', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Brock-Martin.PNG', 'elected', NULL),
('Bryan Terry', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '48', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h48.jpg', 'elected', NULL),
('Bud Hulsey', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '2', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h2.jpg', 'elected', NULL),
('Caleb Hemmer', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '59', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/hemmercaleb.jpg', 'elected', NULL),
('Cameron Sexton', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '25', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h25.jpg', 'elected', NULL),
('Charlane Oliver', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '19', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/CharlaneOliver.png', 'elected', NULL),
('Charlie Baum', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '37', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/H37.jpg', 'elected', NULL),
('Chris Hurt', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '82', NULL, 'Republican', 'https://capitol.tn.gov/house/members/images/H82.jpg', 'elected', NULL),
('Chris Todd', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '73', NULL, 'Republican', 'https://www.capitol.tn.gov/house/members/images/H73.jpg', 'elected', NULL),
('Clark Boyd', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '46', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h46.jpg', 'elected', NULL),
('Clay Doggett', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '70', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/H70.jpg', 'elected', NULL),
('Dan Howell', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '22', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h22.jpg', 'elected', NULL),
('Dave Wright', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '19', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/H19.jpg', 'elected', NULL),
('David Hawk', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '5', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h5.jpg', 'elected', NULL),
('Dawn White', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '13', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s13.jpg', 'elected', NULL),
('Debra Moody', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '81', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h81.jpg', 'elected', NULL),
('Dennis Powers', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '36', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h36.jpg', 'elected', NULL),
('Ed Butler', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '41', NULL, 'Republican', 'http://edbutlerfortn.com/wp-content/uploads/2018/04/Ed-Butler.jpg', 'elected', NULL),
('Ed Jackson', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '25', NULL, 'Republican', 'https://capitol.tn.gov/senate/members/images/S25.jpg', 'elected', NULL),
('Elaine Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '18', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/62669899a296e67b1d34963d/13e0ac0c-9c86-423e-baa5-655fb75829bf/ElaineDavis2022-1.jpg', 'elected', NULL),
('Esther Helton-Haynes', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '30', NULL, 'Republican', 'https://capitol.tn.gov/house/members/images/H30.jpg', 'elected', NULL),
('Ferrell Haile', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '18', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s18.jpg', 'elected', NULL),
('Fred Atchley', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '12', NULL, 'Republican', 'https://static.wixstatic.com/media/2859e9_1cd01bea042640618e87046b22a3e1ef~mv2.png/v1/crop/x_578,y_0,w_2532,h_2534/fill/w_434,h_434,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/2023%201204%20Atchley%20Thank%20You%20Cards.png', 'elected', NULL),
('Gabby Salinas', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '96', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/587e30b61b10e3f62fc61ab4/242a6f6e-67d2-4fa8-8e51-c70a3b595274/IMG_1959.jpg', 'elected', NULL),
('Gary Hicks', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '9', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h9.jpg', 'elected', NULL),
('Gino Bulso', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '61', NULL, 'Republican', 'https://votegino.com/wp-content/uploads/2022/04/gino.png', 'elected', NULL),
('Gloria Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '90', NULL, 'Democratic', 'https://capitol.tn.gov/house/members/images/H90.jpg', 'elected', NULL),
('Greg Martin', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '26', NULL, 'Republican', 'https://www.capitol.tn.gov/house/members/images/h26.jpg', 'elected', NULL),
('Greg Vital', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '29', NULL, 'Republican', 'https://www.capitol.tn.gov/house/members/images/h29.jpg', 'elected', NULL),
('Harold Love', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '58', NULL, 'Democratic', 'http://www.capitol.tn.gov/house/members/images/h58.jpg', 'elected', NULL),
('Heidi Campbell', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '20', NULL, 'Democratic', 'https://www.capitol.tn.gov/senate/members/images/S20.jpg', 'elected', NULL),
('Iris Rudder', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '39', NULL, 'Republican', 'https://data.openstates.org/images/small/ocd-person/96432d4d-ecdf-4fa0-8a20-e8a5636fb7dd', 'elected', NULL),
('Jack Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '27', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/williamsonherald.com/content/tncms/assets/v3/editorial/b/5f/b5ffcba0-f751-11e8-8648-bf381c197480/5c05b9b74599d.image.jpg?resize=334%2C500', 'elected', NULL),
('Jake McCalmon', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '63', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/58f80179be65944c6f5eeb8a/94dc5fac-95f7-4b57-8c52-6bffa35d2a20/JakeMcCalmon-3.jpg', 'elected', NULL),
('Janice Bowling', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '16', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s16.jpg', 'elected', NULL),
('Jason Powell', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '53', NULL, 'Democratic', 'https://www.tennessean.com/gcdn/-mm-/6f03ca527b37558797b9ff3612df6f1ca4cc9386/c=0-42-1946-2637/local/-/media/Nashville/2015/02/11/B9316214695Z.1_20150211202701_000_GF79UD55G.1-0.jpg', 'elected', NULL),
('Jason Zachary', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '14', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h14.jpg', 'elected', NULL),
('Jay Reedy', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '74', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h74.jpg', 'elected', NULL),
('Jeff Yarbro', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '21', NULL, 'Democratic', 'http://www.capitol.tn.gov/senate/members/images/s21.jpg', 'elected', NULL),
('Jeremy Faison', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '11', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h11.jpg', 'elected', NULL),
('Jerome Moon', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '8', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h8.jpg', 'elected', NULL),
('Jesse Chism', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '85', NULL, 'Democratic', 'https://www.capitol.tn.gov/house/members/images/H85.jpg', 'elected', NULL),
('Jessie Seal', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '8', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jason_Weakley_20241023_122227.jpg', 'elected', NULL),
('Jody Barrett', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '69', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jody-Barrett.PNG', 'elected', NULL),
('Joe Towns', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '84', NULL, 'Democratic', 'http://www.capitol.tn.gov/house/members/images/h84.jpg', 'elected', NULL),
('Joey Hensley', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '28', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s28.jpg', 'elected', NULL),
('John Crawford', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '1', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h1.jpg', 'elected', NULL),
('John Gillespie', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '97', NULL, 'Republican', 'https://www.capitol.tn.gov/house/members/images/h97.jpg', 'elected', NULL),
('John Clemmons', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '55', NULL, 'Democratic', 'http://www.capitol.tn.gov/house/members/images/h55.jpg', 'elected', NULL),
('John Stevens', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '24', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s24.jpg', 'elected', NULL),
('Johnny Garrett', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '45', NULL, 'Republican', 'https://www.spencerfane.com/wp-content/uploads/2023/05/garrett-j-731x1024.jpg', 'elected', NULL),
('Johnny Shaw', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '80', NULL, 'Democratic', 'http://www.capitol.tn.gov/house/members/images/h80.jpg', 'elected', NULL),
('Justin Pearson', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '86', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/638e0e4731cb8444ce5a20e8/1d467f44-2f5f-42d0-96e9-8819eee165fb/Justin_21.jpg', 'elected', NULL),
('Justin Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '52', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JustinJones_TN_HD52.jpg', 'elected', NULL),
('Justin Lafferty', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '89', NULL, 'Republican', 'https://fluxconsole.com/files/image/131170', 'elected', NULL),
('Karen Camper', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '87', NULL, 'Democratic', 'http://www.capitol.tn.gov/house/members/images/h87.jpg', 'elected', NULL),
('Kelly Keisling', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '38', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h38.jpg', 'elected', NULL),
('Ken Yager', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '12', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s12.jpg', 'elected', NULL),
('Kerry Roberts', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '23', NULL, 'Republican', 'https://fluxconsole.com/files/image/131100', 'elected', NULL),
('Kevin Raper', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '24', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Kevin-Raper.PNG', 'elected', NULL),
('Kevin Vaughan', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '95', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h95.jpg', 'elected', NULL),
('Kip Capley', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '71', NULL, 'Republican', 'https://votecapley.com/wp-content/uploads/2022/01/capley2-4.png', 'elected', NULL),
('Kirk Haston', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '72', NULL, 'Republican', 'https://capitol.tn.gov/house/members/images/H72.jpg', 'elected', NULL),
('Larry Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '88', NULL, 'Democratic', 'http://www.capitol.tn.gov/house/members/images/h88.jpg', 'elected', NULL),
('Lee Reeves', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '65', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/williamsonherald.com/content/tncms/assets/v3/editorial/7/43/743d158c-3f0e-11ef-855e-4b97c0d5f896/668f0f9e62e96.image.jpg?resize=394%2C500', 'elected', NULL),
('London Lamar', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '33', NULL, 'Democratic', 'https://www.capitol.tn.gov/senate/members/images/s33.jpg', 'elected', NULL),
('Lowell Russell', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '21', NULL, 'Republican', 'https://www.capitol.tn.gov/house/members/images/H21.jpg', 'elected', NULL),
('Mark Cochran', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '23', NULL, 'Republican', 'https://www.capitol.tn.gov/house/members/images/H23.jpg', 'elected', NULL),
('Mark Pody', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '17', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s17.jpg', 'elected', NULL),
('Mark White', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '83', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h83.jpg', 'elected', NULL),
('Mary Littleton', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '78', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h78.jpg', 'elected', NULL),
('Michael Hale', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '40', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Michael_Hale_20230524_083209.jpeg', 'elected', NULL),
('Michael Lankford', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '75', NULL, 'Republican', 'https://montgomerytn.gov/storage/departments/commission/commissioner/Commissioners-Sept-2022/MichaelLankford.jpg', 'elected', NULL),
('Michele Carringer', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '16', NULL, 'Republican', 'http://nebula.wsimg.com/ec18d700041ee80017970cc4f5b0d8cb?AccessKeyId=C9D09D69010A6C1BCFA5&disposition=0&alloworigin=1', 'elected', NULL),
('Michele Reneau', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '27', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Rebecca_Day_20240808_092357.jpg', 'elected', NULL),
('Mike Sparks', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '49', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h49.jpg', 'elected', NULL),
('Monty Fritts', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '32', NULL, 'Republican', 'https://static.wixstatic.com/media/fd35b0_10146244fb184e609fc7bce8e27b2b82~mv2.png/v1/fill/w_252,h_358,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Monty%20Image%20cropped%20(1)_edited.png', 'elected', NULL),
('Page Walley', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '26', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/S26.jpg', 'elected', NULL),
('Pat Marsh', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '62', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h62.jpg', 'elected', NULL),
('Paul Bailey', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '15', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s15.jpg', 'elected', NULL),
('Paul Rose', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '32', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s32.jpg', 'elected', NULL),
('Paul Sherrell', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '43', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h43.jpg', 'elected', NULL),
('Randy McNally', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '5', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s5.jpg', 'elected', NULL),
('Raumesh Akbari', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '29', NULL, 'Democratic', 'http://www.capitol.tn.gov/senate/members/images/s29.jpg', 'elected', NULL),
('Becky Jo Alexander', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '7', NULL, 'Republican', 'https://www.capitol.tn.gov/house/members/images/h7.jpg', 'elected', NULL),
('Renea Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '4', NULL, 'Republican', 'https://reneajones.com/wp-content/uploads/2023/12/aboutimage.jpg', 'elected', NULL),
('Antonio Parkinson', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '98', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Antonio_Parkinson.jpg', 'elected', NULL),
('Richard Briggs', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '7', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s7.jpg', 'elected', NULL),
('Rick Eldridge', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '10', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/H10.jpg', 'elected', NULL),
('Rick Scarbrough', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '33', NULL, 'Republican', 'https://tnhousegop.org/wp-content/uploads/2025/01/Scarbrough-scaled.jpg', 'elected', NULL),
('Robert Stevens', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '13', NULL, 'Republican', 'https://capitol.tn.gov/house/members/images/H13.jpg', 'elected', NULL),
('Ron Gant', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '94', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h94.jpg', 'elected', NULL),
('Ron Travis', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '31', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h31.jpg', 'elected', NULL),
('Ronnie Glynn', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '67', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/1Aug232020602PM_80182230_BLUE-min.png', 'elected', NULL),
('Rush Bricken', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '47', NULL, 'Republican', 'https://data.openstates.org/images/small/ocd-person/271c14e0-433b-42ce-91c5-c01ad5ccfc41', 'elected', NULL),
('Rusty Crowe', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '3', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s3.jpg', 'elected', NULL),
('Rusty Grills', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '77', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h77.jpg', 'elected', NULL),
('Ryan Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '42', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h42.jpg', 'elected', NULL),
('Doc Kumar', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '66', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h66.jpg', 'elected', NULL),
('Sam McKenzie', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '15', NULL, 'Democratic', 'http://www.capitol.tn.gov/house/members/images/h15.jpg', 'elected', NULL),
('Sara Kyle', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '30', NULL, 'Democratic', 'http://www.capitol.tn.gov/senate/members/images/s30.jpg', 'elected', NULL),
('Scott Cepicky', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '64', NULL, 'Republican', 'https://capitol.tn.gov/house/members/images/H64.jpg', 'elected', NULL),
('Shane Reeves', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '14', NULL, 'Republican', 'http://www.capitol.tn.gov/senate/members/images/s14.jpg', 'elected', NULL),
('Shaundelle Brooks', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '60', NULL, 'Democratic', 'https://images.bradyunited.org/production/images/Shaundelle-Brooks.jpeg?w=400&h=336&fm=webp&auto=compress&fit=crop&dm=1717513962&s=8dee64026b44a29de45f896285fc7b35', 'elected', NULL),
('Steve Southerland', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '9', NULL, 'Republican', 'https://capitol.tn.gov/senate/members/images/S9.jpg', 'elected', NULL),
('Susan Lynn', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '57', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h57.jpg', 'elected', NULL),
('T.J. Hardaway', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '93', NULL, 'Democratic', 'https://tennesseelookout.com/wp-content/uploads/2026/05/TJHardaway1.jpg', 'elected', NULL),
('Tandy Darby', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '76', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h76.jpg', 'elected', NULL),
('Tim Hicks', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '6', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h6.jpg', 'elected', NULL),
('Tim Rudd', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '34', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h34.jpg', 'elected', NULL),
('Timothy Hill', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '3', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/TimothyHill.jpg', 'elected', NULL),
('Todd Gardenhire', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '10', NULL, 'Republican', 'https://capitol.tn.gov/senate/members/images/S10.jpg', 'elected', NULL),
('Todd Warner', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '92', NULL, 'Republican', 'https://www.capitol.tn.gov/house/members/images/h92.jpg', 'elected', NULL),
('Tom Hatcher', 'State Senator', 'Legislative Branch', 'Legislative', 'TN', '2', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/6570c60e478ebd26777cfd83/7e2e888c-6da6-4b8f-a79f-279c8e5cd2c2/365772199_7298985810116788_8248702436261909523_n.jpg', 'elected', NULL),
('Tom Leatherwood', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '99', NULL, 'Republican', 'https://d33byq9npfy6u9.cloudfront.net/4/tom-leatherwood/u/original/1333880/tomleatherwoodmug.jpg', 'elected', NULL),
('Tommy Stinnett', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '20', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Tom_Stinnett_2025.jpg', 'elected', NULL),
('Torrey Harris', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '91', NULL, 'Democratic', 'https://capitol.tn.gov/house/members/images/H91.jpg', 'elected', NULL),
('Vincent Dixie', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '54', NULL, 'Democratic', 'https://www.capitol.tn.gov/house/members/images/H54.jpg', 'elected', NULL),
('William Lamberth', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '44', NULL, 'Republican', 'http://www.capitol.tn.gov/house/members/images/h44.jpg', 'elected', NULL),
('William Slater', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '35', NULL, 'Republican', 'https://bloximages.newyork1.vip.townnews.com/gallatinnews.com/content/tncms/assets/v3/editorial/e/3b/e3b758f4-03a2-11ed-9c70-97c00c9ae5a8/62d0609f6cb1e.image.jpg', 'elected', NULL),
('Yusuf Hakeem', 'State Representative', 'Legislative Branch', 'Legislative', 'TN', '28', NULL, 'Democratic', 'https://data.openstates.org/images/small/ocd-person/73d17744-fdda-495d-b5a8-c44342fc5b38', 'elected', NULL);
