-- TX state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'TX';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('A.J. Louderback', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '30', NULL, 'Republican', 'https://house.texas.gov/images/members/4620.jpg?v=1', 'elected', NULL),
('Adam Hinojosa', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '27', NULL, 'Republican', 'https://senate.texas.gov/members/d27/img/Hinojosa_Adam-88-0913D-005-web.jpg', 'elected', NULL),
('Aicha Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '109', NULL, 'Democratic', 'https://www.house.texas.gov/images/members/4465.jpg?v=1', 'elected', NULL),
('Alan Schoolcraft', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '44', NULL, 'Republican', 'https://house.texas.gov/images/members/4745.jpg?v=1', 'elected', NULL),
('Alma Allen', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '131', NULL, 'Democratic', 'https://house.texas.gov/images/members/2100.jpg?v=1', 'elected', NULL),
('Ana Hernandez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '143', NULL, 'Democratic', 'https://house.texas.gov/images/members/3155.jpg?v=1', 'elected', NULL),
('Ana-Maria Rodriguez Ramos', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '102', NULL, 'Democratic', 'https://house.texas.gov/images/members/3735.jpg?v=1', 'elected', NULL),
('Andy Hopper', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '64', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4555.jpg?v=1', 'elected', NULL),
('Angela Paxton', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '8', NULL, 'Republican', 'https://senate.texas.gov/members/d08/img/Paxton_2019.jpg', 'elected', NULL),
('Angelia Orr', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '13', NULL, 'Republican', 'https://house.texas.gov/images/members/4340.jpg?v=1', 'elected', NULL),
('Angie Button', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '112', NULL, 'Republican', 'https://house.texas.gov/images/members/2510.jpg?v=1', 'elected', NULL),
('Ann Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '134', NULL, 'Democratic', 'https://house.texas.gov/images/members/3985.jpg?v=1', 'elected', NULL),
('Mando Martinez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '39', NULL, 'Democratic', 'https://house.texas.gov/images/members/3780.jpg?v=1', 'elected', NULL),
('Armando Walle', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '140', NULL, 'Democratic', 'https://house.texas.gov/images/members/4930.jpg?v=1', 'elected', NULL),
('Barbara Gervin-Hawkins', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '120', NULL, 'Democratic', 'https://house.texas.gov/images/members/3445.jpg?v=1', 'elected', NULL),
('Ben Bumgarner', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '63', NULL, 'Republican', 'https://house.texas.gov/images/members/4125.jpg?v=1', 'elected', NULL),
('Bob Hall', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '2', NULL, 'Republican', 'https://senate.texas.gov/members/d02/img/headshot.jpg', 'elected', NULL),
('Bobby Guerra', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '41', NULL, 'Democratic', 'https://house.texas.gov/images/members/2325.jpg?v=1', 'elected', NULL),
('Borris Miles', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '13', NULL, 'Democratic', 'https://senate.texas.gov/members/d13/img/Sen-Miles-2025-Headshot-web.jpg', 'elected', NULL),
('Brad Buckley', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '54', NULL, 'Republican', 'https://house.texas.gov/images/members/3585.jpg?v=1', 'elected', NULL),
('Brent Hagenbuch', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '30', NULL, 'Republican', 'https://www.senate.texas.gov/members/d30/img/Hagenbuch_89-0029-009-web.jpg', 'elected', NULL),
('Brent Money', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '2', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4670.jpg?v=1', 'elected', NULL),
('Brett Ligon', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '4', NULL, 'Republican', 'https://www.bihmfirm.com/images/att_brett.jpg', 'elected', NULL),
('Brian Birdwell', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '22', NULL, 'Republican', 'https://senate.texas.gov/members/d22/img/headshot.jpg', 'elected', NULL),
('Brian Harrison', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '10', NULL, 'Republican', 'https://house.texas.gov/images/members/4085.jpg?v=1', 'elected', NULL),
('Briscoe Cain', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '128', NULL, 'Republican', 'https://house.texas.gov/images/members/3265.jpg?v=2', 'elected', NULL),
('Brooks Landgraf', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '81', NULL, 'Republican', 'https://house.texas.gov/images/members/3040.jpg?v=1', 'elected', NULL),
('Bryan Hughes', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '1', NULL, 'Republican', 'https://senate.texas.gov/members/d01/img/Hughes_86-0702D-030-web.jpg', 'elected', NULL),
('Candy Noble', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '89', NULL, 'Republican', 'https://house.texas.gov/images/members/3740.jpg?v=1', 'elected', NULL),
('Carl Tepper', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '84', NULL, 'Republican', 'https://house.texas.gov/images/members/4360.jpg?v=1', 'elected', NULL),
('Carol Alvarado', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '6', NULL, 'Democratic', 'https://senate.texas.gov/members/d06/img/CA-2018_web.jpg', 'elected', NULL),
('Caroline Fairly', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '87', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4480.jpg?v=1', 'elected', NULL),
('Caroline Harris Davila', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '52', NULL, 'Republican', 'https://house.texas.gov/images/members/4205.jpg?v=1', 'elected', NULL),
('Carrie Isaac', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '73', NULL, 'Republican', 'https://house.texas.gov/images/members/4265.jpg?v=3', 'elected', NULL),
('Cas Garcia Hernandez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '115', NULL, 'Democratic', 'https://www.house.texas.gov/images/members/4495.jpg?v=1', 'elected', NULL),
('Cecil Bell', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '3', NULL, 'Republican', 'https://house.texas.gov/images/members/2335.jpg?v=1', 'elected', NULL),
('Charlene Ward Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '139', NULL, 'Democratic', 'https://www.house.texas.gov/images/members/4785.jpg?v=3', 'elected', NULL),
('Charles Cunningham', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '127', NULL, 'Republican', 'https://house.texas.gov/images/members/4130.jpg?v=1', 'elected', NULL),
('Charles Perry', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '28', NULL, 'Republican', 'https://senate.texas.gov/members/d28/img/Perry-Headshot-2019.jpg', 'elected', NULL),
('Charles Schwertner', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '5', NULL, 'Republican', 'https://senate.texas.gov/members/d05/img/headshot.jpg', 'elected', NULL),
('Charlie Geren', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '99', NULL, 'Republican', 'https://house.texas.gov/images/members/2945.jpg?v=1', 'elected', NULL),
('Chris Turner', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '101', NULL, 'Democratic', 'https://house.texas.gov/images/members/4680.jpg?v=1', 'elected', NULL),
('Christian Manuel', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '22', NULL, 'Democratic', 'https://house.texas.gov/images/members/4255.jpg?v=1', 'elected', NULL),
('Christina Morales', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '145', NULL, 'Democratic', 'https://house.texas.gov/images/members/3910.jpg?v=1', 'elected', NULL),
('Claudia Ordaz', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '79', NULL, 'Democratic', 'https://house.texas.gov/images/members/4015.jpg?v=3', 'elected', NULL),
('Cody Harris', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '8', NULL, 'Republican', 'https://house.texas.gov/images/members/3580.jpg?v=3', 'elected', NULL),
('Cody Vasut', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '25', NULL, 'Republican', 'https://house.texas.gov/images/members/4065.jpg?v=1', 'elected', NULL),
('Cole Hefner', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '5', NULL, 'Republican', 'https://house.texas.gov/images/members/3505.jpg?v=1', 'elected', NULL),
('César Blanco', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '29', NULL, 'Democratic', 'https://senate.texas.gov/members/d29/img/SCBBio88th-web.jpg', 'elected', NULL),
('Dade Phelan', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '21', NULL, 'Republican', 'https://house.texas.gov/images/members/2905.jpg?v=1', 'elected', NULL),
('Daniel Alders', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '6', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4395.jpg?v=1', 'elected', NULL),
('David Cook', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '96', NULL, 'Republican', 'https://house.texas.gov/images/members/3960.jpg?v=1', 'elected', NULL),
('David Lowe', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '91', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4643.jpg?v=1', 'elected', NULL),
('David Spiller', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '68', NULL, 'Republican', 'https://house.texas.gov/images/members/4075.jpg?v=1', 'elected', NULL),
('Denise Villalobos', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '34', NULL, 'Republican', 'https://house.texas.gov/images/members/4770.jpg?v=1', 'elected', NULL),
('Dennis Paul', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '129', NULL, 'Republican', 'https://house.texas.gov/images/members/3090.jpg?v=1', 'elected', NULL),
('Diego Bernal', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '123', NULL, 'Democratic', 'https://house.texas.gov/images/members/3110.jpg?v=1', 'elected', NULL),
('Don McLaughlin', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '80', NULL, 'Republican', 'https://house.texas.gov/images/members/4655.jpg?v=1', 'elected', NULL),
('Donna Campbell', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '25', NULL, 'Republican', 'https://senate.texas.gov/members/d25/img/headshot.jpg', 'elected', NULL),
('Donna Howard', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '48', NULL, 'Democratic', 'https://house.texas.gov/images/members/3310.jpg?v=1', 'elected', NULL),
('Drew Darby', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '72', NULL, 'Republican', 'https://house.texas.gov/images/members/2645.jpg?v=1', 'elected', NULL),
('Dustin Burrows', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '83', NULL, 'Republican', 'https://house.texas.gov/images/members/3055.jpg?v=2', 'elected', NULL),
('Eddie Morales', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '74', NULL, 'Democratic', 'https://house.texas.gov/images/members/4000.jpg?v=1', 'elected', NULL),
('Liz Campos', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '119', NULL, 'Democratic', 'https://house.texas.gov/images/members/3950.jpg?v=1', 'elected', NULL),
('Ellen Troxclair', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '19', NULL, 'Republican', 'https://house.texas.gov/images/members/4385.jpg?v=1', 'elected', NULL),
('Erin Gámez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '38', NULL, 'Democratic', 'https://house.texas.gov/images/members/4095.jpg?v=1', 'elected', NULL),
('Erin Zwiener', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '45', NULL, 'Democratic', 'https://house.texas.gov/images/members/3710.jpg?v=1', 'elected', NULL),
('Gary Gates', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '28', NULL, 'Republican', 'https://house.texas.gov/images/members/3920.jpg?v=1', 'elected', NULL),
('Gary VanDeaver', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '1', NULL, 'Republican', 'https://house.texas.gov/images/members/2540.jpg?v=1', 'elected', NULL),
('Gene Wu', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '137', NULL, 'Democratic', 'https://house.texas.gov/images/members/2865.jpg?v=1', 'elected', NULL),
('Gina Hinojosa', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '49', NULL, 'Democratic', 'https://house.texas.gov/images/members/3210.jpg?v=1', 'elected', NULL),
('Giovanni Capriglione', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '98', NULL, 'Republican', 'https://house.texas.gov/images/members/2345.jpg?v=1', 'elected', NULL),
('Greg Bonnen', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '24', NULL, 'Republican', 'https://house.texas.gov/images/members/2875.jpg?v=1', 'elected', NULL),
('Harold Dutton', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '142', NULL, 'Democratic', 'https://house.texas.gov/images/members/2650.jpg?v=3', 'elected', NULL),
('Helen Kerwin', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '58', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4575.jpg?v=1', 'elected', NULL),
('Hillary Hickland', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '55', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4520.jpg?v=1', 'elected', NULL),
('Hubert Vo', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '149', NULL, 'Democratic', 'https://house.texas.gov/images/members/4900.jpg?v=1', 'elected', NULL),
('J.M. Lozano', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '43', NULL, 'Republican', 'https://house.texas.gov/images/members/2065.jpg?v=1', 'elected', NULL),
('James Frank', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '69', NULL, 'Republican', 'https://house.texas.gov/images/members/2385.jpg?v=1', 'elected', NULL),
('James Talarico', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '50', NULL, 'Democratic', 'https://house.texas.gov/images/members/3685.jpg?v=1', 'elected', NULL),
('Janie Lopez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '37', NULL, 'Republican', 'https://house.texas.gov/images/members/4295.jpg?v=2', 'elected', NULL),
('Janis Holt', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '18', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4535.jpg?v=2', 'elected', NULL),
('Jared Patterson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '106', NULL, 'Republican', 'https://house.texas.gov/images/members/3655.jpg?v=1', 'elected', NULL),
('Jay Dean', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '7', NULL, 'Republican', 'https://house.texas.gov/images/members/3515.jpg?v=1', 'elected', NULL),
('Jeff Barry', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '29', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4405.jpg?v=1', 'elected', NULL),
('Jeff Leach', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '67', NULL, 'Republican', 'https://house.texas.gov/images/members/2475.jpg?v=1', 'elected', NULL),
('Jessica González', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '104', NULL, 'Democratic', 'https://house.texas.gov/images/members/3335.jpg?v=1', 'elected', NULL),
('Joan Huffman', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '17', NULL, 'Republican', 'https://senate.texas.gov/members/d17/img/Huffman_9S5A0096-2021web.jpg', 'elected', NULL),
('Joanne Shofner', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '11', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4755.jpg?v=1', 'elected', NULL),
('Joe Moody', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '78', NULL, 'Democratic', 'https://house.texas.gov/images/members/3850.jpg?v=1', 'elected', NULL),
('John Bryant', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '114', NULL, 'Democratic', 'https://house.texas.gov/images/members/4120.jpg?v=1', 'elected', NULL),
('John Bucy', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '136', NULL, 'Democratic', 'https://house.texas.gov/images/members/3595.jpg?v=5', 'elected', NULL),
('John Lujan', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '118', NULL, 'Republican', 'https://house.texas.gov/images/members/3145.jpg?v=1', 'elected', NULL),
('John McQueeney', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '97', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4665.jpg?v=1', 'elected', NULL),
('John Smithee', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '86', NULL, 'Republican', 'https://house.texas.gov/images/members/4530.jpg?v=1', 'elected', NULL),
('Jo Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '147', NULL, 'Democratic', 'https://house.texas.gov/images/members/4105.jpg?v=1', 'elected', NULL),
('Jon Rosenthal', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '135', NULL, 'Democratic', 'https://house.texas.gov/images/members/3635.jpg?v=1', 'elected', NULL),
('José Menéndez', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '26', NULL, 'Democratic', 'https://senate.texas.gov/members/d26/img/headshot.jpg', 'elected', NULL),
('Josey Garcia', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '124', NULL, 'Democratic', 'https://house.texas.gov/images/members/4170.jpg?v=1', 'elected', NULL),
('Chuy Hinojosa', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '20', NULL, 'Democratic', 'https://senate.texas.gov/members/d20/img/Hinojosa_84-0784D-006.jpg', 'elected', NULL),
('Judith Zaffirini', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '21', NULL, 'Democratic', 'https://senate.texas.gov/members/d21/img/Zaffirini_2017.jpg', 'elected', NULL),
('Katrina Pierson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '33', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4715.jpg?v=2', 'elected', NULL),
('Keith Bell', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '4', NULL, 'Republican', 'https://house.texas.gov/images/members/3695.jpg?v=1', 'elected', NULL),
('Ken King', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '88', NULL, 'Republican', 'https://house.texas.gov/images/members/2455.jpg?v=1', 'elected', NULL),
('Keresa Richardson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '61', NULL, 'Republican', 'https://house.texas.gov/images/members/4735.jpg?v=1', 'elected', NULL),
('Kevin Sparks', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '31', NULL, 'Republican', 'https://senate.texas.gov/members/d31/img/Sparks_88-0063D-012-web.jpg', 'elected', NULL),
('Lacey Hull', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '138', NULL, 'Republican', 'https://house.texas.gov/images/members/3975.jpg?v=1', 'elected', NULL),
('Lauren Simmons', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '146', NULL, 'Democratic', 'https://house.texas.gov/images/members/4765.jpg?v=1', 'elected', NULL),
('Linda Garcia', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '107', NULL, 'Democratic', 'https://www.house.texas.gov/images/members/4485.jpg?v=3', 'elected', NULL),
('Lois Kolkhorst', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '18', NULL, 'Republican', 'https://senate.texas.gov/members/d18/img/LWK_2020.jpg', 'elected', NULL),
('Lulu Flores', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '51', NULL, 'Democratic', 'https://house.texas.gov/images/members/4150.jpg?v=1', 'elected', NULL),
('Mano DeAyala', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '133', NULL, 'Republican', 'https://house.texas.gov/images/members/4135.jpg?v=1', 'elected', NULL),
('Marc LaHood', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '121', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4595.jpg?v=1', 'elected', NULL),
('Mark Dorazio', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '122', NULL, 'Republican', 'https://house.texas.gov/images/members/4145.jpg?v=2', 'elected', NULL),
('Mary Ann Perez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '144', NULL, 'Democratic', 'https://house.texas.gov/images/members/2535.jpg?v=1', 'elected', NULL),
('Mary González', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '75', NULL, 'Democratic', 'https://house.texas.gov/images/members/2410.jpg?v=1', 'elected', NULL),
('Matt Morgan', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '26', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4675.jpg?v=1', 'elected', NULL),
('Matt Shaheen', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '66', NULL, 'Republican', 'https://house.texas.gov/images/members/2995.jpg?v=1', 'elected', NULL),
('Mayes Middleton', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '11', NULL, 'Republican', 'https://senate.texas.gov/members/d11/img/Middleton_87-0662D-009.jpg', 'elected', NULL),
('Mihaela Pleșa', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '70', NULL, 'Democratic', 'https://house.texas.gov/images/members/4345.jpg?v=1', 'elected', NULL),
('Mike Olcott', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '60', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4705.jpg?v=1', 'elected', NULL),
('Mike Schofield', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '132', NULL, 'Republican', 'https://house.texas.gov/images/members/3095.jpg?v=1', 'elected', NULL),
('Mitch Little', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '65', NULL, 'Republican', 'https://house.texas.gov/images/members/4615.jpg?v=1', 'elected', NULL),
('Molly Cook', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '15', NULL, 'Democratic', 'https://senate.texas.gov/members/d15/img/Cook_88-0807D-014-2025.jpg', 'elected', NULL),
('Morgan Meyer', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '108', NULL, 'Republican', 'https://house.texas.gov/images/members/3075.jpg?v=1', 'elected', NULL),
('Nate Schatzline', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '93', NULL, 'Republican', 'https://house.texas.gov/images/members/4355.jpg?v=1', 'elected', NULL),
('Nathan Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '16', NULL, 'Democratic', 'https://senate.texas.gov/members/d16/img/SNJ-Headshot-2023-web.jpg', 'elected', NULL),
('Nicole Collier', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '95', NULL, 'Democratic', 'https://house.texas.gov/images/members/2360.jpg?v=1', 'elected', NULL),
('Oscar Longoria', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '35', NULL, 'Democratic', 'https://house.texas.gov/images/members/2485.jpg?v=1', 'elected', NULL),
('Pat Curry', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '56', NULL, 'Republican', 'https://house.texas.gov/images/members/4415.jpg?v=2', 'elected', NULL),
('Paul Bettencourt', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '7', NULL, 'Republican', 'https://senate.texas.gov/members/d07/img/action.jpg', 'elected', NULL),
('Paul Dyson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '14', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4475.jpg?v=1', 'elected', NULL),
('Penny Morales Shaw', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '148', NULL, 'Democratic', 'https://house.texas.gov/images/members/4035.jpg?v=1', 'elected', NULL),
('Pete Flores', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '24', NULL, 'Republican', 'https://senate.texas.gov/members/d24/img/Flores_86-0634D-001-web.jpg', 'elected', NULL),
('Phil King', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '10', NULL, 'Republican', 'https://senate.texas.gov/members/d10/img/King_88-0550D-004-WEB.jpg', 'elected', NULL),
('Philip Cortez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '117', NULL, 'Democratic', 'https://house.texas.gov/images/members/2365.jpg?v=2', 'elected', NULL),
('Rafael Anchía', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '103', NULL, 'Democratic', 'https://house.texas.gov/images/members/2150.jpg', 'elected', NULL),
('Ramon Romero', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '90', NULL, 'Democratic', 'https://house.texas.gov/images/members/3060.jpg?v=1', 'elected', NULL),
('Ray Lopez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '125', NULL, 'Democratic', 'https://house.texas.gov/images/members/3915.jpg?v=1', 'elected', NULL),
('Rhetta Bowers', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '113', NULL, 'Democratic', 'https://house.texas.gov/images/members/3565.jpg?v=1', 'elected', NULL),
('Richard Hayes', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '57', NULL, 'Republican', 'https://house.texas.gov/images/members/4165.jpg?v=1', 'elected', NULL),
('Richard Raymond', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '42', NULL, 'Democratic', 'https://house.texas.gov/images/members/4215.jpg?v=1', 'elected', NULL),
('Robert Nichols', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '3', NULL, 'Republican', 'https://senate.texas.gov/members/d03/img/headshot.jpg', 'elected', NULL),
('Roland Gutierrez', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '19', NULL, 'Democratic', 'https://senate.texas.gov/members/d19/img/Gutierrez_87-0522D-016-Web.jpg', 'elected', NULL),
('Ron Reynolds', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '27', NULL, 'Democratic', 'https://house.texas.gov/images/members/2040.jpg?v=1', 'elected', NULL),
('Royce West', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '23', NULL, 'Democratic', 'https://senate.texas.gov/members/d23/img/West_87-0474D-015-web.jpg', 'elected', NULL),
('Ryan Guillen', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '31', NULL, 'Republican', 'https://house.texas.gov/images/members/3045.jpg?v=1', 'elected', NULL),
('Salman Bhojani', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '92', NULL, 'Democratic', 'https://house.texas.gov/images/members/4115.jpg?v=1', 'elected', NULL),
('Sam Harless', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '126', NULL, 'Republican', 'https://house.texas.gov/images/members/3775.jpg?v=1', 'elected', NULL),
('Sarah Eckhardt', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '14', NULL, 'Democratic', 'https://senate.texas.gov/members/d14/img/SE_headshot_2020.jpg', 'elected', NULL),
('Senfronia Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '141', NULL, 'Democratic', 'https://house.texas.gov/images/members/4630.jpg?v=1', 'elected', NULL),
('Sergio Muñoz', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '36', NULL, 'Democratic', 'https://house.texas.gov/images/members/2060.jpg?v=1', 'elected', NULL),
('Shelby Slawson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '59', NULL, 'Republican', 'https://house.texas.gov/images/members/4055.jpg?v=2', 'elected', NULL),
('Shelley Luther', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '62', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4645.jpg?v=1', 'elected', NULL),
('Sheryl Cole', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '46', NULL, 'Democratic', 'https://house.texas.gov/images/members/3625.jpg?v=2', 'elected', NULL),
('Stan Gerdes', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '17', NULL, 'Republican', 'https://house.texas.gov/images/members/4195.jpg?v=1', 'elected', NULL),
('Stan Kitzman', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '85', NULL, 'Republican', 'https://house.texas.gov/images/members/4280.jpg?v=1', 'elected', NULL),
('Stan Lambert', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '71', NULL, 'Republican', 'https://house.texas.gov/images/members/3225.jpg?v=1', 'elected', NULL),
('Steve Toth', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '15', NULL, 'Republican', 'https://house.texas.gov/images/members/2825.jpg?v=1', 'elected', NULL),
('Suleman Lalani', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '76', NULL, 'Democratic', 'https://house.texas.gov/images/members/4285.jpg?v=1', 'elected', NULL),
('Tan Parker', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '12', NULL, 'Republican', 'https://senate.texas.gov/members/d12/img/86_20190619_SAM_0008.jpg', 'elected', NULL),
('Taylor Rehmet', 'State Senator', 'Legislative Branch', 'Legislative', 'TX', '9', NULL, 'Democratic', 'https://senate.texas.gov/members/d09/img/Rehmet-89-0739D-017-web.jpg', 'elected', NULL),
('Terri Leo-Wilson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '23', NULL, 'Republican', 'https://house.texas.gov/images/members/4290.jpg?v=1', 'elected', NULL),
('Terry Canales', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '40', NULL, 'Democratic', 'https://house.texas.gov/images/members/2340.jpg', 'elected', NULL),
('Terry Wilson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '20', NULL, 'Republican', 'https://house.texas.gov/images/members/3525.jpg?v=1', 'elected', NULL),
('Terry Meza', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '105', NULL, 'Democratic', 'https://house.texas.gov/images/members/3455.jpg?v=1', 'elected', NULL),
('Todd Hunter', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '32', NULL, 'Republican', 'https://house.texas.gov/images/members/3365.jpg?v=1', 'elected', NULL),
('Tom Craddick', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '82', NULL, 'Republican', 'https://house.texas.gov/images/members/2610.jpg?v=1', 'elected', NULL),
('Tom Oliverson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '130', NULL, 'Republican', 'https://house.texas.gov/images/members/3535.jpg?v=1', 'elected', NULL),
('Toni Rose', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '110', NULL, 'Democratic', 'https://house.texas.gov/images/members/2555.jpg?v=3', 'elected', NULL),
('Tony Tinderholt', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '94', NULL, 'Republican', 'https://house.texas.gov/images/members/3065.jpg?v=1', 'elected', NULL),
('Trent Ashby', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '9', NULL, 'Republican', 'https://house.texas.gov/images/members/2330.jpg?v=1', 'elected', NULL),
('Trey Martinez Fischer', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '116', NULL, 'Democratic', 'https://house.texas.gov/images/members/2835.jpg?v=1', 'elected', NULL),
('Trey Wharton', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '12', NULL, 'Republican', 'https://house.texas.gov/images/members/4795.jpg?v=1', 'elected', NULL),
('Valoree Swanson', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '150', NULL, 'Republican', 'https://house.texas.gov/images/members/3425.jpg?v=1', 'elected', NULL),
('Venton Jones', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '100', NULL, 'Democratic', 'https://house.texas.gov/images/members/4275.jpg?v=1', 'elected', NULL),
('Vikki Goodwin', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '47', NULL, 'Democratic', 'https://house.texas.gov/images/members/3820.jpg?v=1', 'elected', NULL),
('Vince Perez', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '77', NULL, 'Democratic', 'https://www.house.texas.gov/images/members/4710.jpg?v=1', 'elected', NULL),
('Wes Virdell', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '53', NULL, 'Republican', 'https://www.house.texas.gov/images/members/4775.jpg?v=1', 'elected', NULL),
('Will Metcalf', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '16', NULL, 'Republican', 'https://house.texas.gov/images/members/2900.jpg?v=1', 'elected', NULL),
('Yvonne Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'TX', '111', NULL, 'Democratic', 'https://cdn.ballotpedia.org/images/thumb/0/06/Yvonne_Davis.jpg/200px-Yvonne_Davis.jpg', 'elected', NULL);
