-- UT state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'UT';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Cory Maloy', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '52', NULL, 'Republican', 'https://le.utah.gov/images/legislator/MALOYC.jpg', 'elected', NULL),
('Andrew Stoddard', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '40', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/STODDA.jpg', 'elected', NULL),
('Angela Romero', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '25', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/ROMERAY.jpg', 'elected', NULL),
('Ann Millner', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '5', NULL, 'Republican', 'https://le.utah.gov/images/legislator/MILLNA.jpg', 'elected', NULL),
('Anthony Loubet', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '27', NULL, 'Republican', 'https://le.utah.gov/images/legislator/LOUBEA.jpg', 'elected', NULL),
('Ariel Defay', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '15', NULL, 'Republican', 'https://le.utah.gov/images/legislator/DEFAYA.jpg', 'elected', NULL),
('Ashlee Matthews', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '37', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/MATTHA.jpg', 'elected', NULL),
('Brady Brammer', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '21', NULL, 'Republican', 'https://le.utah.gov/images/legislator/BRAMMB.jpg', 'elected', NULL),
('Bridger Bolinder', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '29', NULL, 'Republican', 'https://le.utah.gov/images/legislator/BOLINB.jpg', 'elected', NULL),
('Cal Roberts', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '46', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/CalRoberts2024.jpg', 'elected', NULL),
('Cal Musselman', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '4', NULL, 'Republican', 'https://le.utah.gov/images/legislator/MUSSECR.jpg', 'elected', NULL),
('Candice Pierucci', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '49', NULL, 'Republican', 'https://le.utah.gov/images/legislator/PIERUC.jpg', 'elected', NULL),
('Carl Albrecht', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '70', NULL, 'Republican', 'https://le.utah.gov/images/legislator/ALBRECR.jpg', 'elected', NULL),
('Carol Moss', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '34', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/MOSSCS.jpg', 'elected', NULL),
('Casey Snider', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '5', NULL, 'Republican', 'https://le.utah.gov/images/legislator/SNIDEC.jpg', 'elected', NULL),
('Cheryl Acton', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '38', NULL, 'Republican', 'https://le.utah.gov/images/legislator/ACTONCK.jpg', 'elected', NULL),
('Chris Wilson', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '2', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WILSOCH.jpg', 'elected', NULL),
('Christine Watkins', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '67', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WATKICF.jpg', 'elected', NULL),
('Clint Okerlund', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '42', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ClintOkerlund2024.jpeg', 'elected', NULL),
('Colin Jack', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '73', NULL, 'Republican', 'https://le.utah.gov/images/legislator/JACKC.jpg', 'elected', NULL),
('Dan McCay', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '18', NULL, 'Republican', 'https://le.utah.gov/images/legislator/MCCAYD.jpg', 'elected', NULL),
('Dave Shallenberger', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '58', NULL, 'Republican', 'https://assets.civicengine.com/uploads/candidate/headshot/414685/414685.jpg', 'elected', NULL),
('David Hinkins', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '26', NULL, 'Republican', 'https://le.utah.gov/images/legislator/HINKIDP.jpg', 'elected', NULL),
('Derrin Owens', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '27', NULL, 'Republican', 'https://le.utah.gov/images/legislator/OWENSD.jpg', 'elected', NULL),
('Don Ipson', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '29', NULL, 'Republican', 'https://le.utah.gov/images/legislator/IPSONDL.jpg', 'elected', NULL),
('Doug Fiefia', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '48', NULL, 'Republican', 'https://dougfiefia.com/wp-content/uploads/2023/11/Doug-Fiefia-header.png', 'elected', NULL),
('Doug Owens', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '33', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/OWENSDO.jpg', 'elected', NULL),
('Doug Welton', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '65', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WELTOD.jpg', 'elected', NULL),
('Emily Buss', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '11', NULL, 'Forward', NULL, 'elected', NULL),
('Evan Vickers', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '28', NULL, 'Republican', 'https://le.utah.gov/images/legislator/VICKEEJ.jpg', 'elected', NULL),
('Grant Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '24', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/gmiller2.jpg', 'elected', NULL),
('Grant Pace', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '60', NULL, 'Republican', 'https://cdn-hdbdp.nitrocdn.com/iWmKbInheBqiLbgJHQSBxQqpIXvFXnqc/assets/images/optimized/rev-e4f0a15/juuva.com/wp-content/uploads/2021/04/grant-portrait-1.jpg', 'elected', NULL),
('Heidi Balderree', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '22', NULL, 'Republican', 'https://le.utah.gov/images/legislator/BALDEH.jpg', 'elected', NULL),
('Hoang Nguyen', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '23', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/HoangNguyen2024.jpg', 'elected', NULL),
('Stuart Adams', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '7', NULL, 'Republican', 'https://le.utah.gov/images/legislator/ADAMSJS.jpg', 'elected', NULL),
('Jackie Larson', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '64', NULL, 'Republican', 'https://static.wixstatic.com/media/355155_bfae42d4d46d4e1f86e11a37eef18af1~mv2.jpeg/v1/fill/w_873,h_1484,fp_0.46_0.23,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/355155_bfae42d4d46d4e1f86e11a37eef18af1~mv2.jpeg', 'elected', NULL),
('Jake Fitisemanu', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '30', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JakeFitisemanu2024.jpg', 'elected', NULL),
('Jake Sawyer', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '9', NULL, 'Republican', 'https://static.wixstatic.com/media/d27656_26f8c475869649a59bad8ae179994b0f~mv2.jpg/v1/fill/w_317,h_383,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/Jake_Website_edited.jpg', 'elected', NULL),
('Jim Dunnigan', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '36', NULL, 'Republican', 'https://le.utah.gov/images/legislator/DUNNIJA.jpg', 'elected', NULL),
('Jason Kyle', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '8', NULL, 'Republican', 'https://le.utah.gov/images/legislator/KYLEJB.jpg', 'elected', NULL),
('Jason Thompson', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '3', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jason_Thompson2024.jpeg', 'elected', NULL),
('Jen Dailey-Provost', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '22', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/DAILEJ.jpg', 'elected', NULL),
('Jen Plumb', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '9', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/PLUMBJ.jpg', 'elected', NULL),
('Jerry Stevenson', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '6', NULL, 'Republican', 'https://le.utah.gov/images/legislator/STEVEJW.jpg', 'elected', NULL),
('Jill Koford', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '10', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JillKoford.jpg', 'elected', NULL),
('John Arthur', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '41', NULL, 'Democratic', NULL, 'elected', NULL),
('John Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '3', NULL, 'Republican', 'https://le.utah.gov/images/legislator/JOHNSJD.jpg', 'elected', NULL),
('Jon Hawkins', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '55', NULL, 'Republican', 'https://le.utah.gov/images/legislator/HAWKIJ.jpg', 'elected', NULL),
('Jordan Teuscher', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '44', NULL, 'Republican', 'https://le.utah.gov/images/legislator/TEUSCJ.jpg', 'elected', NULL),
('Joseph Elison', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '72', NULL, 'Republican', 'https://le.utah.gov/images/legislator/ELISOJ.jpg', 'elected', NULL),
('Karen Kwan', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '12', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/KWANK.jpg', 'elected', NULL),
('Karen Peterson', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '13', NULL, 'Republican', 'https://le.utah.gov/images/legislator/PETERK.jpg', 'elected', NULL),
('Karianne Lisonbee', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '14', NULL, 'Republican', 'https://le.utah.gov/images/legislator/LISONK.jpg', 'elected', NULL),
('Kathleen Riebe', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '15', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/RIEBEK.jpg', 'elected', NULL),
('Katy Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '11', NULL, 'Republican', 'https://le.utah.gov/images/legislator/HALLK.jpg', 'elected', NULL),
('Kay Christofferson', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '53', NULL, 'Republican', 'https://le.utah.gov/images/legislator/CHRISKJ.jpg', 'elected', NULL),
('Keith Grover', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '23', NULL, 'Republican', 'https://le.utah.gov/images/legislator/GROVEK.jpg', 'elected', NULL),
('Ken Ivory', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '39', NULL, 'Republican', 'https://le.utah.gov/images/legislator/IVORYK.jpg', 'elected', NULL),
('Keven Stratton', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '24', NULL, 'Republican', 'https://le.utah.gov/images/legislator/STRATKJ.jpg', 'elected', NULL),
('Kirk Cullimore', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '19', NULL, 'Republican', 'https://le.utah.gov/images/legislator/CULLIKA.jpg', 'elected', NULL),
('Kristen Chevrier', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '54', NULL, 'Republican', NULL, 'elected', NULL),
('Leah Hansen', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '51', NULL, 'Republican', NULL, 'elected', NULL),
('Lincoln Fillmore', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '17', NULL, 'Republican', 'https://le.utah.gov/images/legislator/FILLML.jpg', 'elected', NULL),
('Lisa Shepherd', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '61', NULL, 'Republican', 'https://img1.wsimg.com/isteam/ip/214c6333-69cf-4437-a4a5-149983b67c86/123-bKwEnQhUdpI%20(1)%202.JPEG/:/cr=t:2.05%25,l:12.92%25,w:73.53%25,h:73.53%25/rs=w:355,h:355,cg:true,m', 'elected', NULL),
('Logan Monson', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '69', NULL, 'Republican', 'https://images.squarespace-cdn.com/content/v1/653bf32647727060129bd0cf/f7061061-f68f-4697-9dc5-fd2bcc264299/IMG_7508.jpg', 'elected', NULL),
('Luz Escamilla', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '10', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/ESCAML.jpg', 'elected', NULL),
('Mark Strong', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '47', NULL, 'Republican', 'https://le.utah.gov/images/legislator/STRONMA.jpg', 'elected', NULL),
('Matt MacPherson', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '26', NULL, 'Republican', 'https://le.utah.gov/images/legislator/MACPHM.jpg', 'elected', NULL),
('Melissa Ballard', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '20', NULL, 'Republican', 'https://le.utah.gov/images/legislator/BALLAMG.jpg', 'elected', NULL),
('Mike McKell', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '25', NULL, 'Republican', 'https://le.utah.gov/images/legislator/MCKELMK.jpg', 'elected', NULL),
('Mike Kohler', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '59', NULL, 'Republican', 'https://le.utah.gov/images/legislator/KOHLEM.jpg', 'elected', NULL),
('Mike Petersen', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '2', NULL, 'Republican', 'https://le.utah.gov/images/legislator/PETERM.jpg', 'elected', NULL),
('Mike Schultz', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '12', NULL, 'Republican', 'https://le.utah.gov/images/legislator/SCHULM.jpg', 'elected', NULL),
('Nate Blouin', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '13', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/BLOUIN.jpg', 'elected', NULL),
('Nelson Abbott', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '57', NULL, 'Republican', 'https://le.utah.gov/images/legislator/ABBOTN.jpg', 'elected', NULL),
('Nicholeen Peck', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '28', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/NicholeenPeck2024c.jpg', 'elected', NULL),
('Norm Thurston', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '62', NULL, 'Republican', 'https://le.utah.gov/images/legislator/THURSNK.jpg', 'elected', NULL),
('Paul Cutler', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '18', NULL, 'Republican', 'https://le.utah.gov/images/legislator/CUTLEP.jpg', 'elected', NULL),
('Neil Walter', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '74', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WALTER.jpg', 'elected', NULL),
('Ray Ward', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '19', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WARDR.jpg', 'elected', NULL),
('Rex Shipp', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '71', NULL, 'Republican', 'https://le.utah.gov/images/legislator/SHIPPRP.jpg', 'elected', NULL),
('Rob Bishop', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '6', NULL, 'Republican', NULL, 'elected', NULL),
('Ron Winterton', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '20', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WINTER.jpg', 'elected', NULL),
('Rosalba Dominguez', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '35', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Rosalba_Dominguez_20240921_082723.jpeg', 'elected', NULL),
('Ryan Wilcox', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '7', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WILCORD.jpg', 'elected', NULL),
('Sahara Hayes', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '32', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/HAYESS.jpg', 'elected', NULL),
('Sandra Hollins', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '21', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/HOLLIS.jpg', 'elected', NULL),
('Scott Sandall', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '1', NULL, 'Republican', 'https://le.utah.gov/images/legislator/SANDASD.jpg', 'elected', NULL),
('Scott Chew', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '68', NULL, 'Republican', 'https://le.utah.gov/images/legislator/CHEWSH.jpg', 'elected', NULL),
('Stephanie Gricius', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '50', NULL, 'Republican', 'https://le.utah.gov/images/legislator/GRICIS.jpg', 'elected', NULL),
('Stephanie Pitcher', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '14', NULL, 'Democratic', 'https://le.utah.gov/images/legislator/PITCHS.jpg', 'elected', NULL),
('Stephen Whyte', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '63', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WHYTESL.jpg', 'elected', NULL),
('Steve Eliason', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '43', NULL, 'Republican', 'https://le.utah.gov/images/legislator/ELIASS.jpg', 'elected', NULL),
('Stewart Barlow', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '17', NULL, 'Republican', 'https://le.utah.gov/images/legislator/BARLOSE.jpg', 'elected', NULL),
('Tom Peterson', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '1', NULL, 'Republican', 'https://le.utah.gov/images/legislator/PETERT.jpg', 'elected', NULL),
('Tiara Auxier', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '4', NULL, 'Republican', 'https://le.utah.gov/images/legislator/house/AUXIET.jpg', 'elected', NULL),
('Todd Weiler', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '8', NULL, 'Republican', 'https://le.utah.gov/images/legislator/WEILET.jpg', 'elected', NULL),
('Tracy Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '45', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Tracy_Miller.jpeg', 'elected', NULL),
('Trevor Lee', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '16', NULL, 'Republican', 'https://le.utah.gov/images/legislator/LEETA.jpg', 'elected', NULL),
('Troy Shelley', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '66', NULL, 'Republican', 'https://cdn.prod.website-files.com/659704f376348afc7dd40409/670080f6423ccdeef1b4812e_Troy-Shelley.png', 'elected', NULL),
('Val Peterson', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '56', NULL, 'Republican', 'https://le.utah.gov/images/legislator/PETERVL.jpg', 'elected', NULL),
('Verona Mauga', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '31', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/VeronaMauga.jpg', 'elected', NULL),
('Walt Brooks', 'State Representative', 'Legislative Branch', 'Legislative', 'UT', '75', NULL, 'Republican', 'https://le.utah.gov/images/legislator/BROOKW.jpg', 'elected', NULL),
('Wayne Harper', 'State Senator', 'Legislative Branch', 'Legislative', 'UT', '16', NULL, 'Republican', 'https://le.utah.gov/images/legislator/HARPEWA.jpg', 'elected', NULL);
