-- VA state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'VA';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Aaron Rouse', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '22', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Rouse22', 'elected', NULL),
('Adele McClure', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '2', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0375', 'elected', NULL),
('Alex Askew', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '95', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0311', 'elected', NULL),
('Alfonso Lopez', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '3', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0239', 'elected', NULL),
('Amy Laufer', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '55', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0371', 'elected', NULL),
('Andrew Rice', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '98', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/AndrewRiceVA26.png', 'elected', NULL),
('Angelia Graves', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '21', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Williams%20Graves21', 'elected', NULL),
('Anne Ferrell Tata', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '99', NULL, 'Republican', 'https://house.vga.virginia.gov/delegate_photos/H0345.jpg', 'elected', NULL),
('Atoosa Reaser', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '27', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0380', 'elected', NULL),
('Barbara Favola', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '40', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Favola40', 'elected', NULL),
('Betsy Carr', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '78', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0212', 'elected', NULL),
('Bill DeSteph', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '20', NULL, 'Republican', 'https://apps.dlas.virginia.gov/senatepics/newbiopics/DeSteph08.jpg', 'elected', NULL),
('Bonita Anthony', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '92', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0353', 'elected', NULL),
('Briana Sewell', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '25', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0343', 'elected', NULL),
('Bryce Reeves', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '28', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Reeves28', 'elected', NULL),
('Cliff Hayes', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '91', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0285', 'elected', NULL),
('Charlie Schmidt', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '77', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0402.jpg', 'elected', NULL),
('Charniele Herring', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '4', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0208', 'elected', NULL),
('Chris Runion', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '35', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0321', 'elected', NULL),
('Christie Craig', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '19', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Craig19', 'elected', NULL),
('Chris Head', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '3', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Head3', 'elected', NULL),
('Dan Helmer', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '10', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0317', 'elected', NULL),
('Danica Roem', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '30', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Roem30', 'elected', NULL),
('David Reid', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '28', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0301', 'elected', NULL),
('David Suetterlein', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '4', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Suetterlein4', 'elected', NULL),
('Dave Marsden', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '35', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Marsden35', 'elected', NULL),
('Debra Gardner', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '76', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0361', 'elected', NULL),
('Delores McQuinn', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '81', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0207', 'elected', NULL),
('Delores Oates', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '31', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0377', 'elected', NULL),
('Destiny LeVere Bolling', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '80', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Destiny_LeVere_Bolling.jpg', 'elected', NULL),
('Don Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '88', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0322', 'elected', NULL),
('Elizabeth Bennett-Parker', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '39', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0334', 'elected', NULL),
('Liz Guzmán', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '22', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0297', 'elected', NULL),
('Ellen McLaughlin', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '36', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0350', 'elected', NULL),
('Emily Jordan', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '17', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Jordan17', 'elected', NULL),
('Eric Phillips', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '48', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0384', 'elected', NULL),
('Eric Zehr', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '51', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0383', 'elected', NULL),
('Garrett McGuire', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '17', NULL, 'Democratic', 'https://virginiamercury.com/wp-content/uploads/2026/01/611290992_122105542683186780_8562161094291278751_n.jpg', 'elected', NULL),
('Glen Sturtevant', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '12', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Sturtevant12', 'elected', NULL),
('Gretchen Bulova', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '11', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0403.jpg', 'elected', NULL),
('Otto Wachsmann', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '83', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0347', 'elected', NULL),
('Hillary Pugh Kent', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '67', NULL, 'Republican', 'https://static.wixstatic.com/media/8f5763_3acf103cae51400f8e2caa87b932d971~mv2.jpg/v1/fill/w_402,h_357,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/8f5763_3acf103cae51400f8e2caa87b932d971~mv2.jpg', 'elected', NULL),
('Holly Seibold', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '12', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0351', 'elected', NULL),
('Buddy Fowler', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '59', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0259', 'elected', NULL),
('Irene Shin', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '8', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0344', 'elected', NULL),
('Israel O''Quinn', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '44', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0242', 'elected', NULL),
('Danny Diggs', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '24', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/DiggsDanny.jpg', 'elected', NULL),
('J.J. Singh', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '26', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0385', 'elected', NULL),
('Jackie Glass', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '93', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0349', 'elected', NULL),
('Jay Leftwich', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '90', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0262', 'elected', NULL),
('Will Morefield', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '43', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0224', 'elected', NULL),
('Jason Ballard', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '42', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0333', 'elected', NULL),
('Jeion Ward', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '87', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0173', 'elected', NULL),
('Jennifer Boysko', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '38', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Boysko38', 'elected', NULL),
('Jennifer Carroll Foy', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '33', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Carroll%20Foy33', 'elected', NULL),
('Jeremy McPike', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '29', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/McPike29.jpg', 'elected', NULL),
('Jessica Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '71', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jessica_Anderson_20251008_030628.jpg', 'elected', NULL),
('John McAuliff', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '30', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0395.jpg', 'elected', NULL),
('Joe McNamara', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '40', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0308', 'elected', NULL),
('Josh Thomas', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '21', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Thomas_Headshot_HiRes-1-edited-1536x1536.jpg', 'elected', NULL),
('Josh Cole', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '65', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0314', 'elected', NULL),
('Justin Pence', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '33', NULL, 'Republican', 'https://house.vga.virginia.gov/delegate_photos/H0398.jpg', 'elected', NULL),
('Kacey Carnegie', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '89', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0387.jpg', 'elected', NULL),
('Kannan Srinivasan', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '32', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0381', 'elected', NULL),
('Karen Hamilton', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '62', NULL, 'Republican', 'https://house.vga.virginia.gov/delegate_photos/H0394.jpg', 'elected', NULL),
('Karen Keys-Gamarra', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '7', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0370', 'elected', NULL),
('Karrie Delaney', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '9', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0294', 'elected', NULL),
('Kathy Tran', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '18', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0305', 'elected', NULL),
('Katrina Callsen', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '54', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0354', 'elected', NULL),
('Kelly Fowler', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '96', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0295', 'elected', NULL),
('Kim Adams', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '82', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0399.jpg', 'elected', NULL),
('Kirk McPike', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '5', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0406.jpg', 'elected', NULL),
('Louise Lucas', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '18', NULL, 'Democratic', 'https://apps.dlas.virginia.gov/senatepics/newbiopics/Lucas2018.jpg', 'elected', NULL),
('Lamont Bagby', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '14', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Bagby14', 'elected', NULL),
('Lashrecse Aird', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '13', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Aird13', 'elected', NULL),
('Laura Jane Cohen', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '15', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/LauraJaneCohen.jpg', 'elected', NULL),
('Leslie Mehta', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '73', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0396.jpg', 'elected', NULL),
('Lily Franklin', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '41', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0393.jpg', 'elected', NULL),
('Lindsey Dougherty', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '75', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0391.jpg', 'elected', NULL),
('Luke Torian', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '24', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0227', 'elected', NULL),
('Luther Cifers', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '10', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Cifers10', 'elected', NULL),
('Keith Hodges', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '68', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0238', 'elected', NULL),
('Madison Whittle', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '49', NULL, 'Republican', 'https://house.vga.virginia.gov/delegate_photos/H0401.jpg', 'elected', NULL),
('Mamie Locke', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '23', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Locke23', 'elected', NULL),
('Cia Price', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '85', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0284', 'elected', NULL),
('Marcus Simon', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '13', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0264', 'elected', NULL),
('Margaret Franklin', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '23', NULL, 'Democratic', 'https://www.pwcva.gov/assets/2024-01/dsc_6818retouch.jpg', 'elected', NULL),
('Mark Obenshain', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '2', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Obenshain2', 'elected', NULL),
('Mark Downey', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '69', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0392.jpg', 'elected', NULL),
('Mark Peake', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '8', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Peake8', 'elected', NULL),
('Marty Martinez', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '29', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0374', 'elected', NULL),
('May Nivar', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '57', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0397.jpg', 'elected', NULL),
('Michael Feggans', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '97', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/598f6428d482e9b47f6c2f82/56c91f83-d16a-4ba2-adcb-75d312e265bd/Michael_Feggans_HD97.jpeg', 'elected', NULL),
('Mike Jones', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '15', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Jones15', 'elected', NULL),
('Mike Webert', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '61', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0247', 'elected', NULL),
('Mike Cherry', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '74', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0335', 'elected', NULL),
('Mitchell Cornett', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '46', NULL, 'Republican', 'https://house.vga.virginia.gov/delegate_photos/H0390.jpg', 'elected', NULL),
('Nadarius Clark', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '84', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0336', 'elected', NULL),
('Nicole Cole', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '66', NULL, 'Democratic', 'https://static.wixstatic.com/media/b64009_9f1620ff00c14cdcbfec5e257ba8edd7~mv2.jpg/v1/crop/x_0,y_0,w_2870,h_3177/fill/w_382,h_478,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/IMG_0348_EDIT.jpg', 'elected', NULL),
('Patrick Hope', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '1', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0219', 'elected', NULL),
('Paul Krizek', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '16', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0281', 'elected', NULL),
('Phil Hernandez', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '94', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0366', 'elected', NULL),
('Phil Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '63', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0342', 'elected', NULL),
('Creigh Deeds', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '11', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Deeds11', 'elected', NULL),
('Lee Ware', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '72', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0124', 'elected', NULL),
('Rae Cousins', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '79', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0356.jpg', 'elected', NULL),
('Rip Sullivan', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '6', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0269', 'elected', NULL),
('Richard Stuart', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '25', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Stuart25', 'elected', NULL),
('Rob Bloxom', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '100', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0267', 'elected', NULL),
('Rod Willett', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '58', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0327', 'elected', NULL),
('J.R. Henson', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '19', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0365', 'elected', NULL),
('Russet Perry', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '31', NULL, 'Democratic', 'https://cdn.runforsomething.net/candidates/2023/04/campaign/3388.jpg', 'elected', NULL),
('Ryan McDougle', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '26', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/McDougle26', 'elected', NULL),
('Saddam Salim', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '37', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Salim37', 'elected', NULL),
('Sam Rasoul', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '38', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0266', 'elected', NULL),
('Schuyler VanValkenburg', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '16', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/VanValkenburg16', 'elected', NULL),
('Scott Surovell', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '34', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Surovell34', 'elected', NULL),
('Scott Wyatt', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '60', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0328', 'elected', NULL),
('Shelly Simonds', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '70', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0323', 'elected', NULL),
('Stacey Carroll', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '64', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0388.jpg', 'elected', NULL),
('Stella Pekarsky', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '36', NULL, 'Democratic', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Pekarsky36', 'elected', NULL),
('Travis Hackworth', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '5', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Hackworth5', 'elected', NULL),
('Tammy Mulchi', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '9', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Mulchi9', 'elected', NULL),
('Tara Durant', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '27', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Durant27', 'elected', NULL),
('Terry Kilgore', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '45', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0056', 'elected', NULL),
('Terry Austin', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '37', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0253', 'elected', NULL),
('Tommy Wright', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '50', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0136', 'elected', NULL),
('Tim Griffin', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '53', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0364', 'elected', NULL),
('Timmy French', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '1', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/TimmyFrench2023.jpg', 'elected', NULL),
('Todd Pillion', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '6', NULL, 'Republican', 'https://apps.senate.virginia.gov/Senator/images/member_photos/Pillion6', 'elected', NULL),
('Tom Garrett', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '56', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0362', 'elected', NULL),
('Tony Wilt', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '34', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0231', 'elected', NULL),
('Virgil Thornton', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '86', NULL, 'Democratic', 'https://house.vga.virginia.gov/delegate_photos/H0400.jpg', 'elected', NULL),
('Vivian Watts', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '14', NULL, 'Democratic', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0108', 'elected', NULL),
('Wendell Walker', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '52', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0325', 'elected', NULL),
('Will Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '39', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0357', 'elected', NULL),
('Bill Stanley', 'State Senator', 'Legislative Branch', 'Legislative', 'VA', '7', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Bill_Stanley.jpg', 'elected', NULL),
('Bill Wiley', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '32', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0329', 'elected', NULL),
('Wren Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'VA', '47', NULL, 'Republican', 'https://memdata.virginiageneralassembly.gov/images/display_image/H0348', 'elected', NULL);
