-- WA state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'WA';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Adam Bernbaum', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '24', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34240.jpg', 'elected', NULL),
('Adison Richards', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '26', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/20893.jpg', 'elected', NULL),
('Adrian Cortes', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '18', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35473.jpg', 'elected', NULL),
('Alex Ramel', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '40', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/30127.jpg', 'elected', NULL),
('Alex Ybarra', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '13', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/29318.jpg', 'elected', NULL),
('Alicia Rule', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '42', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/31533.jpg', 'elected', NULL),
('Amy Walen', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '48', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29109.jpg', 'elected', NULL),
('Andrew Barkis', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '2', NULL, 'Republican', 'https://andrewbarkis.houserepublicans.wa.gov/wp-content/uploads/2025/01/Rep-Barkis_Andrew-2025_900x1200.jpg', 'elected', NULL),
('Andrew Engell', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '7', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/35409.jpg', 'elected', NULL),
('Annette Cleveland', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '49', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/17294.jpg', 'elected', NULL),
('April Berg', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '44', NULL, 'Democratic', 'https://housedemocrats.wa.gov/tmp/2021/01/Rep-Berg_April-2021_150x200.jpg', 'elected', NULL),
('April Connors', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '8', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/34027.jpg', 'elected', NULL),
('Beth Doglio', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '22', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/26175.jpg', 'elected', NULL),
('Bob Hasegawa', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '11', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/10030.jpg', 'elected', NULL),
('Brandy Donaghy', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '44', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/33818.jpg', 'elected', NULL),
('Brian Burnett', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '12', NULL, 'Republican', 'https://brianburnett.houserepublicans.wa.gov/wp-content/uploads/2025/01/Rep-Burnett_Brian-2025_900x1200.jpg', 'elected', NULL),
('Brianna Thomas', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '34', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/15410.jpg', 'elected', NULL),
('Carolyn Eslick', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '39', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/27988.jpg', 'elected', NULL),
('Chipalo Street', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '37', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34036.jpg', 'elected', NULL),
('Chris Corry', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '15', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/29097.jpg', 'elected', NULL),
('Chris Gildon', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '25', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/29101.jpg', 'elected', NULL),
('Chris Stearns', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '47', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34023.jpg', 'elected', NULL),
('Cindy Ryu', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '32', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/15736.jpg', 'elected', NULL),
('Claire Wilson', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '30', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29090.jpg', 'elected', NULL),
('Claudia Kauffman', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '47', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/12073.jpg', 'elected', NULL),
('Clyde Shavers', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '10', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34050.jpg', 'elected', NULL),
('Curtis King', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '14', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/13199.jpg', 'elected', NULL),
('Cyndy Jacobsen', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '25', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/31528.jpg', 'elected', NULL),
('Dan Bronoske', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '28', NULL, 'Democratic', 'https://housedemocrats.wa.gov/tmp/sites/68/2021/12/20211005_154818cr_crop.jpg', 'elected', NULL),
('Dan Griffey', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '35', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/20752.jpg', 'elected', NULL),
('Darya Farivar', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '46', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34030.jpg', 'elected', NULL),
('Dave Paul', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '10', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29095.jpg', 'elected', NULL),
('Dave Stuebe', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '17', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/35431.jpg', 'elected', NULL),
('David Hackney', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '11', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/31523.jpg', 'elected', NULL),
('Davina Duerr', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '1', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29877.jpg', 'elected', NULL),
('Deb Krishnadasan', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '26', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35470.jpg', 'elected', NULL),
('Deb Manjarrez', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '14', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/35412.jpg', 'elected', NULL),
('Debra Entenman', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '47', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/11403.jpg', 'elected', NULL),
('Debra Lekanoff', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '40', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29106.jpg', 'elected', NULL),
('Derek Stanford', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '1', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/15809.jpg', 'elected', NULL),
('Drew Hansen', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '23', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/16499.jpg', 'elected', NULL),
('Drew MacEwen', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '35', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/17221.jpg', 'elected', NULL),
('Drew Stokesbary', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '31', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/20756.jpg', 'elected', NULL),
('Ed Orcutt', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '20', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/7635.jpg', 'elected', NULL),
('Edwin Obras', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '33', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35464.jpg', 'elected', NULL),
('Emily Alvarado', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '34', NULL, 'Democratic', 'https://senatedemocrats.wa.gov/alvarado/wp-content/uploads/sites/23/2025/03/Rep-Alvarado_Emily-2023_900x1200.jpg', 'elected', NULL),
('Gerry Pollet', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '46', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/16596.jpg', 'elected', NULL),
('Gloria Mendoza', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '14', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/35414.jpg', 'elected', NULL),
('Greg Nance', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '23', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34760.jpg', 'elected', NULL),
('Hunter Abell', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '7', NULL, 'Republican', 'https://hunterabell.houserepublicans.wa.gov/wp-content/uploads/2025/01/Rep-Abell_Hunter-2025_900x1200.jpg', 'elected', NULL),
('Jake Fey', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '27', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/17241.jpg', 'elected', NULL),
('Jamie Pedersen', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '43', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/12002.jpg', 'elected', NULL),
('Jamila Taylor', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '30', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/31530.jpg', 'elected', NULL),
('Janice Zahn', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '41', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35736.jpg', 'elected', NULL),
('Javier Valdez', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '46', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/27975.jpg', 'elected', NULL),
('Jeff Holy', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '6', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/17223.jpg', 'elected', NULL),
('Jeff Wilson', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '19', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/31537.jpg', 'elected', NULL),
('Jenny Graham', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '6', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/29093.jpg', 'elected', NULL),
('Jeremie Dufault', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '15', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/29098.jpg', 'elected', NULL),
('Jesse Salomon', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '32', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29089.jpg', 'elected', NULL),
('Jess Bateman', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '22', NULL, 'Democratic', 'https://housedemocrats.wa.gov/tmp/2021/01/Rep-Bateman_Jessica-2021_150x200.jpg', 'elected', NULL),
('Jim McCune', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '2', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/2584.jpg', 'elected', NULL),
('Jim Walsh', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '19', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/27181.jpg', 'elected', NULL),
('Joe Fitzgibbon', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '34', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/13198.jpg', 'elected', NULL),
('Joe Schmick', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '9', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/13209.jpg', 'elected', NULL),
('Joe Timmons', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '42', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34037.jpg', 'elected', NULL),
('Joel McEntire', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '19', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/31525.jpg', 'elected', NULL),
('John Braun', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '20', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/17289.jpg', 'elected', NULL),
('John Ley', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '18', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/35422.jpg', 'elected', NULL),
('John Lovick', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '44', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/3476.jpg', 'elected', NULL),
('Josh Penner', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '31', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/35416.jpg', 'elected', NULL),
('Judy Warnick', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '13', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/12084.jpg', 'elected', NULL),
('Julia Reed', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '36', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34033.jpg', 'elected', NULL),
('Julio Cortes', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '38', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/34028.jpg', 'elected', NULL),
('June Robinson', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '38', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/18265.jpg', 'elected', NULL),
('Keith Goehner', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '12', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/29096.jpg', 'elected', NULL),
('Keith Wagoner', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '39', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/28317.jpg', 'elected', NULL),
('Kevin Waters', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '17', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/34038.jpg', 'elected', NULL),
('Kristine Reeves', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '30', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/27182.jpg', 'elected', NULL),
('Larry Springer', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '45', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/10039.jpg', 'elected', NULL),
('Lauren Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '32', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29104.jpg', 'elected', NULL),
('Laurie Jinkins', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '27', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/15817.jpg', 'elected', NULL),
('Leonard Christian', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '4', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/18458.jpg', 'elected', NULL),
('Lillian Ortiz-Self', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '21', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/18546.jpg', 'elected', NULL),
('Lisa Callan', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '5', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29092.jpg', 'elected', NULL),
('Lisa Parshley', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '22', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35415.jpg', 'elected', NULL),
('Lisa Wellman', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '41', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/27211.jpg', 'elected', NULL),
('Liz Berry', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '36', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/31531.jpg', 'elected', NULL),
('Liz Lovelett', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '40', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29548.jpg', 'elected', NULL),
('Manka Dhingra', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '45', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/28022.jpg', 'elected', NULL),
('Marcus Riccelli', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '3', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/15706.jpg', 'elected', NULL),
('Mari Leavitt', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '28', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29102.jpg', 'elected', NULL),
('Mark Klicker', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '16', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/31524.jpg', 'elected', NULL),
('Mark Schoesler', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '9', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/652.jpg', 'elected', NULL),
('Marko Liias', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '21', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/13546.jpg', 'elected', NULL),
('Mary Dye', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '9', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/21490.jpg', 'elected', NULL),
('Mary Fosse', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '38', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/31542.jpg', 'elected', NULL),
('Matt Boehnke', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '8', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/29094.jpg', 'elected', NULL),
('Matt Marshall', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '2', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/35413.jpg', 'elected', NULL),
('Melanie Morgan', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '29', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29103.jpg', 'elected', NULL),
('Mia Gregerson', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '33', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/18264.jpg', 'elected', NULL),
('Michael Keaton', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '25', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/35411.jpg', 'elected', NULL),
('Michelle Valdez', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '26', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/20760.jpg', 'elected', NULL),
('Mike Chapman', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '24', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/26176.jpg', 'elected', NULL),
('Mike Steele', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '12', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/10546.jpg', 'elected', NULL),
('Mike Volz', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '6', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/26170.jpg', 'elected', NULL),
('Monica Stonier', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '49', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/17279.jpg', 'elected', NULL),
('My-Linh Thai', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '41', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29107.jpg', 'elected', NULL),
('Natasha Hill', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '3', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35429.jpg', 'elected', NULL),
('Nicole Macri', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '43', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/26178.jpg', 'elected', NULL),
('Nikki Torres', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '15', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/34047.jpg', 'elected', NULL),
('Noel Frame', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '36', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/23902.jpg', 'elected', NULL),
('Osman Salahuddin', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '48', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35655.jpg', 'elected', NULL),
('Paul Harris', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '17', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/15813.jpg', 'elected', NULL),
('Perry Dozier', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '16', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/31535.jpg', 'elected', NULL),
('Peter Abbarno', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '20', NULL, 'Republican', 'https://peterabbarno.houserepublicans.wa.gov/wp-content/uploads/sites/83/2021/01/Rep-Abbarno_Peter-2021_465x754.jpg', 'elected', NULL),
('Phil Fortunato', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '31', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/3474.jpg', 'elected', NULL),
('Rebecca Saldaña', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '37', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/27290.jpg', 'elected', NULL),
('Rob Chase', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '4', NULL, 'Republican', 'https://robchase.houserepublicans.wa.gov/wp-content/uploads/2025/01/Rep-Chase_Rob-2025_900x1200.jpg', 'elected', NULL),
('Roger Goodman', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '45', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/11999.jpg', 'elected', NULL),
('Ron Muzzall', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '10', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/29908.jpg', 'elected', NULL),
('Sam Low', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '39', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/34031.jpg', 'elected', NULL),
('Sharlett Mena', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '29', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/27494.jpg', 'elected', NULL),
('Sharon Shewmake', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '42', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/29108.jpg', 'elected', NULL),
('Sharon Tomiko Santos', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '37', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/3483.jpg', 'elected', NULL),
('Sharon Wylie', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '49', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/16462.jpg', 'elected', NULL),
('Shaun Scott', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '43', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35430.jpg', 'elected', NULL),
('Shelley Kloba', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '1', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/26168.jpg', 'elected', NULL),
('Shelly Short', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '7', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/11952.jpg', 'elected', NULL),
('Skyler Rude', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '16', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/20837.jpg', 'elected', NULL),
('Stephanie Barnard', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '8', NULL, 'Republican', 'https://stephaniebarnard.houserepublicans.wa.gov/wp-content/uploads/2025/01/Rep-Barnard_Stephanie-2025_900x1200.jpg', 'elected', NULL),
('Stephanie McClintock', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '18', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/34032.jpg', 'elected', NULL),
('Steve Bergquist', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '11', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/17227.jpg', 'elected', NULL),
('Steve Conway', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '29', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/972.jpg', 'elected', NULL),
('Steve Tharinger', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '24', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/15816.jpg', 'elected', NULL),
('Strom Peterson', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '21', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/20755.jpg', 'elected', NULL),
('Suzanne Schmidt', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '4', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/34035.jpg', 'elected', NULL),
('Tarra Simmons', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '23', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/31527.jpg', 'elected', NULL),
('Timm Ormsby', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '3', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/9207.jpg', 'elected', NULL),
('Tina Orwall', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '33', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/14205.jpg', 'elected', NULL),
('Tom Dent', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '13', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/20761.jpg', 'elected', NULL),
('Travis Couture', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '35', NULL, 'Republican', 'https://leg.wa.gov/memberphoto/34029.jpg', 'elected', NULL),
('T''wina Nobles', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '28', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/31536.jpg', 'elected', NULL),
('Vandana Slatter', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '48', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/27504.jpg', 'elected', NULL),
('Victoria Hunt', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '5', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/35410.jpg', 'elected', NULL),
('Yasmin Trudeau', 'State Senator', 'Legislative Branch', 'Legislative', 'WA', '27', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/20732.jpg', 'elected', NULL),
('Zach Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'WA', '5', NULL, 'Democratic', 'https://leg.wa.gov/memberphoto/27391.jpg', 'elected', NULL);
