-- WI state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'WI';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Adam Neylon', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '15', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2492.jpg', 'elected', NULL),
('Alex Dallman', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '39', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2459.jpg', 'elected', NULL),
('Alex Joers', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '81', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2553.jpg', 'elected', NULL),
('Amaad Rivera-Wagner', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '90', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/66195445b4b9aa03925c9d90/46c6514c-c52c-4199-b161-75528cc53721/Amaad+2024-2.jpg', 'elected', NULL),
('Amanda Nedweski', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '32', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2551.jpg', 'elected', NULL),
('André Jacque', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '1', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2419.jpg', 'elected', NULL),
('Andrew Hysell', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '48', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ahysell2.jpg', 'elected', NULL),
('Angela Stroud', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '73', NULL, 'Democratic', 'https://www.northland.edu/wp-content/uploads/2015/08/AngelaStroud-800x800.jpg', 'elected', NULL),
('Angelina Cruz', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '62', NULL, 'Democratic', 'https://victoryfund.org/wp-content/uploads/2024/06/AC-headshot-scaled-e1719503338133-500x500-250x250.jpeg', 'elected', NULL),
('Angelito Tenorio', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '14', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Sep2720211220PM_104500298_AngelitoHeadshot.jpg', 'elected', NULL),
('Ann Roe', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '44', NULL, 'Democratic', NULL, 'elected', NULL),
('Barbara Dittrich', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '99', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2460.jpg', 'elected', NULL),
('Ben DeSmidt', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '65', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Ben_DeSmidt_20240808_100327.jpeg', 'elected', NULL),
('Ben Franklin', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '88', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/BenFranklin2024.png', 'elected', NULL),
('Bob Donovan', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '61', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2555.jpg', 'elected', NULL),
('Brad Pfaff', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '32', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2429.jpg', 'elected', NULL),
('Brent Jacobson', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '87', NULL, 'Republican', 'https://jacobsonforassembly.com/wp-content/uploads/2024/03/IMG_0484.png', 'elected', NULL),
('Brienne Brown', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '43', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Brienne_Brown.jpg', 'elected', NULL),
('Calvin Callahan', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '35', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2456.jpg', 'elected', NULL),
('Chanz Green', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '74', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2558.jpg', 'elected', NULL),
('Chris Kapenga', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '33', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2422.jpg', 'elected', NULL),
('Chris Larson', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '7', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2424.jpg', 'elected', NULL),
('Christian Phelps', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '93', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/ChristianPhelps24.jpg', 'elected', NULL),
('Christine Sinicki', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '20', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2512.jpg', 'elected', NULL),
('Chuck Wichgers', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '84', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2556.jpg', 'elected', NULL),
('Cindi Duchow', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '97', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2463.jpg', 'elected', NULL),
('Clint Moses', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '92', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2487.jpg', 'elected', NULL),
('Clint Anderson', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '45', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2559.jpg', 'elected', NULL),
('Cory Tomczyk', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '29', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2567.jpg', 'elected', NULL),
('Dan Feyen', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '20', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2418.jpg', 'elected', NULL),
('Dan Knodl', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '24', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2688.jpg', 'elected', NULL),
('Darrin Madison', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '10', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2536.jpg', 'elected', NULL),
('Dave Maxey', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '83', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2537.jpg', 'elected', NULL),
('Dave Armstrong', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '67', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2444.jpg', 'elected', NULL),
('Dave Murphy', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '56', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2488.jpg', 'elected', NULL),
('David Steffen', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '4', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2519.jpg', 'elected', NULL),
('Dean Kaufert', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '53', NULL, 'Republican', 'http://legis.wisconsin.gov/sitecollectionimages/2013/asm55.jpeg', 'elected', NULL),
('Deb Andraca', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '23', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2443.jpg', 'elected', NULL),
('Devin LeMahieu', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '9', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2425.jpg', 'elected', NULL),
('Dianne Hesselbein', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '27', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2566.jpg', 'elected', NULL),
('Dora Drake', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '4', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2462.jpg', 'elected', NULL),
('Duke Tucker', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '75', NULL, 'Republican', 'https://dukeforwisconsin.com/wp-content/uploads/2024/03/IMG_0256-scaled.jpg', 'elected', NULL),
('Elijah Behnke', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '6', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2447.jpg', 'elected', NULL),
('Eric Wimberger', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '2', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2439.jpg', 'elected', NULL),
('Francesca Hong', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '76', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2472.jpg', 'elected', NULL),
('Greta Neubauer', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '66', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2491.jpg', 'elected', NULL),
('Howard Marklein', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '17', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2426.jpg', 'elected', NULL),
('Jamie Wall', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '30', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/JamieWall2024.jpg', 'elected', NULL),
('Jeff Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '31', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2433.jpg', 'elected', NULL),
('Jeff Mursau', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '36', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2489.jpg', 'elected', NULL),
('Jenna Jacobson', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '50', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2545.jpg', 'elected', NULL),
('Jerry O''Connor', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '60', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2549.jpg', 'elected', NULL),
('Jesse James', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '23', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2563.jpg', 'elected', NULL),
('Jessie Rodriguez', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '21', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2505.jpg', 'elected', NULL),
('Jill Billings', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '95', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2448.jpg', 'elected', NULL),
('Jim Piwowarczyk', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '98', NULL, 'Republican', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jim_Piwowarczyk_20240814_075459.jpg', 'elected', NULL),
('Joan Fitzgerald', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '46', NULL, 'Democratic', 'https://images.squarespace-cdn.com/content/v1/65b3fbbf2b490f4bfe76c24e/6ba4a753-b2b3-4338-a77b-0f73f067f2cb/JoanFitzgerald%2857of76%29.jpg?format=1500w', 'elected', NULL),
('Jodi Emerson', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '91', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2465.jpg', 'elected', NULL),
('Jodi Habush Sinykin', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '8', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Jodi_Habush_Sinykin.PNG', 'elected', NULL),
('Joe Sheehan', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '26', NULL, 'Democratic', 'https://sheehanforassembly.com/wp-content/uploads/2024/08/Joe_Sheehan-scaled-e1724167126836-1024x825.jpeg', 'elected', NULL),
('Joel Kitchens', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '1', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2476.jpg', 'elected', NULL),
('John Jagler', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '13', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2420.jpg', 'elected', NULL),
('John Spiros', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '86', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2517.jpg', 'elected', NULL),
('Joy Goeben', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '5', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2542.jpg', 'elected', NULL),
('Julian Bradley', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '28', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2412.jpg', 'elected', NULL),
('Kalan Haywood', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '16', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2468.jpg', 'elected', NULL),
('Karen DeSanto', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '40', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Karen_DeSanto_20241106_112902.jpg', 'elected', NULL),
('Karen Hurd', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '69', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2552.jpg', 'elected', NULL),
('Karen Kirsch', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '7', NULL, 'Democratic', 'https://shepherdexpress.com/downloads/66652/download/Karen-Kirsch.jpg?cb=13a333d591ca9798f5ad320c3b7ce126&w=1200&h=', 'elected', NULL),
('Kelda Roys', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '26', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2432.jpg', 'elected', NULL),
('Kevin Petersen', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '57', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2498.jpg', 'elected', NULL),
('Kristin Dassler-Alfheim', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '18', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/KristinAlfheim2024.jpeg', 'elected', NULL),
('LaTonya Johnson', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '6', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2421.jpg', 'elected', NULL),
('Lee Snodgrass', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '52', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2514.jpg', 'elected', NULL),
('Lindee Brill', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '27', NULL, 'Republican', 'https://static.wixstatic.com/media/3d690d_54cafbce3962411589e2a2742be35965~mv2.jpg/v1/fill/w_489,h_634,al_c,lg_1,q_80,enc_avif,quality_auto/3d690d_54cafbce3962411589e2a2742be35965~mv2.jpg', 'elected', NULL),
('Lisa Subeck', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '79', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2521.jpg', 'elected', NULL),
('Lori Palmeri', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '54', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2547.jpg', 'elected', NULL),
('Margaret Arney', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '18', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Brennan_Balestrieri_20240808_094539.jpg', 'elected', NULL),
('Mark Born', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '37', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2449.jpg', 'elected', NULL),
('Mark Spreitzer', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '15', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2561.jpg', 'elected', NULL),
('Mary Felzkowski', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '12', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2417.jpg', 'elected', NULL),
('Maureen McCarville', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '42', NULL, 'Democratic', 'https://static1.squarespace.com/static/661c4ad59cca8c36cee06052/t/6630dc1cdd4eb0334f4f6768/1714478116835/MaureenMcCarville_AD42_Headshot.JPG', 'elected', NULL),
('Melissa Ratcliff', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '16', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2546.jpg', 'elected', NULL),
('Mike Bare', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '80', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2554.jpg', 'elected', NULL),
('Nancy VanderMeer', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '70', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2529.jpg', 'elected', NULL),
('Gus Gustafson', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '55', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2550.jpg', 'elected', NULL),
('Pat Snyder', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '85', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2515.jpg', 'elected', NULL),
('Patrick Testin', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '24', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2437.jpg', 'elected', NULL),
('Paul Melotik', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '22', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2690.jpg', 'elected', NULL),
('Paul Tittl', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '25', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2526.jpg', 'elected', NULL),
('Priscilla Prado', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '9', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/PriscillaPrado2024.jpeg', 'elected', NULL),
('Rachael Cabral-Guevara', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '19', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2562.jpg', 'elected', NULL),
('Randy Udell', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '47', NULL, 'Democratic', 'https://bloximages.chicago2.vip.townnews.com/captimes.com/content/tncms/assets/v3/editorial/c/7b/c7b832ac-dbcf-11ee-ab35-771e1438be52/65e88e3c05aed.image.jpg?crop=1163%2C871%2C26%2C52&resize=668%2C500&order=crop%2Cresize', 'elected', NULL),
('Renuka Mayadev', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '77', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Renuka_Mayadev_20240808_092901.jpg', 'elected', NULL),
('Rick Gundrum', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '58', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2467.jpg', 'elected', NULL),
('Rob Hutton', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '5', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2560.jpg', 'elected', NULL),
('Rob Kreibich', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '28', NULL, 'Republican', 'https://www.kreibichforassembly.com/hobenug/themes/kreibich-wi/assets/kreibich_1.jpg', 'elected', NULL),
('Rob Stafsholt', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '10', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2434.jpg', 'elected', NULL),
('Rob Summerfield', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '68', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2522.jpg', 'elected', NULL),
('Rob Swearingen', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '34', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2523.jpg', 'elected', NULL),
('Rob Brooks', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '59', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2452.jpg', 'elected', NULL),
('Bob Wirch', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '22', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2440.jpg', 'elected', NULL),
('Bob Wittke', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '63', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2534.jpg', 'elected', NULL),
('Robin Vos', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '33', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2531.jpg', 'elected', NULL),
('Robyn Vining', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '13', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2530.jpg', 'elected', NULL),
('Romaine Quinn', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '25', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2564.jpg', 'elected', NULL),
('Ron Tusler', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '3', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2528.jpg', 'elected', NULL),
('Russell Goodwin', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '12', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/rg.jpeg', 'elected', NULL),
('Ryan Clancy', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '19', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2538.jpg', 'elected', NULL),
('Ryan Spaude', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '89', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Ryan_Spaude_20240808_093050.jpg', 'elected', NULL),
('Sarah Keyeski', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '14', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/SarahKeyeski24.jpg', 'elected', NULL),
('Scott Allen', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '82', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2441.jpg', 'elected', NULL),
('Scott Krug', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '72', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2478.jpg', 'elected', NULL),
('Sequanna Taylor', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '11', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/IMG_5830-min.JPG', 'elected', NULL),
('Shae Sortwell', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '2', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2516.jpg', 'elected', NULL),
('Shannon Zimmerman', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '30', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2535.jpg', 'elected', NULL),
('Shelia Stubbs', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '78', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2520.jpg', 'elected', NULL),
('Steve Nass', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '11', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2427.jpg', 'elected', NULL),
('Steve Doyle', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '94', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2461.jpg', 'elected', NULL),
('Supreme Moore Omokunde', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '17', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2486.jpg', 'elected', NULL),
('Sylvia Ortiz-Velez', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '8', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2496.jpg', 'elected', NULL),
('Tara Johnson', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '96', NULL, 'Democratic', 'https://wisconsinpublictv.s3.us-east-2.amazonaws.com/wp-content/uploads/2023/09/politics-election-2024-3rddistrict-tarajohnson-announcement.jpg', 'elected', NULL),
('Tim Carpenter', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '3', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2413.jpg', 'elected', NULL),
('Tip McGuire', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '64', NULL, 'Democratic', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2483.jpg', 'elected', NULL),
('Todd Novak', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '51', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2493.jpg', 'elected', NULL),
('Tony Kurtz', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '41', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2479.jpg', 'elected', NULL),
('Travis Tranel', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '49', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2527.jpg', 'elected', NULL),
('Treig Pronschinske', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '29', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2502.jpg', 'elected', NULL),
('Tyler August', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '31', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2445.jpg', 'elected', NULL),
('Van Wanggaard', 'State Senator', 'Legislative Branch', 'Legislative', 'WI', '21', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/senate/2438.jpg', 'elected', NULL),
('Vinnie Miresse', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '71', NULL, 'Democratic', 'https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Vinnie_Miresse.jpeg', 'elected', NULL),
('Will Penterman', 'Assembly Member', 'Legislative Branch', 'Legislative', 'WI', '38', NULL, 'Republican', 'https://docs.legis.wisconsin.gov/2023/legislators/assembly/2497.jpg', 'elected', NULL);
