-- WV state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'WV';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Adam Burkhammer', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '64', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/burkhammer_adam.jpg', 'elected', NULL),
('Adam Vance', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '35', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/vance_adam.jpg', 'elected', NULL),
('Amy Grady', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '4', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/senate/grady_amy.jpg', 'elected', NULL),
('Andy Shamblin', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '59', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/shamblin_andy.jpg', 'elected', NULL),
('Anitra Hamilton', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '81', NULL, 'Democratic', 'http://www.wvlegislature.gov/images/members/2023/house/hamilton_anitra.jpg', 'elected', NULL),
('Anne Charnock', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '17', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/charnock_anne.jpg', 'elected', NULL),
('Ben Queen', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '12', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2023/senate/queen_ben.jpg', 'elected', NULL),
('Betsy Kelly', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '9', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/kelly_betsy.jpg', 'elected', NULL),
('Bill Bell', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '8', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/bell_bill.jpg', 'elected', NULL),
('Bill Flanigan', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '4', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/flanigan_bill.jpg', 'elected', NULL),
('Bill Hamilton', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '11', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/senate/hamilton_bill.jpg', 'elected', NULL),
('Bill Ridenour', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '100', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/ridenour_bill.jpg', 'elected', NULL),
('Bill Roop', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '44', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/roop_carl.jpg', 'elected', NULL),
('Bob Fehrenbacher', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '11', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/fehrenbacher_bob.jpg', 'elected', NULL),
('Brian Helton', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '9', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/helton_brian.jpg', 'elected', NULL),
('Bryan Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '73', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/smith_bryan.jpg', 'elected', NULL),
('Bryan Ward', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '86', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/ward_bryan.jpg', 'elected', NULL),
('Robbie Martin', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '65', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2019/house/martin_carl.jpg', 'elected', NULL),
('Charles Clements', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '2', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/senate/clements_charles.jpg', 'elected', NULL),
('Chuck Sheedy', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '7', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/sheedy_charles.jpg', 'elected', NULL),
('Chris Anders', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '97', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/anders_chris.jpg', 'elected', NULL),
('Chris Phillips', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '68', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2019/house/phillips_chris.jpg', 'elected', NULL),
('Chris Rose', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '2', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/rose_chris.jpg', 'elected', NULL),
('Chris Toney', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '43', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/toney_christopher.jpg', 'elected', NULL),
('Chuck Horst', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '95', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/horst_chuck.jpg', 'elected', NULL),
('Clay Riley', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '72', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/house/riley_clay.jpg', 'elected', NULL),
('Craig Hart', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '6', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/hart_craig.jpg', 'elected', NULL),
('Buck Jennings', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '84', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/jennings_d.jpg', 'elected', NULL),
('Dana Ferrell', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '60', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/ferrell_dana.jpg', 'elected', NULL),
('Daniel Linville', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '22', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/linville_daniel.jpg', 'elected', NULL),
('Darren Thorne', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '15', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/thorne_darren.jpg', 'elected', NULL),
('Dave Foggin', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '14', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/foggin_dave.jpg', 'elected', NULL),
('Dave McCormick', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '82', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/mccormick_david.jpg', 'elected', NULL),
('David Cannon', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '89', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/cannon_david.jpg', 'elected', NULL),
('Elliott Pritt', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '50', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/pritt_david.jpg', 'elected', NULL),
('David Green', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '36', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/green_david.jpg', 'elected', NULL),
('Dean Jeffries', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '61', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2022/house/jeffries_dean.jpg', 'elected', NULL),
('Donald Bennett', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '94', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/bennett_donald.jpg', 'elected', NULL),
('Doug Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '39', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/smith_doug.jpg', 'elected', NULL),
('Elías Coop-González', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '67', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/coopgonzalez_elias.jpg', 'elected', NULL),
('Eric Brooks', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '45', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/brooks_eric.jpg', 'elected', NULL),
('Eric Tarr', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '4', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/tarr_eric.jpg', 'elected', NULL),
('Erica Moore', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '15', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/moore_erica.jpg', 'elected', NULL),
('Evan Hansen', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '79', NULL, 'Democratic', 'http://www.wvlegislature.gov/images/members/2019/house/hansen_evan.jpg', 'elected', NULL),
('Evan Worrell', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '23', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/worrell_evan.jpg', 'elected', NULL),
('Gary Howell', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '87', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/howell_gary.jpg', 'elected', NULL),
('Geno Chiarelli', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '78', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/chiarelli_geno.jpg', 'elected', NULL),
('George Miller', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '90', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/miller_george.jpg', 'elected', NULL),
('George Street', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '83', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/street_george.jpg', 'elected', NULL),
('Glenn Jeffries', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '8', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/jeffries_glenn.jpg', 'elected', NULL),
('Greg Watt', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '48', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/watt_gregory.jpg', 'elected', NULL),
('Guy Ward', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '74', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/ward_guy.jpg', 'elected', NULL),
('Corby Dillon', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '29', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/dillon_henry.jpg', 'elected', NULL),
('Hollis Lewis', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '57', NULL, 'Democratic', 'https://www.wvlegislature.gov/images/members/2023/house/lewis_hollis.jpg', 'elected', NULL),
('Ian Masters', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '91', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/masters_ian.jpg', 'elected', NULL),
('J.B. Akers', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '55', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/akers_james.jpg', 'elected', NULL),
('Jack Woodrum', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '10', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/woodrum_jack.jpg', 'elected', NULL),
('Jarred Cannon', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '21', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2022/house/cannon_jarred.jpg', 'elected', NULL),
('Jason Barrett', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '16', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/barrett_jason.jpg', 'elected', NULL),
('Jay Taylor', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '14', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/taylor_jay.jpg', 'elected', NULL),
('Jeff Campbell', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '46', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/campbell_jeff.jpg', 'elected', NULL),
('Jeff Eldridge', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '30', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/eldridge_jeff.jpg', 'elected', NULL),
('Jeff Stephens', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '6', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2023/house/stephens_jeffrey.jpg', 'elected', NULL),
('Jim Butler', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '18', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/butler_jim.jpg', 'elected', NULL),
('Jimmy Willis', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '3', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/willis_jimmy.jpg', 'elected', NULL),
('Joe Ellington', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '38', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2023/house/ellington_joe.jpg', 'elected', NULL),
('Joe Funkhouser', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '98', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/funkhouser_joe.jpg', 'elected', NULL),
('Joe Parsons', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '16', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/parsons_frederick.jpg', 'elected', NULL),
('Joe Statler', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '77', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/statler_joe.jpg', 'elected', NULL),
('Joey Garcia', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '13', NULL, 'Democratic', 'https://www.wvlegislature.gov/images/members/2025/senate/garcia_joey.jpg', 'elected', NULL),
('John Jordan', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '42', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/jordan_john.jpg', 'elected', NULL),
('John Paul Hott', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '85', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/house/hott_john.jpg', 'elected', NULL),
('John Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '80', NULL, 'Democratic', 'http://www.wvlegislature.gov/images/members/2021/house/williams_john.jpg', 'elected', NULL),
('Jonathan Kyle', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '66', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/kyle_jonathan.jpg', 'elected', NULL),
('Jonathan Pinson', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '17', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/pinson_jonathan.jpg', 'elected', NULL),
('Jordan Bridges', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '33', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/house/bridges_jordan.jpg', 'elected', NULL),
('Jordan Maynor', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '41', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/maynor_jordan.jpg', 'elected', NULL),
('Josh Holstein', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '32', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/holstein_josh.jpg', 'elected', NULL),
('Kathie Hess Crouse', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '19', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/crouse_kathie.jpg', 'elected', NULL),
('Kayla Young', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '56', NULL, 'Democratic', 'https://www.wvlegislature.gov/images/members/2024/house/young_kayla.jpg', 'elected', NULL),
('Keith Marple', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '69', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/marple_keith.jpg', 'elected', NULL),
('Kevan Bartlett', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '8', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2019/house/bartlett_t.jpg', 'elected', NULL),
('Laura Kimble', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '71', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/kimble_laura.jpg', 'elected', NULL),
('Laura Chapman', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '1', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/chapman_laura.jpg', 'elected', NULL),
('Lisa White', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '96', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/white_lisa.jpg', 'elected', NULL),
('Lori Dittman', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '63', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/dittman_lori.jpg', 'elected', NULL),
('Margitta Mazzocchi', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '31', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/mazzocchi_margitta.jpg', 'elected', NULL),
('Mark Dean', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '34', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/dean_mark.jpg', 'elected', NULL),
('Mark Maynard', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '6', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/maynard_mark.jpg', 'elected', NULL),
('Mark Zatezalo', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '2', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/zatezalo_mark.jpg', 'elected', NULL),
('Marshall Clay', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '51', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/clay_marshall.jpg', 'elected', NULL),
('Marty Gearheart', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '37', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/house/gearheart_marty.jpg', 'elected', NULL),
('Matthew Rohrbach', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '26', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/rohrbach_matthew.jpg', 'elected', NULL),
('Michael Amos', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '27', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/amos_michael.jpg', 'elected', NULL),
('Mike Hite', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '92', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/hite_michael.jpg', 'elected', NULL),
('Mike Hornby', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '93', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/hornby_mike.jpg', 'elected', NULL),
('Mickey Petitto', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '70', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/petitto_mickey.jpg', 'elected', NULL),
('Mike Azinger', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '3', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/azinger_michael.jpg', 'elected', NULL),
('Mike Oliverio', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '13', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/oliverio_michael.jpg', 'elected', NULL),
('Mike Pushkin', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '54', NULL, 'Democratic', 'http://www.wvlegislature.gov/images/members/2023/house/pushkin_mike.jpg', 'elected', NULL),
('Mike Woelfel', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '5', NULL, 'Democratic', 'https://www.wvlegislature.gov/images/members/2025/senate/woelfel_michael.jpg', 'elected', NULL),
('Pat McGeehan', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '1', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/mcgeehan_pat.jpg', 'elected', NULL),
('Patricia Rucker', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '16', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/rucker_patricia.jpg', 'elected', NULL),
('Patrick Lucas', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '24', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/lucas_patrick.jpg', 'elected', NULL),
('Patrick Martin', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '12', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/senate/martin_patrick.jpg', 'elected', NULL),
('Phil Mallow', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '75', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/house/mallow_phil.jpg', 'elected', NULL),
('Randy Smith', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '14', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/smith_randy.jpg', 'elected', NULL),
('Ray Canterbury', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '47', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/canterbury_ray.jpg', 'elected', NULL),
('Rick Garcia', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '76', NULL, 'Democratic', 'https://www.wvlegislature.gov/images/members/2025/house/garcia_rick.jpg', 'elected', NULL),
('Rick Hillenbrand', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '88', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/hillenbrand_rick.jpg', 'elected', NULL),
('Robbie Morris', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '11', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/morris_robbie.jpg', 'elected', NULL),
('Roger Hanshaw', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '62', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/house/hanshaw_roger.jpg', 'elected', NULL),
('Rollan Roberts', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '9', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/roberts_rollan.jpg', 'elected', NULL),
('Roy Cooper', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '40', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/cooper_roy.jpg', 'elected', NULL),
('Rupie Phillips', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '7', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/senate/phillips_rupie.jpg', 'elected', NULL),
('Ryan Browning', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '28', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2024/house/browning_ryan.jpg', 'elected', NULL),
('Ryan Weld', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '1', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/senate/weld_ryan.jpg', 'elected', NULL),
('Sarah Drennan', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '20', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/drennan_sarah.jpg', 'elected', NULL),
('Scot Heckert', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '13', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/heckert_scot.jpg', 'elected', NULL),
('Scott Fuller', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '5', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/fuller_scott.jpg', 'elected', NULL),
('Sean Hornbuckle', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '25', NULL, 'Democratic', 'http://www.wvlegislature.gov/images/members/2023/house/hornbuckle_sean.jpg', 'elected', NULL),
('Shawn Fluharty', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '5', NULL, 'Democratic', 'http://www.wvlegislature.gov/images/members/2023/house/fluharty_shawn.jpg', 'elected', NULL),
('Stan Adkins', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '49', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/adkins_stanley.jpg', 'elected', NULL),
('Tom Takubo', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '17', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/senate/takubo_tom.jpg', 'elected', NULL),
('Tom Willis', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '15', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/senate/willis_tom.jpg', 'elected', NULL),
('Trenton Barnhart', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '3', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/barnhart_trenton.jpg', 'elected', NULL),
('Tresa Howell', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '52', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/howell_tresa.jpg', 'elected', NULL),
('Tristan Leavitt', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '53', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/leavitt_tristan.jpg', 'elected', NULL),
('Vernon Criss', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '12', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/criss_vernon.jpg', 'elected', NULL),
('Vince Deeds', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '10', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/senate/deeds_vince.jpg', 'elected', NULL),
('Walter Hall', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '58', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2023/house/hall_walter.jpg', 'elected', NULL),
('Wayne Clark', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '99', NULL, 'Republican', 'https://www.wvlegislature.gov/images/members/2025/house/clark_wayne.jpg', 'elected', NULL),
('Bill Anderson', 'State Representative', 'Legislative Branch', 'Legislative', 'WV', '10', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2022/house/anderson_bill.jpg', 'elected', NULL),
('Zack Maynard', 'State Senator', 'Legislative Branch', 'Legislative', 'WV', '7', NULL, 'Republican', 'http://www.wvlegislature.gov/images/members/2021/house/maynard_zack.jpg', 'elected', NULL);
