-- WY state legislators
-- Paste into Supabase SQL Editor and Run.

delete from public.state_officials
where court_or_agency = 'Legislative Branch'
  and state_code = 'WY';

insert into public.state_officials (
  full_name,
  title,
  court_or_agency,
  level,
  state_code,
  district_number,
  county_name,
  party,
  photo_url,
  selection_method,
  appointed_by
)
values
('Abby Angelos', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '3', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-AngelosAbby.jpg', 'elected', NULL),
('Andrew Byron', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '22', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-ByronAndrew.jpg', 'elected', NULL),
('Ann Lucas', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '43', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LucasAnn.jpg', 'elected', NULL),
('Art Washut', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '36', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-WashutArt.jpg', 'elected', NULL),
('Barry Crago', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '22', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-CragoBarry.jpg', 'elected', NULL),
('Bill Allemand', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '58', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-AllemandBill.jpg', 'elected', NULL),
('Bill Landen', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '27', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LandenBill.jpg', 'elected', NULL),
('Bo Biteman', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '21', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BitemanBo.jpg', 'elected', NULL),
('Bob Davis', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '47', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-DavisBob.jpg', 'elected', NULL),
('Bob Ide', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '29', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/67th-IdeBob.jpg', 'elected', NULL),
('Bob Nicholas', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '7', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-NicholasBob.jpg', 'elected', NULL),
('Brian Boner', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '2', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BonerBrian.jpg', 'elected', NULL),
('Cale Case', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '25', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-CaseCale.jpg', 'elected', NULL),
('Charles Scott', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '30', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-ScottCharles.jpg', 'elected', NULL),
('Cheri Steinmetz', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '3', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-SteinmetzCheri.jpg', 'elected', NULL),
('Chip Neiman', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '1', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-NeimanChip.jpg', 'elected', NULL),
('Chris Rothfuss', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '9', NULL, 'Democratic', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-RothfussChris.jpg', 'elected', NULL),
('Chris Knapp', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '53', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-KnappChristopher.jpg', 'elected', NULL),
('Clarence Styvar', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '12', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-StyvarClarence.jpg', 'elected', NULL),
('Cody Wylie', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '39', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/67th-WylieCody.jpg', 'elected', NULL),
('Dalton Banks', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '26', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BanksDalton.jpg', 'elected', NULL),
('Dan Dockstader', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '16', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-DockstaderDan.jpg', 'elected', NULL),
('Dan Laursen', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '19', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LaursenDan.jpg', 'elected', NULL),
('Daniel Singh', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '61', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-SinghDaniel.jpg', 'elected', NULL),
('Darin McCann', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '48', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-McCannDarin.jpg', 'elected', NULL),
('Ed Cooper', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '20', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-CooperEd.jpg', 'elected', NULL),
('Elissa Campbell', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '56', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-CampbellElissa.jpg', 'elected', NULL),
('Eric Barlow', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '23', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BarlowEric.jpg', 'elected', NULL),
('Evie Brennan', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '31', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BrennanEvie.jpg', 'elected', NULL),
('Gary Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '41', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BrownGary.jpg', 'elected', NULL),
('Gary Crum', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '10', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-CrumGary.jpg', 'elected', NULL),
('Ivan Posey', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '33', NULL, 'Democratic', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-PoseyIvan.jpg', 'elected', NULL),
('J.D. Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '2', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-WilliamsJD.jpg', 'elected', NULL),
('J.R. Riggins', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '59', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-RigginsJR.jpg', 'elected', NULL),
('J.T. Larson', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '17', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LarsonJT.jpg', 'elected', NULL),
('Jacob Wasserburger', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '11', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-WasserburgerJacob.jpg', 'elected', NULL),
('Jared Olsen', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '8', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-OlsenJared.jpg', 'elected', NULL),
('Jayme Lien', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '38', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LienJayme.jpg', 'elected', NULL),
('Jeremy Haroldson', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '4', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-HaroldsonJeremy.jpg', 'elected', NULL),
('Jim Anderson', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '28', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-AndersonJim.jpg', 'elected', NULL),
('Joe Webb', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '19', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-WebbJoe.jpg', 'elected', NULL),
('Joel Guggenmos', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '55', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-GuggenmosJoel.jpg', 'elected', NULL),
('John Bear', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '31', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BearJohn.jpg', 'elected', NULL),
('John Kolb', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '12', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-KolbJohn.jpg', 'elected', NULL),
('John Winter', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '28', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-WinterJohn.jpg', 'elected', NULL),
('Julie Jarvis', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '57', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-JarvisJulie.jpg', 'elected', NULL),
('Justin Fornstrom', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '10', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-FornstromJustin.JPG', 'elected', NULL),
('Karlee Provenza', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '45', NULL, 'Democratic', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-ProvenzaKarlee.jpg', 'elected', NULL),
('Ken Chestek', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '13', NULL, 'Democratic', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-ChestekKen.jpg', 'elected', NULL),
('Ken Clouston', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '32', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-CloustonKen.jpg', 'elected', NULL),
('Ken Pendergraft', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '29', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-PendergraftKen.jpg', 'elected', NULL),
('Kevin Campbell', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '62', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-CampbellKevin.jpg', 'elected', NULL),
('Landon Brown', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '9', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BrownLandon.jpg', 'elected', NULL),
('Larry Hicks', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '11', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-HicksLarry.jpg', 'elected', NULL),
('Laura Pearson', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '14', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-PearsonLaura.jpg', 'elected', NULL),
('Laurie Bratten', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '51', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BrattenLaurie.jpg', 'elected', NULL),
('Lee Filer', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '44', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-FilerLee.jpg', 'elected', NULL),
('Liz Storer', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '23', NULL, 'Democratic', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-StorerLiz.jpg', 'elected', NULL),
('Lloyd Larsen', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '54', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LarsenLloyd.jpg', 'elected', NULL),
('Lynn Hutchings', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '5', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-HutchingsLynn.jpg', 'elected', NULL),
('Marilyn Connolly', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '40', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-ConnollyMarilyn.jpg', 'elected', NULL),
('Marlene Brady', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '60', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-BradyMarlene.jpg', 'elected', NULL),
('Martha Lawley', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '27', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LawleyMartha.jpg', 'elected', NULL),
('McKay Erickson', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '21', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-EricksonMcKay.jpg', 'elected', NULL),
('Mike Gierau', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '17', NULL, 'Democratic', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-GierauMike.jpg', 'elected', NULL),
('Mike Schmid', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '20', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-SchmidMike.jpg', 'elected', NULL),
('Mike Yin', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '16', NULL, 'Democratic', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-YinMike.jpg', 'elected', NULL),
('Nina Webber', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '24', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-WebberNina.jpg', 'elected', NULL),
('Ocean Andrew', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '46', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/66th-AndrewOcean.jpg', 'elected', NULL),
('Ogden Driskill', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '1', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-DriskillOgden.jpg', 'elected', NULL),
('Pam Thayer', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '15', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-ThayerPamela.jpg', 'elected', NULL),
('Paul Hoeft', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '25', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-HoeftPaul.jpg', 'elected', NULL),
('Pepper Ottman', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '34', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-OttmanPepper.jpg', 'elected', NULL),
('Rachel Rodriguez-Williams', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '50', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-Rodriguez-WilliamsRachel.jpg', 'elected', NULL),
('Reuben Tarver', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '52', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-TarverReuben.jpg', 'elected', NULL),
('Rob Geringer', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '42', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-GeringerRob.jpg', 'elected', NULL),
('Bob Wharff', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '49', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-WharffRobert.jpg', 'elected', NULL),
('Scott Heiner', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '18', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-HeinerScott.jpg', 'elected', NULL),
('Scott Smith', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '5', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/67th-SmithScott.jpg', 'elected', NULL),
('Stacy Jones', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '13', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-JonesStacy.jpg', 'elected', NULL),
('Stephan Pappas', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '7', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-PappasStephan.jpg', 'elected', NULL),
('Steve Harshman', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '37', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-HarshmanSteve.jpg', 'elected', NULL),
('Steve Johnson', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '8', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-JohnsonSteve.jpg', 'elected', NULL),
('Taft Love', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '6', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LoveTaft.jpg', 'elected', NULL),
('Tara Nethercott', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '4', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-NethercottTara.jpg', 'elected', NULL),
('Tim French', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '18', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-FrenchTim.jpg', 'elected', NULL),
('Tim Salazar', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '26', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-SalazarTim.jpg', 'elected', NULL),
('Tom Kelly', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '30', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-KellyTom.jpg', 'elected', NULL),
('Tomi Strock', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '6', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-StrockTomi.jpg', 'elected', NULL),
('Tony Locke', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '35', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-LockeTony.jpg', 'elected', NULL),
('Trey Sherwood', 'State Representative', 'Legislative Branch', 'Legislative', 'WY', '14', NULL, 'Democratic', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-SherwoodTrey.jpg', 'elected', NULL),
('Troy McKeown', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '24', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-McKeownTroy.jpg', 'elected', NULL),
('Wendy Schuler', 'State Senator', 'Legislative Branch', 'Legislative', 'WY', '15', NULL, 'Republican', 'https://wyoleg.gov/LegislatorSummary/Photos/68th-SchulerWendy.jpg', 'elected', NULL);
